### PR TITLE
Fix bad merge

### PR DESCRIPTION
**Pull request by plbossart**
conflict with upstream not detected - branch was stale....https://github.com/thesofproject/linux/pull/4533 should have been rebased before merge. Oh well.

### CODE REVIEW

**Comment by plbossart** [comment]
https://sof-ci.01.org/linuxpr/PR4628/build6943/devicetest/index.html fails on MTL_RVP_HDA?

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
Goodness, same issue with MTL_HDA in https://sof-ci.01.org/linuxpr/PR4628/build6947/devicetest/index.html

**Comment by marc-hb** [comment]
I ssh to https://sof-ci.01.org/linuxpr/PR4628/build6947/devicetest/index.html?model=MTLP_RVP_HDA&testcase=verify-kernel-boot-log and I think I found a real issue, see logs below.

I had to ssh because kernel logs are unfortunately missing. I just filed a new sof-test issue about this:
- https://github.com/thesofproject/sof-test/issues/1112

```
Oct 10 17:33:48 sh-mtlp-rvp-hda-03 kernel: snd_sof:sof_pcm_new: sof-audio-pci-intel-mtl 0000:00:1f.3: spcm: allocate Analog Capture capture DMA buffer size 0x10000 max 0x10000
Oct 10 17:33:48 sh-mtlp-rvp-hda-03 kernel: snd_sof:sof_pcm_new: sof-audio-pci-intel-mtl 0000:00:1f.3: creating new PCM Deepbuffer HDA Analog
Oct 10 17:33:48 sh-mtlp-rvp-hda-03 kernel: snd_sof:sof_pcm_new: sof-audio-pci-intel-mtl 0000:00:1f.3: spcm: allocate Deepbuffer HDA Analog playback DMA buffer size 0x10000 max 0x40000
Oct 10 17:33:48 sh-mtlp-rvp-hda-03 kernel: snd_sof:sof_pcm_new: sof-audio-pci-intel-mtl 0000:00:1f.3: creating new PCM DMIC Raw
Oct 10 17:33:48 sh-mtlp-rvp-hda-03 kernel: snd_sof:sof_pcm_new: sof-audio-pci-intel-mtl 0000:00:1f.3: spcm: allocate Gain Capture 11 capture DMA buffer size 0x10000 max 0x10000
Oct 10 17:33:48 sh-mtlp-rvp-hda-03 kernel: skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Failed to add route iDisp3 Tx -> hifi3(*)
Oct 10 17:33:48 sh-mtlp-rvp-hda-03 kernel: skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Failed to add route iDisp2 Tx -> hifi2(*)
Oct 10 17:33:48 sh-mtlp-rvp-hda-03 kernel: skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Failed to add route iDisp1 Tx -> hifi1(*)
Oct 10 17:33:48 sh-mtlp-rvp-hda-03 kernel: skl_hda_dsp_generic skl_hda_dsp_generic: snd_soc_bind_card: snd_soc_dapm_add_routes failed: -19
```

**Comment by plbossart** [comment]
the regression happens also with all chain DMA patches reverted
https://sof-ci.01.org/linuxpr/PR4629/build6951/devicetest/index.html

So this PR has nothing to do with the issue, I'll merge it to avoid build failures.

**Comment by marc-hb** [comment]
Using ssh again, same error in previous run https://sof-ci.01.org/linuxpr/PR4628/build6943/devicetest/index.html?model=MTLP_RVP_HDA&testcase=verify-kernel-boot-log

```
Oct 10 15:25:48 sh-mtlp-rvp-hda-03 kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: init of i915 and HDMI codec failed
Oct 10 15:25:48 sh-mtlp-rvp-hda-03 kernel: skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Parent card not yet available, widget card binding deferred
Oct 10 15:25:48 sh-mtlp-rvp-hda-03 kernel: skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Failed to add route iDisp3 Tx -> hifi3(*)
Oct 10 15:25:48 sh-mtlp-rvp-hda-03 kernel: skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Failed to add route iDisp2 Tx -> hifi2(*)
Oct 10 15:25:48 sh-mtlp-rvp-hda-03 kernel: skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Failed to add route iDisp1 Tx -> hifi1(*)
Oct 10 15:25:48 sh-mtlp-rvp-hda-03 kernel: skl_hda_dsp_generic skl_hda_dsp_generic: snd_soc_bind_card: snd_soc_dapm_add_routes failed: -19
```

**Pull request merged**
