### PR TITLE
ASoC: SOF: topology: Add support for Crossover

### PR DESCRIPTION
**Pull request by sebcarlucci**
This commit adds the enumerations to support the SOF Crossover
component.

The corresponding SOF PR: https://github.com/thesofproject/sof/pull/2802

Signed-off-by: Sebastiano Carlucci <scarlucci@google.com>

### CODE REVIEW

**Comment by plbossart** [comment]
This is going to conflict with https://github.com/thesofproject/linux/pull/1971

**Comment by plbossart** [comment]
@lgirdwood we have two components being added, shouldn't they be tracked with your ABI tool?

**Comment by kv2019i** [comment]
As this is modifying an enum that is part of the FW ABI, needs to be classified before merging.

**Comment by kv2019i** [comment]
@sebcarlucci @singalsu @lgirdwood @cujomalainey Now that crossover is merged with UUID based identification in https://github.com/thesofproject/sof/pull/3263 , we cna close this kernel PR, right?

**Comment by cujomalainey** [comment]
Thanks Kai, yep let's close it

**Pull request closed without merging**
