### PR TITLE
Merge/sound upstream 20220606

### PR DESCRIPTION
**Pull request by plbossart**
First merge based on v5.19-rc1, things could go sideways.

I will update the topic/sof-dev-rebase branch after smoke tests with this merge.

### CODE REVIEW

**Comment by plbossart** [comment]
@greg-intel @fredoh9 @marc-hb any idea why I get this report

````
sof-ci/jenkins/pr-build — PR has merge conflicts! Need to rebase to continue test! 
````

it's a merge on top of the latest topic/sof-dev, I don't see how we could have merge conflicts?

**Comment by plbossart** [comment]
https://sof-ci.01.org/linuxpr/PR3682/build197/devicetest/ gives pretty good results, "only" one timeout on suspend resume on TGL RVP and known pause/release issue on BYT. Not so bad for an -rc1.

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
Even better with https://sof-ci.01.org/linuxpr/PR3682/build198/devicetest/, only BYT pause/release fail. looks good to me.

**Review by ujfalusi — DISMISSED** [review]

**Comment by ujfalusi** [comment]
@plbossart, there is a merge issue in `sound/soc/codecs/da7219-aad.c`
commit 2d969e8f35b18 comes from upstream and commit  c2d997a46fea2 is coming from sof-dev, we should drop the changes we had in sof-dev (we have duplicated block of `cancel_work_sync()` for the same works, harmless, I know).

**Comment by plbossart** [comment]
> @plbossart, there is a merge issue in `sound/soc/codecs/da7219-aad.c` commit [2d969e8](https://github.com/thesofproject/linux/commit/2d969e8f35b1849a43156029a7a6e2943b89d0c0) comes from upstream and commit [c2d997a](https://github.com/thesofproject/linux/commit/c2d997a46fea29dc265b0a2f3ad7f3ff522ae2e3) is coming from sof-dev, we should drop the changes we had in sof-dev (we have duplicated block of `cancel_work_sync()` for the same works, harmless, I know).

thanks for noticing this @ujfalusi

**Comment by plbossart** [comment]
fixed merge issue and tagged sof-dev-rebase-20220606-1. Muchas gracias @ujfalusi

**Comment by plbossart** [comment]
Started Intel 'shared-daily' plan 13172 for more results before merging.

**Comment by plbossart** [comment]
No significant regression on Test 13172, apart from usual timeouts and disk issues, so merging.

**Pull request merged**
