### PR TITLE
Merge/sound upstream 20220418

### PR DESCRIPTION
**Pull request by plbossart**
pushed topic/sof-dev-rebase and tag sof-dev-rebase-20220418

### CODE REVIEW

**Comment by plbossart** [comment]
results are mostly good except for ONE sh-whl-upext-hda-01 platform that's already problematic in other tests (@XiaoyunWu6666  @keqiaozhang FYI)

https://sof-ci.01.org/linuxpr/PR3595/build13/devicetest/?model=WHL_UPEXT_HDA_ZEPHYR&testcase=check-suspend-resume-with-capture-5

````
[ 1184.544198] kernel: ACPI: PM: Preparing to enter system sleep state S3
[ 1184.545474] kernel: ACPI: PM: Saving platform NVS memory
[ 1184.545497] kernel: Disabling non-boot CPUs ...
[ 1184.547233] kernel: smpboot: CPU 1 is now offline
[ 1184.550420] kernel: Call Trace:
[ 1184.550427] kernel:  
[ 1184.550435] kernel:  x86_acpi_suspend_lowlevel+0x10f/0x180
[ 1184.550444] kernel:  acpi_suspend_enter+0x60/0x260
[ 1184.550450] kernel:  ? _raw_spin_unlock_irqrestore+0x33/0x50
[ 1184.550458] kernel:  suspend_devices_and_enter+0x78e/0x8f0
[ 1184.550467] kernel:  pm_suspend.cold+0x2b1/0x2fc
[ 1184.550474] kernel:  state_store+0x71/0xd0
[ 1184.550480] kernel:  kernfs_fop_write_iter+0x126/0x1c0
[ 1184.550487] kernel:  new_sync_write+0x10c/0x190
[ 1184.550501] kernel:  vfs_write+0x28f/0x310
[ 1184.550506] kernel:  ksys_write+0x68/0xe0
[ 1184.550512] kernel:  do_syscall_64+0x38/0x90
[ 1184.550518] kernel:  entry_SYSCALL_64_after_hwframe+0x44/0xae
[ 1184.550524] kernel: RIP: 0033:0x7fb09cc150a7
[ 1184.550529] kernel: Code: 64 89 02 48 c7 c0 ff ff ff ff eb bb 0f 1f 80 00 00 00 00 f3 0f 1e fa 64 8b 04 25 18 00 00 00 85 c0 75 10 b8 01 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 51 c3 48 83 ec 28 48 89 54 24 18 48 89 74 24
[ 1184.550532] kernel: RSP: 002b:00007ffced37f408 EFLAGS: 00000246 ORIG_RAX: 0000000000000001
[ 1184.550537] kernel: RAX: ffffffffffffffda RBX: 0000000000000004 RCX: 00007fb09cc150a7
[ 1184.550539] kernel: RDX: 0000000000000004 RSI: 00005626d4350730 RDI: 0000000000000004
[ 1184.550542] kernel: RBP: 00005626d4350730 R08: 0000000000000000 R09: 0000000000000004
[ 1184.550544] kernel: R10: 00005626d2e212a6 R11: 0000000000000246 R12: 0000000000000004
[ 1184.550546] kernel: R13: 00005626d434e380 R14: 00007fb09ccf04a0 R15: 00007fb09ccef8a0
[ 1184.550559] kernel:  
[ 1184.550564] kernel: ACPI: PM: Low-level resume complete
[ 1184.550609] kernel: ACPI: PM: Restoring platform NVS memory
[ 1184.553518] kernel: Enabling non-boot CPUs ...
[ 1184.553631] kernel: x86: Booting SMP configuration:
[ 1184.553633] kernel: smpboot: Booting Node 0 Processor 1 APIC 0x2
[ 1184.556950] kernel: CPU1 is up
[ 1184.557397] kernel: ACPI: PM: Waking up from system sleep state S3
````
 
Let's redo the tests.

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
Something's wrong with UpExtreme, we get the same timeout on a different device jf-whl-upext-hda-1 now

https://sof-ci.01.org/linuxpr/PR3595/build16/devicetest/?model=WHL_UPEXT_HDA_ZEPHYR&testcase=check-suspend-resume-with-capture-5

I think these upext-hda devices have been problematic for some time now. @XiaoyunWu6666 @keqiaozhang @fredoh9 @marc-hb is there a way to know when the last test worked for this class of devices?

**Comment by marc-hb** [comment]
@XiaoyunWu6666 is there a bug where you collected these recent whl-upext-hda failures? If not yet then please file one and discuss  there; not here.

**Comment by keqiaozhang** [comment]
@plbossart  according to the TCR history, this issue happened sporadically on WHL UpExtreme. 
http://sof-tcr.sh.intel.com/#/tests

image
image
image

**Comment by XiaoyunWu6666** [comment]
discussion of WHL UP extreme transferred to inner repo

**Comment by plbossart** [comment]
I've seen no issues with that update - outside of known open questions on UpExtreme results, merging to see daily test results tomorrow.

**Pull request merged**
