### PR TITLE
Merge/sound upstream 20210308

### PR DESCRIPTION
**Pull request by plbossart**
merge based on v5.12-rc2

This contains all the fixes needed for -rc1.

It seems that the merge will be problematic and may have to be fixed by hand.

@shumingfan @jack-cy-yu I took whatever was provided upstream for SDCA devices. This means we've lost e.g. the set_tdm_slot for RT1316, I can't recall if this is necessary or not.

### CODE REVIEW

**Comment by ranj063** [comment]
https://github.com/thesofproject/sof-test/pull/627 should fix the device test failures

**Review by bardliao — APPROVED** [review]
Verified with run-all-tests.sh on CML sdw device.

**Review by kv2019i — APPROVED** [review]
Local tests are fine, ok to merge.

**Comment by plbossart** [comment]
Intel test 2536 does not show any regressions (except for an CML HDA timeout), so good to merge.

**Pull request merged**
