### PR TITLE
Use inclusive language for DSP cores

### PR DESCRIPTION
**Pull request by plbossart**
s/master/primary
s/slave/secondary

Most of the changes will have to take place on topic/sof-dev-rebase to reword the commit messages.

### CODE REVIEW

**Review by lyakh — APPROVED** [review]

**Review by juimonen — APPROVED** [review]
Looks ok for me too

**Comment by bardliao** [comment]
Maybe we can do it a little bit more although the terms used for clock are not decided yet but `` /* handle master/slave and inverted clocks */`` in topology.c means ``handle clock direction and inverted`` actually.

**Review by singalsu — APPROVED** [review]

**Comment by kv2019i** [comment]
One CI error is a known issue fixed by https://github.com/thesofproject/sof-test/pull/354 . Rest looks good so merging.

**Comment by plbossart** [comment]
> Maybe we can do it a little bit more although the terms used for clock are not decided yet but ` /* handle master/slave and inverted clocks */` in topology.c means `handle clock direction and inverted` actually.

I wanted to do this in my other fixes, it's really unrelated to cores.

**Pull request merged**
