### PR TITLE
ASoC: SOF: sof-of-dev: add parameter to override tplg/fw_filename

### PR DESCRIPTION
**Pull request by AnneOnciulescu**
Add support to override topology and firmware filename, using module parameters. This is helpful for development and also for testing various scenarios.

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

**Comment by iuliana-prodan** [comment]
> **test this please**

test this please

**Review by bardliao — APPROVED** [review]

**Review by ujfalusi — APPROVED** [review]
I have been thinking of moving these overrides to core.c and mark the options in sof-pci/acpi/of as deprecated.

We have the full set of overrides (including also IPC version) in sof-pci-dev.c only, similar level of override would just duplicate code over time, which does not make much sense.

**Review by iuliana-prodan — APPROVED** [review]

**Comment by bardliao** [comment]
> I have been thinking of moving these overrides to core.c and mark the options in sof-pci/acpi/of as deprecated.
> 
> We have the full set of overrides (including also IPC version) in sof-pci-dev.c only, similar level of override would just duplicate code over time, which does not make much sense.

Agree, my first thought to this PR is that haven't we done this? Then realized this is for different platforms.

**Review by aiChaoSONG — APPROVED** [review]

**Pull request merged**
