### PR TITLE
Merge/sound upstream 20230511

### PR DESCRIPTION
**Pull request by plbossart**
first upstream merge based on v6.4-rc1. No conflicts at all, this looks better than usual. no issues in local tests.

sof-dev-rebase-20230511 pushed, as well as topic/sof-dev-rebase

### CODE REVIEW

**Comment by plbossart** [comment]
Too many failures for me

main-ace has HDAudio FAIL: https://sof-ci.01.org/linuxpr/PR4349/build4833/devicetest/index.html
main-cavs has one timeout while playing on 	TGLU_RVP_SDW_IPC4ZPH https://sof-ci.01.org/linuxpr/PR4349/build4834/devicetest/index.html
stable-2.2 has an alsabat problem on CML_HELIOS https://sof-ci.01.org/linuxpr/PR4349/build4835/devicetest/index.html

let's redo the tests to see if these issues are reproduced

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
No issues detected with stable 2-2

only pause-resume issues failed in https://sof-ci.01.org/linuxpr/PR4349/build4858/devicetest/index.html

I am concerned about the MTLP_HDA_RVP which is a complete fail https://sof-ci.01.org/linuxpr/PR4349/build4857/devicetest/index.html

This device works fine in a different PR https://sof-ci.01.org/linuxpr/PR4354/build4867/devicetest/index.html

I'll redo the tests on more time to check if there's any dependency on firmware? @ujfalusi @ranj063 are you aware of any issues that could explain this major regression?

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
looks like CI is stuck after 9 hours @greg-intel @fredoh9 @keqiaozhang ?

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
Testing on jf-mtlp-rvp-hda-3

TPLG=/lib/firmware/intel/sof-ace-tplg/sof-hda-generic-4ch.tplg MODEL=MTLP_RVP_HDA ~/sof-test/test-case/check-capture.sh -d 10 -l 1 -r 1

a) topic/sof-dev d1cc93d11cbf91e32c08ca7c44de6ca0906d06fb PASS
b) this PR 94ea1fe17acd2bf14d3517f8d3bd91868d343cf5 FAIL

c) merge of sound-fix-6.4-rc1 on top of topic/sof-dev PASS
d) merge of v6.4-rc1 on top of above FAIL

So something not in the sound subsystem impacts the results. Gah.

merge of 4c9818d8652b9824c73e456dd0d73ffba1d0e64d (soundwire-6.4-rc1) on top of c) FAIL

**Comment by plbossart** [comment]
Bisect results point to 

07d971abf436 Merge tag 'tag-chrome-platform-for-v6.4' of git://git.kernel.org/pub/scm/linux/kernel/git/chrome-platform/linux

GOOD

088e0c188513 Merge tag 'platform-drivers-x86-v6.4-1' of git://git.kernel.org/pub/scm/linux/kernel/git/pdx86/platform-drivers-x86

BAD

[linus.txt](https://github.com/thesofproject/linux/files/11492230/linus.txt)

Re-testing the good with #4359 and bad with #4360

**Comment by plbossart** [comment]
bisecting the platform device branch is interesting, not sure what happens here

GOOD

aec8298c093f platform/x86/amd/pmf: Move out of BIOS SMN pair for driver probe
b845772677ea platform/x86/amd: pmc: Don't try to read SMU version on Picasso
5ec9ee0d4647 platform/x86/amd: pmc: Hide SMU version and program attributes for Picasso
7abc3618b653 platform/x86/amd: pmc: Don't dump data after resume from s0i3 on picasso
9217bd1d7699 platform/x86/amd: pmc: Move idlemask check into `amd_pmc_idlemask_read`
310e782a99c7 platform/x86/amd: pmc: Utilize SMN index 0 for driver probe
8d99129eef8f platform/x86/amd: pmc: Move out of BIOS SMN pair for STB init
336ba968d3e3 platform/x86/intel/pmc/mtl: Put GNA/IPU/VPU devices in D3
5b309e80f457 platform/x86: amd: pmc: Remove __maybe_unused from amd_pmc_suspend_handler()

BAD

More bisect after the break

[hans.txt](https://github.com/thesofproject/linux/files/11492672/hans.txt)

**Comment by plbossart** [comment]
confirmed problematic commit:

336ba968d3e3 platform/x86/intel/pmc/mtl: Put GNA/IPU/VPU devices in D3

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
ok, so the results are much better with the last revert. No fails for MTL_RVP_HDA, and the rest of the issues are the 'usual' timeouts for suspend-resume and multiple pause-push/release. Nothing added by this upstream merge.

**Comment by plbossart** [comment]
I am going to make a semi-educated decision to merge this branch, we need to send additional patches upstream and the PMC/GNA issue should not block us.

@ujfalusi has an additional issue with reboots on Up Extreme but things are already in motion here: https://lore.kernel.org/lkml/20230517122931.22385-1-peter.ujfalusi@linux.intel.com/

**Pull request merged**
