### PR TITLE
Support dell 0c11 product

### PR DESCRIPTION
**Pull request by gongjun-song**

### CODE REVIEW

**Comment by gongjun-song** [comment]
This PR relies on the 1318 codec driver's commit, which Shuming is sending upstream.(https://lore.kernel.org/alsa-devel/20221108092727.13011-1-shumingf@realtek.com/T/#u)

**Comment by bardliao** [comment]
sof_sdw_rt1318.c looks almost the same as sof_sdw_rt1316.c. Can we reuse sof_sdw_rt1316.c? @shumingfan What do you think?

**Review by plbossart — APPROVED** [review]
LGTM

**Comment by plbossart** [comment]
> sof_sdw_rt1318.c looks almost the same as sof_sdw_rt1316.c. Can we reuse sof_sdw_rt1316.c? @shumingfan What do you think?

I had the same idea, maybe we can do this in a second step @bardliao with the addition of common functions. For now we want to prioritize hardware enablement and later try to reuse.

**Review by bardliao — APPROVED** [review]

**Pull request merged**
