### PR TITLE
ASoC: Intel: sof_sdw: add SKU for validation device

### PR DESCRIPTION
**Pull request by libinyang**
Missing SKU, add to re-enable tests.

Signed-off-by: Libin Yang <libin.yang@intel.com>

### CODE REVIEW

**Review by bardliao — DISMISSED** [review]

**Comment by kv2019i** [comment]
@libinyang and @bardliao Is this intended to be sent upstream? If yes, the commit message would need to be extended a bit (renable what tests, instead of validation sku, maybe just add "add Dell SKU xxx".

**Comment by libinyang** [comment]
> @libinyang and @bardliao Is this intended to be sent upstream? If yes, the commit message would need to be extended a bit (renable what tests, instead of validation sku, maybe just add "add Dell SKU xxx".

@kv2019i Agree. I have updated the commit message based on your suggestion. Thanks for the suggestion.

**Review by bardliao — APPROVED** [review]
LGTM

**Review by RanderWang — APPROVED** [review]

**Comment by bardliao** [comment]
I will go ahead to merge this since the code itself looks good and the commit message is fair enough. @libinyang Please co-work with @kv2019i to update the commit message before sending to upstream. Thanks.

**Pull request merged**
