### PR TITLE
Merge/sound upstream 20230317 (v6.3-rc2 - try 3)

### PR DESCRIPTION
**Pull request by ujfalusi**
Hi,

this time it should be good!
We have the fix for the bindeb-pkg and the intel soundwire suspend/resume...

fingers crossed.

### CODE REVIEW

**Comment by plbossart** [comment]
@ujfalusi LGTM, should we merge this now? Also do you have a rebase branch?

**Comment by ujfalusi** [comment]
@plbossart, I have the rebase branch locally. We got one PR merged between I have created this and today, but I think it should be still fine.
Optionally I can create  a new one tomorrow.

**Comment by plbossart** [comment]
> @plbossart, I have the rebase branch locally. We got one PR merged between I have created this and today, but I think it should be still fine. Optionally I can create a new one tomorrow.

As you want. I'd like to send the 'board' and 'codec' patches this week.

**Comment by ujfalusi** [comment]
and the SDW fix?

**Comment by plbossart** [comment]
> and the SDW fix?

I let @bardliao deal with SoundWire upstream.

**Comment by ujfalusi** [comment]
Closing in favor of #4259

**Pull request closed without merging**
