### PR TITLE
Fixes for D0i3 patches upstream feedback

### PR DESCRIPTION
**Pull request by ranj063**

### CODE REVIEW

**Comment by ranj063** [comment]
@plbossart these are the fixes for the feedback on the D0i3 patches. I've included the commits that these need to be squashed with. Thanks!

**Comment by plbossart** [comment]
> @plbossart these are the fixes for the feedback on the D0i3 patches. I've included the commits that these need to be squashed with. Thanks!

what about the 'real' issue with the missing check, did I miss it?

````diff
> -    return hda_resume(sdev, false);
> +    ret = hda_resume(sdev, false);
> +    if (ret < 0)
> +        return ret;
> +
> +    hda_dsp_set_power_state(sdev, &target_state);
````

**Comment by ranj063** [comment]
> > @plbossart these are the fixes for the feedback on the D0i3 patches. I've included the commits that these need to be squashed with. Thanks!
> 
> what about the 'real' issue with the missing check, did I miss it?
> 
> ```diff
> > -    return hda_resume(sdev, false);
> > +    ret = hda_resume(sdev, false);
> > +    if (ret < 0)
> > +        return ret;
> > +
> > +    hda_dsp_set_power_state(sdev, &target_state);
> ```

It's on line 683 in the first patch

**Comment by plbossart** [comment]
> > > @plbossart these are the fixes for the feedback on the D0i3 patches. I've included the commits that these need to be squashed with. Thanks!
> > 
> > 
> > what about the 'real' issue with the missing check, did I miss it?
> > ```diff
> > > -    return hda_resume(sdev, false);
> > > +    ret = hda_resume(sdev, false);
> > > +    if (ret < 0)
> > > +        return ret;
> > > +
> > > +    hda_dsp_set_power_state(sdev, &target_state);
> > ```
> 
> It's on line 683 in the first patch

Your esteemed (?) reviewer needs more coffee. Thanks.

**Pull request merged**
