### PR TITLE
Merge/sound upstream 20210623

### PR DESCRIPTION
**Pull request by ranj063**

### CODE REVIEW

**Comment by ranj063** [comment]
SOFCI TEST

**Comment by fredoh9** [comment]
I'm looking at why device testing is pending

**Comment by plbossart** [comment]
@ranj063 ARM compilation fails because
http://security.ubuntu.com/ubuntu/pool/main/g/gcc-10-cross/gcc-10-cross-base_10.2.0-5ubuntu1~20.04cross1_all.deb does not exist.
It should be http://security.ubuntu.com/ubuntu/pool/main/g/gcc-10-cross/gcc-10-cross-base_10.3.0-1ubuntu1~20.04cross1_all.deb

No idea why the package dependencies are broken this way. @marc-hb ?

**Comment by plbossart** [comment]
I tested on my NUC with 20.04 and the command fetches the correct file:

````
sudo apt install gcc-aarch64-linux-gnu
Get:4 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 gcc-10-cross-base all 10.3.0-1ubuntu1~20.04cross1 [15.2 kB]
````

**Comment by marc-hb** [comment]
I would blame a temporary ubuntu and/or github glitch and hit the corresponding "re-run jobs" on github.com.
Every time there is a CI failure please copy the direct URL in the comments, they're often hard to find after re-running.

**Comment by fredoh9** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
> I would blame a temporary ubuntu and/or github glitch and hit the corresponding "re-run jobs" on github.com.
> Every time there is a CI failure please copy the direct URL in the comments, they're often hard to find after re-running.

I did just that, 3 times, and still no luck

**Comment by plbossart** [comment]
I re-ran the GCC ARM64 test on another and same results: https://github.com/thesofproject/linux/pull/3007/checks?check_run_id=2908560633, it's not limited to this PR but an Ubuntu issue

Nothing bad seen in CI otherwise.

**Comment by marc-hb** [comment]
> SOFCI TEST

I don't think these (terribly named) keywords trigger anything besides Jenkins, do they?

**Comment by marc-hb** [comment]
> I did just that, 3 times, and still no luck

I finally spent more than 10 seconds  looking at this and now I'm pretty sure what the problem is: in `.github/workflows/` there MUST be one `apt update` before any `apt install`

I feel even more sorry considering I was the one filing this github documentation bug! https://github.com/actions/virtual-environments/issues/2924

cc: @ranj063

**Comment by ranj063** [comment]
SOFCI TEST

**Comment by fredoh9** [comment]
Daily test was run with this PR, internal test result 4859.

**Comment by ranj063** [comment]
SOFCI TEST

**Review by plbossart — APPROVED** [review]

**Pull request merged**
