### PR TITLE
Fix  set autosuspend delay

### PR DESCRIPTION
**Pull request by kv2019i**
One more attempt to fix this bug. This is a combination of patches from @jason77-wang and @juimonen . We set a non-zero value for codecs after ASoC registration is done, to mimic to programming flow of the legacy driver.

This is alternative to:
- #1837 
- #1726

### CODE REVIEW

**Comment by ranj063** [comment]
SOFCI TEST

**Comment by kv2019i** [comment]
@ClarexZhou or @juimonen , could you double-check this works ok on Mantis? It seems this is otherwise good to go -- we do need ack from you @jason77-wang as well before merging.

**Comment by Liviali155** [comment]
Test on Mantis,jack detection is pass and has no side effect

**Comment by ClarexZhou** [comment]
Tested this PR on lenovo. Mic jack detection works. Still has issue "Trigger again when runtime PM enter suspend" and it's caused by one upstream commit. See https://github.com/thesofproject/linux/pull/1837#issuecomment-605603288. On sof-dev branch, revert that commit directly failed.

@Liviali155 also verified on Mantis. All works ok. Also no side effect.

**Comment by plbossart** [comment]
Can we update this PR to cherry-pick 476c02e0b4fd90 ("ALSA: hda/realtek - a fake key event is triggered by running shutup") and redo the tests?

**Comment by kv2019i** [comment]
@plbossart wrote:
> Can we update this PR to cherry-pick [476c02e](https://github.com/thesofproject/linux/commit/476c02e0b4fd9071d158f6a1a1dfea1d36ee0ffd) ("ALSA: hda/realtek - a fake key event is triggered by running shutup") and redo the tests?

I reviewed that again and that seems orthogonal. As this fix helps with so many machines and has taken so long already, let's go ahead and merge this and fix any follow-ups after the rebase. We anyways still have more issues (like the CML regression https://github.com/thesofproject/linux/issues/1938).

**Comment by plbossart** [comment]
> @plbossart wrote:
> 
> > Can we update this PR to cherry-pick [476c02e](https://github.com/thesofproject/linux/commit/476c02e0b4fd9071d158f6a1a1dfea1d36ee0ffd) ("ALSA: hda/realtek - a fake key event is triggered by running shutup") and redo the tests?
> 
> I reviewed that again and that seems orthogonal. As this fix helps with so many machines and has taken so long already, let's go ahead and merge this and fix any follow-ups after the rebase. We anyways still have more issues (like the CML regression #1938).

@kv2019i I wasn't making this up, this patch was listed in https://github.com/thesofproject/linux/pull/1837#issuecomment-605603288

**Comment by kv2019i** [comment]
@plbossart wrote:
> @kv2019i I wasn't making this up, this patch was listed in [#1837 (comment)](https://github.com/thesofproject/linux/pull/1837#issuecomment-605603288)

Aa, my bad, I didn't check that comment anymore. But alas, it's a regression that also shows up with legacy driver, and now that we align with legacy driver, we hit the regression as well. But it's fixed in upstream, so we should be good once we do the upstream rebase.

**Pull request merged**
