### PR TITLE
SoundWire: add support for link clock source selection

### PR DESCRIPTION
**Pull request by plbossart**
Since CannonLake, we've been using the XTAL oscillator as the link clock source, but since MeteorLake the hardware offers two additional sources: the audio cardinal clock and the internal audio PLL.

Tested on MTL RVP and LNL RVP, with scripts in https://github.com/thesofproject/acpi-scripts/pull/20

One issue was reported for 12.288MHz, the playback is 2x too slow and this is root-caused to a firmware change https://github.com/thesofproject/sof/issues/8251

This PR should not be merged until the firmware issue is better understood.

@bardliao @kv2019i FYI

### CODE REVIEW

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
"This PR should not be merged until the firmware issue is better understood."

It's been 2 weeks and no one looked into this, so let's go ahead and review/merge this capability which does provide the 12 MHz support needed for additional SoundWire work.

**Review by RanderWang — APPROVED** [review]
LGTM

**Review by bardliao — DISMISSED** [review]

**Comment by plbossart** [comment]
SOFCI TEST

**Review by bardliao — APPROVED** [review]

**Pull request merged**
