### PR TITLE
ASoC: SOF: client-probes: Fix couple of doxygen typos

### PR DESCRIPTION
**Pull request by jsarha**
Signed-off-by: Jyri Sarha <jyri.sarha@intel.com>

### CODE REVIEW

**Review by plbossart — CHANGES_REQUESTED** [review]
commit title should start with fixup! and the initial commit title later.

**Comment by plbossart** [comment]
@marc-hb @greg-intel can you help shed light on the 'Merge conflicts'? This PR fixes only a set of typos...

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
Looks like a Github glitch. I found this in Jenkins sofkernel_prs/1187/console

```
22:39:21  GitHub pull request #3935 of commit c2fcb748e259da084edd70b880887b44d589bd50, has merge conflicts.
22:39:58  !!! PR mergeability status has changed !!!  
22:39:58  PR now has NO merge conflicts
         ....
22:40:03  ERROR: Skip PR test with merge conflicts
22:40:03  Finished: FAILURE
```

**Comment by plbossart** [comment]
I'll merge this and deal with the fixup myself. Thanks @jsarha

**Comment by jsarha** [comment]
> commit title should start with fixup! and the initial commit title later.

Oh, was not aware of such function. Is it documented somewhere?

**Comment by ranj063** [comment]
> > commit title should start with fixup! and the initial commit title later.
> 
> Oh, was not aware of such function. Is it documented somewhere?

@jsarha git commit --fixup <HASH>

**Comment by greg-intel** [comment]
UPDATE:  I believe this code was already fixed by https://github.com/intel-innersource/drivers.audio.ci.sof-jenkins/pull/148 
My local source must have been out of date, based on the general timeline.

Sorry for delay, I looked into this a bit, and the CI expects the following string to determine there are no conflicts:
``` JAVA
drivers.audio.ci.sof-jenkins/sofkernel_prs.gvy
104:        if (!ghprbPullDescription.contains('no merge conflicts')){

drivers.audio.ci.sof-jenkins/sof_test_prs.gvy
85:        if (!ghprbPullDescription.contains('no merge conflicts')){

drivers.audio.ci.sof-jenkins/sof_prs.gvy
130:        if (!ghprbPullDescription.contains('no merge conflicts')){
``` 
So in Marc's comment earlier, if GitHub "fixed" the conflict, the message became `PR now has NO merge conflicts` with an uppercase `NO` which our CI doesn't check for.  
At least that looks like what might have happened.

**Pull request merged**
