### PR TITLE
[TEST] SoundWire: PR4241 race condition debug

### PR DESCRIPTION
**Pull request by plbossart**
````diff
diff --git a/drivers/soundwire/intel.c b/drivers/soundwire/intel.c
index 3e0ec6d7d09f..e3efb65c26d0 100644
--- a/drivers/soundwire/intel.c
+++ b/drivers/soundwire/intel.c
@@ -758,6 +758,8 @@ static int intel_prepare(struct snd_pcm_substream *substream,
                return -EIO;
        }
 
+       dev_info(dai->dev, "%s: plb: start\n", __func__);
+
        if (dai_runtime->suspended) {
                dai_runtime->suspended = false;
````

with this single-line change in 4bc3aa86659081cc652162c7c47bcbcb2fb8b10f I am able to get 100% passing tests. They fail 100% otherwise with gcc11

This suggest a race condition around the dai_runtime->suspended flag.

The results were on TGLU_SKU0A32_SDCA with command line:

`TPLG=/lib/firmware/intel/sof-tplg/sof-tgl-rt711-rt1316-rt714.tplg MODEL=TGLU_SKU0A32_SDCA  /root/sof-test/test-case/check-suspend-resume-with-audio.sh -l 1 -m playback`

Let's see if CI devices agree with this first result?

@bardliao @ujfalusi @marc-hb FYI

### CODE REVIEW

**Comment by marc-hb** [comment]
I just had a look at the internal Jenkins page sofkernel_prs/3613/console and discovered that checkpatch has been running for 90 minutes and is still running:

```
12:21:39  Start CheckPatch!
EOF
```

A cap on the number of patches fed to checkpatch would not hurt. 
EDIT: filed new internal jenkins issue number 376


Related to
- https://github.com/thesofproject/linux/issues/2556

cc:
- #4223

**Comment by plbossart** [comment]
> A cap on the number of patches fed to checkpatch would not hurt.

It's a known issue for upstream merges @marc-hb. No one cares about style issues for patches that are already in Linus Torvalds tree, it's just lost time with no one looking at the results.

I don't know how to change this, this is the voodoo magic in jenkins and the CI build system.

**Comment by marc-hb** [comment]
As usual, rescuing these test results from the next force push:
- https://sof-ci.01.org/linuxpr/PR4243/build3614/devicetest/index.html
- https://sof-ci.01.org/linuxpr/PR4243/build3615/devicetest/index.html

**Comment by plbossart** [comment]
no SoundWire issues with https://sof-ci.01.org/linuxpr/PR4243/build3614/devicetest/index.html and https://sof-ci.01.org/linuxpr/PR4243/build3615/devicetest/index.html

**Pull request closed without merging**
