### PR TITLE
Revert "ASoC: SOF: topology: remove embedding kcontrol data into proc…

### PR DESCRIPTION
**Pull request by ranj063**
…ess widget"

This reverts commit d8be50cf0880dc333d0afea63c16763d045a3ef6.
Some components expect data to be sent when the components
are initialized.

fixes https://github.com/thesofproject/linux/issues/2930

### CODE REVIEW

**Comment by ranj063** [comment]
@juimonen we need to keep ths logic for now

**Comment by fredoh9** [comment]
I quickly verified this with TGL Volteer SDW. Working fine as usual. Let's merge this before 2 PM PST. So that this revert can be included in today daily test.

**Review by fredoh9 — APPROVED** [review]

**Review by kv2019i — APPROVED** [review]
Ok, let's take this back.

**Comment by juimonen** [comment]
We need to unify the component logic. Currently we have components behaving different ways: eq can be initialized at prepare, but some components expect private data at init. I don't why we could not do that, the logic has just been drifting between components...

**Comment by ranj063** [comment]
@juimonen im not sure its worth it. if you do unify the logic, we'll still have to maintain the code in the kernel for backward compatibility

**Comment by juimonen** [comment]
yeah I'm fine whatever. It is just "ugly" that we now send anyway the control data 2 times, so it could be cleaned. Also we would get rid of initial loading size restriction (large msg is only for controls) -> so for example in kwd case you need to first initialize with something partial/small, then later send the actual blob with kcontrol. This works for chrome because of ucm.

but yeah if we are running new kernel / old firmware combo -> doesn't work without still having the same code in kernel

**Comment by juimonen** [comment]
actually now thinking of it... all the firmware components _should_ handle 0 private initialization data -> current code in kernel just doesn't send anything if the blob is larger than ipc max size. At least they should check it exists as good programming practice.

**Pull request merged**
