### PR TITLE
[HACK][DO NOT MERGE] es8336 support

### PR DESCRIPTION
**Pull request by plbossart**
added just for reference, this needs to be cleaned-up by codec vendor

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

### CODE REVIEW

**Comment by katyo** [comment]
@plbossart @hli25

With this patch I got working sound on new __Teclast F5__ with __ES8316__ codec.
I tested playback via builtin speakers and via jack 3.5 headset. Also I tested audio recording via builtin mic set.
It amazingly works fine. The suspend/resume also works without issues. Great thanks.

I'm on linux 5.14.9 from NixOS. I applied patches (from patchwork) to add support the __ES8336__. Also I updated _sof-firmware_ to v1.9
This is my fixes for NixOS config https://gist.github.com/katyo/1246ad22ce61be943f30092fc92438f9

**Comment by plbossart** [comment]
> @plbossart @hli25
> 
> With this patch I got working sound on new **Teclast F5** with **ES8316** codec. I tested playback via builtin speakers and via jack 3.5 headset. Also I tested audio recording via builtin mic set. It amazingly works fine. The suspend/resume also works without issues. Great thanks.
> 
> I'm on linux 5.14.9 from NixOS. I applied patches (from patchwork) to add support the **ES8336**. Also I updated _sof-firmware_ to v1.9 This is my fixes for NixOS config https://gist.github.com/katyo/1246ad22ce61be943f30092fc92438f9

Thanks for testing @katyo. Unfortunately this PR is not suitable for upstream, the code quality is way too low. We'll have to see when the codec vendor finally provides a cleaner version.

**Comment by rbreaves** [comment]
I think I was reading that this or some similar patch was being included with the 5.16 mainline kernel, so I installed the RC4 version and my sound is still not working.

Running dmesg I see this. If I can provide more then just let me know.
```
[   13.107679] sof-audio-pci-intel-icl 0000:00:1f.3: error: cl_copy_fw: timeout HDA_DSP_SRAM_REG_ROM_STATUS read
[   13.108199] sof-audio-pci-intel-icl 0000:00:1f.3: ------------[ DSP dump start ]------------
[   13.108202] sof-audio-pci-intel-icl 0000:00:1f.3: fw_state: SOF_FW_BOOT_IN_PROGRESS (2)
[   13.108215] sof-audio-pci-intel-icl 0000:00:1f.3: extended rom status:  0x80000012 0x2c 0x0 0x0 0x0 0x0 0x2100186 0x0
[   13.108217] sof-audio-pci-intel-icl 0000:00:1f.3: ------------[ DSP dump end ]------------
[   13.108219] sof-audio-pci-intel-icl 0000:00:1f.3: error: load fw failed ret: -110
[   13.108242] sof-audio-pci-intel-icl 0000:00:1f.3: error: failed to start DSP
[   13.108244] sof-audio-pci-intel-icl 0000:00:1f.3: error: failed to boot DSP firmware -110
[   13.158736] sof-audio-pci-intel-icl 0000:00:1f.3: error: hda_dsp_core_reset_enter: timeout on HDA_DSP_REG_ADSPCS read
[   13.158745] sof-audio-pci-intel-icl 0000:00:1f.3: error: dsp core reset failed: core_mask 1
[   13.159040] sof-audio-pci-intel-icl 0000:00:1f.3: error: sof_probe_work failed err: -110
```

I've only custom compile linux kernels for smartphones, so trying that on my desktop might take some trial and error vs downloading a precompiled one.

**Comment by plbossart** [comment]
> ```
> [   13.107679] sof-audio-pci-intel-icl 0000:00:1f.3: error: cl_copy_fw: timeout HDA_DSP_SRAM_REG_ROM_STATUS read
> [   13.108199] sof-audio-pci-intel-icl 0000:00:1f.3: ------------[ DSP dump start ]------------
> [   13.108202] sof-audio-pci-intel-icl 0000:00:1f.3: fw_state: SOF_FW_BOOT_IN_PROGRESS (2)
> [   13.108215] sof-audio-pci-intel-icl 0000:00:1f.3: extended rom status:  0x80000012 0x2c 0x0 0x0 0x0 0x0 0x2100186 0x0
> [   13.108217] sof-audio-pci-intel-icl 0000:00:1f.3: ------------[ DSP dump end ]------------
> [   13.108219] sof-audio-pci-intel-icl 0000:00:1f.3: error: load fw failed ret: -110
> [   13.108242] sof-audio-pci-intel-icl 0000:00:1f.3: error: failed to start DSP
> [   13.108244] sof-audio-pci-intel-icl 0000:00:1f.3: error: failed to boot DSP firmware -110
> [   13.158736] sof-audio-pci-intel-icl 0000:00:1f.3: error: hda_dsp_core_reset_enter: timeout on HDA_DSP_REG_ADSPCS read
> [   13.158745] sof-audio-pci-intel-icl 0000:00:1f.3: error: dsp core reset failed: core_mask 1
> [   13.159040] sof-audio-pci-intel-icl 0000:00:1f.3: error: sof_probe_work failed err: -110
> ````

@rbreaves this looks like a firmware authentication issue that was solved with the release 1.9.2 of the sof-bin package.

https://github.com/thesofproject/sof/issues/4916

Can you update the firmware and retry? Thanks!

**Comment by rbreaves** [comment]
@plbossart I would but I have decided to get rid of the hardware that has this sound chip in it. It has been too much of a hassle for me and the company that made it refuses to even provide me with the Windows driver to make it functional even with Windows. I would rather get rid of a product that has 0 support for any OS at all.

I appreciate the work you guys are doing and I am sure it'll eventually work just fine under Linux. Also I ended up trying a custom compiled 5.12.6 kernel that has this patch integrated in it and it did not appear to work there either, but no idea if they really compiled it properly. I was also discouraged that kernel's 5.13-5.16 appear to have dropped support for its touchpad as well or a regression made it into the kernel. Regardless I also purchased a Surface Pro 6 and I am more than happy to use linux on it since it appears to be better supported.

**Comment by lutzseverino** [comment]
Hey there, a family member got the Huawei D 15 and, as all of you might expect, the sound isn't working under Fedora 35.
Is this solution working? If so, can someone help me apply this somehow? I'm experienced but I actually have not compiled anything, never really needed to.

**Comment by plbossart** [comment]
> Hey there, a family member got the Huawei D 15 and, as all of you might expect, the sound isn't working under Fedora 35. Is this solution working? If so, can someone help me apply this somehow? I'm experienced but I actually have not compiled anything, never really needed to.

We've provided all the quirks that we were aware of, but I am not aware of any 'success' results on D15. See https://github.com/thesofproject/linux/issues/3248. @eworm-de reported they could probe a card but not hear anything.

**Comment by lutzseverino** [comment]
> > Hey there, a family member got the Huawei D 15 and, as all of you might expect, the sound isn't working under Fedora 35. Is this solution working? If so, can someone help me apply this somehow? I'm experienced but I actually have not compiled anything, never really needed to.
> 
> We've provided all the quirks that we were aware of, but I am not aware of any 'success' results on D15. See #3248. @eworm-de reported they could probe a card but not hear anything.

What a shame, I'll have to reinstall Windows on the machine, at least until this is resolved.
I wouldn't do that myself but since the computer isn't mine... can't let it without sound.

**Comment by hli25** [comment]
nice to loop @yangxiaohua2009 from codec vendor Everest-semi

**Comment by yangxiaohua2009** [comment]
Device properties like jack-invert and mic source should be provided in ACPI but is not done by ODMs. With the current driver, the user has a 50% chance of having a wrong/inverted jack detection, and the user need to mannually open the Speaker at every system start up. Is there a way to fix this? @hli25

**Comment by plbossart** [comment]
@hli25 @yangxiaohua2009 I rebased this PR but I am not sure what to make of this codec driver. Either it's updated or we close it. It's not in our charter to fix codec issues.

**Comment by yangxiaohua2009** [comment]
Close this please

**Comment by ghost** [comment]
Hi, any news for the cml one? I have a Matebook D15 i5-10210u, like https://github.com/thesofproject/sof/issues/4939 and hope not to move back to weirdos just for audio. If you need I can make all the test you want (if you want please tell me if there is some sort of chat where to talk faster)

**Pull request closed without merging**
