### PR TITLE
RFC: ASoC: SOF: IPC Abstraction - WIP [DO NOT REVIEW YET]

### PR DESCRIPTION
**Pull request by lgirdwood**
Abstract all the IPC specific APIs into a seperate directory structure
so that other IPC mechanisms can be used (detected at FW boot).

This moves all IPC specific functions and code blocks from core into a new separate directory and kernel module and allows SOF support for other IPCs like Intel closed source FW IPC.

This patch is invasive, but it is mostly mecahnical function or code block movement. The only new feature code is the support for detecting IPC flavour at FW boot and Kconfig option to support IPC flavours.

Compile tested onlly.

TODO: 
1) Move IPC headers - include/sound/sof/*.h to include/sound/sof-ipc-v1/*.h - **DONE**
2) Remove any remaining IPC structures from core (only a few in sof-priv.h now and platform IPC like byt.c now).
3) byt_get_reply() (and same function on other platforms needs to be generic)

@ranj063 I'm going to have to hand this on to you. It will be best for this to be done alongside MFD since both are mechanical code movements that are invasive and will conflict.

Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>

### CODE REVIEW

**Comment by ranj063** [comment]
@lgirdwood ack! I have just finished up the MFD changes. While that is under review, I can take up the task of IPC abstraction on top of that.

**Comment by lgirdwood** [comment]
@ranj063 great, you may want to see which will be easier to merge first - this one is +3.5k and - 2k lines of code. This PR also needs some completion on the items above and some validation. 
The general intention is that SOF core code should NOT include any IPC ABI headers or structures and this should all be abstracted.

Btw, looking at the end result may help you make more sense of the PR rather than only reviewing the diff.

**Comment by lgirdwood** [comment]
@cujomalainey fyi, this will allow the SOF driver to support the closed source FW too and allow us to prune the driver code we have upstream in the kernel.

**Comment by cujomalainey** [comment]
@lgirdwood ack. Thanks for the heads up.

**Comment by plbossart** [comment]
Closing, this PR has not moved since Sept 27

**Pull request closed without merging**
