### PR TITLE
Merge/sound upstream 20201125

### PR DESCRIPTION
**Pull request by bardliao**
Weekly upstream merge.

### CODE REVIEW

**Comment by RanderWang** [comment]
@bardliao  please check it on tgl-03 (VOL).   speaker can't work with this PR.

**Review by kv2019i — APPROVED** [review]
I can't test the SDW speaker case mentioned, so I'll leave it to you @bardliao to check that out.
Otherwise looks clean. Did local tests on TGL and JSL and all good.

**Comment by bardliao** [comment]
> @bardliao please check it on tgl-03 (VOL). speaker can't work with this PR.

This is #2584 and it can be fixed by #2585

**Comment by bardliao** [comment]
pr-device-test is passed. I will go ahead to merge it.

**Pull request merged**
