### PR TITLE
[WORKAROUND] ASoC: SOF: trace: drop invalid trace position update

### PR DESCRIPTION
**Pull request by xiulipan**
If DMA trace buffer position update IPC comes when HOST is sending
CTX_SAVE, the position info in mailbox may be invalid. Drop the
invalid position to avoid wrong overflow error.
TODO: Fix the race condition of IPC RX when IPC TX with CTX_SAVE

Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>

This is a workaround for https://github.com/thesofproject/linux/issues/2576 to un-block validation.

### CODE REVIEW

**Comment by kv2019i** [comment]
@xiulipan Do you want this to be merged to sof-dev? This clearly is not something we can push upstream (at least no in this form).

**Comment by xiulipan** [comment]
@kv2019i No, this is a temp workaround to unblock validation.
But I also find the the same race condition will result in #2458, please see detail in https://github.com/thesofproject/linux/issues/2576

**Comment by keyonjie** [comment]
@xiulipan as here the FW has the early awareness of the power supply to memory windows (during handling to CTX_SAVE IPC), so it looks to me that handling this kind of race condition inside the FW is more easy. e.g. don't send any memory window related  FW initiated IPC once the memory window is already powered off.

@slawblauciak @mrajwa FYI.

**Comment by lyakh** [comment]
@xiulipan don't you think it's the same as #2334 in which case invalid values aren't always `0xffffffff`?

**Comment by xiulipan** [comment]
@lyakh Please see https://github.com/thesofproject/linux/issues/2576 for detail. They should be same race condition.

**Comment by xiulipan** [comment]
close as we have solution in FW side https://github.com/thesofproject/sof/pull/3786

**Pull request closed without merging**
