### PR TITLE
Merge/sound upstream 20230208

### PR DESCRIPTION
**Pull request by ujfalusi**
This is long due...

Let's see how it looks like this time. Local smoke test was OK.

### CODE REVIEW

**Comment by plbossart** [comment]
rtcwrite FAIL in a couple of tests https://sof-ci.01.org/linuxpr/PR4182/build3098/devicetest/index.html
That looks new?

**Comment by ranj063** [comment]
> rtcwrite FAIL in a couple of tests https://sof-ci.01.org/linuxpr/PR4182/build3098/devicetest/index.html That looks new?

Yup these are definitely new

**Comment by ujfalusi** [comment]
and I can not see anything helpful in the kernel logs for those. Strange.

**Comment by plbossart** [comment]
And of course my SoundWire PR conflicted with the changes done upstream by Cirrus Logic. Gah.

**Comment by plbossart** [comment]
FWIW, I don't see any errors when 'just' merging v6.2-rc7 @ujfalusi, see https://github.com/thesofproject/linux/pull/4188

**Comment by ujfalusi** [comment]
replaced by another attempt: #4197

**Pull request closed without merging**
