### PR TITLE
fixup! soundwire: stream: uniquify dev_err() logs

### PR DESCRIPTION
**Pull request by plbossart**

### CODE REVIEW

**Review by RanderWang — APPROVED** [review]

**Review by aiChaoSONG — APPROVED** [review]

**Review by bardliao — APPROVED** [review]

**Review by ujfalusi — APPROVED** [review]

**Comment by ujfalusi** [comment]
@plbossart, can we keep this open for a while meanwhile GitHub investigates the merge issue?
Yep, I can not merge this either.

In my ticket I referred to this PR.

**Comment by plbossart** [comment]
Cannot merge either @ujfalusi @lgirdwood. it's crazy.

**Comment by plbossart** [comment]
Still cannot rebase and merge.

**Comment by ujfalusi** [comment]
fwiw, I have given this PR as an example of not merge able one, can we not merge it with hand, please?

**Comment by ujfalusi** [comment]
otoh, it looks like all PR is unmergable from web...

**Comment by plbossart** [comment]
oh well, something changed @ujfalusi. I was able to merge this somehow, the 10s timeout coming back to 'confirm rebase and merge' didn't happen.

**Pull request merged**
