### PR TITLE
Merge/sound upstream 20230919

### PR DESCRIPTION
**Pull request by ujfalusi**
Hi,

second attempt of v6.6-rcX upstream merge.

Replaces #4584

### CODE REVIEW

**Comment by ujfalusi** [comment]
@plbossart, I think it looks OK this time.

**Comment by plbossart** [comment]
MTLP_RVP_NOCODEC: notrun!

let's redo the test

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
@ujfalusi test results are as good as can be - only one pause push/release issue but that's a known issue with firmware. Let's merge this, shall we?

**Comment by ujfalusi** [comment]
> @ujfalusi test results are as good as can be - only one pause push/release issue but that's a known issue with firmware. Let's merge this, shall we?

I have run the daily tests on this and it looks OK (stable v2.2 is identically not good as the current daily)

**Pull request merged**
