### PR TITLE
Upstream/test routes

### PR DESCRIPTION
**Pull request by plbossart**
Patches shared by @crojewsk-intel on https://lore.kernel.org/alsa-devel/20240308090502.2136760-1-cezary.rojewski@intel.com/T/#m0f605bdc26219ae7513550be1f4499de9cf4d67f

### CODE REVIEW

**Comment by plbossart** [comment]
Humm, we have one alsa-bat failure that I don't think was reported before

https://sof-ci.01.org/linuxpr/PR4854/build1754/devicetest/index.html?model=MTLP_RVP_HDA&testcase=check-alsabat-headset-capture-997

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by crojewsk-intel** [comment]
Thanks for testing this out! I see one failure indeed but nothing that points to missing DAPM routes. At least Ctrl+F does not show anything.

**Comment by plbossart** [comment]
no issue in https://sof-ci.01.org/linuxpr/PR4854/build1758/devicetest/index.html?model=MTLP_RVP_HDA&testcase=check-alsabat-headset-capture-997

That was on sh-mtlp-rvp-hda-03.sh.intel.com, the initial issue was on sh-mtlp-rvp-hda-04.sh.intel.com, so I would guess it's a device configuration issue? Re-running the tests.

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
https://sof-ci.01.org/linuxpr/PR4854/build1767/devicetest/index.html and https://sof-ci.01.org/linuxpr/PR4854/build1768/devicetest/index.html have a number of DSP panics....

@kv2019i probably another firmware issue?

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by crojewsk-intel** [comment]
I not see any failures which would be caused by the patchset in question. Are we good to go?

**Comment by plbossart** [comment]
SOFCI TEST

**Pull request closed without merging**
