### PR TITLE
AMD SOF based generic SoundWire machine driver

### PR DESCRIPTION
**Pull request by vijendarmukunda**
This patch series is rebase version of https://github.com/thesofproject/linux/pull/5017.

### CODE REVIEW

**Comment by vijendarmukunda** [comment]
@plbossart : could you please review the patch series?

**Comment by plbossart** [comment]
you may want to fix those warnings. They were probably in the initial code.

````
WARNING: struct snd_soc_ops should normally be const
#557: FILE: sound/soc/intel/boards/sof_sdw_common.h:168:
+extern struct snd_soc_ops soc_sdw_rt1308_i2s_ops;

WARNING: struct snd_soc_ops should normally be const
#936: FILE: sound/soc/intel/boards/sof_sdw_rt_amp.c:236:
+struct snd_soc_ops soc_sdw_rt1308_i2s_ops = {
````

**Comment by vijendarmukunda** [comment]
> you may want to fix those warnings. They were probably in the initial code.
> 
> ```
> WARNING: struct snd_soc_ops should normally be const
> #557: FILE: sound/soc/intel/boards/sof_sdw_common.h:168:
> +extern struct snd_soc_ops soc_sdw_rt1308_i2s_ops;
> 
> WARNING: struct snd_soc_ops should normally be const
> #936: FILE: sound/soc/intel/boards/sof_sdw_rt_amp.c:236:
> +struct snd_soc_ops soc_sdw_rt1308_i2s_ops = {
> ```

These warnings fix was taken care after moving the code to sdw_utils folder.

**Comment by vijendarmukunda** [comment]
> you may want to fix those warnings. They were probably in the initial code.
> 
> ```
> WARNING: struct snd_soc_ops should normally be const
> #557: FILE: sound/soc/intel/boards/sof_sdw_common.h:168:
> +extern struct snd_soc_ops soc_sdw_rt1308_i2s_ops;
> 
> WARNING: struct snd_soc_ops should normally be const
> #936: FILE: sound/soc/intel/boards/sof_sdw_rt_amp.c:236:
> +struct snd_soc_ops soc_sdw_rt1308_i2s_ops = {
> ```

Fixed check patch warning.

**Comment by plbossart** [comment]
sorry @vijendarmukunda both @bardliao and I are busy with other issues, we'll look into this when we have more time. Thanks for your understanding.

**Pull request closed without merging**
