### PR TITLE
2 non-critical fixes

### PR DESCRIPTION
**Pull request by lyakh**
The first fix is cosmetic, the second one is functional, but it doesn't seem to fix anything.

### CODE REVIEW

**Comment by ranj063** [comment]
looks good @lyakh. I'd asked @zhuyingjiang to fix the second commit you have in his PR. But I think the wakests clear isnt even needed as it is done again a little later in the same function.

**Comment by ranj063** [comment]
@lyakh this PR can be closed now that the first commit is applied upstream and the second one is no longer relevant after yingjiang's PR?

**Comment by lyakh** [comment]
> @lyakh this PR can be closed now that the first commit is applied upstream and the second one is no longer relevant after yingjiang's PR?

@ranj063 which PR from @zhuyingjiang are you referring to?

**Comment by ranj063** [comment]
@lyakh https://github.com/thesofproject/linux/pull/1020

**Comment by lyakh** [comment]
the first patch will be merged via the ALSA tree, the second one is made redundant by #1020

**Pull request closed without merging**
