### PR TITLE
ASoC: LunarLake: fixes for 2-amp aggregation

### PR DESCRIPTION
**Pull request by plbossart**
So far we only tested the single-link case, and with more testing in the 2-link 2-amplifier case the following patches were required to avoid confusions in state machines. tested with the sdw-mockup on playback and capture with the bus loopback.

### CODE REVIEW

**Review by ranj063 — DISMISSED** [review]

**Comment by marc-hb** [comment]
SOFCI TEST

**Review by bardliao — DISMISSED** [review]
Thanks @plbossart

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
Hold for now, it's not clear if we want to filter the triggers on the first cpu_dai or use a different solution suggested by @ranj063

**Comment by plbossart** [comment]
v2: remove the patch to trigger only for the first cpu dai and added a more generic patch suggested by Ranjani ("ASoC: SOF: ipc4: avoid uninitialized default instance 0")

**Review by bardliao — APPROVED** [review]

**Review by ranj063 — APPROVED** [review]
looks good @plbossart. The second patch is missing your sign-off though

**Comment by plbossart** [comment]
> looks good @plbossart. The second patch is missing your sign-off though

that's ok, we only need to add it to send patches upstream. it's not strictly required for initial github contributions.

**Pull request merged**
