### PR TITLE
Revert "ACPI: PM: s2idle: Prevent spurious SCIs from waking up the sy…

### PR DESCRIPTION
**Pull request by kv2019i**
This reverts commit fdde0ff8590b4c1c41b3227f5ac4265fccccb96b.

Fixes: #1815

Signed-off-by: Kai Vehmanen <kai.vehmanen@linux.intel.com>

### CODE REVIEW

**Comment by plbossart** [comment]
@kv2019i the revert is fine but have you notified ACPI folks of the issue?

**Comment by kv2019i** [comment]
> @kv2019i the revert is fine but have you notified ACPI folks of the issue?

Ack, already reported and got a response:
https://lore.kernel.org/linux-acpi/10791544.HYfhKnFLvn@kreacher/

Let's merge the proposed fix to sof-dev (and not the revert), so it will be easier to take in via upstream rebase.

FYI for @ranj063  as well

**Comment by kv2019i** [comment]
Once a patch is merged to linux-pm or further upstream, we should pick it up:
https://lore.kernel.org/linux-acpi/10791544.HYfhKnFLvn@kreacher/

[PATCH] ACPI: PM: s2idle: Check fixed wakeup events in acpi_s2idle_wake()

**Comment by plbossart** [comment]
> Once a patch is merged to linux-pm or further upstream, we should pick it up:
> https://lore.kernel.org/linux-acpi/10791544.HYfhKnFLvn@kreacher/
> 
> [PATCH] ACPI: PM: s2idle: Check fixed wakeup events in acpi_s2idle_wake()

Add solution picked up by Linus in PR #1820

**Comment by plbossart** [comment]
replaced by PR #1820

**Pull request closed without merging**
