### PR TITLE
[DO NOT MERGE] Merge/sound upstream 20230306 (v6.3-rc1)

### PR DESCRIPTION
**Pull request by ujfalusi**
a fresh tag of 6.3-rc1, this time I have not tested locally, let's see what CI thinks of this....

### CODE REVIEW

**Comment by plbossart** [comment]
@ujfalusi looks like CI declined to test this, all results are borked?

**Comment by fredoh9** [comment]
SOF CI devices are not back to online with this pr's kernel image.

Found this errors from jf-tglu-rvp-nocodec-1 device,

```
[    2.539153] systemd[1]: systemd-modules-load.service: Main process exited, code=exited, status=1/FAILURE
[    2.539262] systemd[1]: systemd-modules-load.service: Failed with result 'exit-code'.
[    2.539424] systemd[1]: Failed to start Load Kernel Modules.
```

**Comment by marc-hb** [comment]
> a fresh tag of 6.3-rc1, this time I have not tested locally, let's see what CI thinks of this....

@fredoh9 and @greg-intel had  to recover some devices manually. In theory `grub-reboot` should have saved us but in practice theory and practice are different.

Could you please give it a very basic and quick smoke test next time? Should catch the most obvious regressions...

**Comment by plbossart** [comment]
zero problems with this PR on TGLU_SKU0A32_SDCA with 2.2 production-signed firmware - but I don't use the 'saved' option for grub, only GRUB_DEFAULT=0

````
PASS: tplg-binary; pcm_list; playback-d100l1r1; capture-d100l1r1; playback-d1l100r1; capture_d1l100r1; playback_d1l1r50; capture_d1l1r50; speaker; pause-resume-playback; pause-resume-capture; volume; signal-stop-start-playback; signal-stop-start-capture; multiple-pipeline-playback; multiple-pipeline-capture; multiple-pause-resume; kmod-load-unload; kmod-load-unload-after-playback; suspend-resume; suspend-resume-with-playback; suspend-resume-with-capture;
````

**Comment by plbossart** [comment]
zero problems with this PR on TGLU_SKU0A32_SDCA with 2.2 production-signed firmware - but I don't use the 'saved' option for grub, only GRUB_DEFAULT=0

````
PASS: tplg-binary; pcm_list; playback-d100l1r1; capture-d100l1r1; playback-d1l100r1; capture_d1l100r1; playback_d1l1r50; capture_d1l1r50; speaker; pause-resume-playback; pause-resume-capture; volume; signal-stop-start-playback; signal-stop-start-capture; multiple-pipeline-playback; multiple-pipeline-capture; multiple-pause-resume; kmod-load-unload; kmod-load-unload-after-playback; suspend-resume; suspend-resume-with-playback; suspend-resume-with-capture;
````

**Comment by fredoh9** [comment]
> Found this errors from jf-tglu-rvp-nocodec-1 device,
> 
> ```
> [    2.539153] systemd[1]: systemd-modules-load.service: Main process exited, code=exited, status=1/FAILURE
> [    2.539262] systemd[1]: systemd-modules-load.service: Failed with result 'exit-code'.
> [    2.539424] systemd[1]: Failed to start Load Kernel Modules.
> ```

However,
sh-adlp-rvp-sdw-02 doesn't have same error. After force power cycle, it booted fine and online with this pr kernel. Strange.

**Comment by ujfalusi** [comment]
@marc-hb, I did while CI was still building and it looked fine on local devices, otherwise I would have stopped the jobs.

**Comment by ujfalusi** [comment]
SOF  CI TEST

**Comment by ujfalusi** [comment]
I have also tested on APL (up2) locally and it is fine as well, like my TGL devices.

**Comment by marc-hb** [comment]
Please don't SOF CI TEST until we figure out what's wrong, otherwise we're going to lose systems again.

**Comment by ujfalusi** [comment]
@marc-hb, @fredoh9, @plbossart, I have found the reason why none of the machines booted up with the CI built kernel.

The kernel boots, but for some reason the
`linux-image-6.3.0-rc1-pr4223-3445-default-g25f0073e4654_6.3.0-rc1-25f0073e_amd64.deb`
installs:
```
ls -al /boot/ | grep 6.3
-rw-r--r--  1 root root  8034670 Mar  6 16:22 System.map-6.3.0-rc1-pr4223-3445-default-g25f0073e4654
-rw-r--r--  1 root root   184087 Mar  6 16:22 config-6.3.0-rc1-pr4223-3445-default-g25f0073e4654
-rw-r--r--  1 root root 15519101 Mar  7 07:55 initrd.img-6.3.0-rc1-pr4223-3445-default-g25f0073e4654
-rw-r--r--  1 root root 14410496 Mar  6 16:22 vmlinuz-6.3.0-rc1-pr4223-3445-default-g25f0073e4654

ls -al /lib/modules/ | grep 6.3
drwxr-xr-x   3 root root 4096 Mar  7 07:55 6.3.0-rc1-pr4223-3445-default-g25f0073e4654
```
but the booted `vmlinuz-6.3.0-rc1-pr4223-3445-default-g25f0073e4654` is looking for modules under `6.3.0-rc1` directory!!!
```
uname  -a
Linux the-ci-machine-name 6.3.0-rc1 #25f0073e SMP PREEMPT_DYNAMIC Mon Mar  6 08:28:16 PST 2023 x86_64 x86_64 x86_64 GNU/Linux
```

So I did this:
```
cd  /lib/modules/ 
sudo ln -sf 6.3.0-rc1-pr4223-3445-default-g25f0073e4654 6.3.0-rc1

ls -al /lib/modules/ | grep 6.3
lrwxrwxrwx   1 root root   43 Mar  7 08:31 6.3.0-rc1 -> 6.3.0-rc1-pr4223-3445-default-g25f0073e4654
drwxr-xr-x   3 root root 4096 Mar  7 07:55 6.3.0-rc1-pr4223-3445-default-g25f0073e4654

sudo reboot; exit
```
and the board boots up just fine...
the config have:
CONFIG_LOCALVERSION=""
CONFIG_LOCALVERSION_AUTO=y

Something changed with 6.3 regarding to this?

**Comment by plbossart** [comment]
@ujfalusi the kernel I installed uses the full version:

````
[root@fedora-sdca ~]# uname -a
Linux fedora-sdca 6.3.0-rc1-test-05827-g863ad81a6aa9 #77 SMP PREEMPT_DYNAMIC Mon Mar  6 16:47:17 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
````

I have no idea what causes the CI builds to use the plain 6.3.0-rc1? Clearly there's something different in our build setups.

**Comment by ujfalusi** [comment]
@plbossart, I took the deb package from the CI build...

**Comment by marc-hb** [comment]
CI should build the kernel.dpkg using something like this:
https://thesofproject.github.io/latest/getting_started/build-guide/build-from-scratch.html#step-6-build-linux-kernel

**Comment by plbossart** [comment]
> CI should build the kernel.dpkg using something like this: https://thesofproject.github.io/latest/getting_started/build-guide/build-from-scratch.html#step-6-build-linux-kernel

Or use the same sequences as in GitHub Actions... Creativity in build systems is not a good idea in general.

**Comment by marc-hb** [comment]
Also, the kernel.deb should normally have the .config embedded in it: `modprobe configs; zcat /proc/config.gz`

> Or use the same sequences as in GitHub Actions... Creativity in build systems is not a good idea in general.

While I'm usually a broken record with this, this case is a bit different: Github Actions don't need to spend a long time and some unicorns creating a Debian package for deployment.

They should of course use the very same kconfig scripts. We don't have proof yet of a divergence there.

**Comment by ujfalusi** [comment]
@marc-hb , yes the .deb have the.config, it is the same as I got via /proc/config.gz after I have created the symlink to make the remote machine boot. I also built the same config locally with the same result.

@plbossart, what are the LOCALVERSION settings are in your config?

**Comment by plbossart** [comment]
@ujfalusi I don't have a LOCALVERSION, what I have is a localversion file:

````
/data/pbossart/ktest/sof-dev-build$ cat localversion 
-test

/data/pbossart/ktest/sof-dev-build$ grep LOCALVERSION .config
CONFIG_LOCALVERSION=""
CONFIG_LOCALVERSION_AUTO=y
````

**Comment by ujfalusi** [comment]
@plbossart, this is puzzling:
```
# dpkg-deb -R linux-image-6.3.0-rc1-pr4223-3445-default-g25f0073e4654_6.3.0-rc1-25f0073e_amd64.deb out
# rg LOCALVERSION out/boot/config-6.3.0-rc1-pr4223-3445-default-g25f0073e4654 
32:CONFIG_LOCALVERSION=""
33:CONFIG_LOCALVERSION_AUTO=y
```
This is the deb package CI built and deployed. :shrug:

**Comment by ujfalusi** [comment]
Likely among these commits (scripts/setlocalversion):
```
6ab7e1f95e96 setlocalversion: use only the correct release tag for git-describe (<--- by the commit message)
eed36d775177 setlocalversion: clean up the construction of version output
ec31f868ec67 setlocalversion: absorb $(KERNELVERSION)
75280bdf49b2 setlocalversion: make indentation shallower
992ebfab2a75 setlocalversion: simplify the construction of the short version
f6e09b07cc12 kbuild: do not put .scmversion into the source tarball
```

**Comment by fredoh9** [comment]
One thing forgot to mention, even boot fine with this kernel, there is USB recognition issue. USB keyboard and USB ethernet dongle didn't work.

**Comment by ujfalusi** [comment]
This is the commit which breaks things:
eed36d775177 ("setlocalversion: clean up the construction of version output")

**Comment by ujfalusi** [comment]
> This is the commit which breaks things: [eed36d7](https://github.com/thesofproject/linux/commit/eed36d77517786e4b3a9f17c6a66c6df2fc99442) ("setlocalversion: clean up the construction of version output")

No, this still looks fine...

**Comment by ujfalusi** [comment]
> One thing forgot to mention, even boot fine with this kernel, there is USB recognition issue. USB keyboard and USB ethernet dongle didn't work.

The ones I have are working (keyboard and USB dongle)

**Comment by ujfalusi** [comment]
OK, I think this:
3ab18a625ce4 ("kbuild: deb-pkg: improve the usability of source package")
and that in the build script we pass `KDEB_PKGVERSION=$(make kernelversion)-$GITSHA`
The `KERNELRELEASE` and `KBUILD_BUILD_VERSION` extracted from `KDEB_PKGVERSION` and it is present in the vmlinuz instead of the string we would expect.

So, if you:
```
make bindeb-pkg LOCALVERSION=-szervusz
# extract the vmlinuz
strings vmlinuz-6.3.0-rc1-szervusz-05827-g863ad81a6aa9-dirty | grep 6.3.0
6.3.0-rc1-szervusz-05827-g863ad81a6aa9-dirty (me@machine) #114 SMP PREEMPT_DYNAMIC Wed Mar  8 12:55:06 EET 2023
```
```
make bindeb-pkg LOCALVERSION=-szervusz KDEB_PKGVERSION=$(make kernelversion)-pssszt
# extract the vmlinuz
strings vmlinuz-6.3.0-rc1-szervusz-05827-g863ad81a6aa9-dirty | grep 6.3.0
6.3.0-rc1 (me@machine) #pssszt SMP PREEMPT_DYNAMIC Wed Mar  8 13:00:28 EET 2023
```
Notice:
`6.3.0-rc1-szervusz-05827-g863ad81a6aa9-dirty` **VS** `6.3.0-rc1`
`#114` **VS** `#pssszt`

It is also possible that the `make kernelversion` did something differently, but I think it was not taking the LOCALVERSION into account.

Update: the same command on 6.2.0 based sof-dev:
```
make bindeb-pkg LOCALVERSION=-szervusz KDEB_PKGVERSION=$(make kernelversion)-pssszt
# extract the vmlinuz
strings ../vmlinuz-6.2.0-rc8-szervusz-05836-gbe9a23bcb123-dirty | grep 6.2.0 
6.2.0-rc8-szervusz-05836-gbe9a23bcb123-dirty (me@machine) #pssszt SMP PREEMPT_DYNAMIC Wed Mar  8 13:14:46 EET 2023
```
So, it is a recent change.

**Comment by marc-hb** [comment]
> strings vmlinuz-**6.3.0-rc1-szervusz-05827-g863ad81a6aa9-dirty** | grep 6.3.0
> **6.3.0-rc1** (me@machine) #pssszt SMP PREEMPT_DYNAMIC Wed Mar  8 13:00:28 EET 2023

Before even getting into any backwards compatibility discussion, isn't this mismatch a bug? I mean whatever is the user interface of the day, shouldn't these two always agree?

**Comment by marc-hb** [comment]
>  I mean whatever is the user interface of the day, shouldn't these two always agree?

This looks like a "yes there is a bug, wait for a fix":

https://lore.kernel.org/lkml/CAK7LNAT6OwZB6bVHtTtzZa+2syKwGXid9MA_VTGe2ZTRyoHmoQ@mail.gmail.com/

(thx @plbossart)

**Comment by ujfalusi** [comment]
Converting to draft and pushed a revert to 3ab18a625ce42.

We need to do a new merge anyways as we got lots of patches in since I have opened this PR.

**Comment by ujfalusi** [comment]
OK, I would have been really surprised if a fresh -rc1 does not have suspend/resume issue.
The two SoundWire device is failing it: ADLP_RVP_SDW_IPC4ZPH and TGLU_RVP_SDW_IPC4ZPH, for first glance I don't see anything in the kernel log, it must be SDW specific, audio is not resuming after wakeup.

Unfortunately I don't have local device where I can test this. @plbossart are you able to reproduce this locally?

**Comment by plbossart** [comment]
Last time we had such FAILs it boiled down to compiler issues... I'll try to reproduce this later today @ujfalusi

**Comment by marc-hb** [comment]
> Last time we had such FAILs it boiled down to compiler issues... 

For the record this was #4203 . There were failures with more than one toolchain version. We ignored them and standardized on some more "crowd-pleasing" toolchain.

**Comment by marc-hb** [comment]
> OK, I would have been really surprised if a fresh -rc1 does not have suspend/resume issue.

We've had intermittent but frequent suspend/resume failures pretty much across the board since forever. We can't test production hardware and BIOS because of SOF signing, I bet that plays a very large part.

>  it must be SDW specific, 

Because of the above I would recommend a bit more testing before coming to this conclusion.

**Comment by plbossart** [comment]
no issues with TGLU_SKU0A32_SDCA

````
PASS: tplg-binary; pcm_list; playback-d100l1r1; capture-d100l1r1; playback-d1l100r1; capture_d1l100r1; playback_d1l1r50; capture_d1l1r50; speaker; pause-resume-playback; pause-resume-capture; volume; signal-stop-start-playback; signal-stop-start-capture; multiple-pipeline-playback; multiple-pipeline-capture; multiple-pause-resume; kmod-load-unload; kmod-load-unload-after-playback; suspend-resume; suspend-resume-with-playback; suspend-resume-with-capture;
SKIP: sof-logger; ipc-flood; xrun-injection-playback; xrun-injection-capture; simultaneous-playback-capture; volume_levels;

 test end with 0 failed tests
````

**Comment by plbossart** [comment]
@ujfalusi I wonder if this is a new IPC4 issue, it'd make sense to see if we are able to pass the tests on ADLP_RVP_SDW with 2.2 IPC3 firmware.

Alternatively we could launch a daily test with this PR to cover more devices (daily_stable_v2_2 and daily_IPC4).

**Comment by plbossart** [comment]
@ujfalusi I've run hundreds of cycles with suspend+audio, so far nothing bad seen with IPC3. I'll let it run further tonight but I don't think it's a systematic issue with SoundWire, it seems platform specific and possible IPC4 specific. Not an easy one to find.

**Comment by ujfalusi** [comment]
@plbossart, @ranj063, with a similar change as in ##4230 the suspend /resume tests are passing with 6.3.
I see other sequence changes as well, but let me cross check again.

**Comment by ujfalusi** [comment]
@plbossart, gash, no, reverting that change and the kernel I build is working fine.
```
$ gcc --version
gcc (GCC) 12.2.1 20230201
```
CI is using `gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0`

This starts to sound wrong, something is really off, it does not make any sense that with a kernel we need to match a compiler, this cannot be the case.

**Comment by ujfalusi** [comment]
@plbossart and to make things more fun: if I download the deb package from the CI build `pr4223-3510`, install the kernel and modules to my sdw machine, reboot and do the test: I see the same failure and I'm running IPC3 on that laptop.

So: CI built kernel fails suspend/resume on sdw devices with active audio (both IPC4 and IPC3), locally built kernel passes the same test with IPC3 and  IPC4.

FYI: @marc-hb, @fredoh9

How cool is this? Not at all... :(

**Comment by plbossart** [comment]
Thanks @ujfalusi for testing further.

> So: CI built kernel fails suspend/resume on sdw devices with active audio (both IPC4 and IPC3), locally built kernel passes the same test with IPC3 and IPC4.

This points again to a difference in configurations and/or compilers. it's been a recurring issue, and with the CI build system being such a black box it's anyone's guess what it's doing really.

@fredoh9 @marc-hb @greg-intel we'll need your help on this one. If local tests pass and CI tests don't we need the "CI team" on board.

**Comment by plbossart** [comment]
> @plbossart, gash, no, reverting that change and the kernel I build is working fine.
> 
> ```
> $ gcc --version
> gcc (GCC) 12.2.1 20230201
> ```
> 
> CI is using `gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0`
> 
> This starts to sound wrong, something is really off, it does not make any sense that with a kernel we need to match a compiler, this cannot be the case.

I am using `gcc (Ubuntu 12.2.0-3ubuntu1) 12.2.0` with Ubuntu 22.10 on my development device, the target is Fedora-based so no debian plumbing involved

**Comment by ujfalusi** [comment]
I was wondering if we are setting some custom funky compiler flags in CI when building the kernel? My guess is that we don't, but I don't know it for sure.

**Comment by plbossart** [comment]
@ujfalusi possibly a red-herring but there's a difference between what CI did and what I tested

the CI kernel config uses this:
`../kconfig/kconfig-sof-default.sh ../kconfig/xrun-debug-defconfig > /dev/null`

I only used the first part.

the xrun stuff adds the following options

````
CONFIG_SND_DEBUG_VERBOSE=y
CONFIG_SND_PCM_XRUN_DEBUG=y
````

It's quite possible that the first option changes the timing and exposes some sort of race condition, made worse with a compiler change.

**Comment by plbossart** [comment]
And no special compiler flags, the command line is this
````
make bindeb-pkg -j8 LOCALVERSION=$LOCAL_VERSION KDEB_PKGVERSION=$(make kernelversion)-${FORMAT_BRANCH_NAME} KBUILD_OUTPUT=$BUILD_FOLDER > /dev/null
````

**Comment by plbossart** [comment]
The change in the .config has no effect on my local tests, still PASS. Humm...

**Comment by ujfalusi** [comment]
I have taken the config from the CI built kernel and built at the same commit.
What is stunning is that this is the second time in a row and it is again sdw. Something is not quite right, if a compiler swap fixes it, then it is likely works by luck and I don't buy it that this only affects our CI.
Probably worth a question in sdw list?

To sum up: kernel at the same commit with the same config.
Built by CI: broken sdw suspend/resume
Built locally (by you and me): no issues

Just amazing

**Comment by plbossart** [comment]
@ujfalusi I don't know how anyone outside Intel could help. We have non-reproducible results between CI-built and locally build, so the conclusion will be "fix your CI".

**Comment by marc-hb** [comment]
> and with the CI build system being such a black box it's anyone's guess what it's doing really.

I'm usually the first and loudest to complain about CI secrets and CI blackboxes but in this case CI is merely using a regular kconfig script, a plain Ubuntu compiler and regular `make bindeb-pkg` command.

From `sofkernel_prs.gvy`:

```
../kconfig/kconfig-sof-default.sh ../kconfig/xrun-debug-defconfig
# or
../kconfig/kconfig-sof-nocodec.sh ../kconfig/xrun-debug-defconfig

# then
GITSHA=$(cat .gitsha)
PRIDV=$(cat .prid)
make bindeb-pkg LOCALVERSION=-$PRIDV-default KDEB_PKGVERSION=$(make kernelversion)-$GITSHA -j8

```
And that's it, there is really not much to hide. I think and hope the kernel build is not affected by environment variables or any other hidden setting? 

> Something is not quite right, if a compiler swap fixes it, then it is likely works by luck and I don't buy it that this only affects our CI.

Best summary IMHO. I think we've known that since #4122 and #4203 when different Ubuntu compilers gave different results but we tried hard to ignore it at the time. Didn't work.

**Comment by ujfalusi** [comment]
There is a fix upstream: Testing the proposed upstream fix: https://lore.kernel.org/lkml/20230312200731.599706-3-masahiroy@kernel.org/
But this is not testable with this PR (conflicts). I will close and open a new upstream merge today.

**Comment by ujfalusi** [comment]
New merge PR created: #4241, closing.

**Pull request closed without merging**
