### PR TITLE
ASoC: SOF: Intel: hda: Add module parameter to disable display audio bind

### PR DESCRIPTION
**Pull request by ujfalusi**
ASoC: SOF: Intel: hda: Add module parameter to disable display audio bind
    
    The SOF audio stack expects working Intel eGPU to probe and to have working
    analog audio.
    Under special circumstances users or developers can encounter issues of
    no i915/Xe driver available and thus the SOF audio card is not probing:
    - Booting kernel on a new architecture where the display driver is not yet
      working (cannot even force probed)
    - running in virtualized environment without access to eGPU resources
    - booting with nomodeset
    
    While the percentage of affected users are small, it can still cause
    unreasonable obstacles on their use cases.
    
    With the disable_display_audio_bind=true module parameter the binding can
    be disabled to let the SOF stack to probe and provide at least working
    analog audio. Obviously the display audio will not work, but that is
    expected.

and drop the PTL related patch.

    The display audio binding can be disabled with a generic module
    parameter, there is no longer a need for the patch:
    
    options snd-sof-intel-hda-generic disable_display_audio_bind=true

### CODE REVIEW

**Review by bardliao — DISMISSED** [review]

**Review by lgirdwood — DISMISSED** [review]

**Comment by ranj063** [comment]
@ujfalusi is the kernel build failure a CI issue?

**Comment by ujfalusi** [comment]
Hrm:
```
/srv/home/jenkins/workspace/linux_config_build/linux/sound/soc/sof/intel/hda.c: In function â€˜hda_dsp_probe_earlyâ€™:
/srv/home/jenkins/workspace/linux_config_build/linux/sound/soc/sof/intel/hda.c:713:13: error: â€˜disable_display_audio_bindâ€™ undeclared (first use in this function)
  713 |         if (disable_display_audio_bind)
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
/srv/home/jenkins/workspace/linux_config_build/linux/sound/soc/sof/intel/hda.c:713:13: note: each undeclared identifier is reported only once for each function it appears in
make[10]: *** [/srv/home/jenkins/workspace/linux_config_build/linux/scripts/Makefile.build:229: sound/soc/sof/intel/hda.o] Error 1
make[9]: *** [/srv/home/jenkins/workspace/linux_config_build/linux/scripts/Makefile.build:478: sound/soc/sof/intel] Error 2
make[8]: *** [/srv/home/jenkins/workspace/linux_config_build/linux/scripts/Makefile.build:478: sound/soc/sof] Error 2
  CC [M]  drivers/gpu/drm/i915/display/intel_connector.o
make[7]: *** [/srv/home/jenkins/workspace/linux_config_build/linux/scripts/Makefile.build:478: sound/soc] Error 2
make[6]: *** [/srv/home/jenkins/workspace/linux_config_build/linux/scripts/Makefile.build:478: sound] Error 2
make[6]: *** Waiting for unfinished jobs....
```

**Comment by ujfalusi** [comment]
Aarrh, I see, pushing an update and thanks @ranj063 for spotting it!

**Comment by ujfalusi** [comment]
Changes since v1:
- Moved the disable_display_audio_bind module param declaration _outside_ of the `#if IS_ENABLED(CONFIG_SND_SOC_SOF_INTEL_SOUNDWIRE)`, thanks again @ranj063 for noticing it!

**Review by bardliao — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Review by ranj063 — APPROVED** [review]

**Pull request merged**
