### PR TITLE
SoundWire: cadence: remove dma_data - option B

### PR DESCRIPTION
**Pull request by plbossart**
this is an alternative to https://github.com/thesofproject/linux/pull/3943, since the use of 'private_data' didn't exactly thrill the crowds.

@ujfalusi @bardliao @ranj063 please vote on which of the two you guys prefer. I don't really care as long as dma_data is gone.

### CODE REVIEW

**Comment by bardliao** [comment]
I would vote for option B

**Comment by ranj063** [comment]
> I would vote for option B

me too

**Review by ujfalusi — APPROVED** [review]

**Comment by ujfalusi** [comment]
I have voted for option B

**Comment by plbossart** [comment]
alright alright alright, the majority has spoken. Option B it is. thanks for your feedback @bardliao @ujfalusi @ranj063

**Review by bardliao — APPROVED** [review]

**Pull request merged**
