### PR TITLE
Merge/upstream merge 20191030

### PR DESCRIPTION
**Pull request by plbossart**
This merge contains  @kv2019i 's changes for HDMI, so better check that the merge was done right (2-3 conflicts in Makefiles)
Also a fix for rt5677 which should help with CI.

### CODE REVIEW

**Comment by plbossart** [comment]
@fredoh9 can you help me interpret the results, I see two fails on this PR?

**Comment by xiulipan** [comment]
@plbossart We did some manually test on the device and find that this issue is casued by machine driver name changing and our alsactl restore fail.

But the audio quality on those device is clear without noise. The PR can be merged. And we will try to fix the alsactl issue ASAP.

**Comment by kv2019i** [comment]
> This merge contains @kv2019i 's changes for HDMI, so better check that the merge was done right (2-3 conflicts in Makefiles)
> Also a fix for rt5677 which should help with CI.

Indeed, not a nice patch to rebase/merge between versions. But looks good, thanks!
I've tested with common and hdac-hdmi codecs and bothw ork with this PR (tested on CFL).

**Comment by plbossart** [comment]
Thanks @xiulipan and @kv2019i, yes the name changes are not cool but better do it now than later when we have more users.

**Comment by xiulipan** [comment]
@plbossart I have discussed with @kv2019i about the hdmi patch changing. We will try to test with new feature on all CI device before we merge the https://github.com/thesofproject/kconfig/pull/15

**Pull request merged**
