### PR TITLE
Revert patches adding support for i.MX8M

### PR DESCRIPTION
**Pull request by dbaluta**
As per discussion with Pierre I will try to push this myself through Mark's tree. 

@plbossart these are all patches mentionedin 'NXP SOF patches' email.

### CODE REVIEW

**Comment by plbossart** [comment]
@dbaluta why do you want to revert? Just send the patches to Mark and we'll deal with them once they are merged.

**Comment by dbaluta** [comment]
@plbossart all right. for i.MX8M i've made some modifications so they won't match what we have in topic/sof-dev but will sort this out once Marks accepts the patches.

**Comment by plbossart** [comment]
> @plbossart all right. for i.MX8M i've made some modifications so they won't match what we have in topic/sof-dev but will sort this out once Marks accepts the patches.

ok, In general if there are changes it's easier to track by pushing them into topic/sof-dev with an update, then squash them into topic/sof-dev-rebase. But it's so specific in that case that it doesnt' really matter. Thanks @dbaluta

**Comment by kv2019i** [comment]
Seems the patches are still pending for upstream merge, so let's keep the PR open.

**Comment by dbaluta** [comment]
@kv2019i I still need to send a new version to upstream. Hopefully doing it this week.

**Comment by plbossart** [comment]
@dbaluta this was handled upstream and can be closed, yes?

**Comment by dbaluta** [comment]
We can close this. The patches are already in Mark's tree, but there was a problem on adding them to linux-next. I will work with Mark to fix the problem.

**Pull request closed without merging**
