### PR TITLE
SoundWire: Realtek codec fixes

### PR DESCRIPTION
**Pull request by plbossart**
Two fixes for CML 'failed to get private value' and MTL headset mic detection.

### CODE REVIEW

**Review by bardliao — APPROVED** [review]

**Comment by shumingfan** [comment]
@plbossart @bardliao 
The 'ASoC: rt712-sdca: improve headset mic detection' patch still has the button issue (https://github.com/thesofproject/linux/issues/4872#issuecomment-2025989121).
Please don't merge this patch.
I will get the machine from @bardliao next week. 
I want to test it and try to release the final patch. Thanks.

**Comment by plbossart** [comment]
@jack-cy-yu do you want to send the patch "ASoC: rt715: add vendor clear control register" to Mark Brown? Or should I do it?

**Comment by jack-cy-yu** [comment]
@plbossart Yes, I can sent it upstream. Has the patch been verified on device?

**Comment by bardliao** [comment]
> @plbossart Yes, I can sent it upstream. Has the patch been verified on device?

Yes, for "ASoC: rt715: add vendor clear control register"

**Pull request closed without merging**
