### PR TITLE
soundwire: bus: lock in clock stop

### PR DESCRIPTION
**Pull request by plbossart**
This simple lock seems to be enough to cause suspend-resume issues on
CML_RVP_SDW

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

### CODE REVIEW

**Comment by plbossart** [comment]
@bardliao would you mind running tests on your local devices, so see if that PR causes any issues?

**Comment by bardliao** [comment]
> @bardliao would you mind running tests on your local devices, so see if that PR causes any issues?

I didn't see any issue when I try `check-suspend-resume-with-audio.sh`, running `run-all-tests.sh` on my SKU 0A3E laptop now.

**Comment by miRoox** [comment]
SOFCI TEST

**Comment by bardliao** [comment]
> > @bardliao would you mind running tests on your local devices, so see if that PR causes any issues?
> 
> I didn't see any issue when I try `check-suspend-resume-with-audio.sh`, running `run-all-tests.sh` on my SKU 0A3E laptop now.

And all test cases in `run-all-tests.sh` pass

**Comment by plbossart** [comment]
Thanks @bardliao. looks like we have a device-specific issue then. I'll run a test with all SoundWire devices in CI and see what happens.

**Comment by plbossart** [comment]
It's pretty crazy @bardliao, CML_RVP_SDW is the ONLY device that fails! https://sof-ci.sh.intel.com/#/result/planresultdetail/12011

**Comment by plbossart** [comment]
In my local tests, the fails only happen with the HDMI devices - which are unrelated to SoundWire

````
2022-04-22 22:06:01 UTC [COMMAND] aplay -Dhw:0,5 -r 48000 -c 2 -f S16_LE /dev/zero -q
/root/sof-test/test-case/check-suspend-resume-with-audio.sh: line 92:  3034 Killed                  $cmd -D$dev -r $rate -c $channel -f $fmt $file_name -q
process: 3578 status: interruptible sleep (waiting for an event to complete)
2022-04-22 22:06:02 UTC Sub-Test: [INFO] Current suspend/resume type mode: s2idle [deep]
2022-04-22 22:06:03 UTC Sub-Test: [INFO] ===== Round(1/5) =====
2022-04-22 22:06:03 UTC Sub-Test: [COMMAND] Run the command: rtcwake -m mem -s 5
rtcwake: assuming RTC uses UTC ...
rtcwake: wakeup from "mem" using /dev/rtc0 at Fri Apr 22 22:06:09 2022
2022-04-22 22:06:12 UTC Sub-Test: [COMMAND] sleep for 5
2022-04-22 22:06:17 UTC Sub-Test: [INFO] Check for the kernel log status
declare -- cmd="journalctl_cmd --since=@1650665155"
2022-04-22 22:06:17 UTC Sub-Test: [INFO] Check for the wakeup_count
2022-04-22 22:06:17 UTC Sub-Test: [INFO] ===== Round(2/5) =====
2022-04-22 22:06:17 UTC Sub-Test: [COMMAND] Run the command: rtcwake -m mem -s 5
rtcwake: assuming RTC uses UTC ...
rtcwake: wakeup from "mem" using /dev/rtc0 at Fri Apr 22 22:06:23 2022
````

**Comment by plbossart** [comment]
That's really interesting, I locked the device real bad
````
Terminal 1
root@jf-cml-rvp-sdw-1:~# aplay -Dhw:0,5 -r 48000 -c 2 -f S16_LE /dev/zero -q
````

````
Terminal2
root@jf-cml-rvp-sdw-1:~# rtcwake -m mem -s 5
rtcwake: assuming RTC uses UTC ...
rtcwake: wakeup from "mem" using /dev/rtc0 at Fri Apr 22 22:10:58 2022
root@jf-cml-rvp-sdw-1:~# rtcwake -m mem -s 5
rtcwake: assuming RTC uses UTC ...
rtcwake: wakeup from "mem" using /dev/rtc0 at Fri Apr 22 22:11:08 2022
root@jf-cml-rvp-sdw-1:~# rtcwake -m mem -s 5
rtcwake: assuming RTC uses UTC ...
rtcwake: wakeup from "mem" using /dev/rtc0 at Fri Apr 22 22:11:19 2022 <<< STUCK, POWER-CYCLE NEEDED

````

**Comment by plbossart** [comment]
ok, so with my usual luck, instead of testing a SoundWire change, I exposed an HDMI/HDaudio issue. If I filter out the HDMI devices in sof-test, I can run suspend-resume cycles forever.

````diff
diff --git a/case-lib/config.sh b/case-lib/config.sh
index 1479b0a..391fb9e 100644
--- a/case-lib/config.sh
+++ b/case-lib/config.sh
@@ -17,7 +17,7 @@ TPLG_ROOT=${TPLG_ROOT:-/lib/firmware/intel/sof-tplg}
 declare -A TPLG_IGNORE_LST
 # Used in case-lib/pipeline.sh as of October 2020
 # shellcheck disable=SC2034
-TPLG_IGNORE_LST['pcm']='HDA Digital'
+TPLG_IGNORE_LST['pcm']='HDA Digital,HDMI 1,HDMI 2,HDMI 3'
 
 # If not set will be automatically set by logging_ctl function
 # Test case log root
````

@bardliao @ranj063 @kv2019i @ujfalusi I suspect there's something very odd in the HDaudio DMA handling. This sort of hangs has historically been due to DMA/stream management issues. CML_RVP_SDW is very specific in that it uses the link1 only, so there's a possibility of an off-by-one somewhere.

I do see a lot of trace-related logs as well, which is rather unusual. That really brings more credit to the theory that the DMA handling is borked.
````
[  347.339794] sof-audio-pci-intel-cnl 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG: DMA_POSITION
````

Another possibility is that the topology is incorrect, leading to some sort of corruption later on when we deal with HDMI.

I fried my brain on this one...

**Comment by ranj063** [comment]
> Another possibility is that the topology is incorrect, leading to some sort of corruption later on when we deal with HDMI.
> 
> I fried my brain on this one...

@plbossart could you please point me to the original issue?

**Comment by plbossart** [comment]
> > Another possibility is that the topology is incorrect, leading to some sort of corruption later on when we deal with HDMI.
> > I fried my brain on this one...
> 
> @plbossart could you please point me to the original issue?

Sure. https://github.com/thesofproject/linux/pull/3568 adds a device_lock/unlock to make sure it's safe to call the dev->driver->ops->XYZ callbacks, and protect against races with probe/remove.

The CI results showed that the CML_RVP_SDW failed repeatedly, and my manual tests showed that this PR alone was enough to make the device completely unresponsive when doing suspend/resume while playing HDMI devices. This happens ONLY on CML_RVP_SDW, not on any other SoundWire device.

**Comment by plbossart** [comment]
One of the theories was that maybe there's a firmware dependent issue, but reverting commit 78ea40efb48e978756db2ce45fcfa55bac056b91 ("ALSA: hda: intel-sdw-acpi: go through HDAS ACPI at max depth of 2") does not solve the issue.

Still system hang on the second rtcwake.

**Comment by plbossart** [comment]
I made minor progress on this, it seems that when have a spurious wakeen event when we try to suspend.

Same configuration where we suspend while playing on HDMI, so all SoundWire links and devices should be runtime suspended. So in theory nothing do do, but somehow we power the links again.

````
[   87.409164] soundwire_intel soundwire_intel.link.1: intel_pm_prepare: plb: start
[   87.409167] soundwire_intel soundwire_intel.link.1: intel_pm_prepare: plb: end
[   87.409559] sof-audio-pci-intel-cnl 0000:00:1f.3: pcm: trigger stream 5 dir 0 cmd 5
[   87.409565] sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[   87.410282] sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx succeeded: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[   87.410293] sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg[0x160]=0x20140000 successful
[   87.410301] sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[   87.410560] sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[   87.410609] sof-audio-pci-intel-cnl 0000:00:1f.3: hda_link_dma_trigger: cmd=5
[   87.410619] sof-audio-pci-intel-cnl 0000:00:1f.3: ipc3_hda_dai_trigger: cmd=5
[   87.410628] sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[   87.410901] sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[   87.411113] soundwire_intel soundwire_intel.link.1: intel_resume_runtime: plb: start
[   87.411126] soundwire_intel soundwire_intel.link.1: intel_link_power_up: powering up all links
[   87.411129] soundwire_intel soundwire_intel.link.1: intel_link_power_up: first link up, programming SYNCPRD
[   87.411424] rt700 sdw:1:025d:0700:00: sdw_modify_slave_status: initializing enumeration and init completion for Slave 1
[   87.413369] soundwire_intel soundwire_intel.link.1: intel_resume_runtime: plb: end
````

Additional traces show that this comes from the pm_request_resume(dev); added in  intel_link_process_wakeen_event()

It seems that the CML_RVP_SDW device is the only hardware where we get that wake signal, and it's probably the reason why adding a device_lock() creates a problem.

**Comment by plbossart** [comment]
I gave up, the use of device_lock() is a can of worms with race conditions and deadlocks left and right.

I updated https://github.com/thesofproject/linux/pull/3568 to use a bind/unbind notifier, much simpler and less error-prone.

**Pull request closed without merging**
