### PR TITLE
Merge/sound upstream 20201027

### PR DESCRIPTION
**Pull request by kv2019i**
First rebase after 5.10-rc1

FYI @marc-hb This is a potential interesting one for sof-test and CI infra.

### CODE REVIEW

**Comment by kv2019i** [comment]
Wow, surprisingly good results from CI.

One new dmesg error from i915:
[ 1042.840915] [drm:drm_dp_send_link_address [drm_kms_helper]] *ERROR* Sending link address failed with -5

And one case of existing bug: https://github.com/thesofproject/sof/issues/3462  hittin on BSW.

**Comment by plbossart** [comment]
filter suggested in https://github.com/thesofproject/sof-test/pull/476 to work-around DRM issue

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
> Wow, surprisingly good results from CI.

Except for Travis which has been lagging - in every PR, not just this one. 

https://travis-ci.org/github/thesofproject/linux/builds/739280506 has been received hours ago but not started yet.

https://www.traviscistatus.com/ is all green right now. @xiulipan  any idea?

**Comment by kv2019i** [comment]
Remaining Travis builds are in progress still, but they appear not to be stuck, so maybe they'll complete. 

If we have any actions specific to us, that cover the new patches (like running checkpatch on them), those are going to take extra time on this PR as we have 14000+ new commits. I got a Github error multiple times, before I could create the pull req (but it did work in the end).

**Comment by kv2019i** [comment]
Remaining Travis builds now completed... it seems they just took time.

If we have any actions specific to us, that cover the new patches (like running checkpatch on them), those are going to take extra time on this kind of PR as we have 14000+ new commits. I got a Github error multiple times, before I could create the pull req (but it did work in the end).

**Comment by plbossart** [comment]
The results for the CI tests are ok now. I just wonder if we should run a more thorough test on more machines. @xiulipan @fredoh9 can we trigger a manual test on this PR?

**Comment by kv2019i** [comment]
I pushed my sof-dev-rebase candidate to kv/merge/sof-dev-rebase-20201027

@plbossart @ranj063 @bardliao Results look good now, should we go ahead and merge? This time around, this will require forced rebases to multiple open PRs, but I don't see us lowering this number in a short timeframe, so from that perspective, we could just go ahead now. I'll continue with some local tests while waiting for your input.

**Comment by marc-hb** [comment]
> Remaining Travis build now completed... it seems they just took time.

It's very difficult to look at delays because timestamps are surprisingly rare and we still have too many in unknown timezones. Here for instance (cc : @xiulipan) https://sof-ci.01.org/linuxpr/PR2538/build4792/checkpatch/ and https://sof-ci.01.org/linuxpr/PR2538/build4792/devicetest are in different timezones and they are both unknown timezones.

This being said, I commented 17 hours ago that Travis had "been stuck for hours". Right now https://travis-ci.org/github/thesofproject/linux/jobs/739280507 says it started 9 hours ago and finished 8 hours ago. So this one was stuck at least for 8 hours before even starting.

**Comment by marc-hb** [comment]
@kv2019i can you please try this exact command locally and compare the start of its output  with  https://travis-ci.org/github/thesofproject/linux/jobs/739280507 ?


```shell
scripts/checkpatch.pl --strict --codespell -g 8290bd62dfe67dfbbd8177a4eb985c4592c1be05..10c34365cec335fdfcaf3bb32091bbcad97cf3fb
```
It seems checkpatch is confused again and this time it is not missing the merge base (which used to happen sometimes  because of shallow --depth cloning). For now I just want to make sure it fails exactly the same on Travis.

it also took too long and timed out but that's a different issue.

**Review by bardliao — APPROVED** [review]
I think we can go ahead to merge since CI test result is good.

**Comment by xiulipan** [comment]
@plbossart @ranj063 @kv2019i Please check @fredoh9's email for the test result detail. The test is still running, you can decided if this PR is good merge once you checked the result. Next time, you can also trigger a wilder test by yourself once the **sof-ci/jenkins/pr-build** step completed.

**Comment by kv2019i** [comment]
@marc-hb wrote:
> scripts/checkpatch.pl --strict --codespell -g 8290bd62dfe67dfbbd8177a4eb985c4592c1be05..10c34365cec335fdfcaf3bb32091bbcad97cf3fb

No, output doesn't look same at all, so it is getting confused by the shallow clone for sure.

Plus, even if it would have worked, it would have timed out still I think. I didn't have patience to let it run to end locally, but on this machine checkpatch churns through ~65patches/minute, so checking the whole set would have taken almost 4 hours. Our Travis job should just ignore these .. waste of compute cycles to check patches that have anyways been already merged.

**Comment by marc-hb** [comment]
> No, output doesn't look same at all, so it is getting confused by the shallow clone for sure.

Thanks! I finally tested, reproduced, analyzed and understood this. Tentative "fix" submitted in .travis.yml PR #2543 

Note https://travis-ci.org/github/thesofproject/linux/builds/740104633 will take hours and hours to complete because Travis.com just made travis.org mostly unusable: https://travis-ci.community/t/builds-hang-in-queued-state/10250

**Pull request merged**
