### PR TITLE
Merge/upstream merge 20190903

### PR DESCRIPTION
**Pull request by plbossart**
Usual upstream merge, should be uneventful.

### CODE REVIEW

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
@xiulipan I can't figure out what the CI tests mean, ICL looks completely unstable and I don't see any issue with Up2 / NOCODEC. Redoing the tests but will merge is this is still as unclear

**Comment by xiulipan** [comment]
@plbossart 
We will do some manually test to see if the kernel can relay not boot on ICL.
@ClarexZhou Can you try to test this PR kernel with the ICL RVP to see if the RVP can boot up?

**Comment by ClarexZhou** [comment]
ICL RVP can boot up and load success after install kernel by  "bash deploy.sh -d -l -kh=f7651128-1 "

**Comment by xiulipan** [comment]
@plbossart Then it seems to be some ICL RVP stable issue. We still face some i915 related issue with HDMI codec probe.

**Comment by plbossart** [comment]
so between 2 runs, we have 4 different issues... APL UP2 nocodec works now, but Mantis and Bobba don't.
I am just going to merge and deal with bugs when (if) they are confirmed.

**Pull request merged**
