### PR TITLE
ASoC: Intel: boards:  fix SOF-generated echo reference

### PR DESCRIPTION
**Pull request by plbossart**
This PR is in addition to https://github.com/thesofproject/linux/pull/4085. Instead of filtering out invalid BEs, this PR adds the missing dpcm_capture fields needed when the dailink is associated with a firmware-generated echo reference.

One objection is that we're adding capture support unconditionally, but the rule is always that the machine driver needs to support more options that what the topology exposes. When the topology makes use of capabilities not explicitly supported in the machine driver, bad things happen. Usually it's just a topology binding issue, but in this case it was kernel oopses due to an invalid configuration.

### CODE REVIEW

**Review by ranj063 — APPROVED** [review]

**Review by ujfalusi — APPROVED** [review]

**Comment by plbossart** [comment]
Hold for merge, pending information on IPC timeout reported by @Vamshigopal in https://github.com/thesofproject/linux/issues/4083

**Comment by kv2019i** [comment]
Tested on a sof_rt5682 machine where #4083 is hit and this indeed seems to help:

[   13.507950]  Headset: ASoC: dpcm_be_connect FE Headset BE SSP0-Codec, besubstream 0000000008fc2624
[   13.519433]  SSP0-Codec: dpcm_be_connect: FE is nonatomic but BE is not, forcing BE as nonatomic
[   67.900971]  EchoRef: ASoC: dpcm_be_connect FE EchoRef BE SSP1-Codec, besubstream 00000000fdf9fe15
[   67.912358]  SSP1-Codec: dpcm_be_connect: FE is nonatomic but BE is not, forcing BE as nonatomic

... I didn't have #4085 included in the tested kernel.

**Comment by ranj063** [comment]
> This PR is in addition to #4085. Instead of filtering out invalid BEs, this PR adds the missing dpcm_capture fields needed when the dailink is associated with a firmware-generated echo reference.

@plbossart do you mean that even with this PR #4085 is still needed?

**Comment by kv2019i** [comment]
@ranj063 wrote:
>> This PR is in addition to #4085. Instead of filtering out invalid BEs, this PR adds the missing dpcm_capture fields needed when the dailink is associated with a firmware-generated echo reference.
> 
> @plbossart do you mean that even with this PR #4085 is still needed?

I think #4085 should still be done, just to be more robust against mistakes in tplg/machdriver setup, although it's not as critical maybe anymore.

**Comment by plbossart** [comment]
> @ranj063 wrote:
> 
> > > This PR is in addition to #4085. Instead of filtering out invalid BEs, this PR adds the missing dpcm_capture fields needed when the dailink is associated with a firmware-generated echo reference.
> > 
> > 
> > @plbossart do you mean that even with this PR #4085 is still needed?
> 
> I think #4085 should still be done, just to be more robust against mistakes in tplg/machdriver setup, although it's not as critical maybe anymore.

Yes, that's what I meant. This PR fixes existing Chromebook solutions, but there may be other cases we missed or didn't test. PR #4085 is defensive programming that should be added in case the design assumptions are incorrect. I would still extend PR #4085 to deal with all the cases where we use an invalid substream, not just the cases that are known to generate an oops.

**Review by bardliao — APPROVED** [review]

**Pull request merged**
