### PR TITLE
Merge/sound upstream 20211129

### PR DESCRIPTION
**Pull request by kv2019i**

### CODE REVIEW

**Comment by kv2019i** [comment]
CI results seem clean. Please review. Matching sof-dev-rebase is at https://github.com/kv2019i/linux/tree/merge/sof-dev-rebase-20211129-2

**Comment by kv2019i** [comment]
@dbaluta and @yaochunhung a bunch of NXP and MTK patches were now merged and dropped from sof-dev-rebase. There were quite a few merge conflicts, but should be ok in the PR. Please check.

**Comment by dbaluta** [comment]
@kv2019i conflicts appeared because we sent some patches virtually in the same time to Mark and Mark merged them.

Specifically one of the patches causing the conflicts was:

https://github.com/thesofproject/linux/pull/3299/commits/5974f6843203f0061d9df05c32262a10359740a6

@yaochunhung checking the conflicts means that have a brief look over your MTK code and see if there is anything unusual. Also testing the code should reveal the problems.

@kv2019i thanks a lot for taking care of this and lets synchronize better in the future. I wonder how Mark fixed this king of conflicts in the upstream.

**Comment by bardliao** [comment]
> @kv2019i thanks a lot for taking care of this and lets synchronize better in the future. I wonder how Mark fixed this king of conflicts in the upstream.

Mark won't fix conflicts, he will ask us to fix the conflicts and resend the patch.

**Comment by dbaluta** [comment]
> Mark won't fix conflicts, he will ask us to fix the conflicts and resend the patch.

@bardliao the interesting thing is that the patch was applied by Mark and looks like "git merge" didn't generate a conflict (?). 

This is my patch:

https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?id=8253aa4700b37cef1ca3bbda0d986349357608d3

which should have conflicted with:

https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?id=5974f6843203f0061d9df05c32262a10359740a6

But for some reason maybe Mark have used "git merge" which automatically resolved the conflict. The problem is that
when  you just use a simple git rebase -i HEAD~30 on Mark's for-next branch the conflict re-appears:

```
daniel@nio:~/work/repos/linux-next$ git diff
diff --cc sound/soc/sof/imx/imx8.c
index 2d0448b3c8c3,32f852cbba30..000000000000
--- a/sound/soc/sof/imx/imx8.c
+++ b/sound/soc/sof/imx/imx8.c
@@@ -188,7 -196,10 +196,14 @@@ static int imx8_probe(struct snd_sof_de
        if (!priv)
                return -ENOMEM;
  
++<<<<<<< HEAD
 +      sdev->num_cores = 1;
++=======
+       priv->clks = devm_kzalloc(&pdev->dev, sizeof(*priv->clks), GFP_KERNEL);
+       if (!priv->clks)
+               return -ENOMEM;
+ 
++>>>>>>> 8253aa4700b3... ASoC: SOF: imx: Add code to manage DSP related clocks
        sdev->pdata->hw_pdata = priv;
        priv->dev = sdev->dev;
        priv->sdev = sdev;
diff --cc sound/soc/sof/imx/imx8m.c
index c94422323d67,ab40c0bdf796..000000000000
--- a/sound/soc/sof/imx/imx8m.c
+++ b/sound/soc/sof/imx/imx8m.c
@@@ -108,7 -116,10 +116,14 @@@ static int imx8m_probe(struct snd_sof_d
        if (!priv)
                return -ENOMEM;
  
++<<<<<<< HEAD
 +      sdev->num_cores = 1;
++=======
+       priv->clks = devm_kzalloc(&pdev->dev, sizeof(*priv->clks), GFP_KERNEL);
+       if (!priv->clks)
+               return -ENOMEM;
+ 
++>>>>>>> 8253aa4700b3... ASoC: SOF: imx: Add code to manage DSP related clocks
        sdev->pdata->hw_pdata = priv;
        priv->dev = sdev->dev;
        priv->sdev = sdev;
```

I don't understand how git works in this case.

**Comment by dbaluta** [comment]
@kv2019i looks good for imx platforms.

**Comment by kv2019i** [comment]
@dbaluta wrote:
> @bardliao the interesting thing is that the patch was applied by Mark and looks like "git merge" didn't generate a conflict (?).

Hmm, indeed. I usually wait until Mark has picked up the previous series, before rebasing and sending the next one, but I missed this dependency. But yeah, resulting code seems correct.

**Comment by kv2019i** [comment]
There's actually no delta for MTK code between upstream and latest sof-dev-rebase and I confirmed the diff shows no changes, so we are aligned with upstream. So with that, I'll proceed with the merge.

**Comment by marc-hb** [comment]
> But for some reason maybe Mark have used "git merge" which automatically resolved the conflict. The problem is that
when you just use a simple git rebase -i HEAD~30 on Mark's for-next branch the conflict re-appears:

By design, `git rebase` will always experience more conflicts than `git merge` because `git merge` only looks at merge base(s) (~ starting points) and final commits, **not** how you got there.

You can observe this with a very simple example: find some patch series with some dependencies between some of the commits. Branch off just before it. Cherry-pick the entire series and squash it into a single big commit. Now if you merge the giant commit with the finer grained series then everything will be fine. Probably not if you try to replay[*] the big one on top of the finer-grained one.

Some alternatives to git have complained that "git merge" is not smart enough. For instance imagine some commit gets reverted on one branch but whoever cherry-picked elsewhere "forgets" to revert it there too. When you merge then ta-da: the reverted commit gets resurrected! And no one notices.
https://bramcohen.livejournal.com/74462.html

[*] "rebase" is yet another bad command name.

**Pull request merged**
