### PR TITLE
Merge/20190723

### PR DESCRIPTION
**Pull request by ranj063**

### CODE REVIEW

**Comment by ranj063** [comment]
@keqiaozhang @stripes416 @RanderWang could I please request a test run with this PR on GLK/CML/CFL? I will test on Up2

**Comment by fredoh9** [comment]
I tested this on both GLK and APL. Basic test cases(10 test cases) + some tests(11,12) under review. Test results are good. (btw, GLK skips #12 aplay 3 times back to back test cases. looking at the test script)

1. verify_firmware_presense.sh
2. verify_kernel_model_load_probe.sh
3. verify_sof_firmware_load.sh
4. verify_tplg_binary.sh
5. verify_pcm_list.sh
6. check_sof_logger.sh
7. check_aplay_function.sh
8. check_pause_resume.sh
9. multiple-pipeline-playback.sh
10. multiple-pipeline-capture.sh
-----------------------
11. volume_basic_test.sh ; call volume change on all PGAs
12. aplay-3-times.sh ; back to back playback. play-stop-play-stop-play-stop

**Comment by ranj063** [comment]
Thanks @fredoh

**Comment by RanderWang** [comment]
I also tested it on whiskey-lake with HDA codec.
analog playback & capture work, and also DMIC capture.
Runtime-PM works
Headphone Jack detection works, but Mic detection not always work. I didn't have time to debug and I think it is linked to codec driver.
two pipelines simultaneous test passed

**Comment by Jiangxinx** [comment]
I tested this PR on BYT and APL platform.
There are two new issues on APL nocodec platform:
**1.Network is unavailable after power on, this will block all CI test cases.**
**2.System will always freeze after running several cases,and the reproduced rate is 100%, this will block the remain test cases.**

***Env***
Firmware: 82564659 https://github.com/thesofproject/sof/commits/master
Topology: sof-byt-rt5651.tplg & sof-byt-nocodec.tplg & sof-apl-nocodec.tplg

***Test result***

Cases| BTY nocodec | BTY rt5651 | CML_Mantis | ICL_RVP | WHL_RVP | APL UP2 nocodec
-- | -- | -- | -- | -- | -- | --
Verify firmware presence | Pass | Pass | N/T | N/T | Pass | Pass
Verify kernel model load probe | Pass | Pass |   | N/T | Pass | Pass
Verify SOF firmware load | Pass | Pass | N/T | N/T | Pass | Pass
Verify topology binary | Pass | Pass | N/T | N/T | Pass | Pass
Verify PCM device list | Pass | Pass | N/T | N/T | Pass | Pass
Check SOF logger | Pass | Pass | N/T | N/T | Pass | Pass
aplay - playback over headset | Pass | Pass |   | N/T | Pass | Pass
stop/resume playback over headset | Pass | Pass | N/T | N/T | Pass | Pass
Playing -> pause -> s3 -> wakeup -> resume over headset | N/A | N/A | N/T | N/T | Pass | Block
repeat 3 times playback over headset | Pass | Pass | N/T | N/T | Pass | Block
Pause/Resume playback over headset - 10 times | Pass | Pass | N/T | N/T | Pass | Block
Play an audio for 3 minutes | Pass | Pass | N/T | N/T | Pass | Block
Suspend & Resume device during audio playback | N/A | N/A | N/T | N/T | Pass | Block
Change volume during playback. | Pass | Pass | N/T | N/T | Pass | Block
aplay - playback over HDMI | N/A | N/A | N/T | N/T | Pass | N/A
stop/resume playback over HDMI | N/A | N/A | N/T | N/T | Pass | N/A
Playing -> pause -> s3 -> wakeup -> resume over HDMI | N/A | N/A | N/T | N/T | Pass | N/A
repeat 3 times playback over HDMI | N/A | N/A | N/T | N/T | Pass | N/A
Pause/Resume playback over HDMI | N/A | N/A | N/T | N/T | Pass | N/A
Play an audio for 3 minutes | N/A | N/A | N/T | N/T | Pass | N/A
Suspend & Resume device during audio playback | N/A | N/A | N/T | N/T | Pass | N/A
Change volume during playback. | N/A | N/A | N/T | N/T | Pass | N/A
arecord - capture over headset (HDA Analog) | Pass | Pass | N/T | N/T | Pass | Block
Change volume during capture. | Pass | Pass | N/T | N/T | Pass | Block
Pause/Resume capture | Failed (#1578) | Failed (#1578) | N/T | N/T | Pass | Block
Capturing -> pause -> s3 -> wakeup -> resume | N/A | N/A | N/T | N/T | Pass | Block
Capture a audio for 5 minutes via HDA Analog | Pass | Pass | N/T | N/T | Pass | Block
repeat 3 times capture | Pass | Pass | N/T | N/T | Pass | Block
Stop/Resume capture | Pass | Pass | N/T | N/T | Pass | Block
Suspend & Resume device during audio capture | N/A | N/A | N/T | N/T | Pass | Block
arecord - capture over DMIC32 | N/A | N/A | N/T | N/T | Pass | Block
Change volume during capture. | N/A | N/A | N/T | N/T | N/A | Block
Pause/Resume capture | N/A | N/A | N/T | N/T | N/T | Block
Capturing -> pause -> s3 -> wakeup -> resume | N/A | N/A | N/T | N/T | N/T | Block
Capture a audio for 5 minutes | N/A | N/A | N/T | N/T | N/T | Block
repeat 3 times capture | N/A | N/A | N/T | N/T | N/T | Block
Stop/Resume capture | N/A | N/A | N/T | N/T | N/T | Block
Suspend & Resume device during audio capture | N/A | N/A | N/T | N/T | N/T | Block
Do playback and capture at same time | Pass | Pass | N/T | N/T | Pass | Block
2 aplay_Analogue + Media Playback | Pass | Pass | N/A | N/A | N/A | Block
2 aplay_Analogue + HDMI | N/A | N/A | N/T | N/T | Pass | N/A
DPMST test | N/A | N/A | N/T | N/A | N/T | N/A
Check the audio channel via speaker-test | Pass | Pass | N/T | N/T | Pass | Block
Suspend & Resume device without audio playback or capture | N/A | N/A | N/T | N/T | Pass | Block
Check the runtime PM status | N/A | N/A |   | N/T | Pass | Block
paplay - Play an audio with high-level audio player | Pass | Pass | N/T | N/T | Pass | Block
parecord - Record an audio with high-level audio recorder | Pass | Pass | N/T | N/T | N/T | Block
Modules reload | Pass | Failed (#1059) | N/T | N/T | N/T | Block
Modules reload - 100 times | Pass | Failed (#1059) | N/T | N/T | N/T | Block
Suspend & Resume without playback_300 times | N/A | N/A | Pass | N/T | Failed (#1053) | Block
Suspend & Resume with I2S / Analog HDA playback_300 times | N/A | N/A | N/T | N/T | Failed (#1053) | Block
Suspend & Resume with HDMI playback_300 times | N/A | N/A | N/T | N/T | N/T | N/A
S0ix  --Check S0ix -100 times | N/A | N/A | N/A | N/A | N/A | N/A
volume change without playback/capture -1000 times | Pass | Pass | N/T | N/T | Pass | Block

**Comment by ClarexZhou** [comment]
I tested this PR on CML RVP HDA based notebook and WHL-I2S platform.  No regression on WHL i2s. 
But 2 new issues on CML RVP notebook.
1. Kernel null pointer then 0x60050000: GLB_STREAM_MSG: TRIG_STOP ipc timed out when system boot up. Frequency: 30%
[dmesg_failed_5.txt](https://github.com/thesofproject/linux/files/3430465/dmesg_failed_5.txt)
[logger_failed_5.txt](https://github.com/thesofproject/linux/files/3430470/logger_failed_5.txt)
[logger-t_failed_5.txt](https://github.com/thesofproject/linux/files/3430471/logger-t_failed_5.txt)

2. DP no audio output after below steps: play DP->pause DP->enter S3->wake up->resume DP. 
Frequency: 3/3
DP can output normally when stop and replay again.
[DPnoaudiooutputAfterS3duringPaused_soflogger.txt](https://github.com/thesofproject/linux/files/3430491/DPnoaudiooutputAfterS3duringPaused_soflogger.txt)
[DPnoaudiooutputAfterS3duringPaused_dmesg.txt](https://github.com/thesofproject/linux/files/3430492/DPnoaudiooutputAfterS3duringPaused_dmesg.txt)


Env
kernel: https://sof-ci-storage.sh.intel.com/pr/linux/pr1093-4/
Firmware: 82564659 https://github.com/thesofproject/sof/commits/master
Topology: sof-whl-rt5682.tplg and sof-hda-generic-2ch.tplg

**Comment by plbossart** [comment]
> I tested this PR on CML RVP HDA based notebook and WHL-I2S platform. No regression on WHL i2s.
> But 2 new issues on CML RVP notebook.
> 
> 1. Kernel null pointer then 0x60050000: GLB_STREAM_MSG: TRIG_STOP ipc timed out when system boot up. Frequency: 30%
>    [dmesg_failed_5.txt](https://github.com/thesofproject/linux/files/3430465/dmesg_failed_5.txt)
>    [logger_failed_5.txt](https://github.com/thesofproject/linux/files/3430470/logger_failed_5.txt)
>    [logger-t_failed_5.txt](https://github.com/thesofproject/linux/files/3430471/logger-t_failed_5.txt)
> 2. DP no audio output after below steps: play DP->pause DP->enter S3->wake up->resume DP.
>    Frequency: 3/3
>    DP can output normally when stop and replay again.
>    [DPnoaudiooutputAfterS3duringPaused_soflogger.txt](https://github.com/thesofproject/linux/files/3430491/DPnoaudiooutputAfterS3duringPaused_soflogger.txt)
>    [DPnoaudiooutputAfterS3duringPaused_dmesg.txt](https://github.com/thesofproject/linux/files/3430492/DPnoaudiooutputAfterS3duringPaused_dmesg.txt)
> 
> Env
> kernel: https://sof-ci-storage.sh.intel.com/pr/linux/pr1093-4/
> Firmware: 82564659 https://github.com/thesofproject/sof/commits/master
> Topology: sof-whl-rt5682.tplg and sof-hda-generic-2ch.tplg

well we have no choice: we need to merge and track those as new issues.

**Comment by xiulipan** [comment]
If the CI result for APL is caused by SSH issue, then I think this should be some common issue from v5.3 kernel. Need to track this issue.

**Comment by wenqingfu** [comment]
this PR causes lots of trouble to CI, not audio but connectivity.

**Comment by plbossart** [comment]
> this PR causes lots of trouble to CI, not audio but connectivity.

well then *someone* needs to bisect and figure out the regression... We can't stay with the same version, it's going to impact the rest of our work for SoundWire support.

**Comment by plbossart** [comment]
zero connectivity issues for me on APL UP2 boards with Mark Brown's tree and the SOF one. The SSH prompt is even faster than usual.
A local CI lab issue?

**Comment by ranj063** [comment]
> zero connectivity issues for me on APL UP2 boards with Mark Brown's tree and the SOF one. The SSH prompt is even faster than usual.

@plbossart now that @xiulipan mentioned it, I did see the same SSH issue on my UP2 with this PR as well. Yesterday, I dismissed it thinking that my network was poor as well.

**Comment by plbossart** [comment]
> > zero connectivity issues for me on APL UP2 boards with Mark Brown's tree and the SOF one. The SSH prompt is even faster than usual.
> 
> @plbossart now that @xiulipan mentioned it, I did see the same SSH issue on my UP2 with this PR as well. Yesterday, I dismissed it thinking that my network was poor as well.

What sort of network do you have? I have a plain vanilla Gigabit internet switch, in fact the Up2 is behind a set of 3 switches in series.

Anyways, since you kindly volunteered by speaking up you are it ;-)

**Comment by ranj063** [comment]
> Anyways, since you kindly volunteered by speaking up you are it ;-)

@plbossart I was thinking the same thing when I typed my comment. I can look into it tonight for sure. We're in the process to moving to gigabit fiber but wont have it until next week.

**Comment by ranj063** [comment]
@plbossart @xiulipan it is this commit that's causing connectivity issues: 
c12f7c23f7d Merge branch 'asoc-5.3' into asoc-linus

But this is a merge commit and it's going to hard to identify what went wrong. any ideas how to go about it?

**Comment by plbossart** [comment]
> @plbossart @xiulipan it is this commit that's causing connectivity issues:
> [c12f7c2](https://github.com/thesofproject/linux/commit/c12f7c23f7d6570b7c084d836658b0f110bb9b5b) Merge branch 'asoc-5.3' into asoc-linus
> 
> But this is a merge commit and it's going to hard to identify what went wrong. any ideas how to go about it?

if you are trying to root cause a connectivity issue, start with 5.2 and bisect with 5.3_rc1 - without even looking at SOF.

**Comment by ranj063** [comment]
@plbossart could you please send me your kernel config file for UP2?

**Comment by ranj063** [comment]
@plbossart I've identifed the fix for the connectivity issues from the v5.3-rc2 kernel. Should I cherry-pick this into this merge PR?

 r8169: fix RTL8168g PHY init
    
    This fixes a copy&paste error in the original patch. Setting the wrong
    register resulted in massive packet loss on some systems.
    
    Fixes: a2928d28643e ("r8169: use paged versions of phylib MDIO access functions")
    Tested-by: Thomas Voegtle <tv@lio96.de>
    Signed-off-by: Thomas Voegtle <tv@lio96.de>
    Signed-off-by: Heiner Kallweit <hkallweit1@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

**Comment by ranj063** [comment]
I just pushed the fix for the connectivity issue. @xiulipan can you please confirm it works at your end too?

**Comment by xiulipan** [comment]
@ranj063 
Thanks for the fixing! I did not see the error on my own UP2 device.
If the CI is not complaining I am good with the PR!

**Comment by ranj063** [comment]
@plbossart I think this PR is ready for merge now.

**Pull request merged**
