### PR TITLE
Fix Soundwire/Max98373 kconfigs

### PR DESCRIPTION
**Pull request by plbossart**
The initial code split doesn't compile with randconfig or when CONFIG_I2C is not defined. 
Split the baseline into common code and I2C code, and change the Kconfig/Makefile accordingly

While we're at it, add two cases that are not well supported in regmap and soundwire/intel.c

@ryans-lee @RanderWang @naveen-manohar can you please re-test? It compiles fine but I don't have a device to look for regressions.

Thanks!

### CODE REVIEW

**Comment by RanderWang** [comment]
@plbossart  Verified sdw scenario on my device.

**Comment by RanderWang** [comment]
@plbossart  one warning in original driver code is detected. Could you help to resolve it ? thanks!

**Comment by plbossart** [comment]
> @plbossart one warning in original driver code is detected. Could you help to resolve it ? thanks!

If you meant this warning: 
````
WARNING: Possible switch case/default not preceded by break or fallthrough comment
#502: FILE: sound/soc/codecs/max98373-i2c.c:429:
+	case MAX98373_R21FF_REV_ID:
````

this is a false positive. I see it all the time when ... is used in switch cases.

**Comment by plbossart** [comment]
there's been multiple updates for this codec, so I'll go ahead, revert/merge/squash and resubmit a cleaner version for review.

**Pull request merged**
