### PR TITLE
Fix the 5.9-rc1 DRM regression for GLK platform

### PR DESCRIPTION
**Pull request by kv2019i**
Revert the 7 reverts. Actual fix on top.

Fixes: #2410

### CODE REVIEW

**Comment by kv2019i** [comment]
Fix merged in drm-intel upstream, now ready to be merged to sof-dev.

**Review by plbossart — APPROVED** [review]

**Comment by plbossart** [comment]
CI doesn't seem to have improved over the Labor Day week-end, will re-trigger it.

**Comment by plbossart** [comment]
SOFCI TEST

**Review by juimonen — APPROVED** [review]
lgtm

**Comment by kv2019i** [comment]
One failure in CI is a known one -> https://github.com/thesofproject/sof/issues/3395 
Otherwise good, merging.

**Pull request merged**
