### PR TITLE
soundwire: intel: use component suspend instead of dai suspend

### PR DESCRIPTION
**Pull request by plbossart**
With Morimoto-san patches, the SoundWire code can no longer rely on
the DAI .suspend callback removed for 5.6. We can however use the
component suspend and follow the examples in other drivers.

This patch will need to be squashed before upstream.

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

### CODE REVIEW

**Comment by ranj063** [comment]
@plbossart I must say I dont understand the change quite well here. But looking at snd_soc_suspend(), it looks like the dai->driver->suspend would be called without any conditions while snd_soc_component_suspend() would be called only if component dapm bias level is OFF. Does that logic still work in your case?

**Comment by plbossart** [comment]
> @plbossart I must say I dont understand the change quite well here. But looking at snd_soc_suspend(), it looks like the dai->driver->suspend would be called without any conditions while snd_soc_component_suspend() would be called only if component dapm bias level is OFF. Does that logic still work in your case?

I have absolutely no idea, I just tried what @morimoto did for other devices. I seems to work for my very simple suspend tests, e.g. I can resume playback after a suspend (including when I pause before the suspend).

I am not sure in which cases the dapm bias level would be modified. I don't play with it at all.

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
ok, so CI is stuck so going to merge to move forward. I can't delay the upstream rebase further

**Pull request merged**
