### PR TITLE
ASoC: SOF: Use generic IPC type identifiers

### PR DESCRIPTION
**Pull request by ujfalusi**
Hi,

rename the IPC type defines to be more generic and intuitive:
SOF_IPC -> SOF_IPC_TYPE_3
SOF_INTEL_IPC4 -> SOF_IPC_TYPE_4

No functional change, just renaming all around.

### CODE REVIEW

**Review by paulstelian97 — DISMISSED** [review]
Barring some typos in commit descriptions here and there (e.g. in the "Drop unused IPC type defines" one you added an unintentional space as in "...t he generic names...") this is a welcome change.

**Comment by ujfalusi** [comment]
> Barring some typos in commit descriptions here and there (e.g. in the "Drop unused IPC type defines" one you added an unintentional space as in "...t he generic names...") this is a welcome change.

@paulstelian97, thanks, I will fix the typos in v2!

**Review by vijendarmukunda — DISMISSED** [review]

**Review by RanderWang — DISMISSED** [review]

**Review by dbaluta — DISMISSED** [review]

**Comment by ujfalusi** [comment]
Changes since v1:
- typos and commit messages fixed when they where they were wrong

**Review by paulstelian97 — DISMISSED** [review]

**Comment by ujfalusi** [comment]
Changes since v2:
- remove extra line left by the last commit (when removing the defines)

**Review by plbossart — DISMISSED** [review]

**Review by ranj063 — DISMISSED** [review]

**Review by iuliana-prodan — DISMISSED** [review]

**Comment by ujfalusi** [comment]
Thanks you all for the approvals!

I would wait a bit with merging this until other, mor important PRs are merged where the naming change can cause dependency for upstreaming.

I will also have a followup PR to rework the firmware, topology path and firmware name presentation, I will create  a draft with the current implementation, which is likely not going to be the right way, but I need to test how it is stretching.

**Review by RanderWang — DISMISSED** [review]

**Comment by ujfalusi** [comment]
Changes since v3:
- rebased and updated on latest topic/sof-dev

**Comment by ujfalusi** [comment]
Changes since v4:
- update for missed AMD vangogh

**Review by dbaluta — APPROVED** [review]

**Review by RanderWang — APPROVED** [review]
LGTM

**Review by vijendarmukunda — APPROVED** [review]
LGTM

**Review by ranj063 — APPROVED** [review]

**Review by plbossart — APPROVED** [review]

**Pull request merged**
