### PR TITLE
Merge/sound upstream 20211116

### PR DESCRIPTION
**Pull request by kv2019i**
First 5.16-rc1 merge. I had to drop the "ASoC: rt5682: move clk related code to rt5682_i2c_probe"" revert we've carried for a long time. The code no longer compiles with that patch revert. Let's see whether the problem is still present in CI results.

Matching sof-dev-rebase
https://github.com/thesofproject/linux/releases/tag/sof-dev-rebase-20211116-3_5.16-rc1

### CODE REVIEW

**Review by dbaluta — APPROVED** [review]

**Comment by kv2019i** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
ADL failed to boot in https://sof-ci.01.org/linuxpr/PR3278/build6710/devicetest/

By sheer coincidence I heard about a boot regression on ADL, tentative fix at https://patchwork.kernel.org/project/linux-acpi/patch/2623493.mvXUDI8C0e@kreacher/ "on its way to 5.16-rc2"

**Comment by plbossart** [comment]
> ADL failed to boot in https://sof-ci.01.org/linuxpr/PR3278/build6710/devicetest/
> 
> By sheer coincidence I heard about a boot regression on ADL, tentative fix at https://patchwork.kernel.org/project/linux-acpi/patch/2623493.mvXUDI8C0e@kreacher/ "on its way to 5.16-rc2"

Thanks @marc-hb 

@kv2019i do you want to pick this patch?

**Comment by kv2019i** [comment]
Thanks @marc-hb  and @plbossart . Cherrypicked the patch from upstream and pushed a new version.

**Comment by kv2019i** [comment]
Did a hacky merge to today's sof-dev to be able run a new test. 

Due to the conflict, I'll need to do a new merge PR and submit that separately. But let's use this to sanity check the new kernel at least passes CI.

**Comment by kv2019i** [comment]
Ok, now at least all CI machines boot up. There's one new error from kernel on UP2 that shows up in the suspend-resume tests:

```
[1439.266073] kernel: BUG: using smp_processor_id() in preemptible [00000000] code: rtcwake/24603
[ 1439.266405] kernel: BUG: using smp_processor_id() in preemptible [00000000] code: rtcwake/24603
```

EDIT: filed in https://github.com/thesofproject/sof-test/issues/806

**Comment by kv2019i** [comment]
Ok, now at least all CI machines boot up. There's one new error from kernel on UP2 that shows up in the suspend-resume tests:

```
[1439.266073] kernel: BUG: using smp_processor_id() in preemptible [00000000] code: rtcwake/24603
[ 1439.266405] kernel: BUG: using smp_processor_id() in preemptible [00000000] code: rtcwake/24603
```

**Comment by kv2019i** [comment]
Replaced with https://github.com/thesofproject/linux/pull/3282

**Pull request closed without merging**
