### PR TITLE
Merge/sound upstream 20210330

### PR DESCRIPTION
**Pull request by bardliao**
Regular merge

### CODE REVIEW

**Comment by bardliao** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
New USB failures reported in https://sof-ci.01.org/linuxpr/PR2812/build5534/devicetest/. Will try again (though that's starting to border the definition of insanity - trying the same thing expecting different results...)

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
let's retry now that we have a tentative fix in sof-test

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
ok CI is back to normal, thanks @fredoh9 !

**Pull request merged**
