### PR TITLE
[v3] ASoC: rt700/rt711: init jack detection after codec is attached

### PR DESCRIPTION
**Pull request by shumingfan**
[v3] ASoC: rt700: init jack detection after rt700 is attached

[v3] ASoC: rt711: init jack detection after rt711 is attached

### CODE REVIEW

**Comment by plbossart** [comment]
@bardliao can you double-check when you have a chance?

**Comment by shumingfan** [comment]
@bardliao @plbossart I rebase my forked branch, let this PR to be closed. It is my mistake.
If you need me to re-submit the PR, please let me know.

**Comment by plbossart** [comment]
@shumingfan when you force-push, GitHub keeps a trace of your changes, so we can always go back to the code.
This is the main reason why I like to have an open PR for stuff that I keep force-pushing, it keeps a history of the force-pushed branches, while Git doesn't.

@bardliao are you good with the changes in  2086ddc ?

**Comment by bardliao** [comment]
> 
> @bardliao are you good with the changes in [2086ddc](https://github.com/thesofproject/linux/commit/2086ddcc92372eb8c84ccedc3436623818c668a2) ?

@plbossart It looks good to me except it return -EAGAIN; if !rt711->hw_init.
https://github.com/thesofproject/linux/commit/2086ddcc92372eb8c84ccedc3436623818c668a2#diff-db6731e2aa4a2ae70cd72d2989b93584R458

**Pull request closed without merging**
