### PR TITLE
ASoC: Intel: change cs35l56 name_prefix

### PR DESCRIPTION
**Pull request by bardliao**
To use sequential amp numbers. I,e, AMP1, AMP2, AMP3, AMP4

### CODE REVIEW

**Review by aiChaoSONG — APPROVED** [review]

**Review by charleskeepax — APPROVED** [review]
Looks good to me.

**Review by plbossart — APPROVED** [review]

**Comment by plbossart** [comment]
I was tempted to merge but then wondered if any of the CI devices need to be updated? @bardliao please check with @aiChaoSONG and merge if that's ok.

**Comment by bardliao** [comment]
> I was tempted to merge but then wondered if any of the CI devices need to be updated? @bardliao please check with @aiChaoSONG and merge if that's ok.

There is no CI device with cs35l56, so no impact on CI. However, Karim tested the PR with latest UCM, and pipewire is still showing dummy endpoints. Let's wait for some days to see if anything is missing.

**Comment by plbossart** [comment]
I'll merge to remove some of the backlogs, if there is an issue we can handle it with a fixup! patch

**Pull request merged**
