### PR TITLE
Sdw/invert link dai prepare order

### PR DESCRIPTION
**Pull request by plbossart**
PR #4241 exposes a 100% reproducible issue with GCC11 on SoundWire platforms.

This PR suggests that the dailink/dai .prepare order has been wrong since Day1 of SoundWire integration, we always need to make sure the DAIs are prepared/configured *BEFORE* the bank switch is handled at the dailink level.

This was a tough one to crack, with all kinds of Heisenbugs masking the problem, but clearly starting a hardware-synchronized bank switch without first programming the sync period is an invalid programming sequence.

It's probably a 2-3 year bug.

@bardliao @RanderWang @ranj063 @ujfalusi comments welcome.

### CODE REVIEW

**Comment by bardliao** [comment]
@plbossart Adding prepare_dais_first flag makes sense to me. However, can we do back switch in dai .prepare and don't rely on the dailink/dai .prepare order?

**Comment by ujfalusi** [comment]
@plbossart, looks like CI disagrees, SDW fail remains.

**Comment by plbossart** [comment]
it appears this only works on one device. I still think the order matters but it's at a different level.

**Comment by plbossart** [comment]
I still have an interesting log on the same device as @ujfalusi 

````
[ 1658.664240] snd_sof:ipc3_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[ 1658.665175] snd_soc_rt711:rt711_sdw_write: rt711 sdw:1:025d:0711:00: [rt711_sdw_write] 00e0 <= 0003
[ 1658.665237] snd_soc_rt711:rt711_sdw_write: rt711 sdw:1:025d:0711:00: [rt711_sdw_write] 00f0 <= 0003
[ 1658.665239] snd_soc_rt711:rt711_clock_config: rt711 sdw:1:025d:0711:00: rt711_clock_config complete, clk_freq=4800000
[ 1658.666675] soundwire_bus:sdw_handle_slave_alerts: rt711 sdw:1:025d:0711:00: Slave impl defined interrupt
[ 1658.666680] snd_soc_rt711:rt711_interrupt_callback: rt711 sdw:1:025d:0711:00: rt711_interrupt_callback control_port_stat=4
[ 1658.703474] PM: suspend exit

[ 1658.919144] snd_soc_rt711:rt711_sdw_read: rt711 sdw:1:025d:0711:00: [rt711_sdw_read] b921 0000 => 00000000
[ 1658.919156] snd_soc_rt711:rt711_jack_detect_handler: rt711 sdw:1:025d:0711:00: in rt711_jack_detect_handler, jack_type=0x0
[ 1658.919161] snd_soc_rt711:rt711_jack_detect_handler: rt711 sdw:1:025d:0711:00: in rt711_jack_detect_handler, btn_type=0x0
[ 1660.383999] snd_soc_rt711:rt711_sdw_write: rt711 sdw:1:025d:0711:00: [rt711_sdw_write] 00e0 <= 0003
[ 1660.384080] snd_soc_rt711:rt711_sdw_write: rt711 sdw:1:025d:0711:00: [rt711_sdw_write] 00f0 <= 0003
[ 1660.384085] snd_soc_rt711:rt711_clock_config: rt711 sdw:1:025d:0711:00: rt711_clock_config complete, clk_freq=4800000

<< that should happen with a bus config. It's very very suspicious that this happens here.

[ 1660.384731] snd_sof:sof_pcm_trigger: sof-audio-pci-intel-tgl 0000:00:1f.3: pcm: trigger stream 0 dir 0 cmd 0
[ 1660.384739] snd_sof:ipc3_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP

<<< xrun here

````

And the code in sdw_notify_config() has a mutex. So it could very well be that on resume the mutex is already taken or something.

**Comment by plbossart** [comment]
closing, wrong fix

**Pull request closed without merging**
