### PR TITLE
Merge/sound upstream 20210426

### PR DESCRIPTION
**Pull request by plbossart**
Minor merge mostly to add the SDCA codec changes from Realtek.

### CODE REVIEW

**Comment by plbossart** [comment]
It seems we have an upstream regression with the DA7219

````
RMMOD	snd_soc_da7219
rmmod: ERROR: Module snd_soc_da7219 is in use
````

will look into this.

**Comment by plbossart** [comment]
Reverting 12f8127fe9e6154dd4197df97e44f3fd67583071 ("ASoC: da7219: properly get clk from the provider") seems to fix the issue. Will report this upstream.

**Review by bardliao — APPROVED** [review]
Verified it with run-all-tests.sh on TGL sdw laptop.

**Review by kv2019i — APPROVED** [review]
Local tests are ok.

**Pull request merged**
