### PR TITLE
Merge/sound upstream 20220228

### PR DESCRIPTION
**Pull request by ujfalusi**
New merge with few fixes from upstream for compress.

### CODE REVIEW

**Comment by ujfalusi** [comment]
ADLP_RVP_NOCODEC has not audio card, but it is the same thing in the daily results?

**Comment by kv2019i** [comment]
What in the world is happening here:
https://sof-ci.01.org/linuxpr/PR3461/build7242/devicetest/?model=ADLP_RVP_NOCODEC&testcase=verify-kernel-boot-log
```
[    5.164051] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: failed updating IPC struct for pipeline.12
[    5.164226] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: tplg component load failed -22
[    5.164247] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to load DSP topology -22
```

**Comment by ranj063** [comment]
> What in the world is happening here: https://sof-ci.01.org/linuxpr/PR3461/build7242/devicetest/?model=ADLP_RVP_NOCODEC&testcase=verify-kernel-boot-log
> 
> ```
> [    5.164051] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: failed updating IPC struct for pipeline.12
> [    5.164226] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: tplg component load failed -22
> [    5.164247] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to load DSP topology -22
> ```

@kv2019i for some reason this is testing IPC4. not sure why

**Comment by ranj063** [comment]
SOFCI TEST

**Review by kv2019i — APPROVED** [review]
Seems good to go.

**Review by ranj063 — APPROVED** [review]

**Review by plbossart — APPROVED** [review]
lets's go and merge this

**Comment by marc-hb** [comment]
The rt711_jack_detect_handler failure in https://sof-ci.01.org/linuxpr/PR3461/build7243/devicetest/?model=TGLU_RVP_SDW&testcase=check-suspend-resume-with-playback-5  could be one of the first instance of
- #3459

In other words this PR could be the culprit.
```
2022-02-28 18:03:56 UTC Sub-Test: [REMOTE_COMMAND] sleep for 5
2022-02-28 18:04:01 UTC Sub-Test: [REMOTE_INFO] Check for the kernel log status
declare -- cmd="journalctl_cmd --since=@1646071421"
2022-02-28 18:04:02 UTC [ERROR] Caught kernel log error
===========================>>
[ 1409.316458] kernel: soundwire_intel soundwire_intel.link.0: IO transfer timed out, cmd 3 device 1 addr b921 len 1
[ 1409.316466] kernel: soundwire sdw-master-0: trf on Slave 1 failed:-110 write addr b921 count 0
[ 1409.316538] kernel: IO error in rt711_jack_detect_handler, ret -110
<<===========================
2022-02-28 18:04:02 UTC Sub-Test: [REMOTE_ERROR] Caught error in kernel log
2022-02-28 18:04:02 UTC Sub-Test: [REMOTE_ERROR] Starting func_exit_handler(), exit status=1, FUNCNAME stack:
2022-02-28 18:04:02 UTC Sub-Test: [REMOTE_ERROR]  die()  @  /home/ubuntu/sof-test/test-case/../case-lib/lib.sh
2022-02-28 18:04:02 UTC Sub-Test: [REMOTE_ERROR]  main()  @  /home/ubuntu/sof-test/test-case/check-suspend-resume.sh:91
2022-02-28 18:04:02 UTC Sub-Test: [REMOTE_INFO] Test Result: FAIL!
2022-02-28 18:04:02 UTC [REMOTE_ERROR] suspend resume failed
2022-02-28 18:04:02 UTC [REMOTE_ERROR] Starting func_exit_handler(), exit status=1, FUNCNAME stack:
2022-02-28 18:04:02 UTC [REMOTE_ERROR]  die()  @  /home/ubuntu/sof-test/test-case/../case-lib/lib.sh
2022-02-28 18:04:02 UTC [REMOTE_ERROR]  main()  @  /home/ubuntu/sof-test/test-case/check-suspend-resume-with-audio.sh:121
```

**Comment by ujfalusi** [comment]
> The rt711_jack_detect_handler failure in https://sof-ci.01.org/linuxpr/PR3461/build7243/devicetest/?model=TGLU_RVP_SDW&testcase=check-suspend-resume-with-playback-5 could be one of the first instance of
> 
>     * [SoundWire: TGL: IO error in rt711_jack_detect_handler #3459](https://github.com/thesofproject/linux/issues/3459)
> 
> 
> In other words this PR could be the culprit.

@marc-hb, #3459 was created 13 days ago, this PR got merged 9 days ago...

> ```
> 2022-02-28 18:03:56 UTC Sub-Test: [REMOTE_COMMAND] sleep for 5
> 2022-02-28 18:04:01 UTC Sub-Test: [REMOTE_INFO] Check for the kernel log status
> declare -- cmd="journalctl_cmd --since=@1646071421"
> 2022-02-28 18:04:02 UTC [ERROR] Caught kernel log error
> ===========================>>
> [ 1409.316458] kernel: soundwire_intel soundwire_intel.link.0: IO transfer timed out, cmd 3 device 1 addr b921 len 1
> [ 1409.316466] kernel: soundwire sdw-master-0: trf on Slave 1 failed:-110 write addr b921 count 0
> [ 1409.316538] kernel: IO error in rt711_jack_detect_handler, ret -110
> <<===========================
> 2022-02-28 18:04:02 UTC Sub-Test: [REMOTE_ERROR] Caught error in kernel log
> 2022-02-28 18:04:02 UTC Sub-Test: [REMOTE_ERROR] Starting func_exit_handler(), exit status=1, FUNCNAME stack:
> 2022-02-28 18:04:02 UTC Sub-Test: [REMOTE_ERROR]  die()  @  /home/ubuntu/sof-test/test-case/../case-lib/lib.sh
> 2022-02-28 18:04:02 UTC Sub-Test: [REMOTE_ERROR]  main()  @  /home/ubuntu/sof-test/test-case/check-suspend-resume.sh:91
> 2022-02-28 18:04:02 UTC Sub-Test: [REMOTE_INFO] Test Result: FAIL!
> 2022-02-28 18:04:02 UTC [REMOTE_ERROR] suspend resume failed
> 2022-02-28 18:04:02 UTC [REMOTE_ERROR] Starting func_exit_handler(), exit status=1, FUNCNAME stack:
> 2022-02-28 18:04:02 UTC [REMOTE_ERROR]  die()  @  /home/ubuntu/sof-test/test-case/../case-lib/lib.sh
> 2022-02-28 18:04:02 UTC [REMOTE_ERROR]  main()  @  /home/ubuntu/sof-test/test-case/check-suspend-resume-with-audio.sh:121
> ```

**Comment by marc-hb** [comment]
The first sighting of #3459 was in upstream merge #3454 which was... never merged.

Quoting myself from #3459

> The first _SOF_ Pull Requests started failing these two tests on TGLU_RVP_SDW on March 1st and then they almost never passed. #3461 was merged on Feb 28th

Find more data and discuss in #3459

**Comment by ujfalusi** [comment]
@marc-hb, I see, the bug was created for that old PR.
Fwiw, I have checked that there were no diff in the rt711 driver with the upstream merge. Some interesting timing or sequencing change coming via SDW perhaps?

I don't think we can revert this merge, so let's get it fixed asap via #3459

**Comment by marc-hb** [comment]
> Fwiw, I have checked that there were no diff in the rt711 driver with the upstream merge.

Thanks!

> Some interesting timing or sequencing change coming via SDW perhaps?

That was my guess too: race condition and "butterfly effect"...

> I don't think we can revert this merge, 

That was not my intention, I was just sharing the data.

**Pull request merged**
