### PR TITLE
RFC: ASoC: SOF: remove link unload code

### PR DESCRIPTION
**Pull request by RanderWang**
This function is for HDA to release stream. Actually, HDA doesn't
allocate any memory or HW resource, just an id of a logical stream.
Now this function will be called when driver is unload. All resource
would be released after driver unload, so no need to release it.

I first add these code for dynamically topology loading. If topology
is changed by driver, stream id should be released. But now this feature
does not exist, and we could add unload function if this feature is
implemented.

And the unload function introudces some FIXME and hack, it is ugly.

it fixs:https://github.com/thesofproject/linux/issues/336 https://github.com/thesofproject/linux/issues/343

Signed-off-by: Rander Wang <rander.wang@linux.intel.com>

### CODE REVIEW

**Comment by bardliao** [comment]
@RanderWang My opinion is the invert of what we did in sof_link_load() should be done in sof_link_unload(). For example, I will expect snd_soc_dai_put_channel_map() in sof_link_hda_unload() since there is a snd_soc_dai_get _channel_map() in sof_link_hda_load(). But actually, we have only .get_channel_map in hda_link_dai_ops. snd_hdac_ext_stream_assign() is called by hda_link_dma_get_channels() which is our .get_channel_map function. So, it is better to have a .put_channel_map function with snd_hdac_ext_stream_release(). It may be a big change, but our code will look more professional if we can make it more balanced :)

**Comment by RanderWang** [comment]
> @RanderWang My opinion is the invert of what we did in sof_link_load() should be done in sof_link_unload(). For example, I will expect snd_soc_dai_put_channel_map() in sof_link_hda_unload() since there is a snd_soc_dai_get _channel_map() in sof_link_hda_load(). But actually, we have only .get_channel_map in hda_link_dai_ops. snd_hdac_ext_stream_assign() is called by hda_link_dma_get_channels() which is our .get_channel_map function. So, it is better to have a .put_channel_map function with snd_hdac_ext_stream_release(). It may be a big change, but our code will look more professional if we can make it more balanced :)

Yes, I agree with you for balanced. But actually I used put_channel_map first but found it is not fit for this function. And it is only a id to release before driver unload, so it is usefulness.

**Comment by bardliao** [comment]
@RanderWang Indeed, put_channel_map() is not used for release. And actually, I don't think calling snd_hdac_ext_stream_assign() in get_channel_map() is a good idea. People may call snd_soc_dai_get _channel_map() multiple times if they don't know how we implement the .get_channel_map() function. Is it better to call snd_hdac_ext_stream_assign() in somewhere else and just return the tx_slot rx_slot by get_channel_map()? I am thinking can we have a SOF specific function to set the topology information and get all of the tx_num, tx_slot, rx_num, rx_slot from the snd_soc_dai_get _channel_map()?

**Comment by plbossart** [comment]
I don't think the use of get/set_channel_map is a good idea. This really makes sense for TDM but isn't really meaningful for HDaudio link DMA. It might be a better idea to add new callbacks. We've added one for SoundWire (set_sdw_stream), could we look at whether we can build on this? There is no legacy for SoundWire so we can still change the name as needed.

**Pull request closed without merging**
