### PR TITLE
Merge/sound upstream 20200615

### PR DESCRIPTION
**Pull request by plbossart**
First merge based on 5.8-rc1, so regressions are to be expected.
Testers, start your engines.

### CODE REVIEW

**Comment by plbossart** [comment]
WTH is going on with CI? Test report is on but all details are NA? @fredoh9 @marc-hb @xiulipan ?

**Comment by kv2019i** [comment]
Ok test on CFL. My remote ICL device is not booting up with this kernel (and I can't today access the logs). So definitely we'll need at least the CI coverage to go ahead.

**Comment by marc-hb** [comment]
> WTH is going on with CI? Test report is on but all details are NA?

I had a quick look at https://sof-ci.01.org/linuxpr/PR2198/build3945/devicetest/ (pro tip: always save links like this in the comments as force pushes tend to lose them) The tests seem to be running but there seems to be some error when booting back to the stock kernel which seems to stop the results from being transferred and shared. In case I didn't use the verb "seem" enough times: don't quote me.

**Comment by plbossart** [comment]
> > WTH is going on with CI? Test report is on but all details are NA?
> 
> I had a quick look. The tests seem to be running but there seems to be some error when booting back to the stock kernel which seems to stop the results from being transferred and shared. In case I didn't use the verb "seem" enough times: don't quote me.

Ah that would be interesting if e.g. the 5.8-rc1 based solution failed to reboot, maybe that triggers a different error handling.

**Comment by marc-hb** [comment]
> if e.g. the 5.8-rc1 based solution failed to reboot,

I was leaning more towards a failure somewhere in some GRUB save-default magic but I don't really know so I'll stop talking.

**Comment by plbossart** [comment]
> > if e.g. the 5.8-rc1 based solution failed to reboot,
> 
> I was leaning more towards a failure somewhere in some GRUB save-default magic but I don't really know so I'll stop talking.

oh if grub doesn't know how to load a kernel it's fatal, all the install needs to be redone. It happened to me once.

**Comment by plbossart** [comment]
@kv2019i no issues on my side on all SoundWire devices I have (CML-U laptop and ICL-RVP).

Ironically this looked really good for me, not sure why we see such a massive fail.

**Comment by aiChaoSONG** [comment]
SOFCI TEST
Test result now available. Previous no test result is an known CI issue, and now fixed.

**Comment by keyonjie** [comment]
This is verified works fine on my TGL HDA RVP with nocodec mode.

**Comment by bardliao** [comment]
It passes sof-test.sh test on CML-H laptop.

**Comment by plbossart** [comment]
ok, so no problems reported, will merge now.

**Pull request merged**
