### PR TITLE
Merge/sound upstream 20230814

### PR DESCRIPTION
**Pull request by plbossart**
minor update to check what's left to send now that we are at -rc6. this is pretty much the last call for the 6.6 cycle.

Note an upstream conflict fixed with a commit da38ec979c4251966cd6ef64f6bf4c42461751a4 ("ASoC: SOF: remove duplicate code due to merge")

the topic/sof-dev-rebase will be pushed later today.

### CODE REVIEW

**Comment by plbossart** [comment]
let's redo the tests since they are not shown

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
https://sof-ci.01.org/linuxpr/PR4523/build6144/devicetest/index.html failure on MTL_RVP_SDW reported in https://github.com/thesofproject/linux/issues/4532

No other unknown issue, let's redo the tests

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
The problem captured in #4532 is not reproduced, so likely something we have to look at off-line and see if it repeats.
Unless there are objections I'll merge this on Monday.

**Comment by ujfalusi** [comment]
> The problem captured in #4532 is not reproduced, so likely something we have to look at off-line and see if it repeats. Unless there are objections I'll merge this on Monday.

and it is unlikely to be caused by the upstream merge.

**Pull request merged**
