### PR TITLE
Upstream/pre v6.10 rc1

### PR DESCRIPTION
**Pull request by plbossart**
let's see if we have any regression after one week of merge window...

### CODE REVIEW

**Comment by plbossart** [comment]
Outside of new errors reported in https://github.com/thesofproject/sof-test/issues/1198, we have a timeout on MTL HDA boot?
https://sof-ci.01.org/linuxpr/PR5009/build3053/devicetest/index.html?model=MTLP_RVP_HDA&testcase=verify-kernel-boot-log

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
Redoing the tests we get another timeout on MTL, this time on SDW_AIOC
https://sof-ci.01.org/linuxpr/PR5009/build3108/devicetest/index.html?model=MTLP_SDW_AIOC&testcase=verify-kernel-boot-log

Something's off for sure.

**Comment by marc-hb** [comment]
> Redoing the tests we get another timeout on MTL, this time on SDW_AIOC
> https://sof-ci.01.org/linuxpr/PR5009/build3108/devicetest/index.html?model=MTLP_SDW_AIOC&testcase=verify-kernel-boot-log

> Something's off for sure.

I ssh'ed and looked at the logs. I found these unexpected i915 errors. The out-of-date GuC warning is not new but the i915 errors are.

EDIT: once again in https://sof-ci.01.org/linuxpr/PR5022/build3211/devicetest/index.html?model=MTLP_RVP_HDA&testcase=verify-kernel-boot-log


```
ay 21 16:32:18 jf-mtlp-rvp-sdw-4 kernel: i915 0000:00:02.0: [drm] Transparent Hugepage support is recommended for optimal performance on this platform!
May 21 16:32:18 jf-mtlp-rvp-sdw-4 kernel: i915 0000:00:02.0: vgaarb: VGA decodes changed: olddecodes=io+mem,decodes=io+mem:owns=io+mem
May 21 16:32:18 jf-mtlp-rvp-sdw-4 kernel: i915 0000:00:02.0: [drm] Finished loading DMC firmware i915/mtl_dmc.bin (v2.17)
May 21 16:32:18 jf-mtlp-rvp-sdw-4 kernel: snd_hda_core: unknown parameter 'hdac_i915_timeout_ms' ignored
May 21 16:32:18 jf-mtlp-rvp-sdw-4 kernel: snd_hda_core: unknown parameter 'hdac_i915_timeout_ms' ignored
May 21 16:32:18 jf-mtlp-rvp-sdw-4 kernel: i915 0000:00:02.0: [drm] GT0: GuC firmware i915/mtl_guc_70.bin (70.12.1) is recommended, but only i915/mtl_guc_70.bin (70.8.0) was found
May 21 16:32:18 jf-mtlp-rvp-sdw-4 kernel: i915 0000:00:02.0: [drm] GT0: Consider updating your linux-firmware pkg or downloading from https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915
May 21 16:32:18 jf-mtlp-rvp-sdw-4 kernel: i915 0000:00:02.0: [drm] GT1: GuC firmware i915/mtl_guc_70.bin (70.12.1) is recommended, but only i915/mtl_guc_70.bin (70.8.0) was found
May 21 16:32:18 jf-mtlp-rvp-sdw-4 kernel: i915 0000:00:02.0: [drm] GT1: Consider updating your linux-firmware pkg or downloading from https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915
May 21 16:32:18 jf-mtlp-rvp-sdw-4 kernel: i915 0000:00:02.0: [drm] GT0: GuC firmware i915/mtl_guc_70.bin version 70.8.0


May 21 16:32:20 jf-mtlp-rvp-sdw-4 systemd[831]: Starting Portal service (GNOME implementation)...
May 21 16:32:23 jf-mtlp-rvp-sdw-4 kernel: snd_sof_intel_hda:hda_codec_i915_display_power: sof-audio-pci-intel-mtl 0000:00:1f.3: Turning i915 HDAC power 0
May 21 16:32:39 jf-mtlp-rvp-sdw-4 kernel: Fence expiration time out i915-0000:00:02.0:gnome-shell<959>:2!
May 21 16:32:39 jf-mtlp-rvp-sdw-4 kernel: Fence expiration time out i915-0000:00:02.0:gnome-shell<959>:2!
May 21 16:32:39 jf-mtlp-rvp-sdw-4 kernel: Fence expiration time out i915-0000:00:02.0:gnome-shell[959]:2!
May 21 16:32:40 jf-mtlp-rvp-sdw-4 kernel: Fence expiration time out i915-0000:00:02.0:gnome-shell[959]:4!
May 21 16:32:40 jf-mtlp-rvp-sdw-4 kernel: Fence expiration time out i915-0000:00:02.0:gnome-shell[959]:6!
May 21 16:32:40 jf-mtlp-rvp-sdw-4 kernel: Fence expiration time out i915-0000:00:02.0:gnome-shell[959]:8!
May 21 16:32:40 jf-mtlp-rvp-sdw-4 kernel: Fence expiration time out i915-0000:00:02.0:gnome-shell[959]:a!
May 21 16:32:40 jf-mtlp-rvp-sdw-4 kernel: Fence expiration time out i915-0000:00:02.0:gnome-shell[959]:c!
May 21 16:32:40 jf-mtlp-rvp-sdw-4 kernel: Fence expiration time out i915-0000:00:02.0:gnome-shell[959]:e!
May 21 16:32:40 jf-mtlp-rvp-sdw-4 kernel: Fence expiration time out i915-0000:00:02.0:gnome-shell[959]:10!
May 21 16:32:40 jf-mtlp-rvp-sdw-4 kernel: Fence expiration time out i915-0000:00:02.0:gnome-shell[959]:12!
May 21 16:32:40 jf-mtlp-rvp-sdw-4 kernel: Fence expiration time out i915-0000:00:02.0:gnome-shell[959]:14!
May 21 16:32:40 jf-mtlp-rvp-sdw-4 kernel: Fence expiration time out i915-0000:00:02.0:gnome-shell[959]:16!
May 21 16:32:40 jf-mtlp-rvp-sdw-4 kernel: Fence expiration time out i915-0000:00:02.0:gnome-shell[959]:18!
May 21 16:32:40 jf-mtlp-rvp-sdw-4 dbus-daemon[865]: [session uid=1000 pid=865] Successfully activated service 'org.freedesktop.impl.portal.desktop.gnome'
May 21 16:32:40 jf-mtlp-rvp-sdw-4 systemd[831]: Started Portal service (GNOME implementation).
May 21 16:32:50 jf-mtlp-rvp-sdw-4 kernel: Fence expiration time out i915-0000:00:02.0:gnome-shell[959]:1a!
May 21 16:33:00 jf-mtlp-rvp-sdw-4 kernel: i915 0000:00:02.0: [drm] GPU HANG: ecode 12:0:00000000
May 21 16:33:00 jf-mtlp-rvp-sdw-4 kernel: i915 0000:00:02.0: [drm] GT0: Resetting chip for stopped heartbeat on rcs0
May 21 16:33:00 jf-mtlp-rvp-sdw-4 kernel: i915 0000:00:02.0: [drm] GT0: GuC firmware i915/mtl_guc_70.bin version 70.8.0
May 21 16:33:00 jf-mtlp-rvp-sdw-4 kernel: i915 0000:00:02.0: [drm] GT0: GUC: submission enabled
May 21 16:33:00 jf-mtlp-rvp-sdw-4 kernel: i915 0000:00:02.0: [drm] GT0: GUC: SLPC enabled
May 21 16:33:05 jf-mtlp-rvp-sdw-4 dbus-daemon[865]: [session uid=1000 pid=865] Activating via systemd: service name='org.freedesktop.impl.portal.desktop.gtk' unit='xdg-desktop-portal-gtk.service' requested by ':1.71' (u>
May 21 16:33:05 jf-mtlp-rvp-sdw-4 systemd[831]: Starting Portal service (GTK/GNOME implementation)...
May 21 16:33:15 jf-mtlp-rvp-sdw-4 kernel: i915 0000:00:02.0: [drm] GPU HANG: ecode 12:0:00000000
May 21 16:33:15 jf-mtlp-rvp-sdw-4 kernel: i915 0000:00:02.0: [drm] GT0: Resetting chip for stopped heartbeat on rcs0
May 21 16:33:15 jf-mtlp-rvp-sdw-4 kernel: i915 0000:00:02.0: [drm] GT0: GuC firmware i915/mtl_guc_70.bin version 70.8.0
May 21 16:33:15 jf-mtlp-rvp-sdw-4 kernel: i915 0000:00:02.0: [drm] GT0: GUC: submission enabled
May 21 16:33:15 jf-mtlp-rvp-sdw-4 kernel: i915 0000:00:02.0: [drm] GT0: GUC: SLPC enabled
May 21 16:33:30 jf-mtlp-rvp-sdw-4 xdg-desktop-por[1288]: Failed to create settings proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.gtk: Timeout was reached
May 21 16:33:50 jf-mtlp-rvp-sdw-4 systemd[831]: xdg-desktop-portal.service: start operation timed out. Terminating.
May 21 16:33:50 jf-mtlp-rvp-sdw-4 systemd[831]: xdg-desktop-portal.service: Failed with result 'timeout'.
May 21 16:33:50 jf-mtlp-rvp-sdw-4 systemd[831]: Failed to start Portal service.
May 21 16:33:56 jf-mtlp-rvp-sdw-4 kernel: i915 0000:00:02.0: [drm] GPU HANG: ecode 12:0:00000000
May 21 16:33:56 jf-mtlp-rvp-sdw-4 kernel: i915 0000:00:02.0: [drm] GT0: Resetting chip for stopped heartbeat on rcs0
May 21 16:33:56 jf-mtlp-rvp-sdw-4 kernel: i915 0000:00:02.0: [drm] GT0: GuC firmware i915/mtl_guc_70.bin version 70.8.0
May 21 16:33:56 jf-mtlp-rvp-sdw-4 kernel: i915 0000:00:02.0: [drm] GT0: GUC: submission enabled
May 21 16:33:56 jf-mtlp-rvp-sdw-4 kernel: i915 0000:00:02.0: [drm] GT0: GUC: SLPC enabled
May 21 16:34:20 jf-mtlp-rvp-sdw-4 dbus-daemon[865]: [session uid=1000 pid=865] Failed to activate service 'org.freedesktop.portal.Desktop': timed out (service_start_timeout=120000ms)
May 21 16:34:36 jf-mtlp-rvp-sdw-4 systemd[831]: xdg-desktop-portal-gtk.service: start operation timed out. Terminating.
May 21 16:34:36 jf-mtlp-rvp-sdw-4 systemd[831]: xdg-desktop-portal-gtk.service: Failed with result 'timeout'.
May 21 16:34:36 jf-mtlp-rvp-sdw-4 systemd[831]: Failed to start Portal service (GTK/GNOME implementation).
May 21 16:35:05 jf-mtlp-rvp-sdw-4 dbus-daemon[865]: [session uid=1000 pid=865] Failed to activate service 'org.freedesktop.impl.portal.desktop.gtk': timed out (service_start_timeout=120000ms)
May 21 16:36:19 jf-mtlp-rvp-sdw-4 kernel: snd_sof_intel_hda:hda_codec_i915_display_power: sof-audio-pci-intel-mtl 0000:00:1f.3: Turning i915 HDAC power 1
May 21 16:36:19 jf-mtlp-rvp-sdw-4 kernel: snd_sof_intel_hda:hda_codec_i915_display_power: sof-audio-pci-intel-mtl 0000:00:1f.3: Turning i915 HDAC power 0
May 21 16:36:53 jf-mtlp-rvp-sdw-4 kernel: snd_sof_intel_hda:hda_codec_i915_display_power: sof-audio-pci-intel-mtl 0000:00:1f.3: Turning i915 HDAC power 0
May 21 16:36:58 jf-mtlp-rvp-sdw-4 kernel: snd_sof_intel_hda:hda_codec_i915_display_power: sof-audio-pci-intel-mtl 0000:00:1f.3: Turning i915 HDAC power 1
May 21 16:36:58 jf-mtlp-rvp-sdw-4 kernel: snd_sof_intel_hda:hda_codec_i915_display_power: sof-audio-pci-intel-mtl 0000:00:1f.3: Turning i915 HDAC power 0
May 21 16:37:32 jf-mtlp-rvp-sdw-4 kernel: snd_sof_intel_hda:hda_codec_i915_display_power: sof-audio-pci-intel-mtl 0000:00:1f.3: Turning i915 HDAC power 0
May 21 16:37:37 jf-mtlp-rvp-sdw-4 kernel: snd_sof_intel_hda:hda_codec_i915_display_power: sof-audio-pci-intel-mtl 0000:00:1f.3: Turning i915 HDAC power 1
May 21 16:37:37 jf-mtlp-rvp-sdw-4 kernel: snd_sof_intel_hda:hda_codec_i915_display_power: sof-audio-pci-intel-mtl 0000:00:1f.3: Turning i915 HDAC power 0

etc.
```

**Comment by marc-hb** [comment]
Similar i915 errors, GuC version warnings and GPU hang in https://sof-ci.01.org/linuxpr/PR5009/build3053/devicetest/index.html?model=MTLP_RVP_HDA&testcase=verify-kernel-boot-log

> Something's off for sure.

XE is probably ruffling a few i915 feathers:
- https://github.com/thesofproject/kconfig/pull/91#issuecomment-2085435452

**Comment by marc-hb** [comment]
xrandr will not hang forever anymore, so hopefully we'll get logs every time:
- https://github.com/thesofproject/sof-test/pull/1200

Interestingly, I found one case with a (smaller?) number of `i915` "fence" and other warnings. This time the test did not hang which means all logs are available:
https://sof-ci.01.org/linuxpr/PR5009/build3108/devicetest/index.html?model=MTLP_RVP_NOCODEC&testcase=verify-kernel-boot-log
https://sof-ci.01.org/linuxpr/PR5009/build3108/devicetest/index.html?model=MTLP_RVP_NOCODEC&testcase=verify-kernel-boot-log

Maybe this depends on whether a monitor is connected or not and which kind? It wouldn't be the first time:
- https://github.com/thesofproject/sof-test/discussions/998

**Comment by marc-hb** [comment]
SOFCI TEST

EDIT: xrandr still hung in https://sof-ci.01.org/linuxpr/PR5009/build3108/devicetest/index.html?model=MTLP_SDW_AIOC&testcase=verify-kernel-boot-log and still no logs because the old sof-test version was still used :-(

https://sof-ci.01.org/linuxpr/PR5009/build3110/devicetest/index.html?model=CML_HEL_RT5682-ipc3&testcase=verify-kernel-boot-log also failed because it also used the old Kconfig commit :-(

Maybe a force push is required to test the newer stuff...

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
The ISH driver has been blocklisted in LNL https://sof-ci.01.org/linuxpr/PR5009/build3170/devicetest/index.html

The other, LNL alsabat failures are known.

**Comment by marc-hb** [comment]
While they were not fatal, "Fence expiration time out" warnings were found in https://sof-ci.01.org/linuxpr/PR5009/build3171/devicetest/index.html?model=MTLP_SDW_AIOC&testcase=verify-kernel-boot-log but not for the other two MTL models.

There seems to be a correlation between these warnings and the out-of-date GuC warnings (internal issue # 572)

EDIT: more in https://sof-ci.ostc.intel.com/#/result/planresultdetail/41783?model=MTLP_SDW_AIOC&testcase=verify-kernel-boot-log

**Comment by marc-hb** [comment]
Replaced by #5022 which I just found by chance

**Comment by marc-hb** [comment]
BTW: https://docs.kernel.org/driver-api/firmware/firmware-usage-guidelines.html

**Pull request closed without merging**
