### PR TITLE
Merge/backport v4.20 intel audio

### PR DESCRIPTION
**Pull request by plbossart**
two merges in sequence, one to refresh the v4.19 backport then add v4.20 backport.

### CODE REVIEW

**Comment by plbossart** [comment]
@xiulipan can you check what's happening with the build machines? I am able to work with this branch without issues. Checkpatch will not work for sure when applying 10,000 commits during a merge, not sure if this triggers something else.

**Comment by xiulipan** [comment]
@plbossart 
Yes, checkpatch are both broken since there are indeed some error or warning it this 1000+ commit.

For travis it seems the gcc compiler is too old 
```bash
make modules_prepare
scripts/kconfig/conf  --syncconfig Kconfig
You are building kernel with non-retpoline compiler.
Please update your compiler.
make: *** [checkbin] Error 1
```

For sof-ci
There are some build error.
Not sure if this could really build
```bash
make SUBDIRS=sound/soc/sof C=2
  CHECK   sound/soc/sof/intel/byt.c
  CC [M]  sound/soc/sof/intel/byt.o
In file included from ./arch/x86/include/asm/string_64.h:6:0,
                 from ./arch/x86/include/asm/string.h:5,
                 from ./include/linux/string.h:20,
                 from ./include/linux/bitmap.h:9,
                 from ./include/linux/cpumask.h:12,
                 from ./arch/x86/include/asm/cpumask.h:5,
                 from ./arch/x86/include/asm/msr.h:11,
                 from ./arch/x86/include/asm/processor.h:21,
                 from ./arch/x86/include/asm/cpufeature.h:5,
                 from ./arch/x86/include/asm/thread_info.h:53,
                 from ./include/linux/thread_info.h:38,
                 from ./arch/x86/include/asm/preempt.h:7,
                 from ./include/linux/preempt.h:81,
                 from ./include/linux/spinlock.h:51,
                 from ./include/linux/seqlock.h:36,
                 from ./include/linux/time.h:6,
                 from ./include/linux/stat.h:19,
                 from ./include/linux/module.h:10,
                 from sound/soc/sof/intel/byt.c:15:
./include/linux/jump_label.h: In function ‘jump_entry_code’:
./include/linux/jump_label.h:153:14: error: dereferencing pointer to incomplete type ‘const struct jump_entry’
  return entry->code;
              ^~
./include/linux/jump_label.h: In function ‘jump_entry_set_init’:
./include/linux/jump_label.h:180:7: error: dereferencing pointer to incomplete type ‘struct jump_entry’
  entry->key |= 2;
       ^~
./include/linux/jump_label.h: At top level:
./include/linux/jump_label.h:212:26: error: array type has incomplete element type ‘struct jump_entry’
 extern struct jump_entry __start___jump_table[];
                          ^~~~~~~~~~~~~~~~~~~~
./include/linux/jump_label.h:213:26: error: array type has incomplete element type ‘struct jump_entry’
 extern struct jump_entry __stop___jump_table[];
                          ^~~~~~~~~~~~~~~~~~~
```

**Comment by plbossart** [comment]
@xiulipan this branch works fine for me so I will take the risk of merging to make progress. The current sof-dev is archived as archive/sof-dev-v4.19-20190107

**Comment by xiulipan** [comment]
@plbossart 
I will check the build status of the 4.20 and send PR if there are any build errors

**Pull request merged**
