### PR TITLE
ASoC: es8316: add support for ESSX8336 ACPI _HID

### PR DESCRIPTION
**Pull request by plbossart**
The same codec seems to have different personalities. ESSX8316 was
used for Baytrail/CherryTrail, ESSX8336 seems to be used for AppoloLake,
GeminiLake, JasperLake and TigerLake devices.

BugLink: https://github.com/thesofproject/linux/issues/2955
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

### CODE REVIEW

**Comment by plbossart** [comment]
> es8316_i2c_id[ ] needs es8336 entry too, right? @plbossart

I don't think so, there's no requirement to have a 1:1 mapping between ACPI _HID and the entries in the i2c_device_id table.

@bardliao can you comment here?

**Comment by bardliao** [comment]
> > es8316_i2c_id[ ] needs es8336 entry too, right? @plbossart
> 
> I don't think so, there's no requirement to have a 1:1 mapping between ACPI _HID and the entries in the i2c_device_id table.
> 
> @bardliao can you comment here?

Agree with @plbossart ACPI _HID and the i2c id_table is not 1:1 mapping. See [rt5640.c](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/codecs/rt5640.c) for example.

```
static const struct i2c_device_id rt5640_i2c_id[] = {
	{ "rt5640", 0 },
	{ "rt5639", 0 },
	{ "rt5642", 0 },
	{ }
};
static const struct acpi_device_id rt5640_acpi_match[] = {
	{ "INT33CA", 0 },
	{ "10EC3276", 0 },
	{ "10EC5640", 0 },
	{ "10EC5642", 0 },
	{ "INTCCFFD", 0 },
	{ },
};
```
Besides, we don't exactly know if "es8336" is the i2c device id for "ESSX8336".

**Comment by bardliao** [comment]
@hli25 Any objections if we merge this and post upstream?

**Comment by hli25** [comment]
> @hli25 Any objections if we merge this and post upstream?

Please go ahead to merge it, thanks.

**Pull request merged**
