### PR TITLE
ASoC: Intel: add DMIC for bxt_pcm512x

### PR DESCRIPTION
**Pull request by xiulipan**
Add DMIC for bxt_pcm512x as DMIC0 and id 1.

Work with https://github.com/thesofproject/soft/pull/44

### CODE REVIEW

**Comment by plbossart** [comment]
I don't understand why this is needed, sorry. You can test the dmic with the nocodec mode.

**Comment by ranj063** [comment]
@plbossart it is useful for testing suspend/resume with more than one pipeline on APL.

For some unknown reason so far, I cant get the system to suspend with nocodec topology (even if there is only one pipeline).

**Comment by plbossart** [comment]
I am all for more tests, but we already have platforms with DMICs. I 
don't see what gap this fills - and if I follow your logic we should add 
DMICs to the sof-apl-tdf8532 case as well.

BTW I think we should really test suspend/resume when the same SSP is 
used for playback/capture since they share common settings.

**Comment by xiulipan** [comment]
@lgirdwood @plbossart 
Close this PR since topology is closed. No need to add DMIC to UP2

**Pull request closed without merging**
