### PR TITLE
Merge/sound upstream 20240910

### PR DESCRIPTION
**Pull request by bardliao**
Probably last upstream merge for 6.12

### CODE REVIEW

**Comment by bardliao** [comment]
I reverted the https://lore.kernel.org/linux-arm-kernel/20240905-alsa-12-24-128-v1-13-8371948d3921@baylibre.com/T/ series. I seems some other changes are required to apply the series. Or we will get 32000Hz rate, like
```
[  409.852286] sof-audio-pci-intel-lnl 0000:00:1f.3: sof_ipc4_init_input_audio_fmt: Unsupported audio format: 32000Hz, 16bit, 2 channels
[  409.852405] sof-audio-pci-intel-lnl 0000:00:1f.3: failed to prepare widget host-copier.0.playback
[  409.852453] sof-audio-pci-intel-lnl 0000:00:1f.3: Failed to prepare connected widgets
[  409.852497] sof-audio-pci-intel-lnl 0000:00:1f.3: error: failed widget list set up for pcm 0 dir 0
[  409.852544] sof-audio-pci-intel-lnl 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_hw_params on 0000:00:1f.3: -22
```

**Comment by plbossart** [comment]
> I reverted the https://lore.kernel.org/linux-arm-kernel/20240905-alsa-12-24-128-v1-13-8371948d3921@baylibre.com/T/ series. I seems some other changes are required to apply the series. Or we will get 32000Hz rate, like
> 
> ```
> [  409.852286] sof-audio-pci-intel-lnl 0000:00:1f.3: sof_ipc4_init_input_audio_fmt: Unsupported audio format: 32000Hz, 16bit, 2 channels
> [  409.852405] sof-audio-pci-intel-lnl 0000:00:1f.3: failed to prepare widget host-copier.0.playback
> [  409.852453] sof-audio-pci-intel-lnl 0000:00:1f.3: Failed to prepare connected widgets
> [  409.852497] sof-audio-pci-intel-lnl 0000:00:1f.3: error: failed widget list set up for pcm 0 dir 0
> [  409.852544] sof-audio-pci-intel-lnl 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_hw_params on 0000:00:1f.3: -22
> ```

You should report this failure on the mailing list @bardliao 

I also don't really understand how this could be applied without having any side effects, the topology files are likely broken because of the new additions?

**Comment by bardliao** [comment]
> > I reverted the https://lore.kernel.org/linux-arm-kernel/20240905-alsa-12-24-128-v1-13-8371948d3921@baylibre.com/T/ series. I seems some other changes are required to apply the series. Or we will get 32000Hz rate, like
> > ```
> > [  409.852286] sof-audio-pci-intel-lnl 0000:00:1f.3: sof_ipc4_init_input_audio_fmt: Unsupported audio format: 32000Hz, 16bit, 2 channels
> > [  409.852405] sof-audio-pci-intel-lnl 0000:00:1f.3: failed to prepare widget host-copier.0.playback
> > [  409.852453] sof-audio-pci-intel-lnl 0000:00:1f.3: Failed to prepare connected widgets
> > [  409.852497] sof-audio-pci-intel-lnl 0000:00:1f.3: error: failed widget list set up for pcm 0 dir 0
> > [  409.852544] sof-audio-pci-intel-lnl 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_hw_params on 0000:00:1f.3: -22
> > ```
> 
> You should report this failure on the mailing list @bardliao

Ok, I thought we may miss the user space change.

> 
> I also don't really understand how this could be applied without having any side effects, the topology files are likely broken because of the new additions?

**Comment by bardliao** [comment]
SOFCI TEST

**Pull request closed without merging**
