### PR TITLE
Merge/sound upstream 20200710

### PR DESCRIPTION
**Pull request by kv2019i**

### CODE REVIEW

**Comment by plbossart** [comment]
we need to retest w/ the firmware that includes https://github.com/thesofproject/sof/pull/3159 to fix Baytrail/Broadwell. Will run SOFCI TEST but if this doesn't take the latest firmware we probably need help from the CI team. @fredoh9 @aiChaoSONG @xiulipan FYI.

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by aiChaoSONG** [comment]
SOFCI TEST

**Comment by kv2019i** [comment]
@plbossart @aiChaoSONG With the FW patch revert, the previously passing tests are now ok. There are two BYT/CHT failures left. These are both for the alsa-bat. I checked the plot and it seems the playback is severely clipped. Maybe a gain setting is wrong in the DUT? @aiChaoSONG  ?

UPDATE: last CI run I found where alsa-bat test is passing on these devices, is this from June 26th:
https://sof-ci.01.org/linuxpr/PR2232/build4002/devicetest/

**Comment by aiChaoSONG** [comment]
@kv2019i   Maybe, @keqiaozhang  will re-tune alsa setting for all platforms

**Comment by kv2019i** [comment]
@plbossart I think we can push ahead with this one. The alsa-bat failure does not seem related to the kernel upstream update.

**Comment by plbossart** [comment]
the alsa-bat issue is known and due to mixer settings, already being tracked separatetely.

**Pull request merged**
