### PR TITLE
Merge/sound upstream 20200303

### PR DESCRIPTION
**Pull request by kv2019i**
Time for another upstream merge. No merge conflicts this time, so this was pretty straightforward (as for the merges, let's see what CI thinks).

Matching sof-dev-rebase candidate:
https://github.com/kv2019i/linux/tree/merge/sof-dev-rebase-20200303

### CODE REVIEW

**Comment by kv2019i** [comment]
Submitted a test with a partial set of patches -> https://github.com/thesofproject/linux/pull/1856

**Comment by kv2019i** [comment]
Bisect via CI is quite painful, but it would seem the problem is caused by either of these two patches:

ASoC: dapm: Correct DAPM handling of active widgets during shutdown
ASoC: soc-component: tidyup snd_soc_pcm_component_sync_stop()

The connection is not very clear at all, but I've got three failus on the BDW case with these patches and now a clean run without them, so it would seem these are triggering the issue.
Test run with these two patches reverted:
https://sof-ci.01.org/linuxpr/PR1856/build3214/devicetest/

@xiulipan can you take a look?

**Comment by plbossart** [comment]
> Bisect via CI is quite painful, but it would seem the problem is caused by either of these two patches:
> 
> ASoC: dapm: Correct DAPM handling of active widgets during shutdown
> ASoC: soc-component: tidyup snd_soc_pcm_component_sync_stop()
> 
> The connection is not very clear at all, but I've got three failus on the BDW case with these patches and now a clean run without them, so it would seem these are triggering the issue.
> Test run with these two patches reverted:
> https://sof-ci.01.org/linuxpr/PR1856/build3214/devicetest/
> 
> @xiulipan can you take a look?

@lgirdwood do you still have your Dell broadwell laptop? Wondering if you can help us out on this one now that we have a small set of patches identified.

@kv2019i kudos for your work, impressive to use git bisect with CI :+1:

**Comment by ranj063** [comment]
> Bisect via CI is quite painful, but it would seem the problem is caused by either of these two patches:
> 
> ASoC: dapm: Correct DAPM handling of active widgets during shutdown
> ASoC: soc-component: tidyup snd_soc_pcm_component_sync_stop()
> 
> The connection is not very clear at all, but I've got three failus on the BDW case with these patches and now a clean run without them, so it would seem these are triggering the issue.
> Test run with these two patches reverted:
> https://sof-ci.01.org/linuxpr/PR1856/build3214/devicetest/
> 
> @xiulipan can you take a look?

@kv2019i I can confirm that it is only this patch thats the culprit. Still working on figuring out a fix.
ASoC: dapm: Correct DAPM handling of active widgets during shutdown

**Comment by xiulipan** [comment]
@kv2019i @ranj063 @plbossart After some debug on BDW paltform , I found this maybe related with rt286 codec driver.

Somehow with `ASoC: dapm: Correct DAPM handling of active widgets during shutdown` we get an codec IRQ, then it try to force enable PIN `HV, VREF, LDO1`. Not sure why and what is those pins on the codec. Any idea?

```
[ 1673.003963] PXL_TEST REMOVEING snd_sof_acpi
[ 1673.059481] broadwell-audio broadwell-audio: ASoC: Unregistered card 'sof-broadwell-rt286'
[ 1673.059577] sof-audio-acpi INT3438:00: ASoC: Unregistered DAI 'ssp0-port'
[ 1673.059582] sof-audio-acpi INT3438:00: ASoC: Unregistered DAI 'ssp1-port'
[ 1673.059585] sof-audio-acpi INT3438:00: ASoC: Unregistered DAI 'Low Latency 0'
[ 1673.059588] sof-audio-acpi INT3438:00: ASoC: Unregistered DAI 'Media Playback 1'
[ 1673.059958] PXL: rt286 irq
[ 1673.059963] rt286 i2c-INT343A:00: PXL: rt286_jack_detect
[ 1673.061075] rt286 i2c-INT343A:00: ASoC: force enable pin HV
[ 1673.061083] rt286 i2c-INT343A:00: ASoC: pxl force unknown pin HV
[ 1673.061086] rt286 i2c-INT343A:00: ASoC: force enable pin VREF
[ 1673.061089] rt286 i2c-INT343A:00: ASoC: pxl force unknown pin VREF
[ 1673.061092] rt286 i2c-INT343A:00: ASoC: force enable pin LDO1
[ 1673.061095] rt286 i2c-INT343A:00: ASoC: pxl force unknown pin LDO1
```

**Pull request merged**
