### PR TITLE
Merge/sound upstream 20240730

### PR DESCRIPTION
**Pull request by bardliao**
Initial upstream merge for 6.11
tag sof-dev-rebase-20240715 pushed to https://github.com/bardliao/linux/releases/tag/sof-dev-rebase-20240730

### CODE REVIEW

**Comment by plbossart** [comment]
looks like we have a regression on USB audio, 
````
RMMOD	snd_usb_audio
```` 
gets stuck in multiple tests. We need to root-cause this.

We still have the same issue with i915/xe
````
[    5.600600] kernel: sysctl table check failed: dev/xe/(null) procname is null
[    5.600618] kernel: sysctl table check failed: dev/xe/(null) No proc_handler
````

**Comment by bardliao** [comment]
> looks like we have a regression on USB audio,
> 
> ```
> RMMOD	snd_usb_audio
> ```
> 
> gets stuck in multiple tests. We need to root-cause this.

It looks like it gets stuck when we rmmod ANY module. I will look into it tomorrow.

**Comment by bardliao** [comment]
> > looks like we have a regression on USB audio,
> > ```
> > RMMOD	snd_usb_audio
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > gets stuck in multiple tests. We need to root-cause this.
> 
> It looks like it gets stuck when we rmmod ANY module. I will look into it tomorrow.

Sorry, not any module. Some modules can be removed successfully. The know modules that can not be removed are snd_usb_audio, snd_sof_pci_intel_lnl, and snd_soc_sof_sdw.

**Comment by bardliao** [comment]
Look like "ALSA: control: Take power_ref lock primarily" is the problematic commit. Revert it and retest.

**Comment by plbossart** [comment]
That would make sense, it's one of the recent commits on the 6.11 for-next branch from @tiwai. I tested the initial 6.11 and this didn't happen, so clearly coming from the recent sound tree.

**Comment by tiwai** [comment]
My bad, there was a leftover snd_power_unref() in the patch.
The fix patch is below: 
[0001-ALSA-control-Fix-leftover-snd_power_unref.patch.txt](https://github.com/user-attachments/files/16451317/0001-ALSA-control-Fix-leftover-snd_power_unref.patch.txt)

**Comment by plbossart** [comment]
@bardliao do you mind cancelling the tests and applying the fix from Takashi?

**Comment by bardliao** [comment]
> @bardliao do you mind cancelling the tests and applying the fix from Takashi?

Yes, pushed the fixed patch.

**Comment by plbossart** [comment]
LGTM @bardliao we have the known issue with the Xe driver but other than that no new issues reported. We should merge this before the week-end.

**Comment by bardliao** [comment]
Let's merge and check the daily test result.

**Comment by marc-hb** [comment]
> Let's merge and check the daily test result.

There was no need to wait for daily test results, the PR test results were already all broken:

- All LNL https://sof-ci.01.org/linuxpr/PR5127/build4254/devicetest/index.html
- All MTL https://sof-ci.01.org/linuxpr/PR5127/build4255/devicetest/index.html
- TGL fails in stable-v2.2 
https://sof-ci.01.org/linuxpr/PR5127/build4256/devicetest/index.html?model=TGLU_SKU0A32_SDCA-ipc3&testcase=verify-kernel-boot-log

```
[    5.365011] kernel: sysctl table check failed: dev/xe/(null) procname is null
[    5.365030] kernel: sysctl table check failed: dev/xe/(null) No proc_handler
```

**Comment by bardliao** [comment]
> > Let's merge and check the daily test result.
> 
> There was no need to wait for daily test results, the PR test results were already all broken:
> 
> * All LNL https://sof-ci.01.org/linuxpr/PR5127/build4254/devicetest/index.html
> * All MTL https://sof-ci.01.org/linuxpr/PR5127/build4255/devicetest/index.html
> * TGL fails in stable-v2.2
>   https://sof-ci.01.org/linuxpr/PR5127/build4256/devicetest/index.html?model=TGLU_SKU0A32_SDCA-ipc3&testcase=verify-kernel-boot-log
> 
> ```
> [    5.365011] kernel: sysctl table check failed: dev/xe/(null) procname is null
> [    5.365030] kernel: sysctl table check failed: dev/xe/(null) No proc_handler
> ```

I believe that is a xe driver issue and not relate to audio.

**Comment by marc-hb** [comment]
> I believe that is a xe driver issue and not relate to audio.

Enabling `xe` is one of our current objectives: for audio.

Even if it were unrelated to audio, it's generally better to ignore the error first because now every PR is red.

**Comment by kv2019i** [comment]
@bardliao @marc-hb xe issues tracked at https://gitlab.freedesktop.org/drm/xe/kernel/-/issues/2419

**Comment by msatwood** [comment]
from the dmesg of tgl, i915 is doing the guc/huc load so xe isnt even loaded. Did some paths in the SOF driver hardcode xe dependencies?

**Comment by marc-hb** [comment]
> from the dmesg of tgl, i915 is doing the guc/huc load so xe isnt even loaded.

`xe` may not run and not print anything (not a big surprise on TGL and MTL) but it's definitely loaded! I don't think it used to?

```
root@jf-mtlp-rvp-nocodec-3:~# journalctl -k -p 3
Aug 05 17:03:36 jf-mtlp-rvp-nocodec-3 kernel: i8042: Can't read CTR while initializing i8042
Aug 05 17:03:36 jf-mtlp-rvp-nocodec-3 kernel: i8042 i8042: probe with driver i8042 failed with error -5
Aug 05 17:03:37 jf-mtlp-rvp-nocodec-3 kernel: sysctl table check failed: dev/xe/(null) procname is null
Aug 05 17:03:37 jf-mtlp-rvp-nocodec-3 kernel: sysctl table check failed: dev/xe/(null) No proc_handler

root@jf-mtlp-rvp-nocodec-3:~# lsmod | grep xe
xe                   2940928  0
drm_ttm_helper         16384  1 xe
gpu_sched              65536  1 xe
drm_suballoc_helper    12288  1 xe
drm_gpuvm              45056  1 xe
drm_exec               12288  2 drm_gpuvm,xe
i2c_algo_bit           12288  2 xe,i915
drm_buddy              20480  2 xe,i915
ttm                   102400  3 drm_ttm_helper,xe,i915
drm_display_helper    204800  2 xe,i915
drm_kms_helper        241664  4 drm_display_helper,drm_ttm_helper,xe,i915
video                  73728  2 xe,i915
drm                   741376  15 gpu_sched,drm_kms_helper,drm_exec,drm_gpuvm,drm_suballoc_helper,drm_display_helper,drm_buddy,drm_ttm_helper,xe,i915,ttm
```

**Comment by marc-hb** [comment]
Fix submitted: https://patchwork.freedesktop.org/series/136874/

```
drm/xe/observation: Drop empty sysctl table entry

An empty sysctl table entry was inadvertently left behind for observation
sysctl. The breaks on 6.11 with the following errors:

```

```diff
--- a/drivers/gpu/drm/xe/xe_observation.c
+++ b/drivers/gpu/drm/xe/xe_observation.c
@@ -66,7 +66,6 @@  static struct ctl_table observation_ctl_table[] = {
 	 .extra1 = SYSCTL_ZERO,
 	 .extra2 = SYSCTL_ONE,
 	 },
-	{}
 };
 
 /**
```

**Comment by marc-hb** [comment]
Fix successfully tested in cherry-pick https://github.com/thesofproject/linux/pull/5133

**Pull request merged**
