### PR TITLE
ASoC:SOF: Add `src_hash` to `sof_ipc_fw_version` structure

### PR DESCRIPTION
**Pull request by ktrzcinx**
This field will be used to compare ldc file with loaded fw version,
to assert validity of trace logs. Value used in sof-logger.

Signed-off-by: Karol Trzcinski <karolx.trzcinski@linux.intel.com>

Related with https://github.com/thesofproject/sof/pull/3195

### CODE REVIEW

**Comment by plbossart** [comment]
@ktrzcinx when you say 'value is used by sof-logger', did you mean that the value would be exposed in a debugfs value read by sof-logger?

**Comment by ktrzcinx** [comment]
@plbossart `sof_ipc_fw_version` is part of `fw_ready` message, already saved in debugfs and already used by sof-logger for compatibility check

**Comment by ktrzcinx** [comment]
FW part has been merged already, so this PR also should keep going.

**Comment by ktrzcinx** [comment]
SOFCI TEST

**Review by lyakh — APPROVED** [review]

**Comment by ktrzcinx** [comment]
ping @kv2019i @ranj063 @plbossart

**Comment by plbossart** [comment]
@ktrzcinx I need more coffee but do we actually need this from the firmware, can't we get it from the extended manifest?

**Comment by ktrzcinx** [comment]
@plbossart actually not, because only fw_ready message is accessible from sof-logger point of view. Logger is default reader of this information, here it's only added to keep data structures aligned.

**Comment by plbossart** [comment]
> @plbossart actually not, because only fw_ready message is accessible from sof-logger point of view. Logger is default reader of this information, here it's only added to keep data structures aligned.

ok, thanks for the clarification

**Comment by plbossart** [comment]
@kv2019i can you take a look (ABI, etc)? Thanks!

**Comment by kv2019i** [comment]
@plbossart Ack, I'm having some doubts on this -- kernel doesn't use this field, so why add it to the header. But given we don't annotate the changes to FW headers (I have an AR to fix that), keeping them in sync in other ways is problematic as well. Oh well, let's put this in.

**Pull request merged**
