### PR TITLE
Fix/button mappings

### PR DESCRIPTION
**Pull request by plbossart**
random check performed while reviewing upstream patch shows the mappings are incorrect, fix.

### CODE REVIEW

**Comment by bardliao** [comment]
@plbossart I wonder how do you get the correct button mapping. Is there any document somewhere?

**Comment by plbossart** [comment]
> @plbossart I wonder how do you get the correct button mapping. Is there any document somewhere?

There's an Android/USB spec, see 
39f2d114a1c7d73d601f19cbea0a955ade2784c3

**Comment by RanderWang** [comment]
> @plbossart I wonder how do you get the correct button mapping. Is there any document somewhere?

I also found another patch for this case: https://lore.kernel.org/alsa-devel/20200414113527.13532-1-akshu.agrawal@amd.com/

**Comment by plbossart** [comment]
> @plbossart Patch looks ok. Are there any considerations for user-space compatibility? It seems the old definitions were simply wrong and not matching with how codec drivers define the buttons, so seems good, but a bit unfamiliar area until now for me.

it's rather "user compatibility", this only changes what the user needs to press. I think this change is harmless since for CHT there are very few users of the platform and sdw_ drivers don't work with the mainline

**Pull request merged**
