### PR TITLE
Merge/upstream merge 20190812

### PR DESCRIPTION
**Pull request by plbossart**
This is a good week, we only have 4 patches that are not upstream yet, and that's mainly because they were merged an hour ago.

This PR requires the HDaudio platforms to have all topology files in /lib/firmware/intel/sof-tplg

This PR includes a number of cleanups done by Takashi for HDaudio so a specific attention needs to be given to HDaudio support.

### CODE REVIEW

**Comment by ranj063** [comment]
@plbossart looks like Takashi's changes have affected the nocodec compilation. there are quite a few build errors.

**Comment by plbossart** [comment]
> @plbossart looks like Takashi's changes have affected the nocodec compilation. there are quite a few build errors.

yes, a case of Takashi working on an older branch, doing some changes and git merge overrides all corrections done in between.

Pushed a fix, let's see how this work.

**Comment by plbossart** [comment]
This PR is gating some of my other work, so I will take a calculated risk to go ahead and merge.
The HDaudio issues are all related to topology install issues and not something I can fix myself.

**Comment by kv2019i** [comment]
Seems good based on quick testing on multiple HDA machines. And yeah, anyway merged, but just FYI that testing was ongoing ;)

**Pull request merged**
