### PR TITLE
ASoC: SOF: ipc: Use msg->reply_data directly in snd_sof_ipc_get_reply()

### PR DESCRIPTION
**Pull request by ujfalusi**
Instead of using a local reply to first read out the header from the
mailbox then memcpy it or read it again to msg->reply_data, read it
directly to it's final place from the start.

If we received an error we do not need to do a memcpy anymore.
If the reply is reporting a success then we don not need to read the reply
again from the mailbox if the reply_size equals to the already read header
size.

Signed-off-by: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>

### CODE REVIEW

**Review by dbaluta — APPROVED** [review]

**Comment by dbaluta** [comment]
LGTM thanks Peter!

**Review by ranj063 — COMMENTED** [review]
@ujfalusi  can you please make sure that control setup will still work after an IPC error with control put?

**Comment by ujfalusi** [comment]
> @ujfalusi can you please make sure that control setup will still work after an IPC error with control put?

@ranj063, why would it not work? This is not changing anything regarding to that. The reply from the caller is updated in the `tx_wait_done()` only and it is done only if we do not have error in the reply reception.
This patch just removes some of the double memcpy/fetches to the temporary reply_data buffer.

**Comment by ranj063** [comment]
> > @ujfalusi can you please make sure that control setup will still work after an IPC error with control put?
> 
> @ranj063, why would it not work? This is not changing anything regarding to that. The reply from the caller is updated in the `tx_wait_done()` only and it is done only if we do not have error in the reply reception. This patch just removes some of the double memcpy/fetches to the temporary reply_data buffer.

@ujfalusi I'm thinking of this scenario. Let's says you send an IPC to update the kcontrol volume setting. You cache the value to be sent in scontrol->data and the reply points to the same data structure. If the IPC errors out, it will be copied into the scontrol data and we lost the cached value and there's no possibility to recover it with a D3

**Comment by ujfalusi** [comment]
> > > @ujfalusi can you please make sure that control setup will still work after an IPC error with control put?
> > 
> > 
> > @ranj063, why would it not work? This is not changing anything regarding to that. The reply from the caller is updated in the `tx_wait_done()` only and it is done only if we do not have error in the reply reception. This patch just removes some of the double memcpy/fetches to the temporary reply_data buffer.
> 
> @ujfalusi I'm thinking of this scenario. Let's says you send an IPC to update the kcontrol volume setting. You cache the value to be sent in scontrol->data and the reply points to the same data structure. If the IPC errors out, it will be copied into the scontrol data and we lost the cached value and there's no possibility to recover it with a D3

@ranj063, if the reply errors out then we will not copy the received reply data from `sdev->ipc->msg.reply_data` to the reply buffer the caller given.
The `msg.reply_data` is a persistent temporary buffer where we read out the reply from the mailbox. Then the wait function will copy it to the caller's buffer if it is provided.
The reply handling works (or supposed to be working) even if the caller gives NULL as reply_data (no interest on the reply itself).

If the case you are describing is valid than it is valid without this patch as well.

**Review by bardliao — APPROVED** [review]

**Comment by ranj063** [comment]
> If the case you are describing is valid than it is valid without this patch as well.

Ahh you're right. I missed the memcpy we have in case of error.

**Review by ranj063 — APPROVED** [review]

**Pull request merged**
