### PR TITLE
ASoC: SOF: ipc4-topology: Add support for NHLT with 16-bit only DMIC …

### PR DESCRIPTION
**Pull request by ujfalusi**
…blob

The ACPI NHLT table always had 32-bit DMIC blob even if 16-bit was also present and taken as a 'rule' which obviously got broken and there is at least one device on the market which ships with only 16-bit DMIC configuration blob.
This corner case has never been supported and it is going to need topology updates for DMIC copier to support multiple formats.

As for the kernel side: if the copier supports multiple formats and the preferred 32-bit DMIC blob is not found then we will try to get a 16-bit DMIC configuration and look for a 16-bit copier config.

Link: https://github.com/thesofproject/linux/issues/4973

### CODE REVIEW

**Comment by ujfalusi** [comment]
Changes since v1:
- Fixes tag added (well, it is not really fixing the commit, but builds on it to extend it for 16-bit blob only setups)
- @singalsu tested the patch with topology including multiple bit depth support for DMIC copier

**Review by singalsu — APPROVED** [review]
Works correctly and fixed (with tplg change) the reported issue that I was able to replicate with my test setup.

**Comment by plbossart** [comment]
@singalsu can you share the topology as well so that we review both at the same time?

**Comment by ujfalusi** [comment]
> @singalsu can you share the topology as well so that we review both at the same time?

The correspondig topology PR is https://github.com/thesofproject/sof/pull/9102/commits/4048bf8f1b4dcf69d2371ea38bf1f7b60cdcfc72

**Review by plbossart — APPROVED** [review]

**Comment by plbossart** [comment]
@ranj063 I guess you are a mandatory reviewer on this one...

**Review by ranj063 — APPROVED** [review]

**Pull request merged**
