### PR TITLE
Merge/sound upstream 20210105

### PR DESCRIPTION
**Pull request by bardliao**
Regular upstream merge. There are so mane commits in the merge. So we need to test it more.

### CODE REVIEW

**Comment by bardliao** [comment]
I tested on my CML sdw laptop and found no regression.

**Comment by bardliao** [comment]
Also tested on TGL sdw laptop and found no regression.

**Comment by keyonjie** [comment]
I don't see regression on TGL chromebook with this.

**Review by kv2019i — APPROVED** [review]
Did additional local tests on multiple machine (TGL, JSL) and no issues found.

**Comment by kv2019i** [comment]
@bardliao Do you have any open concerns with SDW open? In December there were some regressions you were hunting down and @plbossart did not want to move. But as upstream has moved ahead in anyways, unless the regression hunt is still ongoing, I think we should go ahead and merge this. Otherwise we risk missing regressions in upstream.

**Comment by bardliao** [comment]
> @bardliao Do you have any open concerns with SDW open? In December there were some regressions you were hunting down and @plbossart did not want to move. But as upstream has moved ahead in anyways, unless the regression hunt is still ongoing, I think we should go ahead and merge this. Otherwise we risk missing regressions in upstream.

@kv2019i I have no concern with SDW open. The hunting is done. We are good to merge this now.

**Comment by kv2019i** [comment]
Ack @bardliao . We are missing one more approval and we can then merge.

**Comment by bardliao** [comment]
@keyonjie Could you give this PR a formal approval if your test result is good?

**Review by keyonjie — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
