### PR TITLE
SoundWire/hybrid allocation take2

### PR DESCRIPTION
**Pull request by plbossart**
Address upstream feedback from @vinodkoul and add callbacks rather than make the core logic more complicated.

The code is indeed cleaner with fewer if/else cases, and does not keep stuff we no longer need.

Compile-tested only for now.

### CODE REVIEW

**Comment by plbossart** [comment]
Only failure is multiple_pause_resume, known firmware issue.

**Comment by plbossart** [comment]
moving back to draft, we have a race condition discussed in https://github.com/thesofproject/linux/issues/4426#issuecomment-1598302117 which needs to be handled first.

**Comment by plbossart** [comment]
@bardliao I added a tentative helper to change the device number on the fly. I tested it with debugfs

````
 echo 3 > /sys/kernel/debug/soundwire/master-2-2/sdw\:2\:025d\:1308\:00/device_number
````

this seems to work mostly but there ire issues with interrupts apparently. If you have time to test feedback is welcome. I am not sure how safe this is to change the device_number, if we can't make it work then we have an issue with the IDA stuff, it can be defeated by probe delays

````
[  126.971301] soundwire_cadence:cdns_update_slave_status_work: soundwire_intel soundwire_intel.link.2: Slave status change: 0x40
[  126.975485] soundwire_cadence:cdns_fill_msg_resp: soundwire_intel soundwire_intel.link.2: Msg ignored for Slave 1
[  126.975486] rt1308 sdw:2:025d:1308:00: SDW_SCP_INT1 read failed:-61
[  126.975524] rt1308 sdw:2:025d:1308:00: Slave 1 alert handling failed: -61
[  126.975588] soundwire_cadence:cdns_update_slave_status_work: soundwire_intel soundwire_intel.link.2: Slave status change: 0x4010
[  130.045932] soundwire_bus:sdw_bus_wait_for_clk_prep_deprep: soundwire sdw-master-2: clock stop prep/de-prep done slave:15
`````

**Comment by bardliao** [comment]
@plbossart I didn't meet the same issue as you. It works when the original dev_num is 6.
```
[  351.364253] soundwire sdw-master-0: clock stop prep/de-prep done slave:15
[  351.365995] cdns_update_slave_status_work: 4 callbacks suppressed
[  351.366000] soundwire_intel soundwire_intel.link.0: Slave status change: 0x21000000
```
I verified playback worked after device number changed.
However, `ida_free(&intel_peripheral_ida, slave->dev_num)` will cause problem if the original dev_num is not 6. I think it is because the dev_num is not allocated by ida_alloc.
BTW, the original dev_num is 1 occasionally on my side.

**Pull request closed without merging**
