### PR TITLE
rt700/rt711/rt1308/rt715 patches update

### PR DESCRIPTION
**Pull request by shumingfan**
rt700/rt711/rt1308/rt715 patches update

### CODE REVIEW

**Comment by shumingfan** [comment]
Hi all,
Due to slave property gets from BIOS, we need to update BIOS settings.
Please check the attached. I just capture the part of RT700/711/1308.
[dsdt_700_711_1308.txt](https://github.com/thesofproject/linux/files/3524040/dsdt_700_711_1308.txt)

**Comment by jack-cy-yu** [comment]
ALC715 soundwire codec driver has been added.

**Comment by plbossart** [comment]
> Hi all,
> Due to slave property gets from BIOS, we need to update BIOS settings.
> Please check the attached. I just capture the part of RT700/711/1308.
> [dsdt_700_711_1308.txt](https://github.com/thesofproject/linux/files/3524040/dsdt_700_711_1308.txt)

sorry, what do you mean here and for which platform is this needed? We have existing RVPs where we can't change the RT700 settings.

**Comment by shumingfan** [comment]
> sorry, what do you mean here and for which platform is this needed? We have existing RVPs where we can't change the RT700 settings.

Sorry, I didn't explain clearly.
The patch will modify the .read_prop callback function that uses sdw_slave_read_prop instead.
Check below.
https://github.com/thesofproject/linux/blob/087c5aca8a0f74d47777f61eb936b2e572cb8b9d/sound/soc/codecs/rt700-sdw.c#L199-L203

Therefore, sdw_slave_read_prop function will read from BIOS settings (MIPI disco table as I attached).
These MIPI disco tables are just for rt700/711/1308 codec, not specify which intel platform.

**Comment by plbossart** [comment]
> > sorry, what do you mean here and for which platform is this needed? We have existing RVPs where we can't change the RT700 settings.
> 
> Sorry, I didn't explain clearly.
> The patch will modify the .read_prop callback function that uses sdw_slave_read_prop instead.
> Check below.
> https://github.com/thesofproject/linux/blob/087c5aca8a0f74d47777f61eb936b2e572cb8b9d/sound/soc/codecs/rt700-sdw.c#L199-L203
> 
> Therefore, sdw_slave_read_prop function will read from BIOS settings (MIPI disco table as I attached).
> These MIPI disco tables are just for rt700/711/1308 codec, not specify which intel platform.

Right, but for existing ICL RVP we can't change any properties for ALC700. The BIOS is provided by Intel and it is what it is. 
For the 3-in-1 tests, we can modify DSDT, but we'd need to check that for RT1308/711/715 the values match what BIOS vendors included for commercial platforms. If the values are incorrect or missing, we will have to fix the properties at the kernel level.


Fo

**Pull request closed without merging**
