### PR TITLE
Merge/sound upstream 20210712

### PR DESCRIPTION
**Pull request by plbossart**
First merge based on v5.14-rc1, so validation required.

@bardliao @ujfalusi @ranj063 can you test on your devices?

### CODE REVIEW

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by bardliao** [comment]
I am running test on TGL SDW platform SKU:0A3E.

**Comment by bardliao** [comment]
> I am running test on TGL SDW platform SKU:0A3E.

No regression found.

**Comment by ujfalusi** [comment]
As far as I can tell it works fine on tgl-h (sof-hda-generic.tplg).

**Comment by plbossart** [comment]
SOFCI TEST

**Pull request merged**
