### PR TITLE
Merge/sound upstream 20211004

### PR DESCRIPTION
**Pull request by plbossart**
weekly upstream merge - now that dynamic pipelines is in Mark's tree.

Matching rebased branch topic/sof-dev-rebase (tag sof-dev-rebase-20211004)

### CODE REVIEW

**Comment by kv2019i** [comment]
We have a failure on one CML device:
https://sof-ci.01.org/linuxpr/PR3192/build6477/devicetest/?model=CML_HEL_RT5682&testcase=verify-kernel-boot-log

```
[    2.725780] kernel: rt5682 i2c-10EC5682:00: sysclk/dai not set correctly
[    2.725854] kernel: general protection fault, probably for non-canonical address 0x2bd63a3afec92100: 0000 [#1] SMP NOPTI
[    2.725864] kernel: CPU: 2 PID: 80 Comm: kworker/u8:2 Not tainted 5.15.0-rc4-pr3192-6477-default #7c8961c8
[    2.725870] kernel: Hardware name: Google Helios/Helios, BIOS  01/21/2020
[    2.725874] kernel: Workqueue: events_unbound async_run_entry_fn
[    2.725882] kernel: RIP: 0010:clk_core_get_parent_by_index+0x4a/0x90
[    2.725889] kernel: Code: 8d 2c 92 48 c1 e5 03 4c 8d 24 28 49 8b 44 24 08 48 85 c0 74 0c 5b 5d 41 5c c3 5b 31 c0 5d 41 5c c3 49 8b 04 24 48 85 c0 74 26 <48> 8b 00 48 85 c0 74 e3 48 3d 00 f0 ff ff 77 05 49 89 44 24 08 48
[    2.725899] kernel: RSP: 0018:ffff9cf2c07c7c00 EFLAGS: 00010206
[    2.725903] kernel: RAX: 2bd63a3afec92100 RBX: ffff92ca837cbb00 RCX: 00000000f3c74d52
[    2.725908] kernel: RDX: 0000000000000000 RSI: 0000000000000000 RDI: ffff92ca837cbb00
[    2.725913] kernel: RBP: 0000000000000000 R08: 00000000ffffffff R09: 0000000000000000
[    2.725918] kernel: R10: 0000000000000000 R11: 0000000000000000 R12: ffff92ca861aeec0
[    2.725922] kernel: R13: ffff92ca8cf84420 R14: ffff92ca861aeee8 R15: ffff92ca837cbb00
[    2.725927] kernel: FS:  0000000000000000(0000) GS:ffff92cbd6200000(0000) knlGS:0000000000000000
[    2.725933] kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[    2.725937] kernel: CR2: 00007eff771a8400 CR3: 0000000194a24006 CR4: 00000000003706e0
[    2.725942] kernel: Call Trace:
[    2.725947] kernel:  __clk_register+0x465/0x7e0
[    2.725952] kernel:  ? clk_hw_unregister+0x10/0x10
[    2.725958] kernel:  clk_hw_register+0x19/0x40
[    2.725963] kernel:  devm_clk_hw_register+0x41/0x80
[    2.725969] kernel:  rt5682_register_dai_clks+0x8e/0x130 [snd_soc_rt5682]
[    2.725979] kernel:  rt5682_i2c_probe+0x484/0x600 [snd_soc_rt5682_i2c]

```

This is not happening at least in this run from yesterday:
https://sof-ci.01.org/linuxpr/PR3190/build6476/devicetest/

**Review by kv2019i — CHANGES_REQUESTED** [review]
Local test on JSL passed fine.

But CI caught regression on CML/Helios. Could be caused by "ASoC: rt5682: move clk related code to rt5682_i2c_probe" Test PR with the patch reverted running at https://github.com/thesofproject/linux/pull/3193

**Comment by kv2019i** [comment]
Yup, with "Revert "ASoC: rt5682: move clk related code to rt5682_i2c_probe"", tests pass on CML Helios.

**Comment by plbossart** [comment]
@bardliao and @shumingfan can you work to root-cause the failure with RT5682 in I2C mode? thanks!
In the mean time we're going to proceed with the local revert on topic/sof-dev.

**Comment by jack-cy-yu** [comment]
@kv2019i Could you try #3130 patch? The upstream patch ("ASoC: rt5682: move clk related code to rt5682_i2c_probe") is almost the same as #3130, the only difference is that there is a barrier() in line 2825 in rt5682.c, which could fix this issue.

**Review by kv2019i — APPROVED** [review]

**Comment by kv2019i** [comment]
@jack-cy-yu I think there is something more complex happening here. If you look at all the test runs for #3130 , 3/4 have failed to same error I observed today with asoc upstream:
https://sof-ci.01.org/linuxpr/PR3130/

I think the barrier() is just changing the timing a bit, but the actual rootcause is elsewhere.

**Comment by jack-cy-yu** [comment]
@kv2019i  As per log from #3130 , the barrier() is added after build6398/ (https://sof-ci.01.org/linuxpr/PR3130/), and the test result looks fine. Please try it again. Thanks.

**Comment by kv2019i** [comment]
@jack-cy-yu I understand the barrier() makes the test pass, but this is not a fix that can be accepted usptream unless there are very convincing arguments why. If you search for "barrier()" in asoc drivers, there are no uses of this. Uses of "barrier()" are very speicfic and if you do a search in rest of kernel sources, there's almost always a lengthy comment that explains why this is needed. At a minimum, we'd need to understand if the fail is cause by timing (if yes, adding a delay or printk could make the test pass as well), or if there a genuine problem of memory ordering. If it's the latter, simpler solution like addition of locks should be considered.

**Pull request merged**
