### PR TITLE
[DNM][TEST] Merge/v6.4 rc1

### PR DESCRIPTION
**Pull request by plbossart**
first smoke test to see if v6.4-rc1 works at all.

@ujfalusi the builddep change needs to be reverted first. see "Revert "Revert "kbuild: deb-pkg: use dh_listpackages to know enabled packages""

No issues with local tests on SoundWire device. let's see what happens with CI tests.

### CODE REVIEW

**Comment by plbossart** [comment]
Debian generation fails - again - https://github.com/thesofproject/linux/actions/runs/4919204219/jobs/8786531317?pr=4342

**Comment by ujfalusi** [comment]
SOFCI TEST

**Comment by ujfalusi** [comment]
the debhelper should be now on the build machines.

**Comment by plbossart** [comment]
obviously there's a problem with the build servers. @greg-intel @fredoh9 @keqiaozhang can you please look into this?

**Pull request closed without merging**
