### PR TITLE
Add machine driver for rpl max98373 nau8825

### PR DESCRIPTION
**Pull request by terry182**
Add support for zydron.

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

**Review by plbossart — APPROVED** [review]

**Comment by plbossart** [comment]
test this please

**Review by bardliao — APPROVED** [review]

**Comment by plbossart** [comment]
@terry182 @cujomalainey I overlooked this checkpatch error, which email should be used for this patch:

````
WARNING: From:/Signed-off-by: email address mismatch: 'From: Terry Cheong <terry160434@gmail.com>' != 'Signed-off-by: Terry Cheong <htcheong@chromium.org>'
````

**Comment by cujomalainey** [comment]
@plbossart should be chromium. Thanks!

**Comment by plbossart** [comment]
> @plbossart should be chromium. Thanks!

I will change the author with the chromium address and send upstream when I find a moment.

**Pull request merged**
