### PR TITLE
Merge/sound upstream 20240612

### PR DESCRIPTION
**Pull request by plbossart**
Mid-cycle merge, about 4-5 weeks to go, time to check if anything interferes with SOF,

### CODE REVIEW

**Comment by plbossart** [comment]
Wow, massive failure across the board with errors such as 

````
Jun 12 07:32:56 ba-mtlp-rvp-hda-03 kernel: snd_soc_skl_hda_dsp:skl_hda_add_dai_link: skl_hda_dsp_generic skl_hda_dsp_generic: dai link name - DMIC Raw
Jun 12 07:32:56 ba-mtlp-rvp-hda-03 kernel: snd_sof:sof_route_load: sof-audio-pci-intel-mtl 0000:00:1f.3: sink dai-copier.HDA.iDisp1.playback control none source host-copier.3.playback
Jun 12 07:32:56 ba-mtlp-rvp-hda-03 kernel: snd_sof:sof_route_load: sof-audio-pci-intel-mtl 0000:00:1f.3: sink dai-copier.HDA.iDisp2.playback control none source host-copier.4.playback
Jun 12 07:32:56 ba-mtlp-rvp-hda-03 kernel: snd_sof:sof_route_load: sof-audio-pci-intel-mtl 0000:00:1f.3: sink dai-copier.HDA.iDisp3.playback control none source host-copier.5.playbackpid.socket
Jun 12 07:32:56 ba-mtlp-rvp-hda-03 kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: error: source host-copier.5.playbackpid.socket not found
````


````
Jun 12 07:28:32 jf-mtlp-rvp-nocodec-8 kernel: snd_sof:sof_dai_load: sof-audio-pci-intel-mtl 0000:00:1f.3: tplg: load pcm Port2
Jun 12 07:28:32 jf-mtlp-rvp-nocodec-8 kernel: snd_sof:sof_dai_load: sof-audio-pci-intel-mtl 0000:00:1f.3: tplg: load pcm Deepbuffer Port0
Jun 12 07:28:32 jf-mtlp-rvp-nocodec-8 kernel: snd_sof:sof_dai_load: sof-audio-pci-intel-mtl 0000:00:1f.3: tplg: load pcm Port1
Jun 12 07:28:32 jf-mtlp-rvp-nocodec-8 kernel: [136B blob data]
Jun 12 07:28:32 jf-mtlp-rvp-nocodec-8 kernel: [100B blob data]
Jun 12 07:28:32 jf-mtlp-rvp-nocodec-8 kernel: sof-nocodec sof-nocodec: ASoC: topology: add_route failed: -22
Jun 12 07:28:32 jf-mtlp-rvp-nocodec-8 kernel: sof-nocodec sof-nocodec: ASoC: topology: could not load header: -22
Jun 12 07:28:32 jf-mtlp-rvp-nocodec-8 kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: error: tplg component load failed -22
Jun 12 07:28:32 jf-mtlp-rvp-nocodec-8 kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: error: failed to load DSP topology -22
Jun 12 07:28:32 jf-mtlp-rvp-nocodec-8 kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at snd_soc_component_probe on 0000:00:1f.3: -22
Jun 12 07:28:32 jf-mtlp-rvp-nocodec-8 kernel: sof-nocodec sof-nocodec: ASoC: failed to instantiate card -22
Jun 12 07:28:32 jf-mtlp-rvp-nocodec-8 kernel: sof-nocodec sof-nocodec: probe with driver sof-nocodec failed with error -22
Jun 12 07:28:32 jf-mtlp-rvp-nocodec-8 kernel: i915 0000:00:02.0: [drm] [ENCODER:240:DDI A/PHY A] failed to retrieve link info, disabling eDP
````

````
Jun 12 07:33:10 ba-mtlp-sdw-aioc-03 kernel: snd_sof:sof_dai_load: sof-audio-pci-intel-mtl 0000:00:1f.3: tplg: load pcm Jack In
Jun 12 07:33:10 ba-mtlp-sdw-aioc-03 kernel: snd_sof:sof_dai_load: sof-audio-pci-intel-mtl 0000:00:1f.3: tplg: load pcm Deepbuffer Jack Out
Jun 12 07:33:10 ba-mtlp-sdw-aioc-03 kernel: snd_sof:sof_route_load: sof-audio-pci-intel-mtl 0000:00:1f.3: sink dai-copier.HDA.iDisp1.playback control none source host-copier.5.playbackrt@linux.intel.com>
Jun 12 07:33:10 ba-mtlp-sdw-aioc-03 kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: error: source host-copier.5.playbackrt@linux.intel.com> not found
Jun 12 07:33:10 ba-mtlp-sdw-aioc-03 kernel: sof_sdw sof_sdw: ASoC: topology: add_route failed: -22
Jun 12 07:33:10 ba-mtlp-sdw-aioc-03 kernel: sof_sdw sof_sdw: ASoC: topology: could not load header: -22
Jun 12 07:33:10 ba-mtlp-sdw-aioc-03 kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: error: tplg component load failed -22
Jun 12 07:33:10 ba-mtlp-sdw-aioc-03 kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: error: failed to load DSP topology -22
Jun 12 07:33:10 ba-mtlp-sdw-aioc-03 kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at snd_soc_component_probe on 0000:00:1f.3: -22
Jun 12 07:33:10 ba-mtlp-sdw-aioc-03 kernel: sof_sdw sof_sdw: ASoC: failed to instantiate card -22
Jun 12 07:33:10 ba-mtlp-sdw-aioc-03 kernel: sof_sdw sof_sdw: error -EINVAL: snd_soc_register_card failed -22
Jun 12 07:33:10 ba-mtlp-sdw-aioc-03 kernel: sof_sdw sof_sdw: probe with driver sof_sdw failed with error -22
````

It's 7am and already one disaster @ujfalusi @kv2019i @bardliao @ranj063  :-)

**Comment by plbossart** [comment]
problems confirmed on local tests

````
[   34.801075] snd_sof:sof_route_load: sof-audio-pci-intel-mtl 0000:00:1f.3: sink dai-copier.HDA.iDisp2.playback control none source host-copier.6.playback
[   34.801081] snd_sof:sof_route_load: sof-audio-pci-intel-mtl 0000:00:1f.3: sink dai-copier.HDA.iDisp3.playbackrun_t:s0 control none source host-copier.7.playback
[   34.801084] sof-audio-pci-intel-mtl 0000:00:1f.3: error: sink dai-copier.HDA.iDisp3.playbackrun_t:s0 not found
[   34.801087] sof_sdw sof_sdw: ASoC: topology: add_route failed: -22
````

Some sort of memory leak or bad string copy...

Bisecting.

**Comment by plbossart** [comment]
another nice one

````
[   16.984458] snd_sof:sof_route_load: sof-audio-pci-intel-mtl 0000:00:1f.3: sink gain.15.1\x01 control none source host-copier.31.playback\xff`\x86\xba\x034\x89\xff\xff@N\x83\xb83\x89\xff\xff\x10\x84\xe9\x8b\xff\xff\xff\xffS\x81ی\xff\xff\xff\xff\x0f
[   16.984461] sof-audio-pci-intel-mtl 0000:00:1f.3: error: source host-copier.31.playback\xff`\x86\xba\x034\x89\xff\xff@N\x83\xb83\x89\xff\xff\x10\x84\xe9\x8b\xff\xff\xff\xffS\x81ی\xff\xff\xff\xff\x0f not found

````

**Comment by ujfalusi** [comment]
@plbossart  plain upstream also broken?

**Comment by ujfalusi** [comment]
@plbossart, looks better now with the fix!

**Comment by plbossart** [comment]
Yay, results look good, merging to get daily tests before the week-end.

**Pull request merged**
