### PR TITLE
Merge/sound upstream 20230125

### PR DESCRIPTION
**Pull request by ujfalusi**
Let's clear the fog to see what we have pending for upstream.

### CODE REVIEW

**Comment by ujfalusi** [comment]
one known fail https://github.com/thesofproject/sof/issues/6864 and the usual suspend-resume on CML_RVP_SDW and APL_UP2_NOCODEC, not worst, not better.

**Comment by plbossart** [comment]
@ujfalusi the sparse warnings seem to be a mistake in the AMD code, sent an email to alsa-devel on this.

**Comment by plbossart** [comment]
Sparse warnings go away with this patch 
[0001-ASoC-amd-acp-common-fix-format-handling.txt](https://github.com/thesofproject/linux/files/10502115/0001-ASoC-amd-acp-common-fix-format-handling.txt)


````diff
diff --git a/sound/soc/amd/acp/acp-mach-common.c b/sound/soc/amd/acp/acp-mach-common.c
index b83ae946b3e47..b4dcce4fbae92 100644
--- a/sound/soc/amd/acp/acp-mach-common.c
+++ b/sound/soc/amd/acp/acp-mach-common.c
@@ -186,7 +186,7 @@ static int acp_card_rt5682_hw_params(struct snd_pcm_substream *substream,
 
        srate = params_rate(params);
        ch = params_channels(params);
-       format = 8 * params_format(params);
+       format = params_physical_width(params);
 
        if (drvdata->tdm_mode)
                fmt = SND_SOC_DAIFMT_DSP_A;
@@ -330,7 +330,7 @@ static int acp_card_rt5682s_hw_params(struct snd_pcm_substream *substream,
 
        srate = params_rate(params);
        ch = params_channels(params);
-       format = 8 * params_format(params);
+       format = params_physical_width(params);
 
        if (drvdata->tdm_mode)
                fmt = SND_SOC_DAIFMT_DSP_A;
@@ -475,7 +475,7 @@ static int acp_card_rt1019_hw_params(struct snd_pcm_substream *substream,
 
        srate = params_rate(params);
        ch = params_channels(params);
-       format = 8 * params_format(params);
+       format = params_physical_width(params);
 
        if (drvdata->amp_codec_id != RT1019)
                return -EINVAL;
@@ -616,7 +616,7 @@ static int acp_card_maxim_hw_params(struct snd_pcm_substream *substream,
 
        srate = params_rate(params);
        ch = params_channels(params);
-       format = 8 * params_format(params);
+       format = params_physical_width(params);
 
        if (drvdata->tdm_mode)
                fmt = SND_SOC_DAIFMT_DSP_A;
````

**Comment by plbossart** [comment]
no issues found in my local testing @ujfalusi. maybe wait until we see the AMD response to avoid adding sparse warnings to all other PRs, otherwise looks good to go.

**Comment by ujfalusi** [comment]
and it is introduced by (coming from upstream):
ca9d237994db ("ASoC: amd: acp: Refactor i2s clocks programming sequence")

**Comment by ujfalusi** [comment]
@plbossart, I'm tempted to close this merge PR and do a new one in couple of days so we can merge things (and get the AMD fix from upstream).

**Comment by ujfalusi** [comment]
Closing

**Pull request closed without merging**
