### PR TITLE
ALSA: HDA: Early Forbid of runtime PM

### PR DESCRIPTION
**Pull request by kv2019i**
For certain codecs (like Realtek), pm_runtime_forbid() is invoked
in the probe function after build_controls(). In a stress test,
its observed occasionally that runtime PM calls are invoked
before controls are built. This causes the codec to be
runtime suspended before probe completes. Because of this, not all
controls are enumerated correctly, and audio does not work until
system is rebooted.

This issue being common across all codecs, pm_runtime_forbid() is
called when the codec object is created to fix this issue.
A codec enables or disables runtime pm in its own probe function.

Multiple stress tests of 2000+ cycles has been done to test the fix.

Signed-off-by: Harsha Priya <harshapriya.n@intel.com>
Signed-off-by: Emmanuel Jillela <emmanuel.jillela@intel.com>
Reviewed-by: Kailang Yang <kailang@realtek.com>

### CODE REVIEW

**Comment by keyonjie** [comment]
@kv2019i then do we need to add the corresponding pm_runtime_allow() somewhere else also?

**Comment by kv2019i** [comment]
> 
> 
> @kv2019i then do we need to add the corresponding pm_runtime_allow() somewhere else also?

@keyonjie We do this in snd_hda_set_power_save(), but in now turns out it's not called in all machine drivers, and thus this patch triggers the problems. More details in:
https://mailman.alsa-project.org/pipermail/alsa-devel/2020-September/174358.html

**Comment by kv2019i** [comment]
Just putting a note that the latest approach, of modifying all machine drivers, now passes all tests in CI:
https://sof-ci.01.org/linuxpr/PR2403/build4598/devicetest

.. still not sure this is the way to go, but this seems at least works now on all systems, so I'll build on this.

**Comment by kv2019i** [comment]
Ok passing now. I'll send to upstream directly (as V1 already was) and this doesn't touch SOF directly.

**Comment by kv2019i** [comment]
Merged upstream, closing.

**Pull request closed without merging**
