### PR TITLE
ASoC: Intel: boards: add configuration for RTL5682+MX98390

### PR DESCRIPTION
**Pull request by kv2019i**
Signed-off-by: Kai Vehmanen <kai.vehmanen@linux.intel.com>

### CODE REVIEW

**Comment by kv2019i** [comment]
Experimental patch to address a potential gap between chromeos-5.10 tree and upstream. Not yet for merging.

**Comment by keqiaozhang** [comment]
I have tested this PR with 5.16 rc1 kernel on ADL Chrome device.  it works for codec config "RTL5682+MX98390".

**Comment by macchian** [comment]
Aren't we gonna use comp_ids to deal with variant ACPI ids? 
ASoC: Intel: sof_rt5682: use comp_ids to enumerate rt5682s
https://lore.kernel.org/all/20211029171409.611600-4-brent.lu@intel.com/

**Comment by keqiaozhang** [comment]
@kv2019i , Could you please follow up this PR, we need these Chrome devices to test the latest sof in CI.

**Comment by keqiaozhang** [comment]
@kv2019i , just realized that this configuration "RTL5682+MX98390" has been added to sof-dev.
https://github.com/thesofproject/linux/commit/f316c9d9ba8ea08d6994bc5ba8fa276eab186208

**Comment by kv2019i** [comment]
@keqiaozhang wrote:
> @kv2019i , just realized that this configuration "RTL5682+MX98390" has been added to sof-dev. [f316c9d](https://github.com/thesofproject/linux/commit/f316c9d9ba8ea08d6994bc5ba8fa276eab186208)

Checking this again, the f316c9d patch was already in the tree, so we might still need a versio nof this patch. I'll take a look at this.

@macchian No change to use of comp_ids. This patch was just a quick hack I did to unblock our validation, not ready for merging to upstream.

**Comment by plbossart** [comment]
@kv2019i do you still need this PR?

**Comment by kv2019i** [comment]
@plbossart I'll keep this open for a while. We have some discrepancy between upstream and chromeos-5.10 kernel that we need to figure out. I'll keep this PR open until that is clarified and close then.

**Comment by plbossart** [comment]
> @plbossart I'll keep this open for a while. We have some discrepancy between upstream and chromeos-5.10 kernel that we need to figure out. I'll keep this PR open until that is clarified and close then.

ok, sounds good @kv2019i

**Comment by plbossart** [comment]
closing since there's no activity.

**Pull request closed without merging**
