### PR TITLE
Update changes of snd_hdac_display_power() from upstream

### LINKED ISSUE #400: HDMI: rework the code to align with upstream fixes
Takashi just posted a set of patch on alsa-devel: ALSA: HD-audio display power fixes
We need to rework the code and make sure the i915 power management remains functional.
Yet another example of why we need to upstream faster.

Filing as a bug since it'll gate upstream merges.

### PR DESCRIPTION
**Pull request by bardliao**
This PR include Takashi's snd_hdac_display_power() related patches and the necessary changes on SOF side.

Fix #400

### CODE REVIEW

**Comment by ranj063** [comment]
@bardliao I presume u have tested this to confirm that suspend/resume works with HDMI playback on glk?

**Comment by bardliao** [comment]
@ranj063 I tested it on up2. HDMI playback works fine after suspend/resume. But we will see underrun and  ipc timed out after resume if we suspend during HDMI playback. **This issue also happens without the PR.**

**Comment by ranj063** [comment]
> @ranj063 I tested it on up2. HDMI playback works fine after suspend/resume. But we will see underrun and ipc timed out after resume if we suspend during HDMI playback. **This issue also happens without the PR.**

How about glk?

**Comment by bardliao** [comment]
@ranj063 I don't have glk at hand. I think we can test it once Chrome team decide to cherry-pick Takashi's patch to their code base.

**Comment by bardliao** [comment]
@plbossart Thanks. The comment is removed.

**Comment by plbossart** [comment]
> @plbossart Thanks. The comment is removed.

Ah sorry, I didn't mean to remove the comment only, but also add a display_power(false) as done by the skylake driver.

**Comment by bardliao** [comment]
@plbossart Sorry I misunderstood your comment. Probably it is not necessary to add a display_power(false) in ```hda_codec_i915_exit()``` since we call ```hda_codec_i915_put()``` after ```hda_codec_i915_init()``` in ```hda_init_caps()```. But it is harmless and looks better if we add it in _exit().
We use ```hda_codec_i915_get()``` in ```snd_hdac_i915_init()``` so, I added ```hda_codec_i915_put()``` in ```hda_codec_i915_exit()```.
BTW, I see display_power(false) in azx_free() (hda/hda_intel.c) but didn't see a similar function in skl_free() (skylake/skl.c). Am I missing something?

**Comment by plbossart** [comment]
@bardliao this routine wasn't part of the original skylake but maybe it's missing. Do you want to ask Takashi if this is intentional or a miss due to search/replace?

**Comment by bardliao** [comment]
@plbossart According to Takashi's reply, I think it is missed.

**Pull request merged**
