### PR TITLE
Revert "ASoC: SOF: Intel: hda-bus: Use PIO mode for Lunar Lake"

### PR DESCRIPTION
**Pull request by plbossart**
This reverts commit 9bb1cad55c2a5e0acad1528bd00953fcf61b138a.

Link: https://github.com/thesofproject/linux/issues/4889

### CODE REVIEW

**Review by marc-hb — APPROVED** [review]
Clean revert of the small and last commit in #4844. If removing these 3 lines is all it takes to get some LNL test coverage again then great.

Can you confirm there was no attempt yet to upstream the other 4 commits?

**Comment by marc-hb** [comment]
PR test results look mostly OK - and irrelevant as LNL is not tested in PR yet
https://sof-ci.01.org/linuxpr/PR4892/build1985/devicetest/index.html
https://sof-ci.01.org/linuxpr/PR4892/build1986/devicetest/index.html
https://sof-ci.01.org/linuxpr/PR4892/build1987/devicetest/index.html

**Comment by plbossart** [comment]
I am not sure if we want to apply this revert, because we would fail HDaudio stress tests. I just provided this PR to make sure others could reproduce my painful bisect work.

We first need to root-cause why this PIO mode interferes with SoundWire-based interfaces.

**Comment by plbossart** [comment]
FWIW the 3rd commit partially reverts  6ec3295826d8c11141c970cf3fd68d77d3452adb ("ASoC: SOF: Intel: hda: remove duplicated clear WAKESTS")

I have no idea why this was removed.

It could also be that there's an interference from ae5ff22a884d2aac0908cfd0113d3db633d79ae6 ("ASoC: SOF: Intel: hda-ctrl: only clear WAKESTS for HDaudio codecs"), where in the end we didn't clear all the WAKE_STS fields.

Wow, my brain is officially fried haha.

**Comment by plbossart** [comment]
false positive, the problem is the WAKE_STS clear missing, see
- #4896

**Pull request closed without merging**
