### PR TITLE
[TEST][DNM] soundwire: intel_ace2.x: revert DOAIS setting

### PR DESCRIPTION
**Pull request by plbossart**
go back to the hard-coded 0x1 which was changed in "soundwire: intel_ace2x: cleanup DOAIS/DODS settings"

Link: https://github.com/thesofproject/linux/issues/4943

### CODE REVIEW

**Comment by plbossart** [comment]
@marc-hb @fredoh9 how do I trigger a test of this PR on LNL devices?

**Comment by marc-hb** [comment]
You wait for 1-2 days while @fredoh9 is putting the final touches and then you use the magic words "SOFCI TEST"; alone in a comment.

It's already possible now using our internal interface if you're in a rush. I will share with you the link to our internal doc.

**Comment by fredoh9** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
Done, LNL results: https://sof-ci.01.org/linuxpr/PR4951/build2470/devicetest/index.html

**Comment by plbossart** [comment]
no issues in https://sof-ci.01.org/linuxpr/PR4951/build2470/devicetest/index.html

**Comment by plbossart** [comment]
no issues either with https://sof-ci.01.org/linuxpr/PR4951/build2499/devicetest/index.html, so I don't know how to progress on https://github.com/thesofproject/linux/issues/4943

Could it be that the issue is device-specific on jf-lnlm-rvp-sdw-1 @fredoh9 @marc-hb ?

**Comment by marc-hb** [comment]
#4943 has always been rare so I don't know what to say.

It was spotted on two different devices though.

**Pull request closed without merging**
