### PR TITLE
[TEST] ASoC Cpu/codec M/N dai update

### PR DESCRIPTION
**Pull request by plbossart**
upstream patches from @morimoto (https://lore.kernel.org/alsa-devel/87mswp1ytu.wl-kuninori.morimoto.gx@renesas.com/)

### CODE REVIEW

**Comment by plbossart** [comment]
of course this set of patches conflict with my own changes... Will fix tomorrow.

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
Man, all platforms failed with this PR. That's quite a record.

https://sof-ci.01.org/linuxpr/PR4632/build7049/devicetest/index.html
https://sof-ci.01.org/linuxpr/PR4632/build7050/devicetest/index.html
https://sof-ci.01.org/linuxpr/PR4632/build7051/devicetest/index.html

Let's re-run to see what happened.

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
Results are reproducible and really bad. @bardliao any idea what could cause this?

**Comment by bardliao** [comment]
@plbossart The issue is that `__soc_pcm_hw_params` is called by both FE and BE dai links, and only BE dai links have `ch_mask`.
```
                if (rtd->dai_link->num_cpus >= rtd->dai_link->num_codecs) {
                        /* .ch_map is from CPU */
                        ch_mask = rtd->dai_link->ch_maps[i].ch_mask;
```
`kernel NULL pointer dereference` happens at that point.

[dmesg.txt](https://github.com/thesofproject/linux/files/12923447/dmesg.txt)

Can you try below change?
```patch
diff --git a/sound/soc/soc-pcm.c b/sound/soc/soc-pcm.c
index 0bfff2ea111d..ce84d9c1d8be 100644
--- a/sound/soc/soc-pcm.c
+++ b/sound/soc/soc-pcm.c
@@ -1054,6 +1054,9 @@ static int __soc_pcm_hw_params(struct snd_soc_pcm_runtime *rtd,
                /* copy params for each cpu */
                tmp_params = *params;

+               /* ch_map is only set in BE dai link */
+               if (rtd->dai_link->dynamic)
+                       goto run;
                /*
                 * construct cpu channel mask by combining ch_mask of each
                 * codec which maps to the cpu.
@@ -1075,7 +1078,7 @@ static int __soc_pcm_hw_params(struct snd_soc_pcm_runtime *rtd,
                /* fixup cpu channel number */
                if (ch_mask)
                        soc_pcm_codec_params_fixup(&tmp_params, ch_mask);
-
+run:
                ret = snd_soc_dai_hw_params(cpu_dai, substream, &tmp_params);
                if (ret < 0)
                        goto out;

```

**Comment by plbossart** [comment]
still a really bad result for CML_SKU0955_HDA https://sof-ci.01.org/linuxpr/PR4632/build422/devicetest/index.html

whaaat?

**Comment by plbossart** [comment]
testing v5

**Pull request closed without merging**
