### PR TITLE
Issue552 fix1

### PR DESCRIPTION
**Pull request by lyakh**
These two patches fix at least a part of #552 . Since none of them is SOF related, I'll push them to respective mailing lists too.

### CODE REVIEW

**Comment by lyakh** [comment]
Do I understand correctly, that the reason this PR "failed" checkpatch is the lines, ending in "("? If yes - what is the preferred way to fix that? Without adding major code refactoring the only other options are:
- go beyond 80 characters (my preference)
- break the line around pointer / array / dot separators, i.e. `ret = fn(x-> $$ member $$ [i]. $$ member,` where `$$` are some possible line-break locations, none of which seem prettier than breaking after `fn(`

**Comment by plbossart** [comment]
@lyakh checkpatch is a tool to get the developer attention on possible violation of coding rules.
It's accepted that 100% compliance is not possible, the only ask is that the developer makes a deliberate decision to deal with such issues.
Indeed in this case you have to make a choice between violating the 80-char rule or the parenthesis in the end.
I would use more than 80 chars.

**Comment by plbossart** [comment]
these patches are handled on mailing lists, no action here.
@lyakh I have one favor to ask: please submit one patch per codec if possible, this helps me pick only what is strictly necessary in the weekly backports. In some cases, patches won't apply during the cherry-pick operations because of other dependencies on a part of the tree I don't track and we don't compile. Thanks!

**Comment by lyakh** [comment]
@plbossart great to know, that you'd make the same choice of breaking the 80-character rule, but - for my future submissions, in which I'm sure I'll be often enough tempted to break one or another rule - what do we do with our "chauvinistic" CI tools, that mark even "note" level checkpatch "failures" with a red cross? Can they be ignored and patches accepted regardless? Wouldn't CI tools in such cases abort the testing early and skip some other potentially more revealing tests or do they run all tests even if some early ones fail?

**Comment by plbossart** [comment]
On 2/8/19 1:52 AM, Guennadi Liakhovetski wrote:
>
> @plbossart <https://github.com/plbossart> great to know, that you'd 
> make the same choice of breaking the 80-character rule, but - for my 
> future submissions, in which I'm sure I'll be often enough tempted to 
> break one or another rule - what do we do with our "chauvinistic" CI 
> tools, that mark even "note" level checkpatch "failures" with a red 
> cross? Can they be ignored and patches accepted regardless? Wouldn't 
> CI tools in such cases abort the testing early and skip some other 
> potentially more revealing tests or do they run all tests even if some 
> early ones fail?
>
When checkpatch fails I will look at the results and decide if that's 
acceptable. Think of it as an orange light, not a red.

**Pull request closed without merging**
