### PR TITLE
Merge/sound upstream 20240306

### PR DESCRIPTION
**Pull request by plbossart**

### CODE REVIEW

**Comment by plbossart** [comment]
one pretty bad ipc timeout issue 

https://sof-ci.01.org/linuxpr/PR4850/build1702/devicetest/index.html?model=MTLP_RVP_NOCODEC&testcase=check-suspend-resume-with-playback-5

It's worth redoing the checks....

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
@kv2019i tells me the failures on MTL are known, so unless there's an objection I'll merge this today @bardliao @ujfalusi

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
Oh, this is going to be very painful...

https://sof-ci.01.org/linuxpr/PR4853/build1738/devicetest/index.html does not show the same regressions as this PR, so it's a kernel side regression due to the upstream merge.

I'll run the tests one more time. @ujfalusi @bardliao FYI

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
Still systematic failure for MTLP_RVP_NOCODEC but on different tests...

https://sof-ci.01.org/linuxpr/PR4850/build1742/devicetest/index.html?model=MTLP_RVP_NOCODEC&testcase=check-signal-stop-start-playback-10

The SET_MOD_DX IPC timeout reeks of a firmware problem, but we don't see it without the upstream merge, so not sure what to think...

**Comment by bardliao** [comment]
> Still systematic failure for MTLP_RVP_NOCODEC but on different tests...
> 
> https://sof-ci.01.org/linuxpr/PR4850/build1742/devicetest/index.html?model=MTLP_RVP_NOCODEC&testcase=check-signal-stop-start-playback-10
> 
> The SET_MOD_DX IPC timeout reeks of a firmware problem, but we don't see it without the upstream merge, so not sure what to think...

I think the error is similar to the PR test failure of #4849 

https://sof-ci.01.org/linuxpr/PR4849/build1698/devicetest/index.html?model=MTLP_RVP_NOCODEC&testcase=check-pause-resume-capture-100
```
[ 1513.566793] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx      : 0x47000000|0x0: MOD_SET_DX [data size: 8]
[ 1514.067859] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc timed out for 0x47000000|0x0
[ 1514.067915] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: Attempting to prevent DSP from entering D3 state to preserve context
[ 1514.067923] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ IPC dump start ]------------
[ 1514.067990] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: Host IPC initiator: 0x47000000|0x0|0x0, target: 0x32000000|0x0|0x0, ctl: 0x3
[ 1514.068038] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ IPC dump end ]------------
[ 1514.068073] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ DSP dump start ]------------
[ 1514.068108] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: IPC timeout
[ 1514.068133] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: fw_state: SOF_FW_BOOT_COMPLETE (7)
[ 1514.068172] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: 0x50000005: module: ROM_EXT, state: FW_ENTERED, running
[ 1514.068217] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: Firmware state: 0x0, status/error code: 0x0
[ 1514.068298] kernel: snd_sof:sof_ipc4_find_debug_slot_offset_by_type: sof-audio-pci-intel-mtl 0000:00:1f.3: Slot type 0x4c455400 is not available in debug window
[ 1514.068303] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ DSP dump end ]------------
[ 1514.068361] kernel: Message payload: 00000000: 00000004 00000000
```

**Comment by plbossart** [comment]
Merging since we have at least 3 PRs with the same SET_MOD_DX IPC timeout. Clearly a firmware issue @kv2019i

**Pull request merged**
