### PR TITLE
Revert commits removing bar parameter

### PR DESCRIPTION
**Pull request by dbaluta**
Hi @plbossart @lyakh,

Sorry for missing PR #772 but that just reverts my https://github.com/thesofproject/linux/pull/556/commits/d00146fd8aa8d319f5618f59b61d39ccac64f776

So, I hope you can merge this new PR. I also plan to submit initial support for i.MX this week even if it is not yet complete to avoid this kind of issues.

Thanks again and sorry for the noise.

### CODE REVIEW

**Comment by plbossart** [comment]
@lyakh can you look into this? The timing isn't very good, I was planning on finishing the v6 upstream batches today, so maybe this quick revert is enough for now?

**Comment by lyakh** [comment]
@plbossart hm, interesting. I need to look at that in more detail and I think it would be good to have some more explanations from @dbaluta why he needs that, but fortunately those two patches are indeed the newest ones and are optional and easy enough to revert. So, if it helps - sure, feel free to revert them, otherwise I'd like to have some time to look at that.

**Comment by lyakh** [comment]
@plbossart @dbaluta in general I'd try not to commit code that has no users. It leads to confusion and eventually when users do appear it might well happen that the early preparatory code has to be modified anyway. And in between that code has to be maintained and with no users it cannot be tested etc...

**Comment by dbaluta** [comment]
@lyakh In general I do agree with you. Never submit code without users. Anyhow, in this particular case is just about an API extension which was added here:

https://github.com/thesofproject/linux/commit/d00146fd8aa8d319f5618f59b61d39ccac64f776

You can see that the users already exists but they all use the same bar parameter.

Also, I do agree with you that this comes late in the review, but the point is: since your patches will be squashed together with the rest of the code when sent for review to alsa-devel, next time when I will send my i.MX changes I will need to reinstantiate my https://github.com/thesofproject/linux/commit/d00146fd8aa8d319f5618f59b61d39ccac64f776 commit.

**Comment by plbossart** [comment]
@dbaluta @lyakh I am leaning towards reverting those two patches for the v6 upstream batch. That way, *if* the patches are accepted, we can keep the i.MX support as delta patches and work together on further hardware abstractions. it wouldn't very good in terms of perception if the first change for i.MX was to revert an Intel change, even if that change is minor. Having a second platform supported will be a significant milestone for the project so let's not make it harder than it needs to be.

**Pull request merged**
