### PR TITLE
Merge/sound upstream 20210512

### PR DESCRIPTION
**Pull request by kv2019i**
First merge for 5.13-rc1.

Fixes: #2855

### CODE REVIEW

**Comment by kv2019i** [comment]
CI looks clean, tag sof-dev-rebase-20210512b pushed that matches the contents of this pull request for sof-dev.

**Comment by plbossart** [comment]
@fredoh9 can you run a daily test with this PR to try on more devices? Thanks!

**Comment by plbossart** [comment]
> CI looks clean, tag sof-dev-rebase-20210512b pushed that matches the contents of this pull request for sof-dev.

I don't see this tag @kv2019i ?

**Comment by fredoh9** [comment]
yes, Internal TestPlan Result 3926 triggered!

**Review by plbossart — APPROVED** [review]
no issues found on my local SoundWire devices

**Comment by kv2019i** [comment]
@plbossart  wrote:
> I don't see this tag @kv2019i ?

https://github.com/thesofproject/linux/releases/tag/sof-dev-rebase-20210512b

I didn't update sof/topic/sof-dev-rebase yet

**Comment by plbossart** [comment]
> @plbossart wrote:
> 
> > I don't see this tag @kv2019i ?
> 
> https://github.com/thesofproject/linux/releases/tag/sof-dev-rebase-20210512b
> 
> I didn't update sof/topic/sof-dev-rebase yet

You can push the tag without force-pushing the branch

**Comment by fredoh9** [comment]
Internal TestPlan Result 3926 is available. I scanned the results and compared to yesterday's daily test, no new error is found. Looks good.

**Comment by kv2019i** [comment]
@plbossart wrote:
> > https://github.com/thesofproject/linux/releases/tag/sof-dev-rebase-20210512b
> > I didn't update sof/topic/sof-dev-rebase yet
> You can push the tag without force-pushing the branch

? I did just that :) Above URL is the tag I pushed, but I didn't force put sof-dev-rebase yet.

Results seem good, shall we we go ahead with the merge?

**Comment by plbossart** [comment]
let's merge, this leaves us one day before the week-end to look at potential issues.

**Pull request merged**
