### PR TITLE
Merge/upstream merge 20200107

### PR DESCRIPTION
**Pull request by plbossart**
First merge of the year... Let's see how this goes

### CODE REVIEW

**Comment by plbossart** [comment]
@xiulipan @fredoh9 some strange results with this ICL-RVP

````
Caught error: Jan  7 08:34:44 jf-icl-rvp-hda-5 kernel: [  469.141781] sof-audio-pci 0000:00:1f.3: error: cl_dsp_init: timeout HDA_DSP_SRAM_REG_ROM_STATUS read
Jan  7 08:34:44 jf-icl-rvp-hda-5 kernel: [  469.141830] sof-audio-pci 0000:00:1f.3: error: status = 0x00000000 panic = 0x00000000
Jan  7 08:34:44 jf-icl-rvp-hda-5 kernel: [  469.141899] sof-audio-pci 0000:00:1f.3: error: Error code=0xffffffff: FW status=0xffffffff
Jan  7 08:34:44 jf-icl-rvp-hda-5 kernel: [  469.141902] sof-audio-pci 0000:00:1f.3: error: iteration 0 of Core En/ROM load failed: -110
````

There are also a bunch of 404 errors for log files?

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by ranj063** [comment]
> @xiulipan @fredoh9 some strange results with this ICL-RVP
> 
> ```
> Caught error: Jan  7 08:34:44 jf-icl-rvp-hda-5 kernel: [  469.141781] sof-audio-pci 0000:00:1f.3: error: cl_dsp_init: timeout HDA_DSP_SRAM_REG_ROM_STATUS read
> Jan  7 08:34:44 jf-icl-rvp-hda-5 kernel: [  469.141830] sof-audio-pci 0000:00:1f.3: error: status = 0x00000000 panic = 0x00000000
> Jan  7 08:34:44 jf-icl-rvp-hda-5 kernel: [  469.141899] sof-audio-pci 0000:00:1f.3: error: Error code=0xffffffff: FW status=0xffffffff
> Jan  7 08:34:44 jf-icl-rvp-hda-5 kernel: [  469.141902] sof-audio-pci 0000:00:1f.3: error: iteration 0 of Core En/ROM load failed: -110
> ```
@plbossart this should be fixed with my PR #1631

**Comment by cujomalainey** [comment]
much appreciated, this fixes the block device NULL dereferences that were happening on CML and GLK

**Pull request merged**
