### PR TITLE
Merge/sound upstream 20200417

### PR DESCRIPTION
**Pull request by plbossart**
Minor update mostly made of NXP and Intel contributions upstream merged by Mark Brown.

@dbaluta there was a minor conflict when merging. I kept the static structures we already had in the SOF tree, and created 2 commits on topic/sof-dev-rebase 3fba60cf4bee657ffd3bcde0387483ccbd2f2a88 dade99fc6b6dcc7632479e54b47101e9ac10c24f . Please double-check them and send them upstream with your signed-off by - thanks!

@bardliao we also have a set of SoundWire commits that can go upstream, can you take a look at topic/sof-dev-rebase aac1f95287015eee37f91ddb2b953bfac17e4169 .. 12682e41426ec7ba941b45a0714f386e333d5b88
Thanks!

### CODE REVIEW

**Comment by plbossart** [comment]
@xiulipan @fredoh9 @wenqingfu CI has been stuck for the better part of the day?

**Comment by bardliao** [comment]
> @bardliao we also have a set of SoundWire commits that can go upstream, can you take a look at topic/sof-dev-rebase [aac1f95](https://github.com/thesofproject/linux/commit/aac1f95287015eee37f91ddb2b953bfac17e4169) .. [12682e4](https://github.com/thesofproject/linux/commit/12682e41426ec7ba941b45a0714f386e333d5b88)

Sure.

**Comment by xiulipan** [comment]
SOFCI TEST

**Comment by xiulipan** [comment]
@plbossart CI is offline in last weekend.

**Pull request merged**
