### PR TITLE
ASoC: intel: sof_rt5682: add quirk for Google Hatch

### PR DESCRIPTION
**Pull request by bardliao**
Add quirk for Google Hatch.

Signed-off-by: Bard liao <yung-chuan.liao@linux.intel.com>

### CODE REVIEW

**Comment by plbossart** [comment]
Looks good to me but wondering why we can't also use SSP0 on the WHL RVP and make everything aligned on SSP0?

**Comment by ranj063** [comment]
@plbossart LGTM too and verified on the CML board to fix the noise issue.

**Comment by plbossart** [comment]
> @plbossart LGTM too and verified on the CML board to fix the noise issue.

Did you mean that the noise issue was due to the incorrect MCLK (default to 19.2, needed/actual 24MHz)?

**Comment by ranj063** [comment]
@plbossart with 24MHz MCLK bard explained that we need to enable ASRC in rt5682 to fix the noise

**Comment by plbossart** [comment]
> @plbossart with 24MHz MCLK bard explained that we need to enable ASRC in rt5682 to fix the noise

so it's not this specific patch that fixes the noise then?

**Comment by ranj063** [comment]
@plbossart yes this patch fixes the noise. Adding the DMI id to the quirk table sets sof_rt5682_quirk which is checked along with MCLK value of 24MHz to enable ASRC in sof_rt5682_codec_init

**Comment by bardliao** [comment]
> Looks good to me but wondering why we can't also use SSP0 on the WHL RVP and make everything aligned on SSP0?

@plbossart The WHL RVP is reworked to use SSP1 before shipping to Shanghai.

>@plbossart yes this patch fixes the noise. Adding the DMI id to the quirk table sets sof_rt5682_quirk which is checked along with MCLK value of 24MHz to enable ASRC in sof_rt5682_codec_init

@ranj063 @plbossart The pll output was also wrong due to incorrect input. ie. The driver expect 19.2MHz input, but it is 24MHz actually, so the output will not be 24.576MHz. But, anyway, the sysclk doesn't have to be accurate if ASRC is enabled.

**Pull request merged**
