### PR TITLE
[TEST] soundwire: wait for transfer complete on suspend

### PR DESCRIPTION
**Pull request by bardliao**
We have to wait for sdw transfer complete before suspend.

Signed-off-by: Bard Liao <yung-chuan.liao@linux.intel.com>

### CODE REVIEW

**Comment by plbossart** [comment]
@bardliao I can see that we could do a system suspend where we have in-flight transactions that need to be finished before we can suspend. But for this to work we would need to also prevent new commands from being sent.

For pm_runtime, I don't see how this can happen. The master is idle, the devices are idle, why would there be any transactions?

**Comment by bardliao** [comment]
> @bardliao I can see that we could do a system suspend where we have in-flight transactions that need to be finished before we can suspend. But for this to work we would need to also prevent new commands from being sent.
> 
> For pm_runtime, I don't see how this can happen. The master is idle, the devices are idle, why would there be any transactions?

@plbossart I think it is because we active it on intel_resume(). See [if (md->pm_runtime_suspended)](https://github.com/thesofproject/linux/blob/integration/soundwire-latest/drivers/soundwire/intel.c#L1516) The transfer is to enumerate. See
```
[  388.307245] intel-sdw sdw-master-1: in sdw_assign_device_num, writing dev_num 1
[  388.307246] intel-sdw sdw-master-1: bard: msg->addr: 46
[  388.307304] intel-sdw sdw-master-1: bard: msg->addr: 50
[  388.307393] OOM killer enabled.
[  388.307393] Restarting tasks ... 
[  388.307431] intel-sdw sdw-master-1: intel_suspend_runtime start
[  388.307432] intel-sdw sdw-master-1: bard: msg_lock is locked
[  388.307493] intel-sdw sdw-master-1: intel_suspend_runtime done
```
[test_36.log](https://github.com/thesofproject/linux/files/3861645/test_36.log)

**Comment by bardliao** [comment]
> @bardliao I can see that we could do a system suspend where we have in-flight transactions that need to be finished before we can suspend. But for this to work we would need to also prevent new commands from being sent.

@plbossart Yes, but how do we prevent new commands from being sent? Does check pm_runtime_status_suspended on sdw_transfer() help? Do we need to wait for all the on going task finished? e.g. wait for the  enumeration complete.

**Comment by plbossart** [comment]
Initial issue fixed with different solution

**Pull request closed without merging**
