### PR TITLE
ASoC: Intel: soc-acpi: lnl: Add match entry for TM2 laptops

### PR DESCRIPTION
**Pull request by oortcomet**
Add a new match table entry on Lunarlake for the TM2 laptops with rt713 and rt1318.

### CODE REVIEW

**Review by ujfalusi — APPROVED** [review]

**Comment by ujfalusi** [comment]
Corresponding topology PR: https://github.com/thesofproject/sof/pull/9550

**Review by bardliao — APPROVED** [review]

**Review by ranj063 — APPROVED** [review]

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

**Comment by bardliao** [comment]
test this please

**Comment by ranj063** [comment]
@fredoh9 this ones stuck too

**Comment by fredoh9** [comment]
SOFCI TEST

**Pull request merged**
