### PR TITLE
Merge/sound upstream 20230217

### PR DESCRIPTION
**Pull request by ujfalusi**
Replacing #4197

Just one day, but rc2 ->rc8

@bardliao, tested the 20230216 merge on the CI machine and it was passing the tests with the kernel he compiled, but failing with the CI binary.
He then updated his local gcc from 9.4 to 10.03 and the kernel is failing in CI.

Is this a plausible explanation? @marc-hb, @plbossart ?

### CODE REVIEW

**Comment by ujfalusi** [comment]
Let's try with a revert of 43f1a7f905fc ("soundwire: stream: Add specific prep/deprep commands to port_prep callback")

**Comment by plbossart** [comment]
> @bardliao, tested the 20230216 merge on the CI machine and it was passing the tests with the kernel he compiled, but failing with the CI binary. He then updated his local gcc from 9.4 to 10.03 and the kernel is failing in CI.
> 
> Is this a plausible explanation? @marc-hb, @plbossart ?

well, the last time we had an upstream merge issue it was also attributed to compiler problems. That's starting to be too suspicious now. I can't recall which problem this was, IIRC it was @keqiaozhang who did the experiment of changing compilers. I think it was on GLK_BOBBA, I couldn't reproduce the issue either on my local device but the CI always failed.

**Comment by ujfalusi** [comment]
Right, with the revert patch CI is green now for SDW, can we merge it and figure it out later. We are so behind that it takes the better part of the day to just prepare another merge.

**Comment by ujfalusi** [comment]
One small update to fix an unint32_t -> u32 miss from my side in ipc4-topology.h

**Comment by marc-hb** [comment]
> well, the last time we had an upstream merge issue it was also attributed to compiler problems. That's starting to be too suspicious now. I can't recall which problem this was,

This was discussed in #4122 and internal issue 352.

It's always been suspicious to me. We upgraded compilers because we need consistent build nodes anyway and because we don't have time for low priority stuff like this but I always assumed that this gcc 9.4 version was just the messenger. Compiler bugs exist, as a funny coincidence I just spent a couple of tough days isolating one in https://github.com/thesofproject/sof/issues/7114 but that's in an old, exotic and closed source toolchain. Before suspecting a standard gcc toolchain shipped in a Long Term Support stable Ubuntu release used by millions of people one should rather investigate other, more likely causes - if we had time.

**Comment by ujfalusi** [comment]
@marc-hb, I have a revert of 43f1a7f905fc ("soundwire: stream: Add specific prep/deprep commands to port_prep callback") on top of the upstream merge to not fail in a way it fails and if you look at the patch it really makes no sense, especially if I consider that the `sdw_do_port_prep()` is basically doing nothing in our machines, apart from taking a lock and releasing it.
I have been trying to figure out how is this remotely possible, but I cannot. Butterfly effect? Slight change in generated code causing execution time anomalies? I don't know.

**Comment by ujfalusi** [comment]
SOFCI TEST

**Comment by bardliao** [comment]
@ujfalusi @marc-hb The issue will be gone with below change. (with https://github.com/thesofproject/linux/commit/43f1a7f905fcc796620c6488a7098068a05484ca)
```patch
diff --git a/drivers/soundwire/stream.c b/drivers/soundwire/stream.c
index c2191c07442b..fb338b33ab27 100644
--- a/drivers/soundwire/stream.c
+++ b/drivers/soundwire/stream.c
@@ -405,6 +405,8 @@ static int sdw_do_port_prep(struct sdw_slave_runtime *s_rt,
        int ret = 0;
        struct sdw_slave *slave = s_rt->slave;

+       pr_info("%s cmd %d\n", __func__, cmd);
+
        mutex_lock(&slave->sdw_dev_lock);

        if (slave->probed) {

```

Also build with gcc 11.3.0 can "fix" the issue.

Is it possible that the existing code works by accident?

**Comment by ujfalusi** [comment]
> @ujfalusi @marc-hb The issue will be gone with below change. (with [43f1a7f](https://github.com/thesofproject/linux/commit/43f1a7f905fcc796620c6488a7098068a05484ca))
> 
> ```diff
> diff --git a/drivers/soundwire/stream.c b/drivers/soundwire/stream.c
> index c2191c07442b..fb338b33ab27 100644
> --- a/drivers/soundwire/stream.c
> +++ b/drivers/soundwire/stream.c
> @@ -405,6 +405,8 @@ static int sdw_do_port_prep(struct sdw_slave_runtime *s_rt,
>         int ret = 0;
>         struct sdw_slave *slave = s_rt->slave;
> 
> +       pr_info("%s cmd %d\n", __func__, cmd);
> +
>         mutex_lock(&slave->sdw_dev_lock);
> 
>         if (slave->probed) {
> ```
> 
> Also build with gcc 11.3.0 can "fix" the issue.
> 
> Is it possible that the existing code works by accident?

@bardliao, the issue was also gone with this: https://github.com/thesofproject/linux/pull/4204/commits/27eb18def56412581e862b4dc63ecbe7be0d30a8
and this change is in a path which is not executed on our platforms! I cannot see the `[NOWAY]` in the dmesg in:
https://github.com/thesofproject/linux/pull/4204

**Comment by ujfalusi** [comment]
The compiler is updated in CI, let's drop the revert patch.

**Comment by ujfalusi** [comment]
With the updated compiler it looks OK, there is this https://sof-ci.01.org/linuxpr/PR4203/build3329/devicetest/index.html?model=TGLU_UP_HDA_IPC4ZPH&testcase=check-suspend-resume-5

but I can not find why it is failing...

**Comment by ujfalusi** [comment]
OK, the test failed because of a kernel error print:
```
[ 1077.351864] kernel: tpm tpm0: tpm_try_transmit: send(): error -62
```
and this is not related to SOF.

**Comment by marc-hb** [comment]
> Is it possible that the existing code works by accident?

All C code works by accident :-)

http://blog.llvm.org/2011/05/what-every-c-programmer-should-know_14.html
https://www.acepace.net/integerQuiz/
https://queue.acm.org/detail.cfm?id=3212479
https://github.com/thesofproject/sof/issues/7114

**Review by bardliao — APPROVED** [review]

**Comment by keqiaozhang** [comment]
I have upgraded gcc to 11.1.0 on all our kernel build nodes.

**Pull request merged**
