### PR TITLE
[TEST] Morimoto-san fixes for load/unload modules

### PR DESCRIPTION
**Pull request by plbossart**
Updated from PR #1504 (based on newer tip)

@fredoh9 can you take this for a spin on CI devices?
@morimoto FYI

### CODE REVIEW

**Comment by fredoh9** [comment]
Sure, I will start stress-test on BYT/BSW first.

**Comment by fredoh9** [comment]
@plb @morimoto BYT_MB_NOCODEC has card 1 not card 0. This cause many failures.
I scanned last a few DEVICE-TEST results, it's already broken in topic/master.

I can workaround this, will re-run stress-test manually.

For BYT_MB_RT5682, I ran extra more iterations, the test result is all POSITIVE.

**Comment by fredoh9** [comment]
I ran extra stress-test. For both BYT_MB_RT5682 and BYT_MB_NOCODEC, kmod load/reload tests are rock solid! BSW_CYN_MAX98090 has a separate issue.

Updated:
Let me more clear about BSW_CYN_MAX98090. Currently we don't do kmod tests on CHT/BSW platform as we know it stuck and need to wait till TIMEOUT. I manually run it on a BSW_CYN_MAX98090. I saw same issue with this PR(1509).

**Comment by plbossart** [comment]
will be merged upstream

**Comment by mengdonglin** [comment]
Applied by ASoC for-next:
https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?h=for-next&id=0ced7b050224b18ca73e38e7068f36be8e708c06

https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?h=for-next&id=b2b2afbb48eac7215f951a8a462aa6837e0d495f

**Pull request closed without merging**
