### PR TITLE
ASoC: Intel: sof_sdw: Move get_codec_dai_by_name() into sof_sdw itself

### PR DESCRIPTION
**Pull request by charleskeepax**
Currently sof_sdw relies on sof_board_helpers to provide get_codec_dai_by_name(), but that is the only function from sof_board_helpers it uses and no other machine driver requires that function. There is no reason for sof_sdw to select SSP_COMMON but more and more functions in sof_board_helpers are gaining dependencies on functions that would require stubs for sof_sdw to build without it. Firstly it was sof_ssp_get_codec_name(), as was fixed in c1469c3a8a30 ("ASoC: Intel: ssp-common: Add stub for sof_ssp_get_codec_name"), now it is:

ERROR: modpost: "sof_ssp_detect_amp_type"
[sound/soc/intel/boards/snd-soc-intel-sof-board-helpers.ko] undefined! ERROR: modpost: "sof_ssp_detect_codec_type"
[sound/soc/intel/boards/snd-soc-intel-sof-board-helpers.ko] undefined!

Rather than adding more stubs, simply move the affected function to the sof_sdw machine driver itself and no longer select SND_SOC_INTEL_SOF_BOARD_HELPERS at all. This should allow work on SSP_COMMON to progress without affecting sof_sdw.

### CODE REVIEW

**Comment by plbossart** [comment]
"There is no reason for sof_sdw to select SSP_COMMON"

What about BT offload which does rely on SSP? Or mixed cases where we had one RT711 for headset and 1308 amps in SSP mode?

**Comment by charleskeepax** [comment]
I mean is there a plan to try to convert sof_sdw over to use the board_helpers/ssp_common stuff?

They look fairly unrelated to me, currently the ssp_common is mostly about identifying the codec, but the sof_sdw has its own mechanisms for that. Most of the data structures used in the board helpers stuff look like they are for a completely different machine driver. It looks like it would be fairly major project to refactor sof_sdw to utilise this stuff, fair enough if someone is planning on doing that, but if its not soon I would argue that reverting this change is likely the smallest part of the project.

There is an alternative that I could just make SND_SOC_INTEL_SOUNDWIRE_SOF_MACH select SSP_COMMON, which would be a smaller change, but it feels to me like it would include a bunch of unrelated stuff in the build.

**Comment by charleskeepax** [comment]
Sorry or am I misinterpreting your comment and you just want me to explain that better in the commit message?

**Comment by plbossart** [comment]
Sorry I misunderstood the PR, I thought you were removing a capability but you are only moving it from one place to the other. That's fine.

**Comment by plbossart** [comment]
@bardliao please take a look

**Review by plbossart — APPROVED** [review]

**Review by bardliao — APPROVED** [review]
LGTM

**Pull request merged**
