### PR TITLE
Merge/sound upstream 20230720

### PR DESCRIPTION
**Pull request by bardliao**
2dd3601e5ea7 [NOT FOR UPSTREAM] Revert "platform/x86/intel/pmc/mtl: Put GNA/IPU/VPU devices in D3" was modified due to conflict. It was 2a96c6a33c84abefa

### CODE REVIEW

**Comment by bardliao** [comment]
SOFCI TEST

**Comment by bardliao** [comment]
Checked with @keqiaozhang, the CI test failures are all known issues.

**Comment by ujfalusi** [comment]
@bardliao, all three check_suspend failed on MTLP_RVP_SDW? 
Non audio devices failing to suspend, but it will mask real issues but they are not introduced by 6.5-rc.

I would say, we can proceed with this upstream merge.

**Comment by bardliao** [comment]
SOFCI TEST

**Comment by bardliao** [comment]
> @bardliao, all three check_suspend failed on MTLP_RVP_SDW? Non audio devices failing to suspend, but it will mask real issues but they are not introduced by 6.5-rc.

@ujfalusi I can confirm that the suspend/resume test failures are not introduced by this PR. The same failures can be seen on daily test, too. I also tested manually on CI devices, and it happens with current topic/sof-dev branch with and without this PR.

> 
> I would say, we can proceed with this upstream merge.

Could you approve if you think we are ready to go?

**Comment by plbossart** [comment]
what about the GNA D3 issue @bardliao, did you remove the revert we had in the last cycle?

**Comment by bardliao** [comment]
> what about the GNA D3 issue @bardliao, did you remove the revert we had in the last cycle?

@plbossart You are talking about "[NOT FOR UPSTREAM] Revert "platform/x86/intel/pmc/mtl: Put GNA/IPU/VPU devices in D3" was modified due to conflict.", right? No, I didn't remove the revert, but I did some modification to fix the conflict. It is https://github.com/thesofproject/linux/commit/2dd3601e5ea7610448bfbb05b3323312e9189b56 now.

**Comment by plbossart** [comment]
> > what about the GNA D3 issue @bardliao, did you remove the revert we had in the last cycle?
> 
> @plbossart You are talking about "[NOT FOR UPSTREAM] Revert "platform/x86/intel/pmc/mtl: Put GNA/IPU/VPU devices in D3" was modified due to conflict.", right? No, I didn't remove the revert, but I did some modification to fix the conflict. It is [2dd3601](https://github.com/thesofproject/linux/commit/2dd3601e5ea7610448bfbb05b3323312e9189b56) now.

ok, so when we finally get a reply on whether the firmware fix is ported to main we'll revert this. Thanks @bardliao

**Review by plbossart — APPROVED** [review]
@ujfalusi @ranj063 any objections to merging this?

**Comment by plbossart** [comment]
let's merge this @bardliao, and update the sof-dev-rebase branch accordingly

**Pull request merged**
