### PR TITLE
Merge/sound upstream 20220330

### PR DESCRIPTION
**Pull request by ranj063**

### CODE REVIEW

**Comment by ujfalusi** [comment]
I'm not sure what to make them, but ADLP_RVP_SDW_ZEPHYR and CML_RVP_SDW_ZEPHYR in  check-runtime-pm-status.sh is strange, nothing in dmesg.

Other then that, I think it looks quite normal?

**Review by bardliao — APPROVED** [review]
Pass `run-all-tests.sh -l 1` test on TGL laptop with sof-tgl-rt715-rt711-rt1308-mono.tplg topology

**Comment by ranj063** [comment]
SOFCI TEST

**Comment by ranj063** [comment]
> I'm not sure what to make them, but ADLP_RVP_SDW_ZEPHYR and CML_RVP_SDW_ZEPHYR in check-runtime-pm-status.sh is strange, nothing in dmesg.
> 
> Other then that, I think it looks quite normal?

Lets rerun CI test

**Comment by ranj063** [comment]
> I'm not sure what to make them, but ADLP_RVP_SDW_ZEPHYR and CML_RVP_SDW_ZEPHYR in check-runtime-pm-status.sh is strange, nothing in dmesg.
> 
> Other then that, I think it looks quite normal?

much better this time @ujfalusi

**Pull request merged**
