### PR TITLE
Lenovo 83hm

### PR DESCRIPTION
**Pull request by simontrimmer**

### CODE REVIEW

**Review by charleskeepax — APPROVED** [review]

**Comment by simontrimmer** [comment]
@bardliao Here we go - hopefully this is the final piece of the puzzle (in combination with the topology change we have been smithing in https://github.com/thesofproject/sof/pull/9666 )

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
> @bardliao Here we go - hopefully this is the final piece of the puzzle (in combination with the topology change we have been smithing in [thesofproject/sof#9666](https://github.com/thesofproject/sof/pull/9666) )

Nitpick: the commit messages could have a bit more context. Might need this for upstream to ALSA.

**Comment by bardliao** [comment]
The second commit is easy to understand. However, we still need a commit message. Maybe just "Add debug message when SOC_SDW_CODEC_MIC is enabled"

**Comment by simontrimmer** [comment]
Good thinking - I've rebased and updated the latter one to have a description, as it would be easy to miss that it turns something off

**Review by bardliao — APPROVED** [review]

**Pull request merged**
