### PR TITLE
[RFC] ASoC: SOF: pcm: get position updates at least every 20ms

### PR DESCRIPTION
**Pull request by juimonen**
Currently dsp sends position updates every host_period_bytes copied over
dma. The time interval might be as big as 100ms. If user space uses
timer scheduling, this kind of low frequency update is not enough and we
should anyway decouple alsa/dma periods from postion updates. So set
position update to happen at least every 20 ms.

Signed-off-by: Jaska Uimonen <jaska.uimonen@linux.intel.com>

### CODE REVIEW

**Comment by juimonen** [comment]
@plbossart @ranj063 I know this is ugly but fixes the pulseaudio timer scheduling issue for me. If you have ideas how and where to make position updates more frequent in a nice way, let me know...

**Comment by plbossart** [comment]
@juimonen no we can't do that. At some point we'll want to support 'deep buffer' and need to have the ability to query a timestamp without forcing an IPC.

Maybe I am mistaken but I really thought there was an area in the SRAM window where the firmware would update the position after each elementary DMA transfer, so that the position could be read 'on-demand' without any IPC. This has been a requirement since the Baytrail Windows days that the counters are maintained with a 1ms resolution, and it'd be a huge miss if we didn't do this.

That said, the sof_ipc_stream_posn structure has fundamental issues. It exposes both host side and DAI side, and there can be an M:N relationship between host and DAI, so this structure is just very very limited.

we probably need an SOF developer thread on this one, it looks like things are broken big time, and have been for ages.

**Comment by juimonen** [comment]
@plbossart yes agreed. This is new area to me, so I'm learning this at the same time. As I understand this is: 
1) dw-dma specific (the dma used in hda has read/write pointers in the kernel side). But dw-dma is initiated from dsp side and I have to find out if some registers show the exact position. @tlauda any comments on this?

2) timer scheduling specific. So applications using this usually disable period_elapsed callbacks, like pulseaudio. As we noted applications using "traditional" irq/period_elapsed callbacks work just fine.
Just mean that we could make position updates more frequent when period_elapsed is disabled, but yeah that would kind of destroy the sleep. and it would be nice to have exact position anyway...
 
I think the position struct is stream specific so the "host" field means how much the host widget in dsp has read, so I think that 's 1:1 mapping (?).

**Comment by juimonen** [comment]
closing

**Pull request closed without merging**
