### PR TITLE
ASoC: SOF: Intel: SRAM_REG_FW mailbox update

### PR DESCRIPTION
**Pull request by bkokoszx**
Update SRAM_REG mailbox due to change on FW side (tracing
ipc received and processed counters - https://github.com/thesofproject/sof/pull/1441).

Signed-off-by: Bartosz Kokoszko <bartoszx.kokoszko@linux.intel.com>

### CODE REVIEW

**Comment by plbossart** [comment]
@bkokoszx there are only definitions here and no code, what is the intent here? To have someone else add kernel support? @jajanusz had a PR for this earlier, not sure I get the directions

**Comment by jajanusz** [comment]
@plbossart Yea, a bit of mess, I think we should stop doing commits and figure out what we wanna do with things like this -> https://github.com/thesofproject/sof/pull/1441#discussion_r286855103

**Comment by bkokoszx** [comment]
@lgirdwood 
Should we add debug SRAM_REG_FW_IPC_RECEIVED_COUNT and SRAM_REG_FW_IPC_PROCESSED_COUNT definitions in kernel since they are only conditional (debug option) on firmware?

**Comment by bkokoszx** [comment]
@lgirdwood 
Could you answer my question posted in my previous comment (https://github.com/thesofproject/linux/pull/976#issuecomment-502620499) in a meantime? I would like to complete/close this PR. In my humble opinion adding this mailboxes definitions are not needed (since they are optional in FW), but I might be wrong. Thanks

**Comment by plbossart** [comment]
@bkokoszx this PR has not moved since July 30, please close or update the status

**Pull request closed without merging**
