### PR TITLE
ASoC: Intel: soc-acpi: update codec addr on 0C11/0C4F product

### PR DESCRIPTION
**Pull request by gongjun-song**
Realtek updated rt1318 codec addr of link1 on 0C11/0C4F product.

Signed-off-by: Gongjun Song <gongjun.song@intel.com>

### CODE REVIEW

**Comment by gongjun-song** [comment]
Dell aligns with Realtek and update rt1318 codec addr in bios, so update it in kernel

**Review by bardliao — APPROVED** [review]

**Review by plbossart — APPROVED** [review]

**Comment by bardliao** [comment]
@plbossart Should we send this upstream now?

**Comment by plbossart** [comment]
> @plbossart Should we send this upstream now?

I'll send it.

**Comment by plbossart** [comment]
I ran out of time @bardliao, please send it. We'll need a Fixes tag

**Comment by bardliao** [comment]
> I ran out of time @bardliao, please send it. We'll need a Fixes tag

Sent

**Pull request merged**
