### PR TITLE
ASoC: sof: use iopoll.h macro for polled register reads

### PR DESCRIPTION
**Pull request by kv2019i**
Change to align our polled register reads with iopoll.h, related to issue #358 
Some discussion already in the patch, see my commets to the issue.

Introduce a variant of readx_poll_timeout() macro from linux/iopoll.h
to SOF and use it to replace the old snd_sof_dsp_register_poll()
function. Due to indirection of register i/o in SOF, we can't directly
use the iopoll.h macros.

Signed-off-by: Kai Vehmanen <kai.vehmanen@linux.intel.com>

### CODE REVIEW

**Comment by ranj063** [comment]
@kv2019i looks good to me. One of the main reasons we added the 2 resolution register polling was because of a race that was seen between when the audio fw authentication was requested and when the CSME was available. Could you please try a quick stress test with your patch on your chromebook?
This will run for a long time and you can probably leave it running overnight. Thanks!

./suspend_stress_test -c 1000.

**Comment by ranj063** [comment]
@kv2019i sorry I just realized i said ./suspend_strest_test instead of suspend_stress_test.

Anyway, I've kicked off a 1000 iterations test today. I will update the result tomorrow.

**Comment by ranj063** [comment]
@kv2019i @plbossart a stress test at my end has passed 2500 iterations. So I think this one is good to be merged.

**Comment by plbossart** [comment]
ok, one last comment: isn't there a macro to avoid code like:
((status & chip->ipc_ack_mask)  == chip->ipc_ack_mask),

or can we add one?

**Comment by kv2019i** [comment]
@plbossart wrote:
> ok, one last comment: isn't there a macro to avoid code like:
> ((status & chip->ipc_ack_mask) == chip->ipc_ack_mask),
> 
> or can we add one?

I was wondering the same. I went through all generic bitops headers in include/linux and grepped through dozens of drivers, but couldn't spot an established macro for this.

Then I thought having the bare logic visible is easier to read than a custom macro that is not used elsewhere. In most code locations, the code won't be much shorter in any case.

**Comment by wenqingfu** [comment]
should #358 be closed then?  @kv2019i 

If so, recommend approach: https://help.github.com/en/articles/closing-issues-using-keywords for the future

**Comment by kv2019i** [comment]
@wenqingfu 
> should #358 be closed then? @kv2019i

Ack, #358 closed now. The issue had multiple subissues and this was the last one.

> If so, recommend approach: https://help.github.com/en/articles/closing-issues-using-keywords for the future

Thanks, ack, will follow this in the future.

**Pull request merged**
