### PR TITLE
Merge/sound upstream 20210907

### PR DESCRIPTION
**Pull request by plbossart**
time for a quick upstream merge before maintainers rebase on 5.15-rc1

### CODE REVIEW

**Comment by fredoh9** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
Complete failure on UP2_NOCODEC https://sof-ci.01.org/linuxpr/PR3141/build6306/devicetest/
let's redo the tests.

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
all green now in https://sof-ci.01.org/linuxpr/PR3141/build6313/devicetest/, will test more

**Comment by plbossart** [comment]
Intel test 6422 shows two regressions on SoundWire devices.

https://sof-ci.sh.intel.com/#/result/planresultdetail/6422?model=TGLH_0A5E_SDW&testcase=check-alsabat-headset-playback
https://sof-ci.sh.intel.com/#/result/planresultdetail/6422?model=CML_RVP_SDW&testcase=check-suspend-resume-50

will re-run on those specific devices, I don't see what could cause regressions.

**Comment by plbossart** [comment]
confirmed problem by re-running the tests:
https://sof-ci.sh.intel.com/#/result/planresultdetail/6429?model=TGLH_0A5E_SDW&testcase=check-alsabat-headset-playback

Need to ask the Intel team to look into this....

**Comment by bardliao** [comment]
> confirmed problem by re-running the tests:
> https://sof-ci.sh.intel.com/#/result/planresultdetail/6429?model=TGLH_0A5E_SDW&testcase=check-alsabat-headset-playback
> 
> Need to ask the Intel team to look into this....

I tested headset playback/capture on my TGLH_0A5E_SDW device, but I didn't see any issue.

**Comment by plbossart** [comment]
> > confirmed problem by re-running the tests:
> > https://sof-ci.sh.intel.com/#/result/planresultdetail/6429?model=TGLH_0A5E_SDW&testcase=check-alsabat-headset-playback
> > Need to ask the Intel team to look into this....
> 
> I tested headset playback/capture on my TGLH_0A5E_SDW device, but I didn't see any issue.

Yes, it was a CI issue, fixed now.

**Pull request merged**
