### PR TITLE
Merge/sound upstream 20220914

### PR DESCRIPTION
**Pull request by ujfalusi**
Fairly large merge, the last one was done at 2022.08.01...
Couple  of patches disappeared from -next, but local testing on limited devices passes.
6.0-rc5+

### CODE REVIEW

**Comment by ujfalusi** [comment]
@chunxu-li, can you check the sound/soc/sof/mediatek/mt8186/ and if you could do a local testing of this PR, that would help make sure that I got it right.

**Comment by ujfalusi** [comment]
Right, looks like CI can not swallow this for some reason...
Locally I can manually merge this PR to topic/sof-dev

I'm not sure how this can be kicked forward

**Comment by miRoox** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
@ujfalusi can you add the patch for the sparse fixes that I added for 0822?

**Comment by plbossart** [comment]
Looks pretty good @ujfalusi, is there matching sof-dev-rebase-20220914 tag?

**Comment by fredoh9** [comment]
I triggered a test with stable-v2.2 FW. Internal test 15384.
Still under testing but JSL_ES8336_HDA and BYT_MB_NOCODEC are NOT happy with this.

**Comment by ujfalusi** [comment]
> Looks pretty good @ujfalusi, is there matching sof-dev-rebase-20220914 tag?

Not yet, I was planning to push it only after this has merged, but I can do the ritual right away.

**Comment by plbossart** [comment]
@fredoh9 the test with JSL_ES8336_HDA is likely a setup issue, this is a device that requires the production key. I used it in the past for my own tests and I saw that it was using the wrong firmware as well. Please double-check that this is indeed using the right firmware.

For the BYT nocodec, I have no explanation. we should retry the same test before this PR, and see if there is a change. I suspect this is a random event, and I can't recall when we last had a test result with BYT nocodec anyways.

**Comment by ujfalusi** [comment]
On BYT we have this in firmware log:
```
[      207415.304] (        1927.344) c0 dma-trace                   src/lib/alloc.c:765  ERROR failed to alloc 0x108 bytes zone 0x2 caps 0x1 flags 0x0
[      207535.148] (         119.844) c0 dma-trace             src/ipc/ipc3/helper.c:317  ERROR comp_new(): unable to create the new component
[      207540.408] (           5.260) c0 dma-trace             src/ipc/ipc3/helper.c:638  ERROR ipc_comp_new(): component cd = NULL
[      207545.721] (           5.312) c0 dma-trace            src/ipc/ipc3/handler.c:1274 ERROR ipc: pipe 2 comp 8 creation failed -22
```

which likely corresponds to the kernel side:
```
[  205.214536] kernel: snd_sof:ipc3_log_header: sof-audio-acpi-intel-byt 80860F28:00: ipc tx: 0x30010000: GLB_TPLG_MSG: COMP_NEW
[  205.214836] kernel: sof-audio-acpi-intel-byt 80860F28:00: ipc tx error for 0x30010000 (msg/reply size: 92/20): -22
[  205.215040] kernel: sof-audio-acpi-intel-byt 80860F28:00: Failed to setup widget PCM0C
```

**Comment by plbossart** [comment]
@fredoh9 your test did not use the right firmware, it's based on 2.0, not 2.2

[   29.454566] kernel: sof-audio-acpi-intel-byt 80860F28:00: Firmware info: version 2:0:0-1bd86

should be:

[   20.950880] kernel: sof-audio-acpi-intel-byt 80860F28:00: Firmware info: version 2:2:0-afe46

**Comment by plbossart** [comment]
@fredoh9 the 2.0 firmware was also used on other platforms, so needs to be redone, see e.g. 

https://sof-ci.sh.intel.com/#/result/planresultdetail/15384?model=APL_UP2_PCM512X&testcase=verify-kernel-boot-log
[   16.015596] kernel: sof-audio-pci-intel-apl 0000:00:0e.0: Firmware info: version 2:0:0-1bd86

**Comment by fredoh9** [comment]
Ah, I will double check FW version again. Probably I missed one parameter. I will trigger again

**Comment by fredoh9** [comment]
Internal test 15420 is running well with stable-v2.2 SOF FW now.
Sorry about the noise yesterday.

**Comment by fredoh9** [comment]
Test result with stable-v2.2, mostly good except,

For ADLP_GMB_I2S, 
kmod test failded with this error. Will report to sof-test repo first.

```
[ 6722.552819] kernel: max98390 i2c-MX98390:00: AMP is not ready to run calibration
[ 6722.554197] kernel: max98390 i2c-MX98390:01: AMP is not ready to run calibration
```

Suspend-resume failed with below error. I will report this in linux repo after merge.

```
[  357.577318] kernel: max98390 i2c-MX98390:00: ret=-108, Failed to read: 0x24FF
[  357.577779] kernel: max98390 i2c-MX98390:01: ret=-108, Failed to read: 0x24FF
[  357.957059] kernel: rt5682s i2c-RTL5682:00: Device with ID register c103d020 is not rt5682s
```

For JSL_RVP_NOCODEC,
MAX volume issue came in multiple-pause-resume. Rarely we see MAX volume. This is device setting issue, need more investigation, why this happened again.

For JSL_ES8336_HDA, suspend/resume failed due to below error. Should we file an issue in linux repo?

```
[ 2232.443212] kernel: es8316 i2c-ESSX8336:00: Unable to sync registers 0x0-0x1. -121
```

For BYT_MB_NOCODEC, TIMEOUT at check-kmod-load-unload-after-playback-5.
Stuck at 'MODPROBE	snd_sof_acpi_intel_byt'

**Comment by ujfalusi** [comment]
@fredoh9, thanks for checking and the summary!

> Test result with stable-v2.2, mostly good except,
> 
> For ADLP_GMB_I2S, kmod test failded with this error. Will report to sof-test repo first.
> 
> ```
> [ 6722.552819] kernel: max98390 i2c-MX98390:00: AMP is not ready to run calibration
> [ 6722.554197] kernel: max98390 i2c-MX98390:01: AMP is not ready to run calibration
> ```

This is caused by 6ac246105b4fd737ed51b8ac3ef031f837686dee and if I look closely, the patch is not correct in many ways.
The error should be info in the first place, what it is telling that user space tried to do calibration w/o running stream. Before the patch the calibration was always preformed by enabling the codec for the duration of the calibration, but it was equally wrong at the same time as if there were a running stream, the calibration would have powered off the codec...

The broken code is broken in different way now.
 
> Suspend-resume failed with below error. I will report this in linux repo after merge.
> 
> ```
> [  357.577318] kernel: max98390 i2c-MX98390:00: ret=-108, Failed to read: 0x24FF
> [  357.577779] kernel: max98390 i2c-MX98390:01: ret=-108, Failed to read: 0x24FF
> [  357.957059] kernel: rt5682s i2c-RTL5682:00: Device with ID register c103d020 is not rt5682s
> ```

-108 is `-ESHUTDOWN` and it is coming from the i2c core (likely): The i2c controller is not powered on, so we can not read registers of the codec on a powered down bus.

> For JSL_RVP_NOCODEC, MAX volume issue came in multiple-pause-resume. Rarely we see MAX volume. This is device setting issue, need more investigation, why this happened again.
> 
> For JSL_ES8336_HDA, suspend/resume failed due to below error. Should we file an issue in linux repo?
> 
> ```
> [ 2232.443212] kernel: es8316 i2c-ESSX8336:00: Unable to sync registers 0x0-0x1. -121
> ```

-121 is `-EREMOTEIO`, likely also coming from i2c core?
 
> For BYT_MB_NOCODEC, TIMEOUT at check-kmod-load-unload-after-playback-5. Stuck at 'MODPROBE snd_sof_acpi_intel_byt'

Hrm, that is strange, let me take a closer look.

**Comment by ujfalusi** [comment]
Changes since v1:
- CI patches added from @plbossart for sparse

Changes since v2:
- Tentative fix for max98390's calibration reading added.

**Comment by ujfalusi** [comment]
@fredoh9, I don't get this... Internal run 15438 on BYT_MB_NOCODEC is _all_ green with this PR.
Started a new one (15442) again with BYT_MB_NOCODEC and the ADLP_GMB_I2S to check it again and to check my attempt to fix the calibration error on the codec.

**Comment by ujfalusi** [comment]
> ```
> [  357.577318] kernel: max98390 i2c-MX98390:00: ret=-108, Failed to read: 0x24FF
> [  357.577779] kernel: max98390 i2c-MX98390:01: ret=-108, Failed to read: 0x24FF
> [  357.957059] kernel: rt5682s i2c-RTL5682:00: Device with ID register c103d020 is not rt5682s
> ```

```
[  357.577047] kernel: i2c i2c-0: Transfer while suspended
[  357.577074] kernel: WARNING: CPU: 0 PID: 16532 at drivers/i2c/i2c-core.h:54 __i2c_transfer+0x557/0x5b0
...
[  357.577172] kernel: Call Trace:
[  357.577176] kernel:  
[  357.577181] kernel:  i2c_transfer+0x7f/0x100
[  357.577184] kernel:  regmap_i2c_read+0x69/0xa0 [regmap_i2c]
[  357.577190] kernel:  _regmap_raw_read+0x120/0x2b0
[  357.577197] kernel:  _regmap_bus_read+0x41/0x80
[  357.577199] kernel:  _regmap_read+0x5c/0x160
[  357.577202] kernel:  regmap_read+0x3e/0x70
[  357.577204] kernel:  max98390_i2c_probe.cold+0x179/0x1d0 [snd_soc_max98390]
[  357.577209] kernel:  i2c_device_probe+0x12e/0x360
[  357.577212] kernel:  really_probe+0xde/0x350
[  357.577220] kernel:  ? pm_runtime_barrier+0x50/0x90
[  357.577226] kernel:  __driver_probe_device+0x78/0x180
[  357.577228] kernel:  driver_probe_device+0x1e/0xa0
[  357.577230] kernel:  __driver_attach+0xc5/0x1a0
[  357.577231] kernel:  ? __device_attach_driver+0x110/0x110
[  357.577232] kernel:  ? __device_attach_driver+0x110/0x110
[  357.577234] kernel:  bus_for_each_dev+0x78/0xc0
[  357.577238] kernel:  bus_add_driver+0x1b1/0x200
[  357.577242] kernel:  driver_register+0x6c/0xd0
[  357.577244] kernel:  i2c_register_driver+0x3e/0x90
[  357.577246] kernel:  ? 0xffffffffc064b000
[  357.577248] kernel:  do_one_initcall+0x6f/0x270
[  357.577255] kernel:  ? kmem_cache_alloc_trace+0x4e/0x220
[  357.577262] kernel:  do_init_module+0x4c/0x1f0
[  357.577268] kernel:  load_module+0x1bad/0x1e30
[  357.577274] kernel:  ? kernel_read_file+0x244/0x2a0
[  357.577281] kernel:  ? __do_sys_finit_module+0xb4/0x130
[  357.577283] kernel:  __do_sys_finit_module+0xb4/0x130
[  357.577290] kernel:  do_syscall_64+0x38/0x90
[  357.577298] kernel:  entry_SYSCALL_64_after_hwframe+0x63/0xcd
```
 
> For JSL_RVP_NOCODEC, MAX volume issue came in multiple-pause-resume. Rarely we see MAX volume. This is device setting issue, need more investigation, why this happened again.

What is the 'MAX volume' test?
> 
> For JSL_ES8336_HDA, suspend/resume failed due to below error. Should we file an issue in linux repo?
> 
> ```
> [ 2232.443212] kernel: es8316 i2c-ESSX8336:00: Unable to sync registers 0x0-0x1. -121
> ```

Caused by: 4bac47a7b2f9 ("ASoC: codecs: add suspend and resume for ES8316")
Since the component level of suspend and resume is tied to the card, this is likely caused by the fact that other subsystems resume later than the sound, so i2c is not resumed or some power is not yet restored to the codec (which the codec has not control for as far as I can see in the driver).
The print is harmless as such, it indicates that the pointed patch is not correct and it is not doing what it supposed to be doing.

**Comment by plbossart** [comment]
let's ignore the ES8336 issues for now, we can deal with this later. This wasn't a stable platform to start with, so we shouldn't look at this as a regression. It never worked.

**Comment by ujfalusi** [comment]
Changes since v3:
- revert 4bac47a7b2f9f0c84411cb06944bab8f85c08757 patch added

**Comment by ujfalusi** [comment]
@fredoh9, can you schedule internal daily run after the new binaries are available? 15450 was done with the max98390 patch and it is all green.

**Comment by fredoh9** [comment]
sure, i will trigger new internal daily test with stable-v2.2
==> 15464 is just started

**Comment by fredoh9** [comment]
The test result is great!
All of them are known issue. Except one. A error in simultaneous-playback-capture-25.sh in BYT_MB_NOCODEC is a bit different, 25 loops are done, error with killing sof-logger. But no worry to me.

**Review by fredoh9 — APPROVED** [review]

**Pull request merged**
