### PR TITLE
ASoC: Intel: Chromebooks: remap jack pins

### PR DESCRIPTION
**Pull request by plbossart**
The existing Chromebook machine drivers are incompatible with the existing UCM support. To enable 'JackControl' in UCM, we need to remap the jack pins to controls.

Tested on GLK "bobba" with https://github.com/alsa-project/alsa-ucm-conf/pull/150

### CODE REVIEW

**Comment by cujomalainey** [comment]
> The existing Chromebook machine drivers are incompatible with the existing UCM support. 
> 
In pulse specifically, JackDev is an upstream UCM construct.

**Review by cujomalainey — COMMENTED** [review]
Does this API still create the input device? ChromeOS prefers JackDev over JackControl

**Comment by plbossart** [comment]
> Does this API still create the input device? ChromeOS prefers JackDev over JackControl

@perexg tells me to use JackControl, so you guys need to align @cujomalainey 

For the input, this PR doesn't change anything, see what I get on 'bobba'

````
[   11.819969] input: sof-glkda7219max Headset Jack as /devices/pci0000:00/0000:00:0e.0/glk_da7219_mx98357a/sound/card0/input9
[   11.823415] input: sof-glkda7219max HDMI/DP,pcm=5 as /devices/pci0000:00/0000:00:0e.0/glk_da7219_mx98357a/sound/card0/input10
[   11.825058] input: sof-glkda7219max HDMI/DP,pcm=6 as /devices/pci0000:00/0000:00:0e.0/glk_da7219_mx98357a/sound/card0/input11
[   11.825777] input: sof-glkda7219max HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:0e.0/glk_da7219_mx98357a/sound/card0/input12
````

and for the controls

````
root@plb-Bobba:~# amixer -Dhw:0 controls | grep Jack
numid=70,iface=CARD,name='HDMI/DP,pcm=5 Jack'
numid=76,iface=CARD,name='HDMI/DP,pcm=6 Jack'
numid=82,iface=CARD,name='HDMI/DP,pcm=7 Jack'
numid=65,iface=CARD,name='Headphone Jack'
numid=66,iface=CARD,name='Headset Mic Jack'
numid=67,iface=MIXER,name='Headphone Jack Switch'

````

**Comment by plbossart** [comment]
This seems to generate errors on Chromebooks.

````
[   11.724067] bxt_da7219_max98357a glk_da7219_mx98357a: ASoC: DAPM unknown pin Headphone
````

This must be a naming issue. I originally tried to rename "Headphone Jack" to "Headphone", but then I had a duplicate pin. I don't think anyone knows how those machine drivers work (if they ever worked)...

**Comment by cujomalainey** [comment]
> @perexg tells me to use JackControl, so you guys need to align @cujomalainey

You can specify both in the UCM and the audio server can use whichever it chooses. As long as the driver exposes both it should be fine

**Comment by plbossart** [comment]
Now using "Headphone Jack" everywhere the DAPM errors are gone on my 'Bobba' test device and I get the device switch to work. Finally some progress.

**Comment by perexg** [comment]
> This must be a naming issue. I originally tried to rename "Headphone Jack" to "Headphone", but then I had a duplicate pin. I don't think anyone knows how those machine drivers work (if they ever worked)...

You can try to keep the "Jack" suffix in the pin name. The kctl name will not add another Jack suffix, if there's one present.

And I see that you did it already :+1:

**Comment by plbossart** [comment]
> > @perexg tells me to use JackControl, so you guys need to align @cujomalainey
> 
> You can specify both in the UCM and the audio server can use whichever it chooses. As long as the driver exposes both it should be fine

For my education what prevents audio servers from aligning on one method and what's wrong with JackControl?

**Comment by cujomalainey** [comment]
> > > @perexg tells me to use JackControl, so you guys need to align @cujomalainey
> > 
> > 
> > You can specify both in the UCM and the audio server can use whichever it chooses. As long as the driver exposes both it should be fine
> 
> For my education what prevents audio servers from aligning on one method and what's wrong with JackControl?

@chiang831 do you know why we prefer JackDev? I feel like this is dgreid era decision. @plbossart  we support both at regardless.

**Review by ujfalusi — APPROVED** [review]

**Review by bardliao — APPROVED** [review]

**Pull request merged**
