### PR TITLE
Merge/sound upstream 20200529

### PR DESCRIPTION
**Pull request by bardliao**
Upstream sync.

Matching updated sof-dev-rebase (without reorderings):
https://github.com/bardliao/linux/tree/merge/sof-dev-rebase-20200529

### CODE REVIEW

**Comment by ranj063** [comment]
@bardliao there's a cml.kmod failure. Looks like we need an update for the kmod script?

**Comment by bardliao** [comment]
> @bardliao there's a cml.kmod failure. Looks like we need an update for the kmod script?

Yes, see https://github.com/thesofproject/sof-test/pull/230

**Review by kv2019i — APPROVED** [review]
Great work @bardliao ! Looks good to me. I cross-checked between this PR and bardliao/merge/sof-dev-rebase-20200529-fixup and the two branches are identical, so rebase seems good.

I also tested HDA and HDMI locally on CFL and ICL and no new issues found.

**Comment by plbossart** [comment]
Issue with Minnowboard-rt5682 is due to new module, should be fixed by https://github.com/thesofproject/sof-test/pull/231

**Review by plbossart — APPROVED** [review]
Looks quite good @bardliao, congratulations on joining the maintainer team!

**Comment by plbossart** [comment]
I'll go ahead and merge.

**Pull request merged**
