### PR TITLE
Merge/sound upstream 20230103

### PR DESCRIPTION
**Pull request by plbossart**
first merge based on 6.2-rc2, smoke-tested on SoundWire device

### CODE REVIEW

**Comment by plbossart** [comment]
Major regression on GLK:

https://sof-ci.01.org/linuxpr/PR4122/build2617/devicetest/index.html?model=GLK_BOB_DA7219&testcase=verify-kernel-boot-log

````
[    9.123355] kernel: gpio-607 (sdmode): multiple pull-up, pull-down or pull-disable enabled, invalid configuration
[    9.141513] kernel: max98357a: probe of MX98357A:00 failed with error -22
````

@cujomalainey @bzhg any idea what this could be about?

**Comment by plbossart** [comment]
I can't reproduce this locally on my GLK_BOBB_DA7219 device, gah.

**Comment by cujomalainey** [comment]
Can you see what other driver is trying to use the pin?

**Comment by plbossart** [comment]
> Can you see what other driver is trying to use the pin?

I can't reproduce this either on the same device used by CI, there is some sort of configuration issue here. I do see the error with the kernel used by CI but I cannot generate the same results, so something's off. This will take time to be solved I am afraid.

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by miRoox** [comment]
SOFCI TEST

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Comment by keqiaozhang** [comment]
I can't reproduce this issue on CI devices.

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Comment by keqiaozhang** [comment]
The regression on GLK is not caused by the kernel changes, CI build server "sof-ci-build-01" is Ubuntu 18.04 and gcc version is 9.4.0. It seems that the kernel changes require higher gcc version. I have upgraded the gcc to 11.1.0  and test passed on GLK_BOB_DA7219.

**Comment by plbossart** [comment]
The only errors found are timeouts in suspend-resume cases https://sof-ci.01.org/linuxpr/PR4122/build2655/devicetest/index.html
I am a bit concerned about those, but not to the point where I want to hold this merge further.

@ranj063 @bardliao @ujfalusi if you can give it a try on your local devices that would be nice. I'll wait until Monday for feedback.

**Comment by cujomalainey** [comment]
Let me know if you need me to look into the coreboot configuration on that board. It seems odd that a relatively simple codec driver would all of the sudden have pin problems unless it was fighting another driver for it.

**Comment by marc-hb** [comment]
> CI build server "sof-ci-build-01" is Ubuntu 18.04 and gcc version is 9.4.0. It seems that the kernel changes require higher gcc version. I have upgraded the gcc to 11.1.0 and test passed on GLK_BOB_DA7219.

If this new kernel is not compatible with gcc 9.4.0, compilation with gcc 9.4.0 should be blocked and fail.

According to the documentation and the source code the minimum gcc version is currently 7.1:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=88b61e3bff93

If 7.1 is wrong it should be reported and corrected but... this error message does not look like a compiler-related problem, does it?

It would be interesting to git bisect this failure with gcc 9.4.0

**Comment by bardliao** [comment]
> The only errors found are timeouts in suspend-resume cases https://sof-ci.01.org/linuxpr/PR4122/build2655/devicetest/index.html I am a bit concerned about those, but not to the point where I want to hold this merge further.
> 
> @ranj063 @bardliao @ujfalusi if you can give it a try on your local devices that would be nice. I'll wait until Monday for feedback.

@plbossart I run `run-all-tests.sh` on my Dell SKU0A32 laptop and all cases PASS.

**Comment by ujfalusi** [comment]
@plbossart, I have compile error locally with sparse (git version) and gcc 12.2.0:
```
include/linux/mm.h:1288:58: error: attribute __transparent_union_
```

**Comment by ujfalusi** [comment]
> @plbossart, I have compile error locally with sparse (git version) and gcc 12.2.0:
> 
> ```
> include/linux/mm.h:1288:58: error: attribute __transparent_union_
> ```

Whack a mole solution is to add `-Wno-transparent-union` to `CF` for sparse...

**Comment by ujfalusi** [comment]
@plbossart, looks good on my devices (suspend/resume works on up2 w/ pcm512x topology).

**Comment by plbossart** [comment]
> > @plbossart, I have compile error locally with sparse (git version) and gcc 12.2.0:
> > ```
> > include/linux/mm.h:1288:58: error: attribute __transparent_union_
> > ```
> 
> Whack a mole solution is to add `-Wno-transparent-union` to `CF` for sparse...

that's what I did with the updates.

**Comment by plbossart** [comment]
GitHub won't let me merge this, I keep seeing the 'confirm merge' button and nothing happens.

**Comment by plbossart** [comment]
now it worked. Yay clouds.

**Comment by ujfalusi** [comment]
GH is sluggish recently.

**Pull request merged**
