### PR TITLE
[DNM] ASoC: SOF: pm: store debugfs cache upon errors in resume

### PR DESCRIPTION
**Pull request by kv2019i**
If there are failures in DSP runtime resume, the device state
will not reach active and this makes it impossible e.g. to
retrieve a posible DSP panic dump via "exception" debugfs.
    
To allow debugging these scenarios, update the debugfs caches in case
DSP boots up but errors are hit while setting up the pipelines back.
User-space can then later retrieve DSP panic and other state via debugfs
(depends on existing CONFIG_SND_SOC_SOF_DEBUG_ENABLE_DEBUGFS_CACHE
mechanism).

Link: https://github.com/thesofproject/linux/issues/4274

### CODE REVIEW

**Comment by plbossart** [comment]
@kv2019i you probably want to update your branch?

It's pretty funny that you are trying to deal with failures on resume, I had the opposite case with failures on suspend where we cannot keep the context and stay in D0 while transitioning to D3, see https://github.com/thesofproject/linux/pull/4269/commits/aaec0a1e5ec1427512899cf43d65b9377261189d
I wonder if in this case we should also keep the debugfs caches updated.

**Comment by kv2019i** [comment]
> @kv2019i you probably want to update your branch?

Ack, sorry , this was on top of upstream v6.2.3 tag as I know Jairaj anyways needs to backport to test this out.
 
> It's pretty funny that you are trying to deal with failures on resume, I had the opposite case with failures on 
> suspend where we cannot keep the context and stay in D0 while transitioning to D3, see [aaec0a1]> 
> (https://github.com/thesofproject/linux/commit/aaec0a1e5ec1427512899cf43d65b9377261189d) I wonder if in this case we 

If this helps the reported case, let's indeed improve. The current RETAIN_STATE is indeed annoying as you have to reboot the system after error as the pm-runtime refcounting is no longer recoverable after a failure. 

We could have retrieve the DSP state to cache upon errors and this would cover many of the original requirements why we added RETAIN_DSP_STATE.

And we would then keep CONFIG_SND_SOC_SOF_DEBUG_RETAIN_DSP_CONTEXT only for special cases (e.g. when you want to attach gdb to a crashed DSP).

Or some magic combination that gets us all the benefits (without messing up pm-runtime refcounts).

**Comment by plbossart** [comment]
Maybe use pm_runtime_forbid() to prevent the system from suspending, and use the command line to allow it again?

Edit: the driver could use pm_runtime_forbid() which will keep the device in D0.
The user can then do 'echo auto > /sys/bus/pci/devices/0000\:00\:1f.3/power/control' to keep going. 

No reboot necessary.

**Comment by greg-intel** [comment]
SOFCI TEST
```
16:07:35  ERROR: Skip PR test with merge conflicts:
16:07:35  	GitHub pull request #4282 of commit db7508e62338db240b7854d4412445406c67ded5, has merge conflicts.
```
Sorry, I didn't look closer, we had a CI issue the past two days.  I thought this was one of those cases but it's a different issue.

**Comment by plbossart** [comment]
@kv2019i isn't this replaced by the merged https://github.com/thesofproject/linux/pull/4302? If yes, can we close this?

**Comment by kv2019i** [comment]
Right, sorry, closing this, no longer needed.

**Pull request closed without merging**
