### PR TITLE
Upstream merge 20200226

### PR DESCRIPTION
**Pull request by ranj063**

### CODE REVIEW

**Comment by plbossart** [comment]
@ranj063 did you merge the soundwire/next branch? I don't see it or I missed it?

**Comment by ranj063** [comment]
> @ranj063 did you merge the soundwire/next branch? I don't see it or I missed it?

@plbossart no I did not. Sorry, looks like I missed the memo on that one. Could you please remind me the repo for the soundwire branch?

**Comment by plbossart** [comment]
git://git.kernel.org/pub/scm/linux/kernel/git/vkoul/soundwire.git

see scripts I forwarded to your email

**Comment by ranj063** [comment]
> git://git.kernel.org/pub/scm/linux/kernel/git/vkoul/soundwire.git
> 
> see scripts I forwarded to your email

Thanks @plbossart.
Looks like I only missed the soundwire/next merge. I'll try your scripts now. Let me close this one and submit a new one.

**Pull request closed without merging**
