### PR TITLE
ASoC: SOF: Intel: hda-loader: Revert using the simplified IMR boot se…

### PR DESCRIPTION
**Pull request by ujfalusi**
…quence

It looks like that the full boot sequence causes random IMR failures on
different boards and they all hint that the ROM_CONTROL message somehow
confuses the booted firmware and hardware in case of IMR booting.

Signed-off-by: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>

### CODE REVIEW

**Comment by ujfalusi** [comment]
Replaces  #3622

**Comment by ujfalusi** [comment]
With this change now APL (UP2) no longer able to do IMR boot:
```
[ 5682.038183] sof-audio-pci-intel-apl 0000:00:0e.0: IMR restore supported, booting from IMR directly
[ 5682.038193] sof-audio-pci-intel-apl 0000:00:0e.0: DSP core(s) enabled? 0 : core_mask 1
[ 5682.038208] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x4]=0x1010303 successful
[ 5682.038223] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x4]=0x1010302 successful
[ 5682.038233] sof-audio-pci-intel-apl 0000:00:0e.0: unstall/run core: core_mask = 1
[ 5682.038243] sof-audio-pci-intel-apl 0000:00:0e.0: DSP core(s) enabled? 1 : core_mask 1
[ 5682.188560] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x80000]=0x80000000 timedout
[ 5682.188585] sof-audio-pci-intel-apl 0000:00:0e.0: IMR restore failed, trying to cold boot
[ 5682.188950] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x160]=0x40000 successful
[ 5682.189004] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x160]=0x40000 successful
[ 5682.189017] sof-audio-pci-intel-apl 0000:00:0e.0: hda_dsp_stream_setup_bdl: period_bytes:0x0
[ 5682.189027] sof-audio-pci-intel-apl 0000:00:0e.0: hda_dsp_stream_setup_bdl: periods:1
[ 5682.189321] sof-audio-pci-intel-apl 0000:00:0e.0: Attempting iteration 0 of Core En/ROM load...
[ 5682.189338] sof-audio-pci-intel-apl 0000:00:0e.0: DSP core(s) enabled? 0 : core_mask 3
[ 5682.189354] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x4]=0x3030202 successful
[ 5682.189368] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x4]=0x3030200 successful
[ 5682.189378] sof-audio-pci-intel-apl 0000:00:0e.0: unstall/run core: core_mask = 3
[ 5682.189388] sof-audio-pci-intel-apl 0000:00:0e.0: DSP core(s) enabled? 1 : core_mask 3
[ 5682.189404] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x4]=0x3030000 successful
[ 5682.189415] sof-audio-pci-intel-apl 0000:00:0e.0: unstall/run core: core_mask = 1
[ 5682.189424] sof-audio-pci-intel-apl 0000:00:0e.0: DSP core(s) enabled? 1 : core_mask 1
[ 5682.689722] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x4c]=0x0 timedout
[ 5682.689826] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x4]=0x3030303 successful
[ 5682.689842] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x4]=0x303 successful
[ 5682.689852] sof-audio-pci-intel-apl 0000:00:0e.0: DSP core(s) enabled? 0 : core_mask 3
[ 5682.689998] sof-audio-pci-intel-apl 0000:00:0e.0: Attempting iteration 1 of Core En/ROM load...
[ 5682.690014] sof-audio-pci-intel-apl 0000:00:0e.0: DSP core(s) enabled? 0 : core_mask 3
[ 5682.690030] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x4]=0x3030303 successful
[ 5682.690045] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x4]=0x3030300 successful
[ 5682.690078] sof-audio-pci-intel-apl 0000:00:0e.0: unstall/run core: core_mask = 3
[ 5682.690087] sof-audio-pci-intel-apl 0000:00:0e.0: DSP core(s) enabled? 1 : core_mask 3
[ 5682.690106] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x4]=0x3030000 successful
[ 5682.690116] sof-audio-pci-intel-apl 0000:00:0e.0: unstall/run core: core_mask = 1
[ 5682.690126] sof-audio-pci-intel-apl 0000:00:0e.0: DSP core(s) enabled? 1 : core_mask 1
[ 5682.690751] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x4c]=0x40000000 successful
[ 5682.690776] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x4]=0x3030202 successful
[ 5682.690790] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x4]=0x1010202 successful
[ 5682.690800] sof-audio-pci-intel-apl 0000:00:0e.0: DSP core(s) enabled? 0 : core_mask 2
[ 5682.706958] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x80000]=0x5000001 successful
[ 5682.725972] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x80000]=0x5 successful
[ 5682.726003] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x160]=0x140000 successful
[ 5682.726015] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware download successful, booting...
[ 5682.728517] sof-audio-pci-intel-apl 0000:00:0e.0: ipc rx      : 0x1b080000|0x0: GLB_NOTIFICATION|FW_READY
[ 5682.728544] sof-audio-pci-intel-apl 0000:00:0e.0: fw_state change: 2 -> 5
[ 5682.728567] sof-audio-pci-intel-apl 0000:00:0e.0: ipc rx done : 0x1b080000|0x0: GLB_NOTIFICATION|FW_READY
[ 5682.728709] sof-audio-pci-intel-apl 0000:00:0e.0: Debug PCIR: 00000000 at  00000048
[ 5682.728738] sof-audio-pci-intel-apl 0000:00:0e.0: Debug PCIW: 00000002 at  00000048
[ 5682.728756] sof-audio-pci-intel-apl 0000:00:0e.0: Debug PCIR: 00000004 at  00000044
[ 5682.728767] sof-audio-pci-intel-apl 0000:00:0e.0: Debug PCIW: 00000000 at  00000044
[ 5682.728776] sof-audio-pci-intel-apl 0000:00:0e.0: firmware boot complete
[ 5682.728784] sof-audio-pci-intel-apl 0000:00:0e.0: fw_state change: 5 -> 6
```
Reverting this patch makes UP2 IMR boot work fine:
```
[ 5812.583163] sof-audio-pci-intel-apl 0000:00:0e.0: IMR restore supported, booting from IMR directly
[ 5812.583173] sof-audio-pci-intel-apl 0000:00:0e.0: DSP core(s) enabled? 0 : core_mask 3
[ 5812.583224] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x4]=0x3030303 successful
[ 5812.583241] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x4]=0x3030300 successful
[ 5812.583252] sof-audio-pci-intel-apl 0000:00:0e.0: unstall/run core: core_mask = 3
[ 5812.583261] sof-audio-pci-intel-apl 0000:00:0e.0: DSP core(s) enabled? 1 : core_mask 3
[ 5812.583280] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x4]=0x3030000 successful
[ 5812.583290] sof-audio-pci-intel-apl 0000:00:0e.0: unstall/run core: core_mask = 1
[ 5812.583299] sof-audio-pci-intel-apl 0000:00:0e.0: DSP core(s) enabled? 1 : core_mask 1
[ 5812.583932] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x4c]=0x40000000 successful
[ 5812.583957] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x4]=0x3030202 successful
[ 5812.583969] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x4]=0x1010202 successful
[ 5812.583979] sof-audio-pci-intel-apl 0000:00:0e.0: DSP core(s) enabled? 0 : core_mask 2
[ 5812.583993] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x80000]=0x5 successful
[ 5812.585583] sof-audio-pci-intel-apl 0000:00:0e.0: ipc rx      : 0x1b080000|0x0: GLB_NOTIFICATION|FW_READY
[ 5812.585608] sof-audio-pci-intel-apl 0000:00:0e.0: fw_state change: 2 -> 5
[ 5812.585629] sof-audio-pci-intel-apl 0000:00:0e.0: ipc rx done : 0x1b080000|0x0: GLB_NOTIFICATION|FW_READY
[ 5812.585740] sof-audio-pci-intel-apl 0000:00:0e.0: Debug PCIR: 00000000 at  00000048
[ 5812.585763] sof-audio-pci-intel-apl 0000:00:0e.0: Debug PCIW: 00000002 at  00000048
[ 5812.585780] sof-audio-pci-intel-apl 0000:00:0e.0: Debug PCIR: 00000004 at  00000044
[ 5812.585791] sof-audio-pci-intel-apl 0000:00:0e.0: Debug PCIW: 00000000 at  00000044
[ 5812.585819] sof-audio-pci-intel-apl 0000:00:0e.0: firmware boot complete
[ 5812.585827] sof-audio-pci-intel-apl 0000:00:0e.0: fw_state change: 5 -> 6
```

**Comment by plbossart** [comment]
> Reverting this patch makes UP2 IMR boot work fine:

Too many changes for me to follow

a) APL/UP2 is not enabled for IMR for now, this requires a dedicated firmware change
b) if we use the simplified boot sequence, then APL/UP2 works with IMR enabled in a)
c) but if we revert the simplified boot sequence, then APL/UP2 no longer works, so a) cannot happen?

????

**Comment by ujfalusi** [comment]
@plbossart, with closed source firmware and SOF with https://github.com/thesofproject/sof/pull/5765 the IMR boot works on APL in sof-dev
with this PR however it breaks completely.

We enable IMR boot unconditionally if IPC4 is used which is no longer valid with this PR (APL will brwak).
Without this patch on the other hand we have random failures on other platforms, likely caused by the ROM_CONTROL message (likely needed for APL).

Hrm, I think the correct sequence is somewhere in between the simplified and the full sequence or we should have different ones depending on CAVS versions.

Hard to say without a way to locally reproduce the random failure to debug it efficiently.

**Comment by ujfalusi** [comment]
PR #3649 looks promising among all platforms so far.

**Pull request closed without merging**
