### PR TITLE
Merge/sound upstream 20220725

### PR DESCRIPTION
**Pull request by plbossart**
one more week with 5.19-rcX

### CODE REVIEW

**Comment by plbossart** [comment]
NVME error in https://sof-ci.01.org/linuxpr/PR3785/build446/devicetest/?model=TGLU_UP_HDA&testcase=check-suspend-resume-with-playback-5, let's redo the tests

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
results are available in https://sof-ci.01.org/linuxpr/PR3785/build447/devicetest/ but GitHub still shows 'Pending - On-device testing'? @greg-intel can you please check if we have any known sync issues between jenkins and GitHub? Writing this at 17:02 PDT.

**Comment by plbossart** [comment]
https://sof-ci.01.org/linuxpr/PR3785/build447/devicetest/ all good.

**Review by bardliao — APPROVED** [review]

**Pull request merged**
