### PR TITLE
Merge/sound upstream 20210927

### PR DESCRIPTION
**Pull request by ujfalusi**
Sync up with upstream on this nice autumn day.

### CODE REVIEW

**Comment by ujfalusi** [comment]
The sparse failure is from upstream patch:
e224ef76fa8aa ("ASoC: intel: sof_rt5682: support jsl_rt5682s_mx98360a board")

**Comment by ujfalusi** [comment]
> The sparse failure is from upstream patch:
> [e224ef7](https://github.com/thesofproject/linux/commit/e224ef76fa8aa2410731f0df13c93dffa443a970) ("ASoC: intel: sof_rt5682: support jsl_rt5682s_mx98360a board")

@brentlu, @plbossart, can you propose a fix for this?

include/linux/mod_devicetable.h:
```c
#define PLATFORM_NAME_SIZE	20
#define PLATFORM_MODULE_PREFIX	"platform:"

struct platform_device_id {
	char name[PLATFORM_NAME_SIZE];
	kernel_ulong_t driver_data;
};
```
`jsl_rt5682s_mx98360a` is 20 characters, the file already have `jsl_rt5682_mx98360a` so dropping the `s` is not going to work..

**Comment by brentlu** [comment]
There are four variants MAX98360A/B/C/D . The difference between variants is the DAI format supported and they are all the same to codec driver. I propose removing the last character which does not have meaning to machine driver.

jsl_rt5682_mx98360a -> jsl_rt5682_mx98360

**Comment by ujfalusi** [comment]
> There are four variants MAX98360A/B/C/D . The difference between variants is the DAI format supported and they are all the same to codec driver. I propose removing the last character which does not have meaning to machine driver.
> 
> jsl_rt5682_mx98360a -> jsl_rt5682_mx98360

Can you send it to upstream (please CC me)? I will pick from the list and add to this branch, thank you.

**Comment by brentlu** [comment]
> > There are four variants MAX98360A/B/C/D . The difference between variants is the DAI format supported and they are all the same to codec driver. I propose removing the last character which does not have meaning to machine driver.
> > jsl_rt5682_mx98360a -> jsl_rt5682_mx98360
> 
> Can you send it to upstream (please CC me)? I will pick from the list and add to this branch, thank you.

done.

https://patchwork.kernel.org/project/alsa-devel/patch/20210927143249.439129-1-brent.lu@intel.com/

**Review by kv2019i — DISMISSED** [review]
gave this a local spin on a JSL HDA device and all good.

**Comment by ujfalusi** [comment]
@kv2019i, thanks for the testing!

Changes since v1:
- picked https://patchwork.kernel.org/project/alsa-devel/patch/20210927143249.439129-1-brent.lu@intel.com/ from upstream

**Comment by aiChaoSONG** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
@ujfalusi @kv2019i @ranj063 @bardliao looks like the nocodec mode is broken with this PR, see https://sof-ci.01.org/linuxpr/PR3177/build6440/devicetest/? I don't see any issues with the daily tests using the same firmware (3e260cc8).

**Comment by plbossart** [comment]
I can reproduce a hw_params issue with this PR on UpExtreme:
````
TPLG=/lib/firmware/intel/sof-tplg/sof-cnl-nocodec.tplg ~/sof-test/test-case/multiple-pause-resume.sh -l 3 -r 5
````

````
[  124.366400]  Port0 Deep Buffer: ASoC: no backend DAIs enabled for Port0 Deep Buffer
[  124.366406]  Port0 Deep Buffer: ASoC: dpcm_fe_dai_prepare() failed (-22)
````
Meh.

**Comment by plbossart** [comment]
possible root cause:
0c25db3f7621 ASoC: soc-pcm: Don't reconnect an already active BE

**Comment by plbossart** [comment]
> possible root cause: [0c25db3](https://github.com/thesofproject/linux/commit/0c25db3f7621ce39e959e95b8fea240ea2bfff6a) ASoC: soc-pcm: Don't reconnect an already active BE

Confirmed regression due to this commit, sending feedback upstream

**Comment by ujfalusi** [comment]
Changes since v2:
-  reverted 0c25db3 ASoC: soc-pcm: Don't reconnect an already active BE

**Review by plbossart — APPROVED** [review]

**Review by kv2019i — APPROVED** [review]
I guess main question is whether we revert the one ASoC patch or wait until issue is solved in Mark's tree (full revert or a fixup). Given some discussion is still ongoing, maybe we can go forward with the revert for sof-dev.

**Comment by plbossart** [comment]
I'll merge so that this PR is part of the daily tests starting in 50mn.

**Pull request merged**
