### PR TITLE
Pr4838 debug

### PR DESCRIPTION
**Pull request by plbossart**

### CODE REVIEW

**Comment by plbossart** [comment]
@bardliao would you happen to remember why we do this pm_runtime_disable() ?

````c
static int sdw_intel_cleanup(struct sdw_intel_ctx *ctx)
{
	struct sdw_intel_link_dev *ldev;
	u32 link_mask;
	int i;

	link_mask = ctx->link_mask;

	for (i = 0; i < ctx->count; i++) {
		if (!(link_mask & BIT(i)))
			continue;

		ldev = ctx->ldev[i];

		pm_runtime_disable(&ldev->auxdev.dev);
		if (!ldev->link_res.clock_stop_quirks)
			pm_runtime_put_noidle(ldev->link_res.dev);

		intel_link_dev_unregister(ldev);
	}

	return 0;
}
````

This is potentially problematic... I think the intent was to prevent the device from suspending, but it could very well be suspended already, in which case pm_runtime_disable() could prevent the full resume that can happen if there is an interrupt.

This looks as old as the platform device stuff, but I can't figure out why it was ever needed.

**Comment by bardliao** [comment]
> @bardliao would you happen to remember why we do this pm_runtime_disable() ?
> 
> ```c
> static int sdw_intel_cleanup(struct sdw_intel_ctx *ctx)
> {
> 	struct sdw_intel_link_dev *ldev;
> 	u32 link_mask;
> 	int i;
> 
> 	link_mask = ctx->link_mask;
> 
> 	for (i = 0; i < ctx->count; i++) {
> 		if (!(link_mask & BIT(i)))
> 			continue;
> 
> 		ldev = ctx->ldev[i];
> 
> 		pm_runtime_disable(&ldev->auxdev.dev);
> 		if (!ldev->link_res.clock_stop_quirks)
> 			pm_runtime_put_noidle(ldev->link_res.dev);
> 
> 		intel_link_dev_unregister(ldev);
> 	}
> 
> 	return 0;
> }
> ```
> 
> This is potentially problematic... I think the intent was to prevent the device from suspending, but it could very well be suspended already, in which case pm_runtime_disable() could prevent the full resume that can happen if there is an interrupt.
> 
> This looks as old as the platform device stuff, but I can't figure out why it was ever needed.

Hmm, I can't remember why we did this. But we do the same in sdw_master_device_del() and sdw_delete_slave()

**Comment by plbossart** [comment]
> Hmm, I can't remember why we did this. But we do the same in sdw_master_device_del() and sdw_delete_slave()

The last cases are different. You want to prevent suspend in the remove case. It's all happening in the context of the same device. But the lines above disable pm_runtime() for child devices. This is a layering violation and potentially dangerous because the child device cannot resume any longer...

**Comment by plbossart** [comment]
wow, all tests completed without errors !

https://sof-ci.01.org/linuxpr/PR4845/build1682/devicetest/index.html
https://sof-ci.01.org/linuxpr/PR4845/build1683/devicetest/index.html
https://sof-ci.01.org/linuxpr/PR4845/build1684/devicetest/index.html

I will trigger a new check @bardliao @marc-hb ...

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
ok, we're back to one timeout in suspend-resume but looks good otherwise. Phew.

**Comment by plbossart** [comment]
simpler version suggested in https://github.com/thesofproject/linux/pull/4849

**Comment by bardliao** [comment]
> ok, we're back to one timeout in suspend-resume but looks good otherwise. Phew.

Do you mean https://sof-ci.01.org/linuxpr/PR4849/build1698/devicetest/index.html? I can't reproduce the failure when I tested `TPLG=/lib/firmware/intel/development/sof-mtl-nocodec.tplg MODEL=MTLP_RVP_NOCODEC SOF_TEST_INTERVAL=5 ~/sof-test/test-case/check-pause-resume.sh -c 100 -m capture` on the same device.

**Pull request closed without merging**
