### PR TITLE
[TEST] ASoC: rt711: add traces to understand timeout in jack detect h…

### PR DESCRIPTION
**Pull request by plbossart**
…andler

For some reason this happens only on TGL_RVP_SDW?

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

### CODE REVIEW

**Comment by marc-hb** [comment]
Just spotted this time out in suspend/resume, is it related?

https://sof-ci.01.org/softestpr/PR873/build1001/devicetest/?model=TGLU_RVP_SDW&testcase=check-suspend-resume-with-playback-5

```
[ 1353.269425] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x4]=0xf0f successful
[ 1353.269451] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[ 1353.269597] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Debug PCIR: 00000010 at  00000044
[ 1353.269627] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Turning i915 HDAC power 0
[ 1353.269633] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Current DSP power state: D3
[ 1353.269638] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: fw_state change: 6 -> 0
[ 1353.271125] kernel: e1000e: EEE TX LPI TIMER: 00000011
[ 1353.729572] kernel: ACPI: EC: interrupt blocked
[ 1358.139932] kernel: ACPI: EC: interrupt unblocked
[ 1358.258534] kernel: soundwire_intel soundwire_intel.link.0: IO transfer timed out, cmd 3 device 1 addr b921 len 1
[ 1358.258541] kernel: soundwire sdw-master-0: trf on Slave 1 failed:-110 write addr b921 count 0
[ 1358.258615] kernel: IO error in rt711_jack_detect_handler, ret -110
[ 1358.631699] kernel: serial 00:03: activated
[ 1358.695017] kernel: nvme nvme0: 8/0/0 default/read/poll queues
[ 1358.858400] kernel: atkbd serio0: Failed to deactivate keyboard on isa0060/serio0
[ 1359.000347] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Turning i915 HDAC power 1
[ 1359.003924] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Debug PCIR: 00000000 at  00000044
[ 1359.006898] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Debug PCIR: 00000040 at  00000048
```

Also https://sof-ci.01.org/sofpr/PR5451/build12209/devicetest/?model=TGLU_RVP_SDW&testcase=check-suspend-resume-with-playback-5

**Comment by plbossart** [comment]
The dmesg log is very interesting @bardliao @RanderWang @shumingfan , it seems that we read the jack status after the DSP goes to D3 and way after the links are powered off. So there's something wrong with the work queues with a path where we don't do a cancel_sync

[dmesg.log](https://github.com/thesofproject/linux/files/8173538/dmesg.log)

**Comment by plbossart** [comment]
> Just spotted this time out in suspend/resume, is it related?
> 
> https://sof-ci.01.org/softestpr/PR873/build1001/devicetest/?model=TGLU_RVP_SDW&testcase=check-suspend-resume-with-playback-5
> 
> ```
> [ 1353.269425] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x4]=0xf0f successful
> [ 1353.269451] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
> [ 1353.269597] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Debug PCIR: 00000010 at  00000044
> [ 1353.269627] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Turning i915 HDAC power 0
> [ 1353.269633] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Current DSP power state: D3
> [ 1353.269638] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: fw_state change: 6 -> 0
> [ 1353.271125] kernel: e1000e: EEE TX LPI TIMER: 00000011
> [ 1353.729572] kernel: ACPI: EC: interrupt blocked
> [ 1358.139932] kernel: ACPI: EC: interrupt unblocked
> [ 1358.258534] kernel: soundwire_intel soundwire_intel.link.0: IO transfer timed out, cmd 3 device 1 addr b921 len 1
> [ 1358.258541] kernel: soundwire sdw-master-0: trf on Slave 1 failed:-110 write addr b921 count 0
> [ 1358.258615] kernel: IO error in rt711_jack_detect_handler, ret -110
> [ 1358.631699] kernel: serial 00:03: activated
> [ 1358.695017] kernel: nvme nvme0: 8/0/0 default/read/poll queues
> [ 1358.858400] kernel: atkbd serio0: Failed to deactivate keyboard on isa0060/serio0
> [ 1359.000347] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Turning i915 HDAC power 1
> [ 1359.003924] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Debug PCIR: 00000000 at  00000044
> [ 1359.006898] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Debug PCIR: 00000040 at  00000048
> ```

yes indeed, it;s the same issue that we have a transaction that can happen after the links are powered off during suspend.

The codec device should suspend first, then the parent DSP device. The fact that there is a jack detect workqueue still operational tells me we didn't suspend the codec properly.

**Comment by plbossart** [comment]
Traces show there are two places where we schedule the workqueue, adding traces to see if we missed something in the suspend flows.

**Comment by plbossart** [comment]
https://sof-ci.01.org/linuxpr/PR3469/build7258/devicetest/ shows 'no data' in Chinese again @XiaoyunWu6666 @keqiaozhang @mengdonglin

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
ok, so the race condition happens when the peripheral device is already suspended, and we resume the link to full power. That will cause the io_init() to schedule a work queue, but we turn everything off before that happens.

The root cause is that we only use pm_runtime_get_noresume() which will prevent suspend while we are initializing, but we are missing the handling of the case where the device is already suspended.

[dmesg.log](https://github.com/thesofproject/linux/files/8200854/dmesg.log)

**Comment by plbossart** [comment]
The tests seems to indicate that rt711_jack_init() is called from rt711_set_jack_detect(). This is a callback that will be invoked at the card level IIRC, that is probably the reason why this doesn't work with our logic to cancel the workqueues at the peripheral device level.

**Comment by plbossart** [comment]
Nope, this is really a problem with the suspend routines not being called. It's likely that the approach taken a while ago does not work and we need a full-blown .prepare in the codecs

[dmesg.log](https://github.com/thesofproject/linux/files/8209964/dmesg.log)

**Comment by plbossart** [comment]
back to square one: the problem seems to be that the RT711 is already suspended, and for some reason the Manager device is resumed, which results in the hardware codec attaching, and the io_init() function calling rt711_jack_init() which schedules a workqueue that cannot be cancelled.

[dmesg.log](https://github.com/thesofproject/linux/files/8210725/dmesg.log)

**Comment by plbossart** [comment]
@bardliao @shumingfan it seems that we have a spurious pm_runtime resume that causes a bus restart.
I added a check to prevent the jack detection if the bus is stopped, but that's a bit of a hack. I am not sure what causes this extra resume, we'd need to bisect to see what happened.

[dmesg.log](https://github.com/thesofproject/linux/files/8210957/dmesg.log)

**Comment by bardliao** [comment]
@plbossart I will try to reproduce this issue on my side.

**Comment by bardliao** [comment]
I still can't reproduce this issue on my SKU 0A3E laptop. I tried `check-suspend-resume-with-audio.sh -l 5 -m capture` `check-suspend-resume-with-audio.sh -l 5 -m playback` and `run-all-tests.sh`. All of them are passed.

**Comment by shumingfan** [comment]
Is it possible that soundwire-intel driver resumes by pm_runtime_resume in the intel_pm_prepare?
I'm not sure about this.

And what's the condition to wake up the soundwire-intel driver?
Does the bus controller get the interrupt or something? We could check that in the intel_resume_runtime.

**Comment by plbossart** [comment]
@shumingfan @bardliao the added traces show we don't do anything in intel_pm_prepare() which is normal. This .prepare step is only needed when both the controller and the parent device (HDaudio controller) are suspended.

So the question is why we do a resume only on the intel side.
[dmesg.log](https://github.com/thesofproject/linux/files/8216922/dmesg.log)

**Comment by plbossart** [comment]
the traces show the dai startup is not called, so something else is at play

[dmesg.log](https://github.com/thesofproject/linux/files/8217720/dmesg.log)

**Comment by plbossart** [comment]
classic race condition: the bug disappears after adding traces https://sof-ci.01.org/linuxpr/PR3469/build7319/devicetest/
Gah.

**Comment by marc-hb** [comment]
To reproduce a race condition, I found that nothing beats a well-placed "sleep" delay. Making the race worse allows adding logs. Of course "well-placed" means you have know where the race is in the first place; it's not a silver bullet :-)

**Comment by plbossart** [comment]
This is getting even weirder. Not only do we resume link0 only, but there are a set of wake events reported.

[dmesg.log](https://github.com/thesofproject/linux/files/8219230/dmesg.log)

**Comment by plbossart** [comment]
closing, solutions suggested in PR #3514 and PR #3518

**Pull request closed without merging**
