### PR TITLE
Merge/sound upstream 20220707

### PR DESCRIPTION
**Pull request by plbossart**

### CODE REVIEW

**Comment by plbossart** [comment]
Wow, we've got major boot issues reported in https://sof-ci.01.org/linuxpr/PR3742/build342/devicetest/ 

@ujfalusi any idea if the git merge went sideways?

**Comment by plbossart** [comment]
Failures confirmed in https://sof-ci.01.org/linuxpr/PR3742/build343/devicetest/.

**Comment by marc-hb** [comment]
Successfully bisected Zephyr, testing a revert now

**Comment by marc-hb** [comment]
Zephyr revert successfully tested https://github.com/zephyrproject-rtos/zephyr/pull/47524

**Comment by ujfalusi** [comment]
@plbossart, @marc-hb, I think we are seeing different failures.
https://sof-ci.01.org/linuxpr/PR3742/build342/devicetest/ is not zephyr related and all have:
```
[    7.929758] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump start ]------------
[    7.929759] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware download failed
[    7.929759] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: fw_state: SOF_FW_BOOT_IN_PROGRESS (2)
[    7.929762] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: 0x80000006: module: ROM, state: VERIFY_FEATURE_MASK, not running
[    7.929765] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error code: 0x14 (unknown)
[    7.929775] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: extended rom status:  0x80000006 0x14 0x0 0x0 0x0 0x0 0x25101c2 0x0
[    7.929776] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump end ]------------
[    7.929790] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump start ]------------
[    7.929791] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Failed to start DSP
[    7.929791] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: fw_state: SOF_FW_BOOT_IN_PROGRESS (2)
[    7.929795] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: 0x01009701: unknown ROM status value
[    7.929816] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: extended rom status:  0x1009701 0x1d003c 0x1 0x0 0x10000 0xc00 0x180030 0x0
[    7.929817] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump end ]------------
```
While https://sof-ci.01.org/linuxpr/PR3742/build343/devicetest/ :
```
[    6.838859] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump start ]------------
[    6.838862] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware boot failure due to timeout
[    6.838863] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: fw_state: SOF_FW_BOOT_IN_PROGRESS (2)
[    6.838878] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: 0x00000005: module: ROM, state: FW_ENTERED, running
[    6.839054] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: invalid header size 0xf010e0e. FW oops is bogus
[    6.839055] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: unexpected fault 0x00000000 trace 0x00000000
[    6.839056] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump end ]------------
```

**Comment by ujfalusi** [comment]
and we have this in the logs:
```
[    4.867612] kernel: snd_sof:snd_sof_load_firmware: sof-audio-pci-intel-tgl 0000:00:1f.3: loading firmware
[    4.869086] kernel: snd_sof:snd_sof_load_firmware_raw: sof-audio-pci-intel-tgl 0000:00:1f.3: request_firmware intel/sof/sof-tgl.ri successful
[    4.869088] kernel: snd_sof:snd_sof_load_firmware_raw: sof-audio-pci-intel-tgl 0000:00:1f.3: firmware doesn't contain extended manifest
```
```
[    5.098804] kernel: snd_sof:snd_sof_load_firmware: sof-audio-pci-intel-tgl 0000:00:1f.3: loading firmware
[    5.101342] kernel: snd_sof:snd_sof_load_firmware_raw: sof-audio-pci-intel-tgl 0000:00:1f.3: request_firmware intel/sof/sof-adl.ri successful
[    5.101344] kernel: snd_sof:snd_sof_load_firmware_raw: sof-audio-pci-intel-tgl 0000:00:1f.3: firmware doesn't contain extended manifest
```
I would be not surprised if `intel/sof/sof-tgl.ri`/`intel/sof/sof-adl.ri` is an IPC4 firmware... Might be a side effect of https://github.com/thesofproject/sof/pull/5959 which changed the default firmware name for IPC4 zephyr builds?

**Comment by marc-hb** [comment]
SOFCI TEST

EDIT: https://sof-ci.01.org/linuxpr/PR3742/build346/devicetest is **all green** now but the zephyr commit is a couple days old zephyr commit https://github.com/zephyrproject-rtos/zephyr/commits/e0b1d81acbc5, _before_ the big regression https://github.com/zephyrproject-rtos/zephyr/pull/47524

Now that Zephyr boot fix 47575 has been merged, `sof-ci` should fast forward to the latest Zephyr commit tomorrow, then we can SOFCI TEST again.

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by XiaoyunWu6666** [comment]
SOFCI TEST

**Comment by XiaoyunWu6666** [comment]
The last PR test for this PR looks good https://sof-ci.01.org/linuxpr/PR3742/build346/devicetest/
Maybe we can look at https://sof-ci.01.org/linuxpr/PR3742/build349/devicetest/ for double confirm result.

**Comment by marc-hb** [comment]
There will be a significant Zephyr version difference, see previous comments.

**Comment by marc-hb** [comment]
https://sof-ci.01.org/linuxpr/PR3742/build349/devicetest/ has suspend/resume failures which is usual. Everything else is green.

From https://sof-ci.01.org/linuxpr/PR3742/build349/devicetest/?model=TGLU_UP_HDA_ZEPHYR&testcase=check-sof-logger (and others) we see `zephyr:b161554ee862`

**Comment by plbossart** [comment]
Let's run the tests again, not sure about those timeouts in https://sof-ci.01.org/linuxpr/PR3742/build349/devicetest/

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
> Let's run the tests again, not sure about those timeouts in https://sof-ci.01.org/linuxpr/PR3742/build349/devicetest/

I looked at one of them. NetworkManager did not reconnect even after the Ethernet came back up.

In other examples Ethernet does not come back up.

Testing suspend/resume is hard; being discussed in internal issues 272, 239 and others.


https://sof-ci.01.org/linuxpr/PR3742/build349/devicetest/?model=TGLU_UP_HDA_ZEPHYR&testcase=check-suspend-resume-with-playback-5
```
journalctl -b -11 -g 'freezing|network.?manager|asix|nm_'

Jul 11 06:51:46 sh-tglu-rvp-hda-zephyr-01 NetworkManager[348]: <info>  [1657522306.5721] manager: NetworkManager state is now CONNECTED_LOCAL
Jul 11 06:51:46 sh-tglu-rvp-hda-zephyr-01 NetworkManager[348]: <info>  [1657522306.5732] manager: NetworkManager state is now DISCONNECTED
Jul 11 06:51:47 sh-tglu-rvp-hda-zephyr-01 kernel: asix 3-4.1:1.0 enx000ec6b72c16: Link is Up - 100Mbps/Full - flow control off
Jul 11 06:51:47 sh-tglu-rvp-hda-zephyr-01 NetworkManager[348]: <info>  [1657522307.6922] manager: NetworkManager state is now CONNECTING
Jul 11 06:51:48 sh-tglu-rvp-hda-zephyr-01 kernel: asix 3-4.1:1.0 enx000ec6b72c16: Link is Down
Jul 11 06:51:59 sh-tglu-rvp-hda-zephyr-01 kernel: Freezing user space processes ... (elapsed 0.002 seconds) done.
Jul 11 06:51:59 sh-tglu-rvp-hda-zephyr-01 kernel: Freezing remaining freezable tasks ... (elapsed 0.001 seconds) done.
Jul 11 06:51:59 sh-tglu-rvp-hda-zephyr-01 kernel: asix 3-4.1:1.0 enx000ec6b72c16: Link is Down
Jul 11 06:52:01 sh-tglu-rvp-hda-zephyr-01 NetworkManager[348]: <info>  [1657522321.8485] manager: NetworkManager state is now DISCONNECTED
Jul 11 06:52:03 sh-tglu-rvp-hda-zephyr-01 systemd[1]: NetworkManager-dispatcher.service: Succeeded.
Jul 11 06:52:13 sh-tglu-rvp-hda-zephyr-01 kernel: Freezing user space processes ... (elapsed 0.002 seconds) done.
Jul 11 06:52:13 sh-tglu-rvp-hda-zephyr-01 kernel: Freezing remaining freezable tasks ... (elapsed 0.000 seconds) done.
Jul 11 06:52:13 sh-tglu-rvp-hda-zephyr-01 kernel: asix 3-4.1:1.0 enx000ec6b72c16: Link is Down
Jul 11 06:52:15 sh-tglu-rvp-hda-zephyr-01 kernel: asix 3-4.1:1.0 enx000ec6b72c16: Link is Up - 100Mbps/Full - flow control off
Jul 11 06:52:15 sh-tglu-rvp-hda-zephyr-01 NetworkManager[348]: <info>  [1657522335.5660] manager: NetworkManager state is now CONNECTING
Jul 11 06:52:17 sh-tglu-rvp-hda-zephyr-01 dbus-daemon[345]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service' requested by ':1.6' (uid=0 pid=348 comm="/usr/sbin/NetworkManager --no-daemon " label="kernel")
Jul 11 06:52:17 sh-tglu-rvp-hda-zephyr-01 systemd[1]: Starting Network Manager Script Dispatcher Service...
Jul 11 06:52:17 sh-tglu-rvp-hda-zephyr-01 dbus-daemon[345]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Jul 11 06:52:17 sh-tglu-rvp-hda-zephyr-01 systemd[1]: Started Network Manager Script Dispatcher Service.
Jul 11 06:52:17 sh-tglu-rvp-hda-zephyr-01 NetworkManager[348]: <info>  [1657522337.6807] manager: NetworkManager state is now CONNECTED_LOCAL
Jul 11 06:52:17 sh-tglu-rvp-hda-zephyr-01 NetworkManager[348]: <info>  [1657522337.6816] manager: NetworkManager state is now CONNECTED_SITE
Jul 11 06:52:27 sh-tglu-rvp-hda-zephyr-01 kernel: Freezing user space processes ... (elapsed 0.002 seconds) done.
Jul 11 06:52:27 sh-tglu-rvp-hda-zephyr-01 kernel: Freezing remaining freezable tasks ... (elapsed 0.000 seconds) done.
Jul 11 06:52:27 sh-tglu-rvp-hda-zephyr-01 kernel: asix 3-4.1:1.0 enx000ec6b72c16: Link is Down
Jul 11 06:52:27 sh-tglu-rvp-hda-zephyr-01 kernel: asix 3-4.1:1.0 enx000ec6b72c16: Link is Down
Jul 11 06:52:41 sh-tglu-rvp-hda-zephyr-01 kernel: Freezing user space processes ... (elapsed 0.002 seconds) done.
Jul 11 06:52:41 sh-tglu-rvp-hda-zephyr-01 kernel: Freezing remaining freezable tasks ... (elapsed 0.000 seconds) done.
Jul 11 06:52:41 sh-tglu-rvp-hda-zephyr-01 kernel: asix 3-4.1:1.0 enx000ec6b72c16: Link is Down
Jul 11 06:52:41 sh-tglu-rvp-hda-zephyr-01 NetworkManager[348]: <info>  [1657522361.5777] manager: NetworkManager state is now CONNECTED_LOCAL
Jul 11 06:52:41 sh-tglu-rvp-hda-zephyr-01 NetworkManager[348]: <info>  [1657522361.5783] manager: NetworkManager state is now DISCONNECTED
Jul 11 06:52:55 sh-tglu-rvp-hda-zephyr-01 kernel: Freezing user space processes ... (elapsed 0.002 seconds) done.
Jul 11 06:52:55 sh-tglu-rvp-hda-zephyr-01 kernel: Freezing remaining freezable tasks ... (elapsed 0.001 seconds) done.
Jul 11 06:52:55 sh-tglu-rvp-hda-zephyr-01 kernel: asix 3-4.1:1.0 enx000ec6b72c16: Link is Down
Jul 11 06:52:57 sh-tglu-rvp-hda-zephyr-01 kernel: asix 3-4.1:1.0 enx000ec6b72c16: Link is Up - 100Mbps/Full - flow control off
Jul 11 06:52:57 sh-tglu-rvp-hda-zephyr-01 NetworkManager[348]: <info>  [1657522377.5815] manager: NetworkManager state is now CONNECTING
Jul 11 06:52:57 sh-tglu-rvp-hda-zephyr-01 systemd[1]: NetworkManager-dispatcher.service: Succeeded.
Jul 11 06:52:59 sh-tglu-rvp-hda-zephyr-01 dbus-daemon[345]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service' requested by ':1.6' (uid=0 pid=348 comm="/usr/sbin/NetworkManager --no-daemon " label="kernel")
Jul 11 06:52:59 sh-tglu-rvp-hda-zephyr-01 systemd[1]: Starting Network Manager Script Dispatcher Service...
Jul 11 06:52:59 sh-tglu-rvp-hda-zephyr-01 dbus-daemon[345]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Jul 11 06:52:59 sh-tglu-rvp-hda-zephyr-01 systemd[1]: Started Network Manager Script Dispatcher Service.
Jul 11 06:52:59 sh-tglu-rvp-hda-zephyr-01 NetworkManager[348]: <info>  [1657522379.6827] manager: NetworkManager state is now CONNECTED_LOCAL
Jul 11 06:52:59 sh-tglu-rvp-hda-zephyr-01 NetworkManager[348]: <info>  [1657522379.6842] manager: NetworkManager state is now CONNECTED_SITE
Jul 11 06:53:14 sh-tglu-rvp-hda-zephyr-01 kernel: Freezing user space processes ... (elapsed 0.002 seconds) done.
Jul 11 06:53:14 sh-tglu-rvp-hda-zephyr-01 kernel: Freezing remaining freezable tasks ... (elapsed 0.001 seconds) done.
Jul 11 06:53:14 sh-tglu-rvp-hda-zephyr-01 kernel: asix 3-4.1:1.0 enx000ec6b72c16: Link is Down
Jul 11 06:53:14 sh-tglu-rvp-hda-zephyr-01 kernel: asix 3-4.1:1.0 enx000ec6b72c16: Link is Down
Jul 11 06:53:28 sh-tglu-rvp-hda-zephyr-01 kernel: Freezing user space processes ... (elapsed 0.002 seconds) done.
Jul 11 06:53:28 sh-tglu-rvp-hda-zephyr-01 kernel: Freezing remaining freezable tasks ... (elapsed 0.000 seconds) done.
Jul 11 06:53:28 sh-tglu-rvp-hda-zephyr-01 kernel: asix 3-4.1:1.0 enx000ec6b72c16: Link is Down
Jul 11 06:53:28 sh-tglu-rvp-hda-zephyr-01 NetworkManager[348]: <info>  [1657522408.5851] manager: NetworkManager state is now CONNECTED_LOCAL
Jul 11 06:53:28 sh-tglu-rvp-hda-zephyr-01 NetworkManager[348]: <info>  [1657522408.5969] manager: NetworkManager state is now DISCONNECTED
Jul 11 06:53:30 sh-tglu-rvp-hda-zephyr-01 kernel: asix 3-4.1:1.0 enx000ec6b72c16: Link is Up - 100Mbps/Full - flow control off
Jul 11 06:53:30 sh-tglu-rvp-hda-zephyr-01 NetworkManager[348]: <info>  [1657522410.6070] manager: NetworkManager state is now CONNECTING
Jul 11 06:53:32 sh-tglu-rvp-hda-zephyr-01 NetworkManager[348]: <info>  [1657522412.7044] manager: NetworkManager state is now CONNECTED_LOCAL
Jul 11 06:53:32 sh-tglu-rvp-hda-zephyr-01 NetworkManager[348]: <info>  [1657522412.7054] manager: NetworkManager state is now CONNECTED_SITE
Jul 11 06:53:43 sh-tglu-rvp-hda-zephyr-01 kernel: Freezing user space processes ... (elapsed 0.002 seconds) done.
Jul 11 06:53:43 sh-tglu-rvp-hda-zephyr-01 kernel: Freezing remaining freezable tasks ... (elapsed 0.001 seconds) done.
Jul 11 06:53:43 sh-tglu-rvp-hda-zephyr-01 kernel: asix 3-4.1:1.0 enx000ec6b72c16: Link is Down
Jul 11 06:53:43 sh-tglu-rvp-hda-zephyr-01 kernel: asix 3-4.1:1.0 enx000ec6b72c16: Link is Down
Jul 11 06:53:57 sh-tglu-rvp-hda-zephyr-01 kernel: Freezing user space processes ... (elapsed 0.002 seconds) done.
Jul 11 06:53:57 sh-tglu-rvp-hda-zephyr-01 kernel: Freezing remaining freezable tasks ... (elapsed 0.000 seconds) done.
Jul 11 06:53:57 sh-tglu-rvp-hda-zephyr-01 kernel: asix 3-4.1:1.0 enx000ec6b72c16: Link is Down
Jul 11 06:53:57 sh-tglu-rvp-hda-zephyr-01 NetworkManager[348]: <info>  [1657522437.5644] manager: NetworkManager state is now CONNECTED_LOCAL
Jul 11 06:53:57 sh-tglu-rvp-hda-zephyr-01 NetworkManager[348]: <info>  [1657522437.5673] manager: NetworkManager state is now DISCONNECTED
Jul 11 06:53:59 sh-tglu-rvp-hda-zephyr-01 kernel: asix 3-4.1:1.0 enx000ec6b72c16: Link is Up - 100Mbps/Full - flow control off
Jul 11 06:53:59 sh-tglu-rvp-hda-zephyr-01 NetworkManager[348]: <info>  [1657522439.5286] manager: NetworkManager state is now CONNECTING
Jul 11 06:54:01 sh-tglu-rvp-hda-zephyr-01 NetworkManager[348]: <info>  [1657522441.6311] manager: NetworkManager state is now CONNECTED_LOCAL
Jul 11 06:54:01 sh-tglu-rvp-hda-zephyr-01 NetworkManager[348]: <info>  [1657522441.6343] manager: NetworkManager state is now CONNECTED_SITE
Jul 11 06:54:11 sh-tglu-rvp-hda-zephyr-01 kernel: Freezing user space processes ... (elapsed 0.002 seconds) done.
Jul 11 06:54:11 sh-tglu-rvp-hda-zephyr-01 kernel: Freezing remaining freezable tasks ... (elapsed 0.000 seconds) done.
Jul 11 06:54:11 sh-tglu-rvp-hda-zephyr-01 kernel: asix 3-4.1:1.0 enx000ec6b72c16: Link is Down
Jul 11 06:54:11 sh-tglu-rvp-hda-zephyr-01 kernel: asix 3-4.1:1.0 enx000ec6b72c16: Link is Down
Jul 11 06:54:16 sh-tglu-rvp-hda-zephyr-01 kernel: asix 3-4.1:1.0 enx000ec6b72c16: Link is Up - 100Mbps/Full - flow control off
Jul 11 06:54:21 sh-tglu-rvp-hda-zephyr-01 systemd[1]: NetworkManager-dispatcher.service: Succeeded.
Jul 11 06:54:23 sh-tglu-rvp-hda-zephyr-01 NetworkManager[348]: <info>  [1657522463.6845] manager: NetworkManager state is now CONNECTED_LOCAL
Jul 11 06:54:23 sh-tglu-rvp-hda-zephyr-01 NetworkManager[348]: <info>  [1657522463.6850] manager: NetworkManager state is now DISCONNECTED
Jul 11 06:54:23 sh-tglu-rvp-hda-zephyr-01 dbus-daemon[345]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service' requested by ':1.6' (uid=0 pid=348 comm="/usr/sbin/NetworkManager --no-daemon " label="kernel")
Jul 11 06:54:23 sh-tglu-rvp-hda-zephyr-01 systemd[1]: Starting Network Manager Script Dispatcher Service...
Jul 11 06:54:23 sh-tglu-rvp-hda-zephyr-01 dbus-daemon[345]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Jul 11 06:54:23 sh-tglu-rvp-hda-zephyr-01 systemd[1]: Started Network Manager Script Dispatcher Service.
Jul 11 06:54:33 sh-tglu-rvp-hda-zephyr-01 systemd[1]: NetworkManager-dispatcher.service: Succeeded.
```

**Comment by plbossart** [comment]
https://github.com/thesofproject/linux/issues/3748 added to keep track of failure in https://sof-ci.01.org/linuxpr/PR3742/build354/devicetest/?model=CML_RVP_SDW_ZEPHYR&testcase=multiple-pause-resume-5

This is likely a firmware issue, moving on with the merge.

**Pull request merged**
