### PR TITLE
ASoC: SOF: imx: Add OF machine descriptors for i.MX platforms

### PR DESCRIPTION
**Pull request by paulstelian97**
See each commit description individually.

### CODE REVIEW

**Comment by dbaluta** [comment]
@paulstelian97 please check the feedback got from Mark when I initially sent this.

https://lkml.iu.edu/hypermail/linux/kernel/2107.1/10198.html

So lets start using the approach from MTK: sound/soc/sof/mediatek/mt8186/mt8186.c where we introduce `snd_sof_of_mach` specific for IMX.

**Comment by dbaluta** [comment]
Please also add imx8ulp.

**Comment by paulstelian97** [comment]
> Please also add imx8ulp.

Done, also added a generic name even though technically I could have used the "-btsco.tplg" file. Symlink will be needed on this platform as well.

Also, advice welcome on how we should distinguish the cs42888 from wm8960 cases (i.MX8QXP/QM/MP). I would find it weird if including a DT overlay changed the whole system identifier (is it even possible?). We definitely can stick with the symlink variant for now, but I do want some advice on how we can do better than that.

**Comment by dbaluta** [comment]
OK, great! I will send this to Mark to get some more feedback. 

Will first merge this into alsa-devel and then take it back int topic/sof-dev

**Comment by plbossart** [comment]
> OK, great! I will send this to Mark to get some more feedback.
> 
> Will first merge this into alsa-devel and then take it back int topic/sof-dev

@dbaluta if you send this directly to Mark then there's no need to push a PR for topic/sof-dev, it'll be applied when we do one of the weekly merges

**Review by btian1 — APPROVED** [review]

**Comment by dbaluta** [comment]
we need to refactor this after Mark's comments. He suggested on using audio-graph-card instead of simple-audio-card machine driver. 

discussion here: https://www.spinics.net/lists/alsa-devel/msg159387.html

**Pull request closed without merging**
