### PR TITLE
Update CODEOWNERS for AMD

### PR DESCRIPTION
**Pull request by bhiregoudar**
Remove Ajithkumar Pandey and add Vijendar Mukunda for AMD SOF stack and SoundWire stack

### CODE REVIEW

**Review by plbossart — APPROVED** [review]

**Comment by plbossart** [comment]
@bhiregoudar kind reminder to push patches in your own cloned tree. there is no reason to add a sof/bhiregoudar-patch-1 branch

**Comment by bhiregoudar** [comment]
> bhiregoudar-patch-

Thanks, 

Should we create a new PR for this or we just need to take care of this going forward?

**Comment by plbossart** [comment]
I merged and deleted the branch, just remember to use your own tree next time @bhiregoudar

**Comment by bhiregoudar** [comment]
> I merged and deleted the branch, just remember to use your own tree next time @bhiregoudar

Got it thanks

**Pull request merged**
