### PR TITLE
SoundWire: Cirrus Logic fixes for multiple devices

### PR DESCRIPTION
**Pull request by plbossart**
revert Intel changes and apply the fixes from Cirrus Logic.

https://lore.kernel.org/alsa-devel/20220825122241.273090-1-rf@opensource.cirrus.com/T/#t

### CODE REVIEW

**Comment by plbossart** [comment]
yay build stuck... any idea what's going on @keqiaozhang @fredoh9 @greg-intel ?

**Comment by plbossart** [comment]
SOFCI TEST

**Review by bardliao — APPROVED** [review]

**Review by RanderWang — APPROVED** [review]
Add to my favorite list although I can't 100% get it.

**Comment by plbossart** [comment]
We don't want to merge this as is. the code has already changed upstream. I'll re-add it when the code is merged,

**Pull request closed without merging**
