### PR TITLE
Fix no hdmi support for machine drviers

### PR DESCRIPTION
**Pull request by xiulipan**
There ifdef in machine drvier bxt_pcm512x and tgl_rt1308 to enable HDMI support or not.

Fix the Kconfig to make the support working with no hdmi mode.

### CODE REVIEW

**Comment by ranj063** [comment]
@plbossart @xiulipan for the sof_rt5682 machine driver, we seem to check is SOF_HDA_COMMON is selected. Is that incorrect?

**Comment by plbossart** [comment]
> @plbossart @xiulipan for the sof_rt5682 machine driver, we seem to check is SOF_HDA_COMMON is selected. Is that incorrect?

Nice catch @ranj063 

we should also use
select SND_SOC_HDAC_HDMI if SND_SOC_SOF_HDA_LINK
for sof_rt5682.

Currently we select HDAC_HDMI even on Baytrail only, and we would also select HDAC_HDMI even if the link was not selected. HDA_COMMON is just a shortcut for 'cAVS platforms', it doesn't describe HDMI or HDaudio codec support.

@xiulipan can you also add a fix for this machine driver?

**Comment by xiulipan** [comment]
@plbossart @ranj063 
Let me check on the machine drivers, now we only have selection for the HMDI support with
`#if IS_ENABLED(CONFIG_SND_SOC_HDAC_HDMI)` on bxt_pcm512x.c and tgl_rt1308.c

For sof_rt5682.c I am seeing another solution with run-time dai-link create by platform. I think we should first add some if def in machine driver before we add kconfig change to sof-rt5682.c.
Otherwise, sof_rt5682 will probe fail on APL+ ('cAVS platforms') paltform if we do not select HDA_LINK as it default enables HDMI on these platforms. And I think now the kconfig for rt5682 is right to check this. As it only support HDMI for these cavs paltforms.

BTW, could we merge this first for the TGL test without HDMI support? If we would also like to have some selection for HDMI on sof_rt5682 machine driver, I will do some test on the WHL-I2S device with RT5682 and maybe we also need some more tplg file.

**Comment by plbossart** [comment]
> @plbossart @ranj063
> Let me check on the machine drivers, now we only have selection for the HMDI support with
> `#if IS_ENABLED(CONFIG_SND_SOC_HDAC_HDMI)` on bxt_pcm512x.c and tgl_rt1308.c
> 
> For sof_rt5682.c I am seeing another solution with run-time dai-link create by platform. I think we should first add some if def in machine driver before we add kconfig change to sof-rt5682.c.
> Otherwise, sof_rt5682 will probe fail on APL+ ('cAVS platforms') paltform if we do not select HDA_LINK as it default enables HDMI on these platforms. And I think now the kconfig for rt5682 is right to check this. As it only support HDMI for these cavs paltforms.
> 
> BTW, could we merge this first for the TGL test without HDMI support? If we would also like to have some selection for HDMI on sof_rt5682 machine driver, I will do some test on the WHL-I2S device with RT5682 and maybe we also need some more tplg file.

I am going to engage the parking brake here. It's too complicated for us to maintain multiple versions of TGL, so we need information on what the recommended ones are. E.g. does anyone care about the ALC1308 in I2S mode?

**Comment by ranj063** [comment]
> I am going to engage the parking brake here. It's too complicated for us to maintain multiple versions of TGL, so we need information on what the recommended ones are. E.g. does anyone care about the ALC1308 in I2S mode?

@sathya-nujella would you know?

**Comment by ranj063** [comment]
> BTW, could we merge this first for the TGL test without HDMI support? If we would also like to have some selection for HDMI on sof_rt5682 machine driver, I will do some test on the WHL-I2S device with RT5682 and maybe we also need some more tplg file.

@xiulipan this is a bit flawed. Basically if any other machine driver is selected say for example the GLK_DA7219_MAX08*, then SND_SOC_HDAC_HDMI gets selected. It will only work if the TGL_RT1308 is the only machine driver selected

**Comment by sathya-nujella** [comment]
> > I am going to engage the parking brake here. It's too complicated for us to maintain multiple versions of TGL, so we need information on what the recommended ones are. E.g. does anyone care about the ALC1308 in I2S mode?
> 
> @sathya-nujella would you know?

We need I2S support in TGL too. One way to prove I2S is to enable ALC1308. 
IMHO, I see the possiblities like:
1. ALC1308 I2S (I2S)
2. ALC1308 SDW + ALC711 (SDW)

**Comment by xiulipan** [comment]
@ranj063 
And I think that is the point for some test case. As we already have some topology for `apl-up2-pcm512x-nohdmi` to test without hdmi.

**Comment by bardliao** [comment]
@xiulipan @ranj063 @plbossart We select SND_SOC_HDAC_HDMI if SND_SOC_SOF_HDA_COMMON for SOF machine drivers. However, if we don't select SND_SOC_SOF_HDA_COMMON, but select another machine driver with hdmi supported e.g. skl_rt286,  SND_SOC_HDAC_HDMI will be selected by skl_rt286. Will it cause any problem?

**Comment by xiulipan** [comment]
@bardliao In that case, we will enable the HDMI support for the kernel. If we would like to test nohdmi, we should not select other machine driver.
This is for some debug needed for device without HDMI.

**Comment by plbossart** [comment]
> > > I am going to engage the parking brake here. It's too complicated for us to maintain multiple versions of TGL, so we need information on what the recommended ones are. E.g. does anyone care about the ALC1308 in I2S mode?
> > 
> > 
> > @sathya-nujella would you know?
> 
> We need I2S support in TGL too. One way to prove I2S is to enable ALC1308.
> IMHO, I see the possiblities like:
> 
> 1. ALC1308 I2S (I2S)
> 2. ALC1308 SDW + ALC711 (SDW)

I'd need more information to figure out which configuration we are going to select.

is the ALC1308 HID always reported with status 0xf in /sys/bus/acpi/devices/10EC1308/status, or does it report a non-zero status when the I2S mode is selected?

**Comment by sathya-nujella** [comment]
> > > > I am going to engage the parking brake here. It's too complicated for us to maintain multiple versions of TGL, so we need information on what the recommended ones are. E.g. does anyone care about the ALC1308 in I2S mode?
> > > 
> > > 
> > > @sathya-nujella would you know?
> > 
> > 
> > We need I2S support in TGL too. One way to prove I2S is to enable ALC1308.
> > IMHO, I see the possiblities like:
> > 
> > 1. ALC1308 I2S (I2S)
> > 2. ALC1308 SDW + ALC711 (SDW)
> 
> I'd need more information to figure out which configuration we are going to select.
> 
> is the ALC1308 HID always reported with status 0xf in /sys/bus/acpi/devices/10EC1308/status, or does it report a non-zero status when the I2S mode is selected?


From BIOS settings,
1)
If we choose "Audio Link Mode = I2S (and choose I2S codec as ALC1308)"
then,
cat /sys/bus/acpi/devices/10EC1308\:00/status
	15

2)
if we choose "Audio Link Mode = SounWire"
In /sys/bus/acpi/devices/   <<<< no entry for 10EC1308

**Comment by plbossart** [comment]
> @xiulipan @ranj063 @plbossart We select SND_SOC_HDAC_HDMI if SND_SOC_SOF_HDA_COMMON for SOF machine drivers. However, if we don't select SND_SOC_SOF_HDA_COMMON, but select another machine driver with hdmi supported e.g. skl_rt286, SND_SOC_HDAC_HDMI will be selected by skl_rt286. Will it cause any problem?

yes it's a problem, but in practice if we want to build without HDAC_HDMI we also don't select the Skylake drivers. so we can punt and ignore SKL/KBL for now.

**Comment by plbossart** [comment]
please submit a follow-up PR for sof-rt5682

**Comment by xiulipan** [comment]
@plbossart Sure, will do.

**Pull request merged**
