### PR TITLE
Fix closed source skylake drivers

### PR DESCRIPTION
**Pull request by cujomalainey**
With the cros-sof-v4.14-rebase can only build SOF, we cannot build the closed source drivers which is an issue for backwards compatibility. This will need to be corrected. I'm going to be building up a set of patches to fix the skylake and glk-da-max drivers. If anyone wants to contribute you are more than welcome to send them to the parent branch for this pull request in my fork. I will comment when this pull request is ready to be pulled in. I am just making this initially so that there is a record that there is an issue here.

### CODE REVIEW

**Comment by cujomalainey** [comment]
@plbossart This allows the kernel to compile skylake in closed source, these bugs appear to have been introduced by 66cb9e4c913564ae3c51b8638366ac6b2abc7553 I can fix the commit formatting issues, but before I go forward I just wanted to get your input and see if you wanted me to do any squashing.

**Comment by RanderWang** [comment]
Pierre is enjoying his holiday and will return back 10.22

**Comment by ranj063** [comment]
@keyonjie @mengdonglin could you please take a look at the comments from Curtis?

**Comment by ranj063** [comment]
@cujomalainey https://github.com/thesofproject/linux/commit/66cb9e4c913564ae3c51b8638366ac6b2abc7553 was one of the required patches to enable HDMI audio in SOF.

If these commits fix the build issues with legacy drivers, I can merge them to cros-sof-v4.14-rebase.

**Comment by cujomalainey** [comment]
@ranj063 that would be awesome. I have another pull request I will be sending to fix glk-rt-max driver as well. If those could go in this week that would be awesome.

**Comment by cujomalainey** [comment]
ignore my comment about the glk-rt-max driver, it looks like they have been fixed in cros-rebase since the v0.4 drop

**Pull request merged**
