### PR TITLE
SoundWire: use master device

### PR DESCRIPTION
**Pull request by plbossart**
revert the revert and get rid of platform devices for good this time.

@RanderWang @bardliao @YvonneYang2 @ClarexZhou please recheck and retest

The companion branch is https://github.com/plbossart/sound/tree/sdw/master_device-rebase

### CODE REVIEW

**Comment by RanderWang** [comment]
> Tested on Comet Lake H & U, Tiger Lake RVP 1308 in sdw and I2S mode

sorry，  comment at wrong PR.  I will test later

**Comment by YvonneYang2** [comment]
Tried latest topic/sof-dev + PR1822 and https://github.com/plbossart/sound/tree/sdw/master_device-rebase branch on CML-U SDW laptop, both kernel crashed when system boot up.
Tested with latest topic/sof-dev without any PR, it can boot up successfully.

[dmesg.log](https://github.com/thesofproject/linux/files/4247951/dmesg.log)

**Comment by sinahuang** [comment]
Tried latest topic/sof-dev + PR1822 and https://github.com/plbossart/sound/tree/sdw/master_device-rebase branch on CML-H SDW laptop and TGL-U RVP 1308 in sdw and I2S mode, both kernel crashed when system boot up.
Tested with latest topic/sof-dev without any PR, it can boot up successfully.
CML-H log:
[dmesg25.log](https://github.com/thesofproject/linux/files/4248131/dmesg25.log)
TGL-U log:
[dmesg.log](https://github.com/thesofproject/linux/files/4248145/dmesg.log)

**Comment by bardliao** [comment]
@plbossart The NULL pointer happens when Master 0 probe timed out. Below patch can fix it. 
But the main issue here is master driver doesn't probe.
I do see sdw_uevent() is triggered. But **__sdw_register_master_driver() is never triggered.**
```patch
diff --git a/drivers/soundwire/intel_init.c b/drivers/soundwire/intel_init.c. 
index 03215a417071..a4b94a8876da 100644
--- a/drivers/soundwire/intel_init.c
+++ b/drivers/soundwire/intel_init.c
@@ -301,6 +301,7 @@ static struct sdw_intel_ctx
 	return ctx;
 
 err:
+	ctx->count = i;
 	sdw_intel_cleanup(ctx);
 link_err:
 	kfree(ctx);
```

**Comment by RanderWang** [comment]
@plbossart @bardliao   I found there are two KO files: soundwire-intel-init.ko and soundwire-intel.ko.
With this PR,  soundwire-intel.ko is not loaded.  I checked Makefile and applied the following patch, then everything worked.    In my opinion, we should only create soundwire-intel.ko

````
 #Intel driver
-soundwire-intel-objs :=        intel.o
+soundwire-intel-objs :=        intel.o intel_init.o
 obj-$(CONFIG_SOUNDWIRE_INTEL) += soundwire-intel.o
 
-soundwire-intel-init-objs := intel_init.o
-obj-$(CONFIG_SOUNDWIRE_INTEL) += soundwire-intel-init.o
-
````

@YvonneYang2  @sinahuang  can you help to test with this patch ? Thanks!

**Comment by plbossart** [comment]
weird, I try with modprobe snd-sof-pci with no issues. Not sure why the module is not loaded at boot, that seems very odd.

**Comment by plbossart** [comment]
> @plbossart The NULL pointer happens when Master 0 probe timed out. Below patch can fix it.
> But the main issue here is master driver doesn't probe.
> I do see sdw_uevent() is triggered. But **__sdw_register_master_driver() is never triggered.**
> 
> ```diff
> diff --git a/drivers/soundwire/intel_init.c b/drivers/soundwire/intel_init.c. 
> index 03215a417071..a4b94a8876da 100644
> --- a/drivers/soundwire/intel_init.c
> +++ b/drivers/soundwire/intel_init.c
> @@ -301,6 +301,7 @@ static struct sdw_intel_ctx
>  	return ctx;
>  
>  err:
> +	ctx->count = i;
>  	sdw_intel_cleanup(ctx);
>  link_err:
>  	kfree(ctx);
> ```

ack, added this fix, thanks @bardliao

**Comment by plbossart** [comment]
@YvonneYang2 @RanderWang @bardliao I am not able to reproduce the timeout issue. 
I can only think of two issues
1. difference in configurations. I use the default from the kconfig tree, can you try with the attached settings 
[sof-dev-defconfig.txt](https://github.com/thesofproject/linux/files/4251155/sof-dev-defconfig.txt)

2. a difference in machine setup, maybe the 2s timeout is too short. Can you try with e.g. 10s?

````diff
diff --git a/drivers/soundwire/intel.h b/drivers/soundwire/intel.h
index 23f7e32072f7..cdaec504f97b 100644
--- a/drivers/soundwire/intel.h
+++ b/drivers/soundwire/intel.h
@@ -41,6 +41,6 @@ struct sdw_intel_link_res {
 
 #define SDW_INTEL_QUIRK_MASK_BUS_DISABLE      BIT(1)
 
-#define SDW_INTEL_MASTER_PROBE_TIMEOUT 2000
+#define SDW_INTEL_MASTER_PROBE_TIMEOUT 10000
 
 #endif /* __SDW_INTEL_LOCAL_H */
````

**Comment by plbossart** [comment]
Now I can reproduce it on ICL-U, none of the two options below actually matter. Something's off with module loading.

**Comment by plbossart** [comment]
> Now I can reproduce it on ICL-U, none of the two options below actually matter. Something's off with module loading.

but on another machine with Ubuntu 19.10, things work fine again.
I suspect there is a userspace issue here.
@bardliao @RanderWang what distribution do you use?

**Comment by plbossart** [comment]
Updating the device to Ubuntu 19.10 fixes the issue.

**Comment by bardliao** [comment]
> but on another machine with Ubuntu 19.10, things work fine again.
> I suspect there is a userspace issue here.
> @bardliao @RanderWang what distribution do you use?

I use Ubuntu 18.04

**Comment by RanderWang** [comment]
> > Now I can reproduce it on ICL-U, none of the two options below actually matter. Something's off with module loading.
> 
> but on another machine with Ubuntu 19.10, things work fine again.
> I suspect there is a userspace issue here.
> @bardliao @RanderWang what distribution do you use?

Most of us use 18.04 LTS

**Comment by plbossart** [comment]
Come on people, for development you are supposed to use the latest distro on your target devices...

**Pull request merged**
