### PR TITLE
Merge/upstream merge 20190603

### PR DESCRIPTION
**Pull request by plbossart**
This is an important merge from upstream.
We need a CI round on this and make sure that this doesn't impact the on-going HDaudio support.
@RanderWang @ranj063 @lyakh @kv2019i @keyonjie please test this!

### CODE REVIEW

**Comment by plbossart** [comment]
Take 2 pushed since Mark merged a set of SOF patches moments ago.

**Comment by plbossart** [comment]
@xiulipan can you check the CI results? there's been topology errors reported in the two tests done today and I don't see what the issue is.

**Comment by ranj063** [comment]
> @RanderWang @ranj063 @lyakh @kv2019i @keyonjie please test this!

@plbossart I'm testing this right now. Will report back the status by tonight.

**Comment by xiulipan** [comment]
@plbossart 
This need to check. It seems some ASoC and machine driver issues are there.
```
[   10.523410 <    0.110290>] bytcr_rt5651 bytcr_rt5651: quirk IN1_MAP enabled
[   10.523420 <    0.000010>] bytcr_rt5651 bytcr_rt5651: quirk MCLK_EN enabled
[   10.523454 <    0.000034>] bytcr_rt5651 bytcr_rt5651: ASoC: failed to init link Audio Port
[   10.523773 <    0.000319>] bytcr_rt5651 bytcr_rt5651: devm_snd_soc_register_card failed -517
```

Will update later when I debug into this.

**Comment by ranj063** [comment]
@plbossart no issues on APL (up2) and CML

**Comment by xiulipan** [comment]
@plbossart 
Manually test with my device and one of CI device for BYT_RT5651 model.
No error, rerun the test. Maybe some codec issue with one of the CI device.

**Comment by kv2019i** [comment]
@plbossart Looks good:
APL/UP2:  playback with I2S and HDMI
WHL: HDA playback, HDMI+DP playback, DMIC recording, S3 stress tests -> all ok (or as good as baseline)

**Comment by plbossart** [comment]
Thanks for the tests!

**Pull request merged**
