### PR TITLE
[DEBUG]CI: Travis: Enable Travis CI for linux kernel

### PR DESCRIPTION
**Pull request by xiulipan**
Add checkpatch for pull-request only.
Build x86_64 kernel with kconfig sof base config.

Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>

### CODE REVIEW

**Comment by xiulipan** [comment]
@lgirdwood 
May need to turn on the linux build on Travis CI dash board.

**Comment by xiulipan** [comment]
@plbossart 
PR build result will look like https://github.com/xiulipan/sound/pull/2
We may need to check checkpatch result to ignore some checkpatch warnings like:

> WARNING: added, moved or deleted file(s), does MAINTAINERS need updating?
I added a .travis.yml into repo and did not want to change the MAINTAINERS file because we did not use this file for upstream

**Comment by plbossart** [comment]
Sorry, I am confused. Would this patch need to be maintained forever and re-applied every time we do a kernel change?

**Comment by lgirdwood** [comment]
@plbossart yes, similar to a .gitignore - only used in tooling never for upstreaming.

**Comment by xiulipan** [comment]
@plbossart 
This is some limitations for online third-party free CI.
If you would like to use some more customized system, please wait for few weeks.
We are still working on it.

**Comment by xiulipan** [comment]
@plbossart 
NP, I will add one more test job
They can run parallelly

@lgirdwood 
Could you open the trigger for travis CI first? So that is PR can be tracked by it now.
There will be no influence if no .travis.yml is in the repo

**Comment by xiulipan** [comment]
@plbossart 
SST build is added
log here https://travis-ci.org/xiulipan/sound/builds/449194426
can see sst is built from log
> LD [M]  sound/soc/intel/atom/sst/snd-intel-sst-core.o (https://travis-ci.org/xiulipan/sound/jobs/449194416#L2283)

**Comment by lgirdwood** [comment]
@xiulipan now enabled in Travis CI

**Comment by xiulipan** [comment]
@plbossart 
It seems I need to rebase to 4.19 since the recent branch switch.

**Comment by xiulipan** [comment]
@plbossart 
rebase the code and seems travis-ci is already start to work now.

**Comment by lgirdwood** [comment]
@xiulipan Looks like it takes 45 minutes for a build. Any chance we could only do an incremental build for each PR ? i.e. container keeps all build output files

**Comment by xiulipan** [comment]
@plbossart 
Travis CI will start a totally fresh environment for the build. And it will not even keep data even for each job in the same build.

To achieve that goal we may need some third part storage to keep the  

> all build output files
May be AWS S3 can do that.

**Comment by lgirdwood** [comment]
@xiulipan ok, maybe we then need a bare minimum kconfig that builds SOF + ASoC/ALSA  + Intel GFX only (alongside minimum other items)

**Comment by xiulipan** [comment]
@lgirdwood 
I have enable an internal Jenkins to enable incremental build.

**Pull request merged**
