### PR TITLE
Merge/sound upstream 20230216

### PR DESCRIPTION
**Pull request by ujfalusi**
Hi,

It must work at some point.....

Replaces #4182

### CODE REVIEW

**Comment by plbossart** [comment]
same FAIL issues on suspend-resume?

**Comment by ujfalusi** [comment]
> same FAIL issues on suspend-resume?

indeed, and it is affecting SDW machines?

**Comment by bardliao** [comment]
PCM IO error and only SoundWire machines are affected. It must be something wrong.

**Comment by bardliao** [comment]
I can't reproduce with my built kernel, but I can reproduce the issue with the CI build kernel binary. I will trigger a new CI test. The link of current test result is https://sof-ci.01.org/linuxpr/PR4197/build3239/devicetest/index.html

**Comment by bardliao** [comment]
SOFCI TEST

**Comment by ujfalusi** [comment]
One test patch on top to see if that helps before reverting
43f1a7f905fc soundwire: stream: Add specific prep/deprep commands to port_prep callback

Since that does not make any sense to me.

**Comment by ujfalusi** [comment]
Closing, 20230217 merge is done

**Pull request closed without merging**
