### PR TITLE
ASoC: Intel: soc-acpi-intel-mtl-match: add rt713 rt1316 config

### PR DESCRIPTION
**Pull request by bardliao**
Adding rt713 jack + rt1316 amp + rt1713 dmic configuration support.

### CODE REVIEW

**Review by plbossart — DISMISSED** [review]
LGTM, we can add and update later.

**Comment by bardliao** [comment]
v2 change: Move mtl_rt713_l0_rt1316_l12_rt1713_l3 upper to meet the rule that more devices need to be added first.

**Comment by bardliao** [comment]
ODM confirmed that the patch has been verified on a real device. So, it is ready for review now.

**Review by plbossart — DISMISSED** [review]

**Comment by bardliao** [comment]
Let's wait for some days.

**Comment by plbossart** [comment]
@bardliao any reason to wait longer? if not, can @RanderWang approve?

**Review by RanderWang — DISMISSED** [review]
LGTM

**Comment by bardliao** [comment]
@plbossart @RanderWang 
Changes: The rt1316 on link 1 is for left speaker, and the one on link 2 is for right speaker. Add a new group2 to avoid the existing configurations.

**Review by plbossart — APPROVED** [review]

**Comment by bardliao** [comment]
> @bardliao any reason to wait longer? if not, can @RanderWang approve?

We can merge this PR now. Realtek got the device and confirmed the PR works.

**Review by RanderWang — APPROVED** [review]

**Pull request merged**
