### PR TITLE
Test/glk bobba regression - take 2

### PR DESCRIPTION
**Pull request by ujfalusi**
Expanding on #4764 with the following diff now:
```diff
diff --git a/sound/soc/intel/boards/bxt_da7219_max98357a.c b/sound/soc/intel/boards/bxt_da7219_max98357a.c
index 816fad8c1ff0..975ee5c91d9b 100644
--- a/sound/soc/intel/boards/bxt_da7219_max98357a.c
+++ b/sound/soc/intel/boards/bxt_da7219_max98357a.c
@@ -797,6 +797,9 @@ static int broxton_audio_probe(struct platform_device *pdev)
 		broxton_audio_card.name = "glkda7219max";
 		/* Fixup the SSP entries for geminilake */
 		for (i = 0; i < ARRAY_SIZE(broxton_dais); i++) {
+			if (!broxton_dais[i].codecs || !broxton_dais[i].codecs->dai_name)
+				continue;
+
 			/* MAXIM_CODEC is connected to SSP1. */
 			if (!strcmp(broxton_dais[i].codecs->dai_name,
 				    BXT_MAXIM_CODEC_DAI)) {
@@ -822,6 +825,9 @@ static int broxton_audio_probe(struct platform_device *pdev)
 			broxton_audio_card.name = "cmlda7219max";
 
 		for (i = 0; i < ARRAY_SIZE(broxton_dais); i++) {
+			if (!broxton_dais[i].codecs || !broxton_dais[i].codecs->dai_name)
+				continue;
+
 			/* MAXIM_CODEC is connected to SSP1. */
 			if (!strcmp(broxton_dais[i].codecs->dai_name,
 					BXT_MAXIM_CODEC_DAI)) {
```

Hoping better results on solving the bad kernel oops reported in https://github.com/thesofproject/linux/pull/4759

### CODE REVIEW

**Comment by marc-hb** [comment]
https://sof-ci.01.org/linuxpr/PR4765/build905/devicetest/index.html does look better! All green.

**Review by bardliao — DISMISSED** [review]

**Comment by bardliao** [comment]
@ujfalusi We also need
```patch
diff --git a/sound/soc/intel/boards/bxt_rt298.c b/sound/soc/intel/boards/bxt_rt298.c
index 4631106f2a28..a56fa60b55b1 100644
--- a/sound/soc/intel/boards/bxt_rt298.c
+++ b/sound/soc/intel/boards/bxt_rt298.c
@@ -604,6 +604,8 @@ static int broxton_audio_probe(struct platform_device *pdev)
        int i;

        for (i = 0; i < ARRAY_SIZE(broxton_rt298_dais); i++) {
+               if (!card->dai_link[i].codecs || !card->dai_link[i].codecs->dai_name)
+                       continue;
                if (!strncmp(card->dai_link[i].codecs->name, "i2c-INT343A:00",
                             I2C_NAME_SIZE)) {
                        if (!strncmp(card->name, "broxton-rt298",
```

**Comment by ujfalusi** [comment]
Changes since v1:
- check only for `!broxton_dais[i].codecs->dai_name` in bxt_da7219_max98357a.c
- add similar patch for bxt_rt298.c

**Comment by marc-hb** [comment]
Fixes submitted upstream:
https://marc.info/?l=linux-sound&m=170470721717674&w=2

and in #4759

**Pull request closed without merging**
