### PR TITLE
ASoC: rt5682s: do not block workqueue if card is unbound

### PR DESCRIPTION
**Pull request by kv2019i**
The current rt5682s_jack_detect_handler() assumes the component
and card will always show up and implements an infinite usleep
loop waiting for them to show up.

This does not hold true if a codec interrupt (or other
event) occurs when the card is unbound. The codec driver's
remove  or shutdown functions cannot cancel the workqueue due
to the wait loop. As a result, code can either end up blocking
the workqueue, or hit a kernel oops when the card is freed.

Fix the issue by rescheduling the jack detect handler in
case the card is not ready. In case card never shows up,
the shutdown/remove/suspend calls can now cancel the detect
task.

Signed-off-by: Kai Vehmanen <kai.vehmanen@linux.intel.com>

### CODE REVIEW

**Comment by kv2019i** [comment]
I believe this could explain the rare failures we've seen with "ASoC: core: unregister clients and machine drivers in .shutdown".By modifying the timing of bit, I can easily hit a kernel oops on shutdown. 5682s irq occurs while SOF shutdown is already in proress, but 5682s cannot cancel the workqueue as it's running a infinite usleep loop. Once SOF unbinds the card, the jack detected handler will oops.

If this turns out to be a legit fix, I can make similar patches to other drivers (there are 2-3 other codec driver at least that have the same design).

**Review by ujfalusi — DISMISSED** [review]
I have spotted similar thing in the rt5682.c driver and it did felt a bit broken design.

Your analysis is spot on and we should have similar patch for the other codec.

**Review by ujfalusi — APPROVED** [review]
Still looks sane to me.

**Review by ranj063 — APPROVED** [review]
looks good. nice catch @kv2019i

**Review by plbossart — APPROVED** [review]

**Comment by plbossart** [comment]
we should let the Realtek team @shumingfan @oder-chiou @jack-cy-yu as well as @bardliao an opportunity to comment after the CNY break.

**Comment by kv2019i** [comment]
@plbossart wrote:
> we should let the Realtek team @shumingfan @oder-chiou @jack-cy-yu as well as @bardliao an opportunity to comment after the CNY break.

Ack, let's wait until next week. This needs to be sent together (or before) the unregister_client patch to SOF as that will open a window to hit kernel oopses in these codec drivers (with much more common scenarios).

**Comment by shumingfan** [comment]
> Ack, let's wait until next week. This needs to be sent together (or before) the unregister_client patch to SOF as that will open a window to hit kernel oopses in these codec drivers (with much more common scenarios).

@kv2019i Thanks for these patches. It looks good to me.

**Review by bardliao — APPROVED** [review]
LGTM Thanks

**Comment by kv2019i** [comment]
Thanks all for reviews! I'll send these directly to upstream today, no need to separately integrate via sof-dev. FYI to @plbossart  and @ujfalusi

**Comment by kv2019i** [comment]
Sent as https://mailman.alsa-project.org/pipermail/alsa-devel/2022-February/195560.html Closing here.

**Pull request closed without merging**
