### PR TITLE
Merge/sound upstream 20220822

### PR DESCRIPTION
**Pull request by plbossart**
First merge based on 6.0-rc1

I will add the rebased branch after validation results are shown

### CODE REVIEW

**Comment by ujfalusi** [comment]
@plbossart, sparse is screaming like there is no tomorrow both in CI and locally:
```
arch/x86/include/asm/bitops.h:66:1: warning: unreplaced symbol 'return'
```
and
```
include/asm-generic/bitops/generic-non-atomic.h:29:9: warning: unreplaced symbol 'mask'
include/asm-generic/bitops/generic-non-atomic.h:30:9: warning: unreplaced symbol 'p'
include/asm-generic/bitops/generic-non-atomic.h:32:10: warning: unreplaced symbol 'p'
include/asm-generic/bitops/generic-non-atomic.h:32:16: warning: unreplaced symbol 'mask'
include/asm-generic/bitops/generic-non-atomic.h:27:1: warning: unreplaced symbol 'return'
```
and others from `bitops.h` and `generic-non-atomic.h`. I'm sure it can be explained...

https://lore.kernel.org/lkml/32609325-C7A7-4CB1-B9F1-7AB0B6B51AE1@oracle.com/T/ ?

**Comment by ujfalusi** [comment]
@plbossart, updating sparse to sparse-git (v0.6.4-39-gce1a6720f69e) and the warnings are gone here.

**Comment by ujfalusi** [comment]
I have hit this on my sdw device:
```
[    2.904414] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx done: 0x70000000: FW_READY
[    2.904747] soundwire_intel soundwire_intel.link.0: PCM cap bd:6 in:0 out:0
[    2.904786] divide error: 0000 [#1] PREEMPT SMP NOPTI
[    2.904813] CPU: 7 PID: 51 Comm: kworker/7:0 Not tainted 6.0.0-rc1+ #621
[    2.904834] Hardware name: Dell Inc. Latitude 9520/, BIOS 0.5.5 09/29/2020
[    2.904852] Workqueue: events sof_probe_work [snd_sof]
[    2.904883] RIP: 0010:sdw_cdns_init+0x1b/0x130 [soundwire_cadence]
[    2.904906] Code: c9 31 f6 eb bf 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 41 54 31 d2 55 53 8b 87 f4 01 00 00 48 89 fb 48 8b b7 68 05 00 00 <f7> b7 c0 01 00 00 83 e8 01 8b 56 30 30 d2 48 8b 8f 68 05 00 00 09
[    2.904950] RSP: 0018:ffffb9e48029bd28 EFLAGS: 00010246
[    2.904967] RAX: 000000000124f800 RBX: ffff9e009446b828 RCX: 0000000000000003
[    2.904987] RDX: 0000000000000000 RSI: ffffb9e481c30000 RDI: ffff9e009446b828
[    2.905008] RBP: 0000000000000000 R08: 0000000000000002 R09: 0000000031050505
[    2.905027] R10: 0000000000000000 R11: 0000000000000000 R12: ffff9e009446b000
[    2.905051] R13: 0000000000000000 R14: ffffb9e481c2c000 R15: ffff9e07ef7f1305
[    2.905073] FS:  0000000000000000(0000) GS:ffff9e07ef600000(0000) knlGS:0000000000000000
[    2.905097] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[    2.905114] CR2: 00007f7b7e5c8798 CR3: 000000010477c006 CR4: 0000000000770ee0
[    2.905135] PKRU: 55555554
[    2.905145] Call Trace:
[    2.905156]  <TASK>
[    2.905167]  intel_link_startup+0x281/0x590 [soundwire_intel]
[    2.905191]  sdw_intel_startup+0x6e/0xa0 [soundwire_intel]
[    2.905211]  hda_dsp_post_fw_run+0x27/0x80 [snd_sof_intel_hda_common]
[    2.905241]  ? _raw_spin_unlock_irqrestore+0x36/0x60
[    2.905261]  snd_sof_run_firmware+0x145/0x320 [snd_sof]
[    2.905292]  ? destroy_sched_domains_rcu+0x30/0x30
[    2.905313]  sof_probe_work+0xc7/0x220 [snd_sof]
[    2.905341]  process_one_work+0x2c4/0x520
[    2.905361]  worker_thread+0x4c/0x3c0
[    2.905376]  ? rescuer_thread+0x3a0/0x3a0
[    2.905391]  kthread+0xf2/0x120
[    2.905404]  ? kthread_complete_and_exit+0x20/0x20
[    2.905422]  ret_from_fork+0x1f/0x30
[    2.905440]  </TASK>
[    2.905450] Modules linked in: snd_soc_rt715 snd_soc_rt711 snd_soc_rt1308_sdw regmap_sdw snd_hda_codec_hdmi snd_soc_dmic snd_sof_pci_intel_tgl snd_sof_intel_hda_common soundwire_intel soundwire_generic_allocation soundwire_cadence snd_sof_intel_hda snd_sof_pci snd_sof_xtensa_dsp snd_sof snd_sof_utils snd_soc_hdac_hda snd_hda_ext_core snd_soc_acpi_intel_match snd_soc_acpi soundwire_bus snd_soc_core snd_compress snd_hda_intel snd_intel_dspcfg snd_intel_sdw_acpi hid_multitouch snd_hda_codec snd_hwdep snd_hda_core wmi_bmof iwlmvm x86_pkg_temp_thermal i915 intel_powerclamp snd_pcm i2c_algo_bit psmouse drm_buddy drm_display_helper r8153_ecm drm_kms_helper cfbfillrect cdc_ether syscopyarea snd_timer cfbimgblt sysfillrect usbnet sysimgblt snd fb_sys_fops r8152 soundcore intel_lpss_pci cfbcopyarea mei_me intel_lpss ttm processor_thermal_device_pci_legacy idma64 mei processor_thermal_device iwlwifi mfd_core processor_thermal_rfim drm intel_ish_ipc(+) processor_thermal_mbox
[    2.905518]  drm_panel_orientation_quirks intel_ishtp intel_soc_dts_iosf wmi i2c_hid_acpi i2c_hid int3403_thermal int340x_thermal_zone int3400_thermal intel_pmc_core acpi_thermal_rel efivarfs xhci_pci xhci_hcd
[    2.905796] ---[ end trace 0000000000000000 ]---
[    2.905810] RIP: 0010:sdw_cdns_init+0x1b/0x130 [soundwire_cadence]
[    2.905832] Code: c9 31 f6 eb bf 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 41 54 31 d2 55 53 8b 87 f4 01 00 00 48 89 fb 48 8b b7 68 05 00 00 <f7> b7 c0 01 00 00 83 e8 01 8b 56 30 30 d2 48 8b 8f 68 05 00 00 09
[    2.905876] RSP: 0018:ffffb9e48029bd28 EFLAGS: 00010246
[    2.905892] RAX: 000000000124f800 RBX: ffff9e009446b828 RCX: 0000000000000003
[    2.907289] RDX: 0000000000000000 RSI: ffffb9e481c30000 RDI: ffff9e009446b828
[    2.908626] RBP: 0000000000000000 R08: 0000000000000002 R09: 0000000031050505
[    2.909924] R10: 0000000000000000 R11: 0000000000000000 R12: ffff9e009446b000
[    2.911251] R13: 0000000000000000 R14: ffffb9e481c2c000 R15: ffff9e07ef7f1305
[    2.912558] FS:  0000000000000000(0000) GS:ffff9e07ef600000(0000) knlGS:0000000000000000
[    2.913863] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[    2.915195] CR2: 00007f7b7e5c8798 CR3: 000000010477c006 CR4: 0000000000770ee0
[    2.916536] PKRU: 55555554
```

**Comment by ujfalusi** [comment]
@plbossart, it because of:
```
[    2.869790] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx done: 0x70000000: FW_READY
[    2.870116] soundwire_intel soundwire_intel.link.0: PCM cap bd:6 in:0 out:0
[    2.870147] cdns_init_clock_ctrl: prop->max_clk_freq is 0!!!!
[    2.870149] cdns_init_clock_ctrl: prop->clk_freq is 19200000
[    2.871979] soundwire_intel soundwire_intel.link.1: PCM cap bd:6 in:0 out:0
[    2.872008] cdns_init_clock_ctrl: prop->max_clk_freq is 0!!!!
[    2.872009] cdns_init_clock_ctrl: prop->clk_freq is 19200000
[    2.873961] soundwire_intel soundwire_intel.link.2: PCM cap bd:6 in:0 out:0
[    2.873990] cdns_init_clock_ctrl: prop->max_clk_freq is 0!!!!
[    2.873991] cdns_init_clock_ctrl: prop->clk_freq is 19200000
```

**Comment by ujfalusi** [comment]
```c
		fwnode_property_read_u32_array(link,
				"mipi-sdw-clock-frequencies-supported",
				prop->clk_freq, prop->num_clk_freq);
```
reads zero into the clk_freq array (in drivers/soundwire/mipi_disco.c : sdw_master_read_prop() ):
```
sdw_master_read_prop: prop->max_clk_freq is 0
sdw_master_read_prop: nval is 1
sdw_master_read_prop: prop->clk_freq[0] is 0
sdw_master_read_prop: thus: prop->max_clk_freq is 0
```
while the same in current topic/sof-dev:
```
sdw_master_read_prop: prop->max_clk_freq is 0
sdw_master_read_prop: nval is 1
sdw_master_read_prop: prop->clk_freq[0] is 4800000
sdw_master_read_prop: thus: prop->max_clk_freq is 4800000
```

**Comment by plbossart** [comment]
@ujfalusi that kernel doesn't even complete booting on my TGL device :-(

**Comment by plbossart** [comment]
> ```c
> 		fwnode_property_read_u32_array(link,
> 				"mipi-sdw-clock-frequencies-supported",
> 				prop->clk_freq, prop->num_clk_freq);
> ```
> 
> reads zero into the clk_freq array (in drivers/soundwire/mipi_disco.c : sdw_master_read_prop() ):
> 
> ```
> sdw_master_read_prop: prop->max_clk_freq is 0
> sdw_master_read_prop: nval is 1
> sdw_master_read_prop: prop->clk_freq[0] is 0
> sdw_master_read_prop: thus: prop->max_clk_freq is 0
> ```
> 
> while the same in current topic/sof-dev:
> 
> ```
> sdw_master_read_prop: prop->max_clk_freq is 0
> sdw_master_read_prop: nval is 1
> sdw_master_read_prop: prop->clk_freq[0] is 4800000
> sdw_master_read_prop: thus: prop->max_clk_freq is 4800000
> ```

I see a number of changes in drivers/acpi related to device and non-device nodes, I bet it's related.

**Comment by ujfalusi** [comment]
This: 923044133367c8d72662938da0ea531bbdb39799

**Comment by ujfalusi** [comment]
The fix is:
```diff
diff --git a/drivers/acpi/property.c b/drivers/acpi/property.c
index 7b3ad8ed2f4e..2cf85b68f67c 100644
--- a/drivers/acpi/property.c
+++ b/drivers/acpi/property.c
@@ -1042,7 +1042,7 @@ static int acpi_data_prop_read_single(const struct acpi_device_data *data,
 				ret = -EPROTO;				\
 				break;					\
 			}						\
-			if (__items[i].integer.value > _Generic(__val,	\
+			if (__items[i].integer.value > _Generic((*val),	\
 								u8: U8_MAX, \
 								u16: U16_MAX, \
 								u32: U32_MAX, \
```

**Comment by ujfalusi** [comment]
looks like there is a fix already:
https://lore.kernel.org/lkml/20220812130645.14710-1-sbinding@opensource.cirrus.com/

**Comment by plbossart** [comment]
> looks like there is a fix already: https://lore.kernel.org/lkml/20220812130645.14710-1-sbinding@opensource.cirrus.com/

I just added that patch on this branch. thanks @ujfalusi

**Comment by ujfalusi** [comment]
Now it sounds OK on my devices.

**Comment by plbossart** [comment]
Ci tests are not so good. We have a boot issue detected on a number of platforms

https://sof-ci.01.org/linuxpr/PR3829/build531/devicetest/?model=TGLU_RVP_SDW&testcase=verify-kernel-boot-log
````
[    0.603980] kernel: ACPI: \_SB_.PC00.HDAS.SNDW.SWD0.DPN_: Can't tag data node
[    0.605019] kernel: ACPI: \_SB_.PC00.HDAS.SNDW.SWD1.DPN_: Can't tag data node
[    0.605941] kernel: ACPI: \_SB_.PC00.HDAS.SNDW.SWD2.DPN_: Can't tag data node
[    0.606869] kernel: ACPI: \_SB_.PC00.HDAS.SNDW.SWD3.DPN_: Can't tag data node
[    0.607789] kernel: ACPI: \_SB_.PC00.HDAS.SNDW.SWD4.DPN_: Can't tag data node
[    0.608710] kernel: ACPI: \_SB_.PC00.HDAS.SNDW.SWD5.DPN_: Can't tag data node
[    0.609632] kernel: ACPI: \_SB_.PC00.HDAS.SNDW.SWD6.DPN_: Can't tag data node
[    0.610564] kernel: ACPI: \_SB_.PC00.HDAS.SNDW.SWD7.DPN_: Can't tag data node
````

https://sof-ci.01.org/linuxpr/PR3829/build531/devicetest/?model=WHL_UPEXT_HDA_ZEPHYR&testcase=verify-kernel-boot-log
````
[    0.546813] kernel: ACPI: \_SB_.PCI0.HDAS.SNDW.SWD0.DPN_: Can't tag data node
[    0.548891] kernel: ACPI: \_SB_.PCI0.HDAS.SNDW.SWD1.DPN_: Can't tag data node
[    0.550953] kernel: ACPI: \_SB_.PCI0.HDAS.SNDW.SWD2.DPN_: Can't tag data node
[    0.553011] kernel: ACPI: \_SB_.PCI0.HDAS.SNDW.SWD3.DPN_: Can't tag data node
[    0.555074] kernel: ACPI: \_SB_.PCI0.HDAS.SNDW.SWD4.DPN_: Can't tag data node
[    0.557130] kernel: ACPI: \_SB_.PCI0.HDAS.SNDW.SWD5.DPN_: Can't tag data node
[    0.559191] kernel: ACPI: \_SB_.PCI0.HDAS.SNDW.SWD6.DPN_: Can't tag data node
[    0.561254] kernel: ACPI: \_SB_.PCI0.HDAS.SNDW.SWD7.DPN_: Can't tag data node
````

and we also have a configuration problem @fredoh9 @keqiaozhang 
https://sof-ci.01.org/linuxpr/PR3829/build531/devicetest/?model=ADLP_RVP_SDW_ZEPHYR&testcase=verify-kernel-boot-log
````
[    6.882624] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Direct firmware load for intel/sof-tplg/sof-adl-rt711.tplg failed with error -2
[    6.882627] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: tplg request firmware intel/sof-tplg/sof-adl-rt711.tplg failed err: -2
````

**Comment by fredoh9** [comment]
I will take a look ADLP_RVP_SDW_ZEPHYR failure

**Comment by fredoh9** [comment]
Failure is due to trying to load intel/sof-tplg/sof-adl-rt711.tplg while we copied intel/sof-tplg/sof-adl-rt711**-4ch**.tplg. Fixed now.

But I remember it wasn't FAILURE case. One of PR test in Aug 18th, loading intel/sof-tplg/sof-adl-rt711-4ch.tplg. Looks like recently loading tplg name is changed.

`[    7.126365] kernel: snd_sof:snd_sof_load_topology: sof-audio-pci-intel-tgl 0000:00:1f.3: loading topology:intel/sof-tplg/sof-adl-rt711-4ch.tplg
`

**Comment by plbossart** [comment]
@fredoh9 the topology name is created dynamically based on NHLT reports. In the test there is no DMIC reported, so the topology name does not have the -4ch suffix.

I still think there's a configuration issue, something must have changed here.

````
[    6.777267] kernel: snd_intel_dspcfg:intel_nhlt_get_dmic_geo: sof-audio-pci-intel-tgl 0000:00:1f.3: dmic number 0 max_ch 0
[    6.777271] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: DMICs detected in NHLT tables: 0
````

**Comment by plbossart** [comment]
All tests are now passing except for some suspend-resume tests.
https://sof-ci.01.org/linuxpr/PR3829/build535/devicetest/

I am a bit concerned about all CML_RVP_SDW_ZEPHYR failing all three tests, this unusual. WIll run the tests again to see what happens.

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
Humm, there seems to be a suspend-resume regression on CML_RVP_SDW_ZEPHYR, all 3 tests failed twice. This isn't random any more.
https://sof-ci.01.org/linuxpr/PR3829/build537/devicetest/

I don't have a clue how to interpret the results
 https://sof-ci.01.org/linuxpr/PR3829/build537/devicetest/?model=CML_RVP_SDW_ZEPHYR&testcase=check-suspend-resume-5

the failure seems to happen on the second suspend. Meh. @ujfalusi any ideas?

**Comment by plbossart** [comment]
See e.g these results: https://sof-ci.01.org/linuxpr/PR3832/build538/devicetest/ We never see any failures for that platform.

**Comment by ujfalusi** [comment]
@plbossart, on APL (UP2) I see this on suspend:
```
[   41.706490] PM: suspend entry (deep)
[   41.712747] Filesystems sync: 0.006 seconds
[   41.718271] Freezing user space processes ... (elapsed 0.002 seconds) done.
[   41.721324] OOM killer disabled.
[   41.721332] Freezing remaining freezable tasks ... (elapsed 0.001 seconds) done.
[   41.723246] printk: Suspending console(s) (use no_console_suspend to debug)
[   41.775687] sd 1:0:0:0: [sda] Synchronizing SCSI cache
[   41.778877] sd 1:0:0:0: [sda] Stopping disk
[   41.779699] r8169 0000:02:00.0 eth0: Link is Down
[   41.958909] ACPI: PM: Preparing to enter system sleep state S3
[   41.960161] ACPI: PM: Saving platform NVS memory
[   41.960326] Disabling non-boot CPUs ...
[   41.966597] smpboot: CPU 1 is now offline
[   41.973873] smpboot: CPU 2 is now offline
[   41.978815] smpboot: CPU 3 is now offline
[   41.981700] unchecked MSR access error: WRMSR to 0x122 (tried to write 0x80000dbc00000244) at rIP: 0xffffffffa8028950 (restore_processor_state+0x280/0x360)
[   41.981735] Call Trace:
[   41.981745]  <TASK>
[   41.981766]  x86_acpi_suspend_lowlevel+0x10a/0x190
[   41.981784]  acpi_suspend_enter+0x69/0x240
[   41.981795]  ? _raw_spin_unlock_irqrestore+0x36/0x60
[   41.981812]  suspend_devices_and_enter+0x795/0x9c0
[   41.981837]  pm_suspend.cold+0x270/0x2fc
[   41.981850]  state_store+0x68/0xd0
[   41.981868]  kernfs_fop_write_iter+0x144/0x200
[   41.981887]  vfs_write+0x27e/0x480
[   41.981927]  ksys_write+0x74/0xf0
[   41.981946]  do_syscall_64+0x3a/0x90
[   41.981958]  entry_SYSCALL_64_after_hwframe+0x63/0xcd
[   41.981969] RIP: 0033:0x7f8031a21e94
[   41.981980] Code: 15 f9 0e 0e 00 f7 d8 64 89 02 48 c7 c0 ff ff ff ff eb b7 0f 1f 00 f3 0f 1e fa 80 3d 8d 96 0e 00 00 74 13 b8 01 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 54 c3 0f 1f 00 48 83 ec 28 48 89 54 24 18 48
[   41.981987] RSP: 002b:00007ffef3498878 EFLAGS: 00000202 ORIG_RAX: 0000000000000001
[   41.982000] RAX: ffffffffffffffda RBX: 0000000000000004 RCX: 00007f8031a21e94
[   41.982006] RDX: 0000000000000004 RSI: 0000558bce4255c0 RDI: 0000000000000004
[   41.982011] RBP: 0000558bce4255c0 R08: 0000000000001000 R09: 00007f8031b04030
[   41.982016] R10: 00007f8031b04030 R11: 0000000000000202 R12: 0000000000000004
[   41.982021] R13: 0000558bce423570 R14: 0000000000000004 R15: 00007f8031aff940
[   41.982062]  </TASK>
[   41.982069] ACPI: PM: Low-level resume complete
[   41.982196] ACPI: PM: Restoring platform NVS memory
[   41.983304] Enabling non-boot CPUs ...
[   41.983685] x86: Booting SMP configuration:
[   41.983692] smpboot: Booting Node 0 Processor 1 APIC 0x2
[   41.987621] ACPI: \_PR_.CPU1: Found 3 idle states
[   41.988714] CPU1 is up
[   41.988927] smpboot: Booting Node 0 Processor 2 APIC 0x4
[   41.992063] ACPI: \_PR_.CPU2: Found 3 idle states
[   41.993082] CPU2 is up
[   41.993328] smpboot: Booting Node 0 Processor 3 APIC 0x6
[   41.996886] ACPI: \_PR_.CPU3: Found 3 idle states
[   41.998090] CPU3 is up
[   41.998532] ACPI: PM: Waking up from system sleep state S3
[   42.028608] sd 1:0:0:0: [sda] Starting disk
[   42.148868] r8169 0000:03:00.0 eth1: Link is Down
[   42.184844] r8169 0000:02:00.0 eth0: Link is Down
[   42.300269] OOM killer enabled.
[   42.300279] Restarting tasks ... done.
[   42.302573] random: crng reseeded on system resumption
[   42.302631] video LNXVIDEO:00: Restoring backlight state
[   42.302643] PM: suspend exit
[   42.342555] ata1: SATA link down (SStatus 4 SControl 300)
[   42.503723] ata2: SATA link up 6.0 Gbps (SStatus 133 SControl 300)
[   42.506799] ata2.00: NCQ Send/Recv Log not supported
[   42.509108] ata2.00: NCQ Send/Recv Log not supported
[   42.509877] ata2.00: configured for UDMA/133
[   44.933286] r8169 0000:02:00.0 eth0: Link is Up - 1Gbps/Full - flow control rx/tx
```
The first suspend/resume succeeds, the second will not wake up.
The error is printed during the first suspend/resume and happens without the audio drivers loaded.

Might be the same issue as with CML?

**Comment by ujfalusi** [comment]
mainline 6.0-rc2 has the same failure, let's see v5.19 and then bisect...

**Comment by ujfalusi** [comment]
Right, so it is not that. Looks like now it also happens with 5.19 and sof-dev on the board. When I first saw it I could not reproduce it with the sof-dev based kernel..
Oh well.

**Comment by ujfalusi** [comment]
@plbossart, not what I have expected...
```
88f1669019bd62b3009a3cebf772fbaaa21b9f38 is the first bad commit
commit 88f1669019bd62b3009a3cebf772fbaaa21b9f38
Author: Bart Van Assche <bvanassche@acm.org>
Date:   Thu Jun 30 12:57:03 2022 -0700

    scsi: sd: Rework asynchronous resume support
    
    For some technologies, e.g. an ATA bus, resuming can take multiple
    seconds. Waiting for resume to finish can cause a very noticeable delay.
    Hence this commit that restores the behavior from before "scsi: core: pm:
    Rely on the device driver core for async power management" for most SCSI
    devices.
    
    This commit introduces a behavior change: if the START command fails, do
    not consider this as a SCSI disk resume failure.
    
    Link: https://bugzilla.kernel.org/show_bug.cgi?id=215880
    Link: https://lore.kernel.org/r/20220630195703.10155-3-bvanassche@acm.org
    Fixes: a19a93e4c6a9 ("scsi: core: pm: Rely on the device driver core for async power management")
    Cc: Ming Lei <ming.lei@redhat.com>
    Cc: Hannes Reinecke <hare@suse.de>
    Cc: John Garry <john.garry@huawei.com>
    Cc: ericspero@icloud.com
    Cc: jason600.groome@gmail.com
    Tested-by: jason600.groome@gmail.com
    Signed-off-by: Bart Van Assche <bvanassche@acm.org>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

 drivers/scsi/sd.c | 84 +++++++++++++++++++++++++++++++++++++++++++------------
 drivers/scsi/sd.h |  5 ++++
 2 files changed, 71 insertions(+), 18 deletions(-)
```
the bisect log:
```
git bisect start
# status: waiting for both good and bad commits
# good: [3d7cb6b04c3f3115719235cc6866b10326de34cd] Linux 5.19
git bisect good 3d7cb6b04c3f3115719235cc6866b10326de34cd
# status: waiting for bad commit, 1 good commit known
# bad: [568035b01cfb107af8d2e4bd2fb9aea22cf5b868] Linux 6.0-rc1
git bisect bad 568035b01cfb107af8d2e4bd2fb9aea22cf5b868
# good: [b44f2fd87919b5ae6e1756d4c7ba2cbba22238e1] Merge tag 'drm-next-2022-08-03' of git://anongit.freedesktop.org/drm/drm
git bisect good b44f2fd87919b5ae6e1756d4c7ba2cbba22238e1
# bad: [6614a3c3164a5df2b54abb0b3559f51041cf705b] Merge tag 'mm-stable-2022-08-03' of git://git.kernel.org/pub/scm/linux/kernel/git/akpm/mm
git bisect bad 6614a3c3164a5df2b54abb0b3559f51041cf705b
# good: [c040862bfbd9c5f3cb64e1df1c623e20e38fe656] Merge tag 'xtensa-20220804' of https://github.com/jcmvbkbc/linux-xtensa
git bisect good c040862bfbd9c5f3cb64e1df1c623e20e38fe656
# bad: [746fc76b820dce8cbb17a1e5e70a1558db4d7406] Merge tag 'scsi-misc' of git://git.kernel.org/pub/scm/linux/kernel/git/jejb/scsi
git bisect bad 746fc76b820dce8cbb17a1e5e70a1558db4d7406
# good: [36001a2fa6cc63d58664a2a99b90a864f9eb587a] Merge tag 'clk-for-linus' of git://git.kernel.org/pub/scm/linux/kernel/git/clk/linux
git bisect good 36001a2fa6cc63d58664a2a99b90a864f9eb587a
# good: [eff0cb3d91c06acbb957be1134a07afa2c4978e3] Merge tag 'pci-v5.20-changes' of git://git.kernel.org/pub/scm/linux/kernel/git/helgaas/pci
git bisect good eff0cb3d91c06acbb957be1134a07afa2c4978e3
# bad: [4ecc9b0271a7623deabcbe8fcb39f065701d8f74] scsi: lpfc: Fix uninitialized cqe field in lpfc_nvme_cancel_iocb()
git bisect bad 4ecc9b0271a7623deabcbe8fcb39f065701d8f74
# good: [bc602ae977f3e6d47cd4c9c7aebc431019206712] scsi: ufs: ufs-mediatek: Support flexible parameters for SMC calls
git bisect good bc602ae977f3e6d47cd4c9c7aebc431019206712
# good: [cc06af0bbc21bcee40d57e3ee569d3a09741dafd] scsi: trace: Print driver_tag and scheduler_tag in SCSI trace
git bisect good cc06af0bbc21bcee40d57e3ee569d3a09741dafd
# good: [bcec04b3cce4c498ef0d416a3a2aaf0369578151] scsi: ufs: ufs-qcom: Remove unneeded code
git bisect good bcec04b3cce4c498ef0d416a3a2aaf0369578151
# good: [34bd1dcacf0dd86ab8c35f703bc237723fee354c] scsi: target: Detect UNMAP support post configuration
git bisect good 34bd1dcacf0dd86ab8c35f703bc237723fee354c
# good: [158da6bcae7a66e631bbec458f35ea3bd0ac5d71] scsi: gvp11: Convert m68k WD33C93 drivers to DMA API
git bisect good 158da6bcae7a66e631bbec458f35ea3bd0ac5d71
# good: [90552cd2d1f962478f1bb426c686540cbd145bec] scsi: core: Move the definition of SCSI_QUEUE_DELAY
git bisect good 90552cd2d1f962478f1bb426c686540cbd145bec
# bad: [11e50ed239b5b7f383874dd737283ae93f62ece3] Merge branch '5.19/scsi-fixes' into 5.20/scsi-staging
git bisect bad 11e50ed239b5b7f383874dd737283ae93f62ece3
# bad: [88f1669019bd62b3009a3cebf772fbaaa21b9f38] scsi: sd: Rework asynchronous resume support
git bisect bad 88f1669019bd62b3009a3cebf772fbaaa21b9f38
# first bad commit: [88f1669019bd62b3009a3cebf772fbaaa21b9f38] scsi: sd: Rework asynchronous resume support
```

**Comment by ujfalusi** [comment]
But sure enough, reverting 88f1669019bd62b3009a3cebf772fbaaa21b9f38 makes consequent suspend/resume to work on my UP2 board.
Note: I'm not using the eMMC as rootfs, I have an mSATA drive in there...

**Comment by ujfalusi** [comment]
@plbossart, can you pick 785538bfdd682c8e962341d585f9b88262a0475e from linux next and push it?

**Comment by plbossart** [comment]
> @plbossart, can you pick [785538b](https://github.com/thesofproject/linux/commit/785538bfdd682c8e962341d585f9b88262a0475e) from linux next and push it?

done. I am glad we didn't press the merge button and were a bit more cautious. suspend-resume is hard.

**Comment by miRoox** [comment]
SOFCI TEST

**Comment by miRoox** [comment]
Sorry, I just tested a new CI feature around 6 hours ago, please ignore the error of sof-ci/jenkins/pr-device-test/main

**Comment by ujfalusi** [comment]
SOFCI TEST

**Comment by miRoox** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
@ujfalusi is working on an update.

**Pull request closed without merging**
