### PR TITLE
[TEST] SoundWire: fix FIELD_PREP usage

### PR DESCRIPTION
**Pull request by plbossart**
CI check on @vinodkoul's fix

### CODE REVIEW

**Comment by plbossart** [comment]
Looks ok to me, I didn't find any other examples of read-modify-write.
@bardliao can you double-check and provide a Tested-by when you are done?

**Comment by plbossart** [comment]
v2 of patches forced-pushed

**Comment by bardliao** [comment]
@plbossart I will get build error if #2298 is applied. 
```
file included from ./include/linux/soundwire/sdw.h:8:0,
                 from sound/soc/codecs/rt1316-sdw.h:12,
                 from sound/soc/codecs/rt1316-sdw.c:19:
./include/linux/bitfield.h:93:2: error: braced-group within expression allowed only inside a function
  ({        \
  ^
./include/linux/soundwire/sdw_registers.h:334:2: note: in expansion of macro ‘FIELD_PREP’
  FIELD_PREP(GENMASK(24, 22), FIELD_GET(GENMASK(2, 0), (fun))) | \
  ^~~~~~~~~~
sound/soc/codecs/rt1316-sdw.h:102:4: note: in expansion of macro ‘SDW_SDCA_CTL’
  { SDW_SDCA_CTL(FUN_SMART_AMP, RT1316_SDCA_ENT_UDMPU21, RT1316_SDCA_CTL_UDMPU_CLUSTER, 0), 0x00 },
    ^~~~~~~~~~~~
./include/linux/bitfield.h:93:2: error: braced-group within expression allowed only inside a function
  ({        \
  ^
```

**Comment by bardliao** [comment]
Sorry, I thought the fix is for sdca codecs but obviously not. Verified it on TGL-U laptop.

**Comment by plbossart** [comment]
ok, this is upstream so closing

**Pull request closed without merging**
