### PR TITLE
Merge/sound upstream 20210419

### PR DESCRIPTION
**Pull request by plbossart**
Last merge before the next merge window.

I had a couple of conflicts with the dai_config/curr_config, @ranj063 please double-check the code is what you expect.

topic/sof-dev-rebase and tag sof-dev-rebase-20210419 pushed.

### CODE REVIEW

**Comment by plbossart** [comment]
Not sure why MINNOW_BOARD is starting to behave, will restart a test.

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by ranj063** [comment]
> Last merge before the next merge window.
> 
> I had a couple of conflicts with the dai_config/curr_config, @ranj063 please double-check the code is what you expect.
> 
> topic/sof-dev-rebase and tag sof-dev-rebase-20210419 pushed.

looks good to me!

**Review by kv2019i — APPROVED** [review]
Local test on JSL ok and the the dai_config merge seems ok as well.

**Comment by fredoh9** [comment]
Extended test results is also available. internal test 3370. multi-pipeline-capture.sh on TGLU_VOLT_SDW, this error is occurred.

```
[  719.496631] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[  719.496841] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: ipc error for 0x60050000 size 12
[  719.496854] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg=0x240000 successful
[  719.496860] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: error at soc_component_trigger on 0000:00:1f.3: -22
[  719.496866] kernel:  Amplifier Reference: ASoC: trigger FE cmd: 0 failed: -22
[  719.496926] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: pcm: free stream 3 dir 1
[  719.496932] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[  719.497243] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[  719.497351] kernel: sdw_deprepare_stream: subdevice #0-Capture: inconsistent state state 3
[  719.497386] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[  719.497595] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[  719.497615] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: pcm: close stream 3 dir 1
[  719.547539] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  719.547575] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  720.047545] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  720.047583] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  720.842734] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: pcm: trigger stream 2 dir 0 cmd 0
[  720.842750] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[  720.842871] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: ipc error for 0x60050000 size 12
[  720.842894] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg=0x140000 successful
[  720.842899] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: error at soc_component_trigger on 0000:00:1f.3: -22
[  720.842905] kernel:  Speaker: ASoC: trigger FE cmd: 0 failed: -22
```

**Comment by plbossart** [comment]
> Extended test results is also available. internal test 3370. multi-pipeline-capture.sh on TGLU_VOLT_SDW, this error is occurred.
> 
> ```
> [  719.496631] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
> [  719.496841] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: ipc error for 0x60050000 size 12
> [  719.496854] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg=0x240000 successful
> [  719.496860] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: error at soc_component_trigger on 0000:00:1f.3: -22
> [  719.496866] kernel:  Amplifier Reference: ASoC: trigger FE cmd: 0 failed: -22
> [  719.496926] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: pcm: free stream 3 dir 1
> [  719.496932] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
> [  719.497243] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
> [  719.497351] kernel: sdw_deprepare_stream: subdevice #0-Capture: inconsistent state state 3
> [  719.497386] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
> [  719.497595] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
> [  719.497615] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: pcm: close stream 3 dir 1
> [  719.547539] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
> [  719.547575] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
> [  720.047545] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
> [  720.047583] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
> [  720.842734] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: pcm: trigger stream 2 dir 0 cmd 0
> [  720.842750] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
> [  720.842871] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: ipc error for 0x60050000 size 12
> [  720.842894] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg=0x140000 successful
> [  720.842899] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: error at soc_component_trigger on 0000:00:1f.3: -22
> [  720.842905] kernel:  Speaker: ASoC: trigger FE cmd: 0 failed: -22
> ```

I think that's a know error, not added by this upstream merge. see https://github.com/thesofproject/linux/issues/2835

**Comment by plbossart** [comment]
@fredoh9 the error you mentioned is also seen in the daily test 3353 so I really don't think it's added by this merge PR

@ranj063 do you have a Volteer SDW device? It seems the IPC error is still there and it was root caused to one of your PRs in #2835.

**Comment by ranj063** [comment]
> @fredoh9 the error you mentioned is also seen in the daily test 3353 so I really don't think it's added by this merge PR
> 
> @ranj063 do you have a Volteer SDW device? It seems the IPC error is still there and it was root caused to one of your PRs in #2835.

@plbossart the latest muli CPU DAI fixes were confimed to fix #2835 https://github.com/thesofproject/linux/issues/2821#issuecomment-817438901

Let me check with @fredoh9 about the error he's seeing

**Comment by fredoh9** [comment]
@plbossart you're right. this error was reported in previously daily test. then nothing to do with this pr.

**Comment by ranj063** [comment]
> @ranj063 do you have a Volteer SDW device? It seems the IPC error is still there and it was root caused to one of your PRs in #2835.

@plbossart the IPC error is misleading in this case. This isnt the same issue as #2835. There was an xrun that caused the pipeline to be stopped in the FW and then when the app closes the stream, the STOP IPC results in an error because it was already stopped.

**Comment by plbossart** [comment]
> > @ranj063 do you have a Volteer SDW device? It seems the IPC error is still there and it was root caused to one of your PRs in #2835.
> 
> @plbossart the IPC error is misleading in this case. This isnt the same issue as #2835. There was an xrun that caused the pipeline to be stopped in the FW and then when the app closes the stream, the STOP IPC results in an error because it was already stopped.

I don't know what is going but do you agree with me and Fred that this test case never worked and was broken before this PR?

**Comment by ranj063** [comment]
> I don't know what is going but do you agree with me and Fred that this test case never worked and was broken before this PR?

please give me a few minutes @plbossart . let me work with @fredoh9 to confirm this

**Comment by ranj063** [comment]
> I don't know what is going but do you agree with me and Fred that this test case never worked and was broken before this PR?

@plbossart yes, confirmed with Fred that the issue exists with the daily test even before ths PR. So this one is good to go.

**Comment by plbossart** [comment]
alright, let's merge then. We'll have to spend time on those pesky Volteer issues, this platform needs more attention

**Pull request merged**
