### PR TITLE
Merge/sound upstream 20240822

### PR DESCRIPTION
**Pull request by bardliao**
There are some conflicts. I skipped "ASoC: Intel: Skylake: remove HDA machine driver support" since "ASoC: Intel: Drop skl_machine_pdata usage" is already upstream. And I fix some conflict related to AMD ACP 7.0 stuff. @brentlu @vijendarmukunda could you take a look?

### CODE REVIEW

**Comment by bardliao** [comment]
@brentlu Removing comments in snd_soc_acpi_intel_hda_machines[] is now done at https://github.com/thesofproject/linux/commit/a4498f3a05f9980ef65b0edd1ac3116db7d778d6

**Comment by vijendarmukunda** [comment]
@bardliao : PR#5103 changes slightly got modified and further split in to some more patches when it was submitted to asoc tree.
You can drop PR#5103 changes and rebase latest commits from asoc for-next tree.

**Comment by brentlu** [comment]
Looks good to me since entire skylake driver got removed...

**Review by vijendarmukunda — APPROVED** [review]
@bardliao  I can find only change is in acp.c file , a comment addition. LGTM

**Pull request merged**
