### PR TITLE
ASoC: es8316: fix suspend/resume sync issue

### PR DESCRIPTION
**Pull request by plbossart**
Error reported by the Intel CI during upstream merge in PR #https://github.com/thesofproject/linux/pull/3859

@fredoh9 can you give this a try with the stable 2.2 firmware?

@ujfalusi @bardliao @yangxiaohua2009 comments welcome. I really have no idea if this is an acceptable fix.

### CODE REVIEW

**Comment by bardliao** [comment]
single_read/single_write should be set if the codec doesn't support bulk read/write

**Comment by yangxiaohua2009** [comment]
Yes the fix should work. CS42l42 has [the same issue](https://patchwork.kernel.org/project/alsa-devel/patch/20210511132855.27159-1-rf@opensource.cirrus.com/#24169689).

I have no idea why some platforms use bulk write by default and others don't.

**Comment by plbossart** [comment]
@yangxiaohua2009 the default is that bulk_read/write is used, unless explicitly disabled with the .use_single_read/write. So the question is whether this bulk_read/write is supported *in hardware*, and if no we do need to set those two flags. Can you check the hardware capabilities?

**Comment by yangxiaohua2009** [comment]
Yes these two flags are needed. ES8336 only supports I2C read/write one byte a time.

**Comment by plbossart** [comment]
Thanks @yangxiaohua2009, I updated the commit message. You should have an invite to join the SOF project, that will enable you to provide you approval directly in GitHub.

**Review by ujfalusi — APPROVED** [review]

**Comment by fredoh9** [comment]
missed the notification. Will run the test with stable-v2.2.

**Comment by fredoh9** [comment]
just triggered internal test 15531 now. Had to wait as daily test uses same device pool. Will update the results.

**Review by fredoh9 — APPROVED** [review]
test result on JSL_ES8336_HDA is GOOD!

**Comment by plbossart** [comment]
thanks @fredoh9. Let's wait for @bardliao's review.

**Review by bardliao — APPROVED** [review]

**Pull request merged**
