### PR TITLE
ASoC: SOF: OF: Avoid reverse module dependency

### PR DESCRIPTION
**Pull request by dbaluta**
Similar with commit 8a49cd11e68ed0 ("ASoC: SOF: ACPI: avoid reverse
module dependency") we will be having hardware specific drivers that
link against a common "helper" framework.

sof-of-dev.c becomes a library with the interface defined in the newly
created file sof-of-dev.h.

This is the final step started with Kconfig simplification in
commit 7548a391c53ca ("ASoC: SOF: i.MX: simplify Kconfig")

Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>

### CODE REVIEW

**Comment by plbossart** [comment]
missing include @dbaluta, that leads to sparse complaining about definitions

**Review by paulstelian97 — APPROVED** [review]

**Review by ujfalusi — APPROVED** [review]
@dbaluta, thank you, looks good!

**Comment by dbaluta** [comment]
@yaochunhung care to test this patch for MTK platforms?

**Comment by yaochunhung** [comment]
@dbaluta OK, I will verify it. Thanks

**Review by plbossart — APPROVED** [review]

**Pull request merged**
