### PR TITLE
 ASoC: SOF: topology: Fix memory leak of scontrol->name 

### PR DESCRIPTION
**Pull request by ujfalusi**
The scontrol->name is allocated with kstrdup, it must be freed before the
scontrol is freed to avoid leaking memory.

Signed-off-by: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>

### CODE REVIEW

**Review by kv2019i — COMMENTED** [review]
@ujfalusi Can you add a fixes tag, so this gets backported to all stable trees?

**Comment by ujfalusi** [comment]
Changes since v1:
- fixes tag added (with upstream SHA)

**Review by plbossart — DISMISSED** [review]

**Comment by ranj063** [comment]
> Changes since v1:
> 
> * fixes tag added (with upstream SHA)

@ujfalusi I think there was a fix submitted upstream for this already. Can you pleas check?

**Comment by ujfalusi** [comment]
> > Changes since v1:
> > 
> > * fixes tag added (with upstream SHA)
> 
> @ujfalusi I think there was a fix submitted upstream for this already. Can you pleas check?

I can not find any fix for this upstream, do you have a link? We should pick that instead.

**Comment by ranj063** [comment]
> I can not find any fix for this upstream, do you have a link? We should pick that instead.

can't find it. maybe Im confused. Lets go with this.

**Review by ranj063 — DISMISSED** [review]

**Review by dbaluta — DISMISSED** [review]

**Comment by bardliao** [comment]
Do we need to free `scontrol->name` in `sof_widget_unload`, too?

**Comment by ujfalusi** [comment]
> Do we need to free `scontrol->name` in `sof_widget_unload`, too?

Yes, that is the one which is leaking memory, kmemleak was really confused about this, it was pointing to different path.

**Comment by ujfalusi** [comment]
Changes since v2:
- The real memory leak was happening via the sof_mixer_unload which failed to free scontrol->name, free it up on that path as well.

**Review by plbossart — APPROVED** [review]

**Review by ranj063 — APPROVED** [review]

**Pull request merged**
