### PR TITLE
[TEST] soundwire: intel: waiting for all Slaves be attached

### PR DESCRIPTION
**Pull request by bardliao**
Everything should be ready when resume function returns.

Signed-off-by: Bard Liao <yung-chuan.liao@linux.intel.com>

### CODE REVIEW

**Comment by naveen-manohar** [comment]
Hi @bardliao 
Still observe the issue with enumeration_complete 
[dmesg_enumeration_comp-fail.log](https://github.com/thesofproject/linux/files/5427822/dmesg_enumeration_comp-fail.log)

**Comment by naveen-manohar** [comment]
Tried another experiment with both ( https://github.com/thesofproject/linux/pull/2521 + https://github.com/thesofproject/linux/pull/2521 ), still issue persists
LOG: 
[dmesg_2521--2526-fail.log](https://github.com/thesofproject/linux/files/5427895/dmesg_2521--2526-fail.log)

```
[   35.335379] max98373 sdw:1:19f:8373:0:7: sdw_modify_slave_status: signaling completion for Slave 1
[   35.840560] max98373 sdw:1:19f:8373:0:3: enumeration not complete, timed out
[   35.840571] max98373 sdw:1:19f:8373:0:7: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:7: -16
[   35.840610] soundwire sdw-master-1: SDW_SCP_INTMASK1 write failed:-16
[   35.840613] soundwire sdw-master-1: Slave 1 initialization failed: -16
[   35.840616] max98373 sdw:1:19f:8373:0:3: sdw_modify_slave_status: signaling completion for Slave 2
[   35.840617] soundwire sdw-master-1: SDW_SCP_INTMASK1 write failed:-16
[   35.840618] soundwire sdw-master-1: Slave 2 initialization failed: -16
[   35.840662] max98373 sdw:1:19f:8373:0:7: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:7: -16
[   35.840695] max98373 sdw:1:19f:8373:0:7: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:7: -16
[   35.841016] max98373 sdw:1:19f:8373:0:3: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:3: -16
[   35.841034] max98373 sdw:1:19f:8373:0:3: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:3: -16
[   35.841042] max98373 sdw:1:19f:8373:0:3: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:3: -16
[   35.842876] max98373 sdw:1:19f:8373:0:7: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:7: -16
[   35.842893] max98373 sdw:1:19f:8373:0:7: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:7: -16
[   35.842904] max98373 sdw:1:19f:8373:0:7: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:7: -16
[   35.843122] max98373 sdw:1:19f:8373:0:3: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:3: -16
[   35.843138] max98373 sdw:1:19f:8373:0:3: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:3: -16
[   35.843144] max98373 sdw:1:19f:8373:0:3: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:3: -16

```

**Comment by RanderWang** [comment]
@naveen-manohar  I found some errors in sdw driver before ASoC error. Is this ASoC error caused by these sdw errors ?

**Comment by naveen-manohar** [comment]
> @naveen-manohar I found some errors in sdw driver before ASoC error. Is this ASoC error caused by these sdw errors ?

Hi @RanderWang , I stress tested recipe (#2521 + #2526) for 10 iterations and observed following sdw issue only with 1st & 10th iteration, all others only reported ASoC.
`SDW_SCP_INTMASK1 write failed:-16`
Note: Observed this sdw error only with experiment -  [#2521 + #2526]

**Comment by plbossart** [comment]
I don't think this is needed @bardliao. If we do a pm_runtime_get_sync() on the codec driver, it will by design resume all parents, and in the codec resume function we wait for the device to be initialized.

If resuming the codec driver does not work, something is not right in our sequence. We don't need to change the sequence on the parent side, it's at the codec level that we have a problem.

**Pull request closed without merging**
