### PR TITLE
Merge/sound upstream 20220408

### PR DESCRIPTION
**Pull request by plbossart**
This is the first version based on v5.18-rc1, so we need more tests than usual.

the companion branch topic/sof-dev-rebase was updated with tag sof-dev-rebase-20220408, still 150 patches to upstream.

### CODE REVIEW

**Comment by plbossart** [comment]
tested on SKL, no regressions found.

**Comment by ujfalusi** [comment]
All devices with nvme drivers have failures: `kernel: nvme0: Admin Cmd(0x2), I/O Error (sct 0x0 / sc 0x2)`

which is likely related to: https://lore.kernel.org/linux-nvme/F2ACCD82-052F-473F-9882-1703147FA662@oracle.com/T/#m14a43e0c73c589876d0cf20680c792e8d2ef5063

a patch is in works, but nothing is final: https://lore.kernel.org/linux-nvme/5a6ca93f-0542-762b-587f-312c9e429626@nvidia.com/T/#t

Other than that, it looks fine.

**Comment by plbossart** [comment]
Added minor fixup and pushed a matching new tag sof-dev-rebase-20220411-2

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
Now that https://github.com/thesofproject/sof-test/pull/889 is merged, we should see better results with suspend-resume.

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
using private links since SOF CI doesn't show the results

https://sof-ci.sh.intel.com/#/result/planresultdetail/11758?model=CML_SKU0955_HDA&testcase=check-suspend-resume-with-playback-5 shows a suspend-resume error (rtcwake: write failed), as usual preceded by errors that don't seem audio related

````
[ 1214.868106] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: fw_state change: 6 -> 0
[ 1214.870859] kernel: intel_pch_thermal 0000:00:12.0: CPU-PCH current temp [55C] higher than the threshold temp [50C], sleep 1 times for 100 ms duration
[ 1214.878025] kernel: sd 0:0:0:0: [sda] Synchronizing SCSI cache
[ 1214.977974] kernel: intel_pch_thermal 0000:00:12.0: CPU-PCH current temp [54C] higher than the threshold temp [50C], sleep 2 times for 100 ms duration
[ 1215.058321] kernel: sd 0:0:0:0: [sda] Stopping disk
[ 1215.081970] kernel: intel_pch_thermal 0000:00:12.0: CPU-PCH current temp [53C] higher than the threshold temp [50C], sleep 3 times for 100 ms duration
[ 1215.185975] kernel: intel_pch_thermal 0000:00:12.0: CPU-PCH current temp [53C] higher than the threshold temp [50C], sleep 4 times for 100 ms duration
[ 1215.289965] kernel: intel_pch_thermal 0000:00:12.0: CPU-PCH current temp [53C] higher than the threshold temp [50C], sleep 5 times for 100 ms duration
[ 1215.393965] kernel: intel_pch_thermal 0000:00:12.0: CPU-PCH current temp [53C] higher than the threshold temp [50C], sleep 6 times for 100 ms duration
[ 1215.497961] kernel: intel_pch_thermal 0000:00:12.0: CPU-PCH current temp [55C] higher than the threshold temp [50C], sleep 7 times for 100 ms duration
[ 1215.601962] kernel: intel_pch_thermal 0000:00:12.0: CPU-PCH current temp [53C] higher than the threshold temp [50C], sleep 8 times for 100 ms duration
[ 1215.705966] kernel: intel_pch_thermal 0000:00:12.0: CPU-PCH current temp [54C] higher than the threshold temp [50C], sleep 9 times for 100 ms duration
[ 1215.809958] kernel: intel_pch_thermal 0000:00:12.0: CPU-PCH current temp [54C] higher than the threshold temp [50C], sleep 10 times for 100 ms duration
[ 1215.913957] kernel: intel_pch_thermal 0000:00:12.0: CPU-PCH is hot [53C] even after delay, continue to suspend. S0ix might fail
[ 1216.032840] kernel: PM: Some devices failed to suspend, or early wake event detected
[ 1216.033715] kernel: sd 0:0:0:0: [sda] Starting disk
````

**Comment by plbossart** [comment]
We have to redo the tests, which is going to make CI even less responsive I guess...

**Comment by plbossart** [comment]
SOFCI TEST

**Review by ranj063 — APPROVED** [review]

**Comment by plbossart** [comment]
ok, let's merge and see what the daily tests say.

**Pull request merged**
