### PR TITLE
ASoC: SOF: Intel: byt: fixup topology filename for BYT-CR

### PR DESCRIPTION
**Pull request by plbossart**
On Baytrail-CR, SSP0 needs to be used instead of SSP0.  The
substitution is assumed to be done in the topology file.

When Baytrail-CR is detected, add -ssp0 suffix to the topology file
name so that the topology code picks up the correct file.

Tested on Asus T100HAN

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

### CODE REVIEW

**Comment by ranj063** [comment]
LGTM @plbossart  except the commit message has a typo where it says ssp0 in both places

**Comment by xiulipan** [comment]
@plbossart So the BE dai name will still  be `SSP2-Codec` as I found the change in https://github.com/thesofproject/sof/pull/2142 do not change the dai name.

**Comment by plbossart** [comment]
> LGTM @plbossart except the commit message has a typo where it says ssp0 in both places

thanks for the review, fixed now

**Comment by plbossart** [comment]
merging despite no CI, I can't wait.

**Pull request merged**
