### PR TITLE
kmod/travis: fail build on module errors

### PR DESCRIPTION
**Pull request by plbossart**
This is a companion patch to https://github.com/thesofproject/linux/pull/2450
we want to detect all module issues moving forward.

This PR should fail on the ARM build.

### CODE REVIEW

**Comment by plbossart** [comment]
Mission accomplished: the build failed as expected due to missing module license.

**Review by marc-hb — COMMENTED** [review]
The very small travis.yml change obviously LGTM; just remind me to submit a follow-up patch to move the common VARIABLES to a new, common section. I think this PR moves the code just past the point where a common section starts making sense.

**Comment by plbossart** [comment]
> The very small travis.yml change obviously LGTM; just remind me to submit a follow-up patch to move the common VARIABLES to a new, common section. I think this PR moves the code just past the point where a common section starts making sense.

Yes indeed.

**Review by kv2019i — APPROVED** [review]
And Travis fails as expected. Looks good!

**Comment by plbossart** [comment]
let's not merge just yet, trying to clarify directions with kbuild folks upstream

**Comment by plbossart** [comment]
PR abandoned, no response from kmod maintainer. Oh well.

**Pull request closed without merging**
