### PR TITLE
ASoC: Intel: sof_sdw: add Bluetooth offload support

### PR DESCRIPTION
**Pull request by yongzhi1**
AlderLake has support for BT audio offload capability,
so add the quirks to use it.

Signed-off-by: Yong Zhi <yong.zhi@intel.com>

### CODE REVIEW

**Comment by yongzhi1** [comment]
@Vamshigopal will soon submit "ASoC: Intel: sof_sdw: add quirk support for Brya", upon which this patch will be rebased with BT offload support for Brya as well. Thanks!

**Comment by plbossart** [comment]
Looks good to me @yongzhi1.

One nit-pick on the commit message: it's my understanding that some versions of ADL have support for BT offload. I think it was @kv2019i who mentioned this? We should probably be clearer that adding this dailink by default in the machine driver does not actually enable BT offload, you need a topology file that will refer to that dailink, and on top of this you need the BT stack to enable this PCM as well.

**Comment by yongzhi1** [comment]
Ack, let me work on the commit message, thanks!

**Comment by kv2019i** [comment]
@plbossart wrote: 
> One nit-pick on the commit message: it's my understanding that some versions of ADL have support for BT offload. I think it was @kv2019i who mentioned this? We should probably be clearer that adding this dailink by default in the machine driver does not actually enable BT offload, you need a topology file that will refer to that dailink, and on top of this you need the BT stack to enable this PCM as well.

Ack, this is a good comment. This feature needs to be enabled in platform firmware (including the pinmux), the BT hw solution needs to be in place and you need support in the BT stack. So this patch enables the audio part for a specific DMI configuration.

**Review by kv2019i — CHANGES_REQUESTED** [review]
This looks good to go (together with the FW tplg change). Can you remove the draft-status and update the commit? Something in the  lines of "add Bluetooth for ADL platforms" and then in body "Add Bluetooth capability support to the Alder Lake reference platform." I believe that's inline with the text we've used before. Other ADL systems may choose differently

**Comment by yongzhi1** [comment]
The changes will be added in https://github.com/thesofproject/linux/pull/2905, so close this one.

**Pull request closed without merging**
