### PR TITLE
ASoC: SOF: remove workaround for HDA

### PR DESCRIPTION
**Pull request by RanderWang**
The correct sequence to initialize HDA is i915 should
be initialized before hda bus

Signed-off-by: Rander Wang <rander.wang@linux.intel.com>

### CODE REVIEW

**Comment by RanderWang** [comment]
Test on WHL with HDA + SOF, pass

**Comment by plbossart** [comment]
Looks good, thanks. @keqiaozhang @ranj063 can we try this on GeminiLake just to be sure?

**Comment by RanderWang** [comment]
rebase my patch, thanks for review

**Comment by plbossart** [comment]
@ranj063 can you run a quick smoke test with this, I have no reports on GLK

**Comment by RanderWang** [comment]
rebase my patch, thanks.

**Comment by ranj063** [comment]
@plbossart @RanderWang sorry missed this earlier. Tested to work fine on GLK now.

**Pull request merged**
