### PR TITLE
Merge/sound upstream 20240103

### PR DESCRIPTION
**Pull request by plbossart**
We have quite a backlog of patches since December 4, this first upstream merge should help check for regression and organize the next kernel cycle (we are at -rc8 so in theory the merge window closes in 20 days).

sof-dev-rebase-20240103 pushed as well.

### CODE REVIEW

**Comment by bardliao** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
Complete failure for https://sof-ci.01.org/linuxpr/PR4759/build877/devicetest/index.html?model=GLK_BOB_DA7219-ipc3&testcase=verify-kernel-boot-log on sh-glk-bob-da7219-01

Not sure if this is a bad device or a kernel issue?

Let's redo the test.

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
Confirmed issue on GLK Bobba https://sof-ci.01.org/linuxpr/PR4759/build889/devicetest/index.html

@keqiaozhang @aiChaoSONG @mengdonglin can I please ask that you double check if this device behaves correctly and it's possible to run a quick regression. I unfortunately don't have a device with me and remote bisect with a device located in China is going to take eons. Thanks!

**Comment by bardliao** [comment]
@plbossart Here is the kernel log.
```
[   17.447750] snd_sof:sof_machine_register: sof-audio-pci-intel-apl 0000:00:0e.0: created machine glk_da7219_mx98357a
[   17.448076] snd_sof_pci:sof_pci_probe_complete: sof-audio-pci-intel-apl 0000:00:0e.0: Completing SOF PCI probe
[   17.559614] BUG: kernel NULL pointer dereference, address: 0000000000000000
[   17.559626] #PF: supervisor read access in kernel mode
[   17.559630] #PF: error_code(0x0000) - not-present page
[   17.559632] PGD 0 P4D 0 
[   17.559638] Oops: 0000 [#1] PREEMPT SMP PTI
[   17.559642] CPU: 1 PID: 238 Comm: systemd-udevd Not tainted 6.7.0-rc3+ #867
[   17.559646] Hardware name: Google Bobba/Bobba, BIOS Google_Bobba.11825.0.2019_03_06_2015 03/06/2019
[   17.559649] RIP: 0010:broxton_audio_probe+0xd7/0x2f0 [snd_soc_sst_bxt_da7219_max98357a]
[   17.559666] Code: c1 8f c8 c0 48 c7 42 10 cc 8f c8 c0 48 05 d8 00 00 00 49 39 c2 74 58 48 8b 50 20 b9 05 00 00 00 4c 89 cf 4c 8b 42 10 4c 89 c6 <f3> a6 0f 97 c2 80 da 00 84 d2 74 c3 48 c7 c7 6a 8f c8 c0 b9 0c 00
[   17.559670] RSP: 0000:ffffc90000a77ba8 EFLAGS: 00010282
[   17.559674] RAX: ffffffffc0c826c0 RBX: ffff88811664e000 RCX: 0000000000000005
[   17.559677] RDX: ffffffffc0c83c40 RSI: 0000000000000000 RDI: ffffffffc0c88fbc
[   17.559680] RBP: ffff888110fe4de8 R08: 0000000000000000 R09: ffffffffc0c88fbc
[   17.559682] R10: ffffffffc0c83368 R11: 0000000000000010 R12: 0000000000000000
[   17.559684] R13: ffff88811664e010 R14: ffff888112ab6788 R15: ffff88810d4651a8
[   17.559687] FS:  00007ff3b22948c0(0000) GS:ffff88817bc00000(0000) knlGS:0000000000000000
[   17.559689] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   17.559692] CR2: 0000000000000000 CR3: 0000000102e3e000 CR4: 0000000000350ef0
[   17.559694] Call Trace:
[   17.559699]  <TASK>
[   17.559704]  ? __die+0x24/0x70
[   17.559712]  ? page_fault_oops+0x15b/0x440
[   17.559717]  ? klist_next+0x160/0x170
[   17.559723]  ? local_clock+0x15/0x30
[   17.559728]  ? lock_release+0x25c/0x3b0
[   17.559733]  ? exc_page_fault+0x64/0x190
[   17.559739]  ? asm_exc_page_fault+0x26/0x30
[   17.559748]  ? broxton_audio_probe+0xd7/0x2f0 [snd_soc_sst_bxt_da7219_max98357a]
[   17.559756]  ? broxton_audio_probe+0x7b/0x2f0 [snd_soc_sst_bxt_da7219_max98357a]
[   17.559764]  platform_probe+0x5c/0xd0
[   17.559770]  really_probe+0x1a2/0x410
[   17.559776]  __driver_probe_device+0x78/0x160
[   17.559780]  driver_probe_device+0x1e/0x90
[   17.559784]  __driver_attach+0xda/0x1d0
[   17.559788]  ? __pfx___driver_attach+0x10/0x10
[   17.559792]  bus_for_each_dev+0x7c/0xd0
[   17.559797]  bus_add_driver+0x119/0x220
[   17.559801]  driver_register+0x60/0x120
[   17.559805]  ? __pfx_broxton_audio_init+0x10/0x10 [snd_soc_sst_bxt_da7219_max98357a]
[   17.559813]  do_one_initcall+0x5c/0x270
[   17.559819]  ? kmalloc_trace+0xa8/0xb0
[   17.559825]  do_init_module+0x64/0x230
[   17.559831]  init_module_from_file+0x8b/0xd0
[   17.559838]  idempotent_init_module+0x18d/0x240
[   17.559844]  __x64_sys_finit_module+0x5b/0xb0
[   17.559848]  do_syscall_64+0x42/0xf0
[   17.559854]  entry_SYSCALL_64_after_hwframe+0x6e/0x76
[   17.559858] RIP: 0033:0x7ff3b298d69d
[   17.559863] Code: 5b 41 5c c3 66 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 63 a7 0f 00 f7 d8 64 89 01 48
[   17.559867] RSP: 002b:00007ffe9adc4138 EFLAGS: 00000246 ORIG_RAX: 0000000000000139
[   17.559871] RAX: ffffffffffffffda RBX: 0000562610c9d320 RCX: 00007ff3b298d69d
[   17.559873] RDX: 0000000000000000 RSI: 0000562610c8d150 RDI: 0000000000000010
[   17.559875] RBP: 0000000000020000 R08: 0000000000000000 R09: 0000000000000002
[   17.559877] R10: 0000000000000010 R11: 0000000000000246 R12: 0000562610c8d150
[   17.559880] R13: 0000562610ba53c0 R14: 0000000000000000 R15: 0000562610c8bd50
[   17.559885]  </TASK>
[   17.559886] Modules linked in: snd_soc_sst_bxt_da7219_max98357a(+) snd_soc_hdac_hdmi snd_soc_intel_hda_dsp_common snd_sof_probes snd_sof_ipc_msg_injector snd_sof_ipc_flood_test snd_soc_dmic snd_hda_codec_hdmi snd_sof_pci_intel_apl snd_sof_intel_hda_generic soundwire_intel soundwire_generic_allocation soundwire_cadence snd_sof_intel_hda_common snd_sof_intel_hda_mlink snd_sof_intel_hda snd_sof_pci snd_sof_xtensa_dsp snd_sof snd_sof_utils soundwire_bus snd_soc_avs x86_pkg_temp_thermal squashfs snd_soc_hda_codec intel_powerclamp snd_soc_skl snd_soc_hdac_hda i915 snd_hda_ext_core snd_soc_sst_ipc snd_soc_sst_dsp snd_soc_acpi_intel_match snd_soc_acpi snd_soc_da7219 snd_soc_max98357a i2c_algo_bit snd_intel_dspcfg drm_buddy snd_usb_audio snd_soc_core snd_seq_midi snd_intel_sdw_acpi snd_seq_midi_event snd_usbmidi_lib snd_hda_codec snd_compress regmap_i2c video processor_thermal_device_pci_legacy wmi snd_hwdep snd_rawmidi ttm snd_hda_core snd_seq processor_thermal_device processor_thermal_wt_hint processor_thermal_rfim
[   17.559956]  drm_display_helper snd_pcm snd_seq_device processor_thermal_rapl intel_rapl_common processor_thermal_wt_req processor_thermal_power_floor processor_thermal_mbox int3403_thermal drm_kms_helper snd_timer intel_soc_dts_iosf snd int340x_thermal_zone elan_i2c soundcore int3400_thermal acpi_thermal_rel fuse efivarfs ax88796b asix phylink usbnet spi_pxa2xx_platform mmc_block sdhci_pci i2c_hid_acpi xhci_pci intel_lpss_pci cqhci intel_lpss idma64 i2c_hid sdhci xhci_hcd mfd_core drm
[   17.560004] CR2: 0000000000000000
[   17.560007] ---[ end trace 0000000000000000 ]---
[   17.560010] RIP: 0010:broxton_audio_probe+0xd7/0x2f0 [snd_soc_sst_bxt_da7219_max98357a]
[   17.560018] Code: c1 8f c8 c0 48 c7 42 10 cc 8f c8 c0 48 05 d8 00 00 00 49 39 c2 74 58 48 8b 50 20 b9 05 00 00 00 4c 89 cf 4c 8b 42 10 4c 89 c6 <f3> a6 0f 97 c2 80 da 00 84 d2 74 c3 48 c7 c7 6a 8f c8 c0 b9 0c 00
[   17.560021] RSP: 0000:ffffc90000a77ba8 EFLAGS: 00010282
[   17.560024] RAX: ffffffffc0c826c0 RBX: ffff88811664e000 RCX: 0000000000000005
[   17.560026] RDX: ffffffffc0c83c40 RSI: 0000000000000000 RDI: ffffffffc0c88fbc
[   17.560028] RBP: ffff888110fe4de8 R08: 0000000000000000 R09: ffffffffc0c88fbc
[   17.560030] R10: ffffffffc0c83368 R11: 0000000000000010 R12: 0000000000000000
[   17.560032] R13: ffff88811664e010 R14: ffff888112ab6788 R15: ffff88810d4651a8
[   17.560035] FS:  00007ff3b22948c0(0000) GS:ffff88817bc00000(0000) knlGS:0000000000000000
[   17.560038] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   17.560040] CR2: 0000000000000000 CR3: 0000000102e3e000 CR4: 0000000000350ef0
[   17.560042] note: systemd-udevd[238] exited with irqs disabled
[   17.745163] asix 1-2.1:1.0 enx000ec6c68636: configuring for phy/internal link mode
[   22.427950] rfkill: input handler disabled
[   24.952867] asix 1-2.1:1.0 enx000ec6c68636: Link is Up - 100Mbps/Full - flow control rx/tx

```
[dmesg_bob.txt](https://github.com/thesofproject/linux/files/13842461/dmesg_bob.txt)

**Comment by plbossart** [comment]
wow, that's indeed a major regression, thanks @bardliao 

I don't see any machine driver changes, but there are da7219 changes since the last update

5f44de697383 ASoC: da7219: Support low DC impedance headset
ab5201e20c18 ASoC: da7219: Improve system suspend and resume handling

I am probably missing something but nothing else comes to my mind atm

**Comment by ujfalusi** [comment]
My hunch is around this: 13f58267cda3 ("ASoC: soc.h: don't create dummy Component via COMP_DUMMY()")
with combination of these: `strcmp(broxton_dais[i].codecs->dai_name, SOMETHING);`, it might be lethal...

@bardliao, this might work?
```diff
diff --git a/sound/soc/intel/boards/bxt_da7219_max98357a.c b/sound/soc/intel/boards/bxt_da7219_max98357a.c
index 816fad8c1ff0..9aa86ed6b22b 100644
--- a/sound/soc/intel/boards/bxt_da7219_max98357a.c
+++ b/sound/soc/intel/boards/bxt_da7219_max98357a.c
@@ -797,6 +797,9 @@ static int broxton_audio_probe(struct platform_device *pdev)
 		broxton_audio_card.name = "glkda7219max";
 		/* Fixup the SSP entries for geminilake */
 		for (i = 0; i < ARRAY_SIZE(broxton_dais); i++) {
+			if (!broxton_dais[i].codecs)
+				continue;
+
 			/* MAXIM_CODEC is connected to SSP1. */
 			if (!strcmp(broxton_dais[i].codecs->dai_name,
 				    BXT_MAXIM_CODEC_DAI)) {
@@ -822,6 +825,9 @@ static int broxton_audio_probe(struct platform_device *pdev)
 			broxton_audio_card.name = "cmlda7219max";
 
 		for (i = 0; i < ARRAY_SIZE(broxton_dais); i++) {
+			if (!broxton_dais[i].codecs)
+				continue;
+
 			/* MAXIM_CODEC is connected to SSP1. */
 			if (!strcmp(broxton_dais[i].codecs->dai_name,
 					BXT_MAXIM_CODEC_DAI)) {
```

**Comment by bardliao** [comment]
> My hunch is around this: [13f5826](https://github.com/thesofproject/linux/commit/13f58267cda3d6946c8f4de368ad5d4a003baa61) ("ASoC: soc.h: don't create dummy Component via COMP_DUMMY()") with combination of these: `strcmp(broxton_dais[i].codecs->dai_name, SOMETHING);`, it might be lethal...
> 
> @bardliao, this might work?
> 
> ```diff
> diff --git a/sound/soc/intel/boards/bxt_da7219_max98357a.c b/sound/soc/intel/boards/bxt_da7219_max98357a.c
> index 816fad8c1ff0..9aa86ed6b22b 100644
> --- a/sound/soc/intel/boards/bxt_da7219_max98357a.c
> +++ b/sound/soc/intel/boards/bxt_da7219_max98357a.c
> @@ -797,6 +797,9 @@ static int broxton_audio_probe(struct platform_device *pdev)
>  		broxton_audio_card.name = "glkda7219max";
>  		/* Fixup the SSP entries for geminilake */
>  		for (i = 0; i < ARRAY_SIZE(broxton_dais); i++) {
> +			if (!broxton_dais[i].codecs)
> +				continue;
> +
>  			/* MAXIM_CODEC is connected to SSP1. */
>  			if (!strcmp(broxton_dais[i].codecs->dai_name,
>  				    BXT_MAXIM_CODEC_DAI)) {
> @@ -822,6 +825,9 @@ static int broxton_audio_probe(struct platform_device *pdev)
>  			broxton_audio_card.name = "cmlda7219max";
>  
>  		for (i = 0; i < ARRAY_SIZE(broxton_dais); i++) {
> +			if (!broxton_dais[i].codecs)
> +				continue;
> +
>  			/* MAXIM_CODEC is connected to SSP1. */
>  			if (!strcmp(broxton_dais[i].codecs->dai_name,
>  					BXT_MAXIM_CODEC_DAI)) {
> ```

Unfortunately, no. I tested the change, but it didn't fix the issue.

**Comment by bardliao** [comment]
@ujfalusi @plbossart Below change can fix the issue,

```patch
diff --git a/sound/soc/intel/boards/bxt_da7219_max98357a.c b/sound/soc/intel/boards/bxt_da7219_max98357a.c
index 816fad8c1ff0..975ee5c91d9b 100644
--- a/sound/soc/intel/boards/bxt_da7219_max98357a.c
+++ b/sound/soc/intel/boards/bxt_da7219_max98357a.c
@@ -797,6 +797,9 @@ static int broxton_audio_probe(struct platform_device *pdev)
                broxton_audio_card.name = "glkda7219max";
                /* Fixup the SSP entries for geminilake */
                for (i = 0; i < ARRAY_SIZE(broxton_dais); i++) {
+                       if (!broxton_dais[i].codecs || !broxton_dais[i].codecs->dai_name)
+                               continue;
+
                        /* MAXIM_CODEC is connected to SSP1. */
                        if (!strcmp(broxton_dais[i].codecs->dai_name,
                                    BXT_MAXIM_CODEC_DAI)) {
@@ -822,6 +825,9 @@ static int broxton_audio_probe(struct platform_device *pdev)
                        broxton_audio_card.name = "cmlda7219max";

                for (i = 0; i < ARRAY_SIZE(broxton_dais); i++) {
+                       if (!broxton_dais[i].codecs || !broxton_dais[i].codecs->dai_name)
+                               continue;
+
                        /* MAXIM_CODEC is connected to SSP1. */
                        if (!strcmp(broxton_dais[i].codecs->dai_name,
                                        BXT_MAXIM_CODEC_DAI)) {
```

**Comment by bardliao** [comment]
> wow, that's indeed a major regression, thanks @bardliao
> 
> I don't see any machine driver changes, but there are da7219 changes since the last update
> 
> [5f44de6](https://github.com/thesofproject/linux/commit/5f44de697383fcc9a9a1a78f99e09d1838704b90) ASoC: da7219: Support low DC impedance headset [ab5201e](https://github.com/thesofproject/linux/commit/ab5201e20c181563774631258f737caeefed2364) ASoC: da7219: Improve system suspend and resume handling
> 
> I am probably missing something but nothing else comes to my mind atm

@plbossart This is related to 13f58267cda3d. `COMP_DUMMY()` has been changed and no longer assign `.dai_name`. We may need to check all existing machine drivers.
```
git grep COMP_DUMMY sound/soc/intel/boards/
sound/soc/intel/boards/bdw-rt5650.c:    DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/bdw-rt5677.c:    DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/bdw_rt286.c:SND_SOC_DAILINK_DEF(dummy, DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/bxt_da7219_max98357a.c:  DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/bxt_rt298.c:     DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/bytcht_cx2072x.c:        DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/bytcht_da7213.c: DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/bytcht_es8316.c: DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/bytcht_nocodec.c:        DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/bytcr_rt5640.c:  DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/bytcr_rt5651.c:  DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/bytcr_wm5102.c:  DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/cht_bsw_max98090_ti.c:   DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/cht_bsw_nau8824.c:       DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/cht_bsw_rt5645.c:        DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/cht_bsw_rt5672.c:        DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/glk_rt5682_max98357a.c:  DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/hsw_rt5640.c:SND_SOC_DAILINK_DEF(dummy, DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/kbl_da7219_max98357a.c:  DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/kbl_da7219_max98927.c:   DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/kbl_rt5660.c:    DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/kbl_rt5663_max98927.c:   DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/kbl_rt5663_rt5514_max98927.c:    DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/skl_nau88l25_max98357a.c:        DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/skl_nau88l25_ssm4567.c:  DAILINK_COMP_ARRAY(COMP_DUMMY()));
sound/soc/intel/boards/skl_rt286.c:     DAILINK_COMP_ARRAY(COMP_DUMMY()));
```

**Comment by ujfalusi** [comment]
> @ujfalusi @plbossart Below change can fix the issue,

Yes, see my test PR from Friday: https://github.com/thesofproject/linux/pull/4765

> 
> ```diff
> diff --git a/sound/soc/intel/boards/bxt_da7219_max98357a.c b/sound/soc/intel/boards/bxt_da7219_max98357a.c
> index 816fad8c1ff0..975ee5c91d9b 100644
> --- a/sound/soc/intel/boards/bxt_da7219_max98357a.c
> +++ b/sound/soc/intel/boards/bxt_da7219_max98357a.c
> @@ -797,6 +797,9 @@ static int broxton_audio_probe(struct platform_device *pdev)
>                 broxton_audio_card.name = "glkda7219max";
>                 /* Fixup the SSP entries for geminilake */
>                 for (i = 0; i < ARRAY_SIZE(broxton_dais); i++) {
> +                       if (!broxton_dais[i].codecs || !broxton_dais[i].codecs->dai_name)
> +                               continue;
> +
>                         /* MAXIM_CODEC is connected to SSP1. */
>                         if (!strcmp(broxton_dais[i].codecs->dai_name,
>                                     BXT_MAXIM_CODEC_DAI)) {
> @@ -822,6 +825,9 @@ static int broxton_audio_probe(struct platform_device *pdev)
>                         broxton_audio_card.name = "cmlda7219max";
> 
>                 for (i = 0; i < ARRAY_SIZE(broxton_dais); i++) {
> +                       if (!broxton_dais[i].codecs || !broxton_dais[i].codecs->dai_name)
> +                               continue;
> +
>                         /* MAXIM_CODEC is connected to SSP1. */
>                         if (!strcmp(broxton_dais[i].codecs->dai_name,
>                                         BXT_MAXIM_CODEC_DAI)) {
> ```

However we only need to check for `if (!broxton_dais[i].codecs->dai_name))`

**Comment by bardliao** [comment]
@plbossart @ujfalusi I checked all machine drivers above. In addition to bxt_da7219_max98357a.c, only bxt_rt298.c uses codecs->dai_name. Hope I didn't miss any machine driver.

**Comment by ujfalusi** [comment]
> > wow, that's indeed a major regression, thanks @bardliao
> > I don't see any machine driver changes, but there are da7219 changes since the last update
> > [5f44de6](https://github.com/thesofproject/linux/commit/5f44de697383fcc9a9a1a78f99e09d1838704b90) ASoC: da7219: Support low DC impedance headset [ab5201e](https://github.com/thesofproject/linux/commit/ab5201e20c181563774631258f737caeefed2364) ASoC: da7219: Improve system suspend and resume handling
> > I am probably missing something but nothing else comes to my mind atm
> 
> @plbossart This is related to [13f5826](https://github.com/thesofproject/linux/commit/13f58267cda3d6946c8f4de368ad5d4a003baa61). `COMP_DUMMY()` has been changed and no longer assign `.dai_name`. We may need to check all existing machine drivers.
> 
> ```
> git grep COMP_DUMMY sound/soc/intel/boards/
> sound/soc/intel/boards/bdw-rt5650.c:    DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/bdw-rt5677.c:    DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/bdw_rt286.c:SND_SOC_DAILINK_DEF(dummy, DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/bxt_da7219_max98357a.c:  DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/bxt_rt298.c:     DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/bytcht_cx2072x.c:        DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/bytcht_da7213.c: DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/bytcht_es8316.c: DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/bytcht_nocodec.c:        DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/bytcr_rt5640.c:  DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/bytcr_rt5651.c:  DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/bytcr_wm5102.c:  DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/cht_bsw_max98090_ti.c:   DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/cht_bsw_nau8824.c:       DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/cht_bsw_rt5645.c:        DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/cht_bsw_rt5672.c:        DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/glk_rt5682_max98357a.c:  DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/hsw_rt5640.c:SND_SOC_DAILINK_DEF(dummy, DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/kbl_da7219_max98357a.c:  DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/kbl_da7219_max98927.c:   DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/kbl_rt5660.c:    DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/kbl_rt5663_max98927.c:   DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/kbl_rt5663_rt5514_max98927.c:    DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/skl_nau88l25_max98357a.c:        DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/skl_nau88l25_ssm4567.c:  DAILINK_COMP_ARRAY(COMP_DUMMY()));
> sound/soc/intel/boards/skl_rt286.c:     DAILINK_COMP_ARRAY(COMP_DUMMY()));
> ```

`sound/soc/intel/boards/bxt_rt298.c` is affected as well for sure because of
```c
607		if (!strncmp(card->dai_link[i].codecs->name, "i2c-INT343A:00",
```

**Comment by plbossart** [comment]
tests are mostly good except for ONE timeout. Let's merge.

Thanks @ujfalusi and @bardliao for your help in root-causing the GLK regression.

**Pull request merged**
