### PR TITLE
ACPI: add helper to read 64-bit address

### PR DESCRIPTION
**Pull request by plbossart**
Based on comment from @charleskeepax 

@andy-shev comments?

### CODE REVIEW

**Review by ujfalusi — APPROVED** [review]

**Review by bardliao — APPROVED** [review]

**Review by charleskeepax — APPROVED** [review]

**Comment by andy-shev** [comment]
> Based on comment from @charleskeepax
> 
> @andy-shev comments?

Sure. The idea of the initial helper was to have more users that want to retrieve either `"reg"` (OF) or `_ADR` (ACPI) value (if you look at the current users). Since all of them so far are using 32-bit version, and there only three of them, I would rename original helper to have `_u32` in its name, since we might want to have 64-bit version of the common helper as well. Otherwise I have no objections.

**Comment by plbossart** [comment]
@andy-shev I thought about renaming but that'd be interesting with changes across 3 subsystems, in addition to ACPI.

````
drivers/i2c/muxes/i2c-mux-gpio.c:                       rc = acpi_get_local_address(ACPI_HANDLE_FWNODE(child), values + i);
drivers/net/ethernet/freescale/dpaa2/dpaa2-mac.c:                       err = acpi_get_local_address(ACPI_HANDLE_FWNODE(child), &id);
drivers/net/mdio/acpi_mdio.c:           ret = acpi_get_local_address(ACPI_HANDLE_FWNODE(child), &addr);
````

I try to avoid such cross-tree changes since they take time. I already have changes across ACPI, ASoC, ALSA, SoundWire which could be fun to deal with :-)

Maybe we can rename the original helper with u32 in a follow-up patch, to avoid having 7 subsystems involved at the same time.

**Comment by andy-shev** [comment]
I'm fine with doing this in the followup, but please send them as a series, so the maintainers will be at least aware of this change.

**Comment by plbossart** [comment]
> I'm fine with doing this in the followup, but please send them as a series, so the maintainers will be at least aware of this change.

Not sure I understand, a rename is usually a single patch, or we need to add a new helper, do the rename and then remove the old helper. Is this what you meant by 'series' @andy-shev ?

**Comment by andy-shev** [comment]
> > I'm fine with doing this in the followup, but please send them as a series, so the maintainers will be at least aware of this change.
> 
> Not sure I understand, a rename is usually a single patch, or we need to add a new helper, do the rename and then remove the old helper. Is this what you meant by 'series' @andy-shev ?

I meant to add that patch to this series.

**Pull request merged**
