### PR TITLE
Merge/upstream 20190717

### PR DESCRIPTION
**Pull request by plbossart**
Merges from Takashi/Mark/soundwire trees (includes all patches submitted for 5.3)

### CODE REVIEW

**Comment by plbossart** [comment]
CI doesn't detect any issues so volunteers will have to check if there is any issue.
A matching update is provided on topic/sof-dev-rebase for people who want to look at the current upstream debt of about 20 patches.

**Comment by ranj063** [comment]
UP2 looks good in my testing.

**Comment by ranj063** [comment]
@plbossart what is the switch to use to ignore checkpatch warnings when cherrypicking patches?

**Comment by plbossart** [comment]
> @plbossart what is the switch to use to ignore checkpatch warnings when cherrypicking patches?

-n  works for commits, not sure about cherry-picks. I removed the pre-commit checks, I always look at the post-commit results.

**Pull request merged**
