### PR TITLE
Merge/sound upstream 20230302

### PR DESCRIPTION
**Pull request by ujfalusi**
Small merge with 6.2 base.

### CODE REVIEW

**Comment by ujfalusi** [comment]
SOFCI TEST

**Comment by ujfalusi** [comment]
if there are no objections, I will merge this in about 16 hours.

**Comment by bardliao** [comment]
SOFCI TEST

**Comment by bardliao** [comment]
suspend resume timeout with stable-v2.2 sdw test cases https://sof-ci.01.org/linuxpr/PR4220/build3432/devicetest/index.html. Trigger a new CI test to double check.

**Comment by ujfalusi** [comment]
> suspend resume timeout with stable-v2.2 sdw test cases https://sof-ci.01.org/linuxpr/PR4220/build3432/devicetest/index.html. Trigger a new CI test to double check.

The CML_RVP_SDW suspend-resume always fails that, I cannot recall a CI run when it did not, but let's wait for this new run.

**Review by bardliao — APPROVED** [review]
The same timeout can be seen on other PR tests. So, it looks good to me.

**Pull request merged**
