### PR TITLE
Merge/sound upstream 20230911

### PR DESCRIPTION
**Pull request by ujfalusi**
Hi,

first attempt of v6.6-rc1 upstream merge.

### CODE REVIEW

**Comment by ujfalusi** [comment]
To be faithful to the there is no uneventful -rc1 upstream merge:
```
sound/core/seq/seq_midi.c: In function ‘snd_seq_midisynth_probe’:
sound/core/seq/seq_midi.c:354:83: error: ‘%s’ directive output may be truncated writing up to 79 bytes into a region of size 64 [-Werror=format-truncation=]
  354 |                                         snprintf(port->name, sizeof(port->name), "%s", info->name);
      |                                                                                   ^~
sound/core/seq/seq_midi.c:354:41: note: ‘snprintf’ output between 1 and 80 bytes into a destination of size 64
  354 |                                         snprintf(port->name, sizeof(port->name), "%s", info->name);
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sound/core/seq/seq_midi.c:352:83: error: ‘%s’ directive output may be truncated writing up to 79 bytes into a region of size 64 [-Werror=format-truncation=]
  352 |                                         snprintf(port->name, sizeof(port->name), "%s-%u", info->name, p);
      |                                                                                   ^~
sound/core/seq/seq_midi.c:352:82: note: directive argument in the range [0, 31]
  352 |                                         snprintf(port->name, sizeof(port->name), "%s-%u", info->name, p);
      |                                                                                  ^~~~~~~
sound/core/seq/seq_midi.c:352:41: note: ‘snprintf’ output between 3 and 83 bytes into a destination of size 64
  352 |                                         snprintf(port->name, sizeof(port->name), "%s-%u", info->name, p);
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
and
```
sound/pci/hda/hda_generic.c: In function ‘create_extra_outs’:
sound/pci/hda/hda_generic.c:1001:42: error: ‘%s’ directive output may be truncated writing 8 bytes into a region of size between 0 and 43 [-Werror=format-truncation=]
 1001 |         snprintf(name, sizeof(name), "%s %s %s", pfx, dir, sfx);
      |                                          ^~
sound/pci/hda/hda_generic.c:1001:9: note: ‘snprintf’ output between 17 and 60 bytes into a destination of size 44
 1001 |         snprintf(name, sizeof(name), "%s %s %s", pfx, dir, sfx);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
These lines are from 201x or older

**Comment by ujfalusi** [comment]
The reason is:
6d4ab2e97dcf ("extrawarn: enable format and stringop overflow warnings in W=1")

**Comment by ujfalusi** [comment]
In a parallel build I can see these also to break now:
sound/usb/mixer_scarlett_gen2.c
sound/usb/mixer.c
sound/soc/codecs/hdac_hdmi.c
sound/hda/intel-sdw-acpi.c
sound/core/init.c

**Comment by ujfalusi** [comment]
I'm not sure how to fix this for example:
```
sound/pci/hda/hda_generic.c: In function ‘create_extra_outs’:
sound/pci/hda/hda_generic.c:1001:42: error: ‘%s’ directive output may be truncated writing 8 bytes into a region of size between 0 and 43 [-Werror=format-truncation=]
 1001 |         snprintf(name, sizeof(name), "%s %s %s", pfx, dir, sfx);
      |                                          ^~
sound/pci/hda/hda_generic.c:1001:9: note: ‘snprintf’ output between 17 and 60 bytes into a destination of size 44
 1001 |         snprintf(name, sizeof(name), "%s %s %s", pfx, dir, sfx);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
The warning is kind of correct since the compiler does not know the size of the `pfx` (it knows the `dir` and `sfx`) so the next formated print can be truncated (and it does not need to be %s, a %d will trigger the same warning).
 For that matter it should be warning for the first `%s` for the `pfx` as it could be longer than 44 char and can get truncated as well?

I don't know what mechanism should be used to 'fix' this warning.

Actually it looks like that the gcc thinks that the `pfx` might be up to 43 character long, which might come from some call path where a tmp char array is passed along (sized SNDRV_CTL_ELEM_ID_NAME_MAXLEN - 44), but the string itself is never that long.

**Comment by ujfalusi** [comment]
```diff
diff --git a/sound/pci/hda/hda_generic.c b/sound/pci/hda/hda_generic.c
index dbf7aa88e0e3..d355969b15ff 100644
--- a/sound/pci/hda/hda_generic.c
+++ b/sound/pci/hda/hda_generic.c
@@ -997,11 +997,18 @@ static int add_control_with_pfx(struct hda_gen_spec *spec, int type,
 				const char *pfx, const char *dir,
 				const char *sfx, int cidx, unsigned long val)
 {
-	char name[SNDRV_CTL_ELEM_ID_NAME_MAXLEN];
-	snprintf(name, sizeof(name), "%s %s %s", pfx, dir, sfx);
-	if (!add_control(spec, type, name, cidx, val))
+	int ret = 0;
+	char *name;
+
+	name = kasprintf(GFP_KERNEL, "%s %s %s", pfx, dir, sfx);
+	if (!name)
 		return -ENOMEM;
-	return 0;
+
+	if (!add_control(spec, type, name, cidx, val))
+		ret = -ENOMEM;
+
+	kfree(name);
+	return ret;
 }
 
 #define add_pb_vol_ctrl(spec, type, pfx, val)			\
```

**Comment by ujfalusi** [comment]
The warning in sound/core/init.c is clearly false:
```
sound/core/init.c: In function ‘snd_card_init’:
sound/core/init.c:367:28: error: ‘%d’ directive writing between 1 and 10 bytes into a region of size 4 [-Werror=format-overflow=]
  367 |         sprintf(name, "card%d", idx);
      |                            ^~
sound/core/init.c:367:23: note: directive argument in the range [0, 2147483646]
  367 |         sprintf(name, "card%d", idx);
      |                       ^~~~~~~~
sound/core/init.c:367:9: note: ‘sprintf’ output between 6 and 15 bytes into a destination of size 8
  367 |         sprintf(name, "card%d", idx);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
`idx` is limited to max 8 (SNDRV_CARDS), we print 6 bytes unconditionally, there is no need to fix this. We can increase the name array to `char name[15]`

**Comment by ujfalusi** [comment]
@plbossart, I'm tempted to revert https://github.com/thesofproject/linux/commit/6d4ab2e97dcfbcd748ae71761a9d8e5e41cc732c for now to get things fixed upstream?

**Comment by plbossart** [comment]
We're probably missing something @ujfalusi, there are tons of W1 builds done by bots, It would be surprising if we were the first ones to report this.

Maybe @tiwai has a fix for all this?

**Comment by ujfalusi** [comment]
> We're probably missing something @ujfalusi, there are tons of W1 builds done by bots, It would be surprising if we were the first ones to report this.

I also thought that I'm missing something, but I don't see fixes anywhere.
Even my fix for the core/init.c did not got discarded as it is already fixed (v2: https://lore.kernel.org/alsa-devel/20230912110113.3166-1-peter.ujfalusi@linux.intel.com/)

Anyways, I have now fixes locally for these:
```
$ git ls-files --modified
sound/core/seq/seq_midi.c
sound/hda/intel-sdw-acpi.c
sound/pci/hda/hda_generic.c
sound/soc/codecs/hdac_hdmi.c
sound/usb/mixer.c
sound/usb/mixer_scarlett_gen2.c
```
> Maybe @tiwai has a fix for all this?

If I send these, he will ;)

**Comment by tiwai** [comment]
I have fixes for sound/core/seq/seq_midi.c, sound/core/seq/seq_ump_client.c, sound/usb/caiaq/device.c and sound/usb/mixer_scarlett_gen2.c.

Most of them are false-positive and can be ignored by replacing snprintf() with scnprintf().
One for UMP was sorted out differently by specifying the string precision.

**Comment by plbossart** [comment]
Thanks @tiwai, much appreciated.

@ujfalusi probably best to revert 6d4ab2e for now, we'll probably have other surprises on specific platforms.

**Comment by tiwai** [comment]
Now I have fixes for almost all warnings. Found in my test branch:
  https://git.kernel.org/pub/scm/linux/kernel/git/tiwai/sound.git/log/?h=test/format-truncation-fixes

**Comment by ujfalusi** [comment]
> I have fixes for sound/core/seq/seq_midi.c, sound/core/seq/seq_ump_client.c, sound/usb/caiaq/device.c and sound/usb/mixer_scarlett_gen2.c.
> 
> Most of them are false-positive and can be ignored by replacing snprintf() with scnprintf(). One for UMP was sorted out differently by specifying the string precision.

@tiwai, for me `snprintf()` just gave different warning saying that it is truncated instead of writing more than available, no?
I just sent one out of my local ones:
https://lore.kernel.org/alsa-devel/20230912162617.29178-1-peter.ujfalusi@linux.intel.com/

**Comment by ujfalusi** [comment]
> > I have fixes for sound/core/seq/seq_midi.c, sound/core/seq/seq_ump_client.c, sound/usb/caiaq/device.c and sound/usb/mixer_scarlett_gen2.c.
> > Most of them are false-positive and can be ignored by replacing snprintf() with scnprintf(). One for UMP was sorted out differently by specifying the string precision.
> 
> @tiwai, for me `snprintf()` just gave different warning saying that it is truncated instead of writing more than available, no? I just sent one out of my local ones: https://lore.kernel.org/alsa-devel/20230912162617.29178-1-peter.ujfalusi@linux.intel.com/

Right, `scnprintf()`

**Comment by ujfalusi** [comment]
@tiwai, your patches are smaller for sure:
```diff
diff --git a/sound/soc/codecs/hdac_hdmi.c b/sound/soc/codecs/hdac_hdmi.c
index 8b6b76029694..eae8c9e7b7bc 100644
--- a/sound/soc/codecs/hdac_hdmi.c
+++ b/sound/soc/codecs/hdac_hdmi.c
@@ -1790,7 +1790,7 @@ static int create_fill_jack_kcontrols(struct snd_soc_card *card,
 			name = devm_kstrdup(component->dev, xname, GFP_KERNEL);
 			if (!name)
 				return -ENOMEM;
-			snprintf(kc_name, sizeof(kc_name), "%s Switch", xname);
+			scnprintf(kc_name, sizeof(kc_name), "%s Switch", xname);
 			kc[i].name = devm_kstrdup(component->dev, kc_name,
 							GFP_KERNEL);
 			if (!kc[i].name)
```
vs
```diff
diff --git a/sound/soc/codecs/hdac_hdmi.c b/sound/soc/codecs/hdac_hdmi.c
index 8b6b76029694..b9c5ffbfb5ba 100644
--- a/sound/soc/codecs/hdac_hdmi.c
+++ b/sound/soc/codecs/hdac_hdmi.c
@@ -1771,7 +1771,6 @@ static int create_fill_jack_kcontrols(struct snd_soc_card *card,
 {
 	struct hdac_hdmi_pin *pin;
 	struct snd_kcontrol_new *kc;
-	char kc_name[NAME_SIZE], xname[NAME_SIZE];
 	char *name;
 	int i = 0, j;
 	struct hdac_hdmi_priv *hdmi = hdev_to_hdmi_priv(hdev);
@@ -1785,14 +1784,14 @@ static int create_fill_jack_kcontrols(struct snd_soc_card *card,
 
 	list_for_each_entry(pin, &hdmi->pin_list, head) {
 		for (j = 0; j < pin->num_ports; j++) {
-			snprintf(xname, sizeof(xname), "hif%d-%d Jack",
-						pin->nid, pin->ports[j].id);
-			name = devm_kstrdup(component->dev, xname, GFP_KERNEL);
+			name = devm_kasprintf(component->dev, GFP_KERNEL,
+					      "hif%d-%d Jack",
+					      pin->nid, pin->ports[j].id);
 			if (!name)
 				return -ENOMEM;
-			snprintf(kc_name, sizeof(kc_name), "%s Switch", xname);
-			kc[i].name = devm_kstrdup(component->dev, kc_name,
-							GFP_KERNEL);
+
+			kc[i].name = devm_kasprintf(component->dev, GFP_KERNEL,
+						    "%s Switch", name);
 			if (!kc[i].name)
 				return -ENOMEM;
 ```

**Comment by tiwai** [comment]
For the changes for hdac_hdmi.c, yours looks better, it reduces the unneeded temp buffer :)
So go ahead.  If you have other fixes, let me know. I can submit only the remaining ones.

**Comment by ujfalusi** [comment]
@tiwai, thanks, I will send it soon, I have another one which might be considered:
```diff
diff --git a/sound/usb/mixer.c b/sound/usb/mixer.c
index 9105ec623120..985b1aea9cdc 100644
--- a/sound/usb/mixer.c
+++ b/sound/usb/mixer.c
@@ -1929,7 +1929,6 @@ static int parse_clock_source_unit(struct mixer_build *state, int unitid,
 	struct uac_clock_source_descriptor *hdr = _ftr;
 	struct usb_mixer_elem_info *cval;
 	struct snd_kcontrol *kctl;
-	char name[SNDRV_CTL_ELEM_ID_NAME_MAXLEN];
 	int ret;
 
 	if (state->mixer->protocol != UAC_VERSION_2)
@@ -1966,10 +1965,9 @@ static int parse_clock_source_unit(struct mixer_build *state, int unitid,
 
 	kctl->private_free = snd_usb_mixer_elem_free;
 	ret = snd_usb_copy_string_desc(state->chip, hdr->iClockSource,
-				       name, sizeof(name));
+				       kctl->id.name, sizeof(kctl->id.name));
 	if (ret > 0)
-		snprintf(kctl->id.name, sizeof(kctl->id.name),
-			 "%s Validity", name);
+		append_ctl_name(kctl, " Validity");
 	else
 		snprintf(kctl->id.name, sizeof(kctl->id.name),
 			 "Clock Source %d Validity", hdr->bClockID);
```

**Comment by ujfalusi** [comment]
@tiwai, I will send the patch for sound/usb/mixer.c as well, for the others, your versions are better.

**Comment by plbossart** [comment]
@ujfalusi can we try to merge this or an updated version? Need to rebase our internal tree soonish.

**Comment by ujfalusi** [comment]
New merge created which should have now the W=1 fixes: #4597

**Pull request closed without merging**
