### PR TITLE
Sound card binding fails on TGL DUT with 4 HDMI DAI's in tplg

### PR DESCRIPTION
**Pull request by sathya-nujella**
Our TGL DUT is using tplg with 4-HDMI DAI's.

When we tried **latest kernel from topic/sof-dev**, we saw the below errors:
[21.806286] sof_rt5682 tgl_max98357a_rt5682: ASoC: CPU DAI iDisp4 Pin not registered
[20.084160] sof_rt5682 tgl_max98357a_rt5682: ASoC: CODEC DAI intel-hdmi-hifi4 not registered

Patches in this PR addresses this issue.

### CODE REVIEW

**Comment by plbossart** [comment]
@sathya-nujella the changes look ok but I wonder if the tests would work on a platform that only has 3 iDISP links. @kv2019i I guess this is for you to check/review?

And I forget how the traditional HDaudio machine driver would work as well with 4 links instead of 3.

**Comment by kv2019i** [comment]
@plbossart wrote:
> @sathya-nujella the changes look ok but I wonder if the tests would work on a platform that only has 3 iDISP links. @kv2019i I guess this is for you to check/review?

Yup, I held off adding the 4th link in the initial patches as I had not checked, but it seems CI is clean for this so looks good. I'll do some local tests as well, just to be sure. Approved based on CI results, will update if anything found in local tests today.

**Comment by kv2019i** [comment]
Yup, local tests are fine, this is good to go. We need to add 4 CVT support to the generic driver as well. Filed a ticket for myself so I don't forget:
https://github.com/thesofproject/linux/issues/1639

**Comment by sathya-nujella** [comment]
> @sathya-nujella the changes look ok but I wonder if the tests would work on a platform that only has 3 iDISP links. @kv2019i I guess this is for you to check/review?
> 
> And I forget how the traditional HDaudio machine driver would work as well with 4 links instead of 3.

sorry for late here. Cross checked on CML/Google Hatch DUT, it works well.

**Comment by ranj063** [comment]
> > @sathya-nujella the changes look ok but I wonder if the tests would work on a platform that only has 3 iDISP links. @kv2019i I guess this is for you to check/review?
> > And I forget how the traditional HDaudio machine driver would work as well with 4 links instead of 3.
> 
> sorry for late here. Cross checked on CML/Google Hatch DUT, it works well.
@sathya-nujella hatch does not use the HDAudio machine driver.
@plbossart did you mean the legacy HDAudio machine driver or the generic skl machine driver here?

**Comment by sathya-nujella** [comment]
> > @sathya-nujella hatch does not use the HDAudio machine driver.
yes, I verified with a DUT which has 3-HDMI links.

**Comment by sathya-nujella** [comment]
> > > @sathya-nujella the changes look ok but I wonder if the tests would work on a platform that only has 3 iDISP links. @kv2019i I guess this is for you to check/review?
> > > And I forget how the traditional HDaudio machine driver would work as well with 4 links instead of 3.
> > 
> > 
> > sorry for late here. Cross checked on CML/Google Hatch DUT, it works well.
> > @sathya-nujella hatch does not use the HDAudio machine driver.
> > @plbossart did you mean the legacy HDAudio machine driver or the generic skl machine driver here?

I cross checked on a WHL DUT which is using legacy HDA (not using DSP). Flashed kernel with these patches and it works fine.
This WHL DUT sound card lists these (for ref):
==
localhost ~ # aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: ALC236 Analog [ALC236 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 9: HDMI 3 [HDMI 3]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 10: HDMI 4 [HDMI 4]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by ranj063** [comment]
@sathya-nujella the HDMI 4 device is legit for WHL?

**Comment by sathya-nujella** [comment]
> @sathya-nujella the HDMI 4 device is legit for WHL?

Without adding these patches too, it was listing 4 HDMI devices (this is from legacy HDA DUT). So, I cross verified and checked that no side effect from these two patches.

**Comment by ranj063** [comment]
> > @sathya-nujella the HDMI 4 device is legit for WHL?
> 
> Without adding these patches too, it was listing 4 HDMI devices (this is from legacy HDA DUT). So, I cross verified and checked that no side effect from these two patches.

@sathya-nujella great. Thanks for confirming!

**Comment by aiChaoSONG** [comment]
@plbossart The commit message of https://github.com/thesofproject/linux/pull/1636/commits/4d28db9a19cc326f225dde3e32657d12e93ec425 :
> Without this patch, we saw the below error in TGL DUT:
 sof_rt5682 tgl_max98357a_rt5682: ASoC: CODEC DAI intel-hdmi-hifi4 not

Is `registered` absent?

**Pull request merged**
