### PR TITLE
[TEST][UPSTREAM] SoundWire: move to use regmap-maple for SoundWire codecs

### PR DESCRIPTION
**Pull request by plbossart**

### CODE REVIEW

**Comment by plbossart** [comment]
@bardliao can you take this for a local test, I am running out of time. Thanks!

**Comment by bardliao** [comment]
> @bardliao can you take this for a local test, I am running out of time. Thanks!

@plbossart I tested on Dell SKU 0A32 and found no issue.

**Comment by plbossart** [comment]
@broonie FYI, this looks good.

**Comment by broonie** [comment]
On Tue, Jun 13, 2023 at 04:27:32AM -0700, Pierre-Louis Bossart wrote:

> @broonie FYI, this looks good.

Thanks - any chance of a Tested-by: on the list?

**Comment by bardliao** [comment]
> On Tue, Jun 13, 2023 at 04:27:32AM -0700, Pierre-Louis Bossart wrote: @broonie FYI, this looks good.
> Thanks - any chance of a Tested-by: on the list?

Added Tested-by: Bard Liao <yung-chuan.liao@linux.intel.com> on the list

**Pull request closed without merging**
