### PR TITLE
Revert "ASoC: SOF: Force polling mode on CFL and CNL"

### PR DESCRIPTION
**Pull request by kv2019i**
One additional patch on top of PR1281 to revert the old workaround.

@bardliao Do you think this is good to go? I'll mark this as draft for now..

### CODE REVIEW

**Comment by kv2019i** [comment]
@plbossart wrote:
> thanks @kv2019i

Oops, this was meaning to be a draft PR. Now you merged also a version of https://github.com/thesofproject/linux/pull/1281 with the old text (I had updated commit msg in PR1281 but not this one).

UPDATE: considering the Bobba, can you revert this? (or I can send a revert PR later today)

**Comment by plbossart** [comment]
I can fix the commit message later, not sure how this happened. Looks like github rebase/merge discarded the first commit.

I don't think this PR for CFL/CNL has any impact on Bobba (GLK), the issue is rather the sync_write, so let's keep it for now and treat it as a bug if this is indeed reproduced.

**Comment by kv2019i** [comment]
@plbossart wrote: 
> I can fix the commit message later, not sure how this happened. Looks like github rebase/merge discarded the first commit.

Ok thanks. This was completely my bad. I had the same patch for sync_write in two PRs and only updated the commit message in one (as I thought I had marked this PR1282 as draft). So a mess, sorry about that.

> I don't think this PR for CFL/CNL has any impact on Bobba (GLK), the issue is rather 
> the sync_write, so let's keep it for now and treat it as a bug if this is indeed reproduced.

That's true. I believe on GLK you can still hit the HDMI probe error and the sync_write patch might make it more likelier, and/or it was just good/bad luck to hit it with this CI round.

Based on testing on ICL (same display hw as GLK), this patch should address the problem:

"drm/i915: Fix audio power up sequence for gen10+ display"

... it's not yet in sof-dev, but I've had it as part of the RFC PR1155 for the new hdmi codec.  
The 4th Oct round was all pass for GLK&ICL:
https://sof-ci.01.org/linuxpr/PR1155/build2025/devicetest/

But, but, today's round with the sync_write included, failed on GLK (a different error):
https://sof-ci.01.org/linuxpr/PR1155/build2038/devicetest/

.. so I'm afraid sync_write may fix issues on ICL and create new ones on GLK. :(

**Comment by kv2019i** [comment]
> But, but, today's round with the sync_write included, failed on GLK (a different error):
> https://sof-ci.01.org/linuxpr/PR1155/build2038/devicetest/

@plbossart  It's not the sync_write patch. I submitted a test PR with the sync_write patch reverted on top of latst sof-dev and GLK still failed:

https://sof-ci.01.org/linuxpr/PR1289/build2044/devicetest/GLK_BOB_DA7219/
https://sof-ci.01.org/linuxpr/PR1289/build2044/devicetest/GLK_BOB_DA7219/verify-pcm-list.sh/dmesg.txt

... OTOH, the upstream merge passed on GLK yesterday, so based on CI data, it's impossible to say what triggered the new problem on GLK.

**Pull request merged**
