### PR TITLE
[DO NOT MERGE] test for sof-ci report

### PR DESCRIPTION
**Pull request by Jiangxinx**
SOFCI TEST
Signed-off-by: Jiangxinx <xinx.jiang@intel.com>

### CODE REVIEW

**Comment by plbossart** [comment]
I don't see any activity here so make this PR go away.

**Comment by Jiangxinx** [comment]
@plbossart This is for testing linux PR report function of CI, seem as sof PR#931. I still need a few days to run and retest.

**Comment by plbossart** [comment]
no activity -> closing

**Comment by Jiangxinx** [comment]
I need serval days to retest the report genarator.

**Pull request closed without merging**
