### PR TITLE
ASoC: SOF: Intel: hda: Fix non PCM stream position tracking

### PR DESCRIPTION
**Pull request by ujfalusi**
For a compressed stream the hda_dsp_pcm_pointer() callback is not going to
be used, but we had a custom hda_dsp_set_bytes_transferred() function to
essentially implement the position query using the legacy SKL mode.

Since this mode is no longer the default, any compressed stream will fail
to get the position and this will break for example the probes support.

To fix the issue:
introduce a new function to query the position of a given stream and use
this from hda_dsp_pcm_pointer() and the hda_dsp_compr_bytes_transferred()

Signed-off-by: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>

### CODE REVIEW

**Comment by ujfalusi** [comment]
@plbossart, this is basically extending, re-working the 288fad2f71fa0 ("ASoC: SOF: Intel: hda: add quirks for HDAudio DMA position information") by moving out the position reading to a generic helper.

This patch is needed to get the probes extract streams again.

**Review by plbossart — CHANGES_REQUESTED** [review]
The fix looks good @ujfalusi, but the commit message is convoluted. I would simplify it as suggested below

Commit 288fad2f71fa0b989c075d4984879c26d47cfb06 ("ASoC: SOF: Intel: hda: add quirks for HDAudio DMA position information") modified the PCM path only, but left the compressed data patch using an obsolete option. 
Move the functionality in a helper that can be called for both PCM and compressed data.

**Comment by ujfalusi** [comment]
@plbossart, thank you, I'll update the commit mesage.

**Review by jsarha — DISMISSED** [review]
Looks good to me, with Pierre's update for the commit message. Would have taken me few more hours or days to realize what is wrong with snd_hdac_stream_get_pos_posbuf().

**Comment by ranj063** [comment]
> The fix looks good @ujfalusi, but the commit message is convoluted. I would simplify it as suggested below
> 
> Commit [288fad2](https://github.com/thesofproject/linux/commit/288fad2f71fa0b989c075d4984879c26d47cfb06) ("ASoC: SOF: Intel: hda: add quirks for HDAudio DMA position information") modified the PCM path only, but left the compressed data patch using an obsolete option. Move the functionality in a helper that can be called for both PCM and compressed data.

@plbossart @ujfalusi @mengdonglin Should we consider adding a test for probes in our CI test suite? This isnt the first time we've caused a regression in the compressed code in the SOF driver until someone tests the probes feature.

**Comment by plbossart** [comment]
> @plbossart @ujfalusi @mengdonglin Should we consider adding a test for probes in our CI test suite? This isnt the first time we've caused a regression in the compressed code in the SOF driver until someone tests the probes feature.

Great suggestion @ranj063. We could do something like a 'probe-based loopback', where the last buffer before the DAI would be added to a probe point. That would capture the last data and we could feed the information in alsa-bat with some changes for the compressed data/parsing of payload.

**Comment by ujfalusi** [comment]
Changes since v1:
- commit message updated as  suggested by @plbossart 
- Added Fixes tag (applies fine to 5.17 with only offset changes, no conflict)
- Dropped the buffer_size parameter for `hda_dsp_compr_bytes_transferred()`

**Comment by jsarha** [comment]
I've now verified that this PR alone is enough to get the probes working without any other changes anywhere else (e.g. it looks like the probes are fine with using blocking DMA on the firmware side).

**Review by plbossart — APPROVED** [review]

**Review by ranj063 — APPROVED** [review]

**Comment by ujfalusi** [comment]
> I've now verified that this PR alone is enough to get the probes working without any other changes anywhere else (e.g. it looks like the probes are fine with using blocking DMA on the firmware side).

@jsarha, strange as I still need this hack in firmware to get the probes working (tgl-h laptop):
```diff
diff --git a/rimage b/rimage
index 9d453321f892..8ba3d1729656 160000
--- a/rimage
+++ b/rimage
@@ -1 +1 @@
-Subproject commit 9d453321f892b7ec3f0c74d3382eaa4e674a6e6a
+Subproject commit 8ba3d17296563af5166f2f59448e9c21e11194bf
diff --git a/src/ipc/dma-copy.c b/src/ipc/dma-copy.c
index 4f9390e6d81d..a1d42221876f 100644
--- a/src/ipc/dma-copy.c
+++ b/src/ipc/dma-copy.c
@@ -66,7 +66,7 @@ int dma_copy_to_host(struct dma_copy *dc, struct dma_sg_config *host_sg,
 	int ret;
 
 	/* tell gateway to copy */
-	ret = dma_copy_legacy(dc->chan, size, DMA_COPY_BLOCKING);
+	ret = dma_copy_legacy(dc->chan, size, 0);
 	if (ret < 0)
 		return ret;
 
diff --git a/src/probe/probe.c b/src/probe/probe.c
index 265c6fe9fea2..9bfba5412819 100644
--- a/src/probe/probe.c
+++ b/src/probe/probe.c
@@ -200,13 +200,15 @@ static enum task_state probe_task(void *data)
 	struct probe_pdata *_probe = probe_get();
 	int err;
 
-	if (_probe->ext_dma.dmapb.avail > 0)
+	if (_probe->ext_dma.dmapb.avail > 0) {
+		tr_err(&pr_tr, "probe_task(): copy to host: %u", _probe->ext_dma.dmapb.avail);
 		err = dma_copy_to_host(&_probe->ext_dma.dc,
 				       &_probe->ext_dma.config, 0,
 				       (void *)_probe->ext_dma.dmapb.r_ptr,
 				       _probe->ext_dma.dmapb.avail);
-	else
+	} else {
 		return SOF_TASK_STATE_RESCHEDULE;
+	}
 
 	if (err < 0) {
 		tr_err(&pr_tr, "probe_task(): dma_copy_to_host() failed.");
```
with that the firmware log looks like this:
```
[    46521935.234718] (        1850.885376) c0 pga          30.51 ......./module_adapter.c:557  INFO module_adapter_copy(): start
[    46522015.026381] (          79.791664) c0 pga          1.2   ......./module_adapter.c:557  INFO module_adapter_copy(): start
[    46522083.724295] (          68.697914) c0 probe                     src/probe/probe.c:204  ERROR probe_task(): copy to host: 412
[    46523935.911722] (        1852.187378) c0 pga          30.51 ......./module_adapter.c:557  INFO module_adapter_copy(): start
[    46524015.859635] (          79.947914) c0 pga          1.2   ......./module_adapter.c:557  INFO module_adapter_copy(): start
[    46524083.776299] (          67.916664) c0 probe                     src/probe/probe.c:204  ERROR probe_task(): copy to host: 412
[    46525935.286642] (        1851.510376) c0 pga          30.51 ......./module_adapter.c:557  INFO module_adapter_copy(): start
[    46526015.234556] (          79.947914) c0 pga          1.2   ......./module_adapter.c:557  INFO module_adapter_copy(): start
[    46526083.672053] (          68.437500) c0 probe                     src/probe/probe.c:204  ERROR probe_task(): copy to host: 412
[    46527936.119896] (        1852.447876) c0 pga          30.51 ......./module_adapter.c:557  INFO module_adapter_copy(): start
[    46528015.755309] (          79.635414) c0 pga          1.2   ......./module_adapter.c:557  INFO module_adapter_copy(): start
[    46528083.932390] (          68.177078) c0 probe                     src/probe/probe.c:204  ERROR probe_task(): copy to host: 412
```
Otherwise crecord would not receive anything (`We read 8192, DSP sent 0`).

**Comment by jsarha** [comment]
I will verify my finding, maybe I made some mistake. I have a proper fix for the above and will send it a PR if it indeed needed.

**Comment by jsarha** [comment]
Yep. My screw up... had I'll make the PR.

**Pull request merged**
