### PR TITLE
ASoC: SOF: use devm_kfree to free which was allocated by devm_kzalloc

### PR DESCRIPTION
**Pull request by bardliao**
We should use devm_kfree to free which was allocated by devm_kzalloc.

### CODE REVIEW

**Comment by keyonjie** [comment]
@bardliao they are both allocated with kzalloc on my side:

		stream = kzalloc(sizeof(*stream), GFP_KERNEL);

	sroute = kzalloc(sizeof(*sroute), GFP_KERNEL);

**Comment by bardliao** [comment]
@keyonjie It is modified by commit [801d176](https://github.com/thesofproject/linux/commit/801d1765db4eec9acaaeb58edc20c64c91c2f20a) and [0ec5600](https://github.com/thesofproject/linux/commit/0ec5600afd68908bc4be40ef998c27cf61db1ce8)

**Comment by lgirdwood** [comment]
@bardliao this implies we have 2 or more different paths for freeing the memory ? Can you confirm.

**Comment by bardliao** [comment]
@lgirdwood I am afraid to say yes. [801d176](https://github.com/thesofproject/linux/commit/801d1765db4eec9acaaeb58edc20c64c91c2f20a) and [c3f224a](https://github.com/thesofproject/linux/pull/149/commits/c3f224acdab1640c602cb8cd8378edc46886f5e6) should be merge to one patch. And same thing as [bb16f18](https://github.com/thesofproject/linux/pull/149/commits/bb16f18188019517b3f597288bb33588580f04f2) and [0ec5600](https://github.com/thesofproject/linux/commit/0ec5600afd68908bc4be40ef998c27cf61db1ce8). I wish that I can amend the commits merged yesterday.

**Comment by lgirdwood** [comment]
@bardliao no need to amend, they will be squashed as part of upstreaming

**Pull request merged**
