### PR TITLE
debug prints for probes client reload failure

### PR DESCRIPTION
**Pull request by ujfalusi**
one debug patch on top of the SOF client support PR to get more information on the failure.

### CODE REVIEW

**Comment by ujfalusi** [comment]
@plbossart, fyi

**Comment by ujfalusi** [comment]
There is one thing that stands out (apart from the complete disaster on `ADLP_RVP_NOCODEC`) regarding to probes module unload:
When the consequent loading is OK:
```
snd_sof_probes snd_sof.hda-probes.0: sof_client_dev_unregister: unregistering this device
snd_sof_probes snd_sof.hda-probes.0: sof_probes_client_remove: ENTER
sound controlC0: snd_unregister_device (sof-probes): free minor (0) for type: 0
sound comprC0D0: snd_unregister_device (sof-probes): free minor (2) for type: 2
auxiliary snd_sof.hda-probes.0: sof_client_auxdev_release: ENTER
```
and when it is failing to probe next time:
```
snd_sof_probes snd_sof.hda-probes.0: sof_client_dev_unregister: unregistering this device
auxiliary snd_sof.hda-probes.0: sof_client_auxdev_release: ENTER
```
The driver's remove is not called, thus leaving the card registered.
It looks like that we have some interesting race when deleting the auxiliary device vs the driver unload.

**Comment by ujfalusi** [comment]
@plbossart, with SND_DYNAMIC_MINORS selected along with compress support the device test looks a bit better, than you for the suggestion

**Comment by plbossart** [comment]
is this still needed @ujfalusi ?

**Comment by ujfalusi** [comment]
> is this still needed @ujfalusi ?

Certainly not, I thought I have already closed it.

**Pull request closed without merging**
