### PR TITLE
Merge/broonie next 20190521

### PR DESCRIPTION
**Pull request by plbossart**
We need to check the latest upstream code from Mark's tree
platform owners and testers, knock yourselves out.

### CODE REVIEW

**Comment by juimonen** [comment]
@plbossart compiled the PR and very quick check in mb+rt5682: no obvious flaws, logs clean, can playback audio, everything to me looks the same as in topic/sof-dev.

**Comment by plbossart** [comment]
Thanks @juimonen. I will have to assume things are fine, it's sad to see there is only one person who tested. merging now.

**Comment by wenqingfu** [comment]
> very quick check in mb+rt5682

👍

**Comment by singalsu** [comment]
@plbossart This may have impacted that on UP2 the nocodec mode topologies do not load any more.

```
[    4.451438] sof-audio-pci 0000:00:0e.0: error: can't connect DAI DMIC0.IN stream NoCodec-6
[    4.452084] sof-audio-pci 0000:00:0e.0: error: can't connect DAI DMIC1.IN stream NoCodec-7
```

Yep, I didn't test this when you requested ...

**Pull request merged**
