### PR TITLE
Merge/sound upstream 20200311

### PR DESCRIPTION
**Pull request by ranj063**

### CODE REVIEW

**Comment by ranj063** [comment]
checking the build failures

**Comment by plbossart** [comment]
@ranj063 build failed?

**Comment by ranj063** [comment]
> @ranj063 build failed?

@plbossart yes looking into it now

**Comment by ranj063** [comment]
@plbossart fixed now hopefully. I needed to change the use of macros in 2 files:
https://github.com/thesofproject/linux/pull/1888/commits/c84e556b67f5030841bde487cc3e67cc7f0085a8
https://github.com/thesofproject/linux/pull/1888/commits/a3f9f8a3895f03970e6c4983149b72e0a9c036d8

**Comment by kv2019i** [comment]
> both of these changes should be squashed before being sent upstream

But not to each other, right? The second problem is related to Bard's patch "ASoC: SOF: topology: connect dai widget to all cpu-dais" (also not sent out)

@ranj063 and @plbossart I think we need some kind of system to track these. Now the patches in sof-dev and sof-dev-rebase have no hints to which patches they should be squashed to. I don't think we can distribute this part of maintainer work unless this is tracked somehow. 

I would propose to have explciit "git commit --squash <commit-id>" before merging any patch to sof-dev that we know already that won't be sent as-is to upstream. Then this decision gets recorded to the commit and is easier to manage.

**Comment by kv2019i** [comment]
Otherwise, this looks good.  Only issue are the "bdw-wsb" CI failures. I don't see them in other today's PR tests like here https://sof-ci.01.org/linuxpr/PR1889/build3272/devicetest/

The panic footprint doesn't exact match open bugs like https://github.com/thesofproject/sof/issues/2532

I'll approve conditionally and try to kick CI again. If another failure, we need someone with BDW to check this out.

**Comment by kv2019i** [comment]
SOFCI TEST

**Comment by kv2019i** [comment]
Build 3270 seems to have passed on BDW, so this looks like unrelated:
https://sof-ci.01.org/linuxpr/PR1888/build3270/devicetest/

**Comment by bardliao** [comment]
> @plbossart fixed now hopefully. I needed to change the use of macros in 2 files:
> [c84e556](https://github.com/thesofproject/linux/commit/c84e556b67f5030841bde487cc3e67cc7f0085a8)
> [a3f9f8a](https://github.com/thesofproject/linux/commit/a3f9f8a3895f03970e6c4983149b72e0a9c036d8)

I think the first one is due to we did the topology.c change based on older version of multi cpu dai supported patches, but didn't update it when the final version of multi cpu dai supported patches are applied by Mark.

**Comment by plbossart** [comment]
@ranj063 can you merge and update topic/sof-dev-rebase? I need to do some SoundWire cleanups and I'll take care of the squashes while I am at it. Thanks!

**Comment by plbossart** [comment]
> The panic footprint doesn't exact match open bugs like [thesofproject/sof#2532](https://github.com/thesofproject/sof/issues/2532)

probably because it's not the same platform :-)
bsw/bdw...

**Comment by ranj063** [comment]
> @ranj063 can you merge and update topic/sof-dev-rebase? I need to do some SoundWire cleanups and I'll take care of the squashes while I am at it. Thanks!

@plbossart done!

**Pull request merged**
