### PR TITLE
[DRAFT][TEST] NoReview: sof ci test only

### PR DESCRIPTION
**Pull request by fredoh9**
Test only.

### CODE REVIEW

**Comment by fredoh9** [comment]
LNL device test is nicely started.

ImgPic_20240419_164709

**Comment by fredoh9** [comment]
Internal test result:
planresultdetail/40081

Waiting for the result to be published.

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by ujfalusi** [comment]
I guess, I can close this?

**Pull request closed without merging**
