### PR TITLE
Merge/sound upstream 20200415

### PR DESCRIPTION
**Pull request by plbossart**
This is the first merge based on v5.7-rc1 so it's likely that something broke. Please everyone give it a try and provide feedback

### CODE REVIEW

**Comment by cujomalainey** [comment]
@sebcarlucci I don't have capacity to test this today, can you test this today on your board

**Comment by sebcarlucci** [comment]
I am not able to build this on my environment. I get the following error using LLD 10.0.0:
````bash
scripts/link-vmlinux.sh: line 62:  9449 Segmentation fault      ${LD} ${KBUILD_LDFLAGS} ${LDFLAGS_vmlinux} ${strip_debug#-Wl,} -o ${output} -T ${lds} ${objects}
````

**Comment by ClarexZhou** [comment]
Tested on all platforms. Most works OK. But find below regression on BSW.  Error not seen on sof-dev.
Case “Check alsabat: headset playback” , fail result in http://sof-tcr.sh.intel.com/#/tests/5228d677-9393-45f7-977e-36300b469288/detail  , log is attached. Only “SSP2-Codec: ASoC: no backend playback stream”, no other error message.

[dmesg11.txt](https://github.com/thesofproject/linux/files/4486903/dmesg11.txt)
[sof_trace11.txt](https://github.com/thesofproject/linux/files/4486904/sof_trace11.txt)

**Comment by kv2019i** [comment]
@sebcarlucci wrote: 
> I am not able to build this on my environment. I get the following error using LLD 10.0.0:

Hmm, you'll probably get this with vanilla 5.7-rc1 as well? I recall getting a very similar error when I last build upstream kernel in ChromeOS SDK -- seems to be a recurring theme with kernel updates.

**Comment by kv2019i** [comment]
I tested on a ICL device with some HDA ext codec and HDMI and no issues found. 

The CI results also seems suprisingly good. The BDW/BSW failures are interesting. Audio is played back, but there is a lot of noise in playback and/or volume is very, very low (check the wavs in failing case). Alsa-bat does find the correct 1kHz test sine tone, but it also finds multiple peaks other peaks in the signal and thus the failure. So basic PCM setup is correct and seemingly e.g. playback speed is correct. Maybe an issue with jack detection and/or mixer settings?

Anyone with BDW/BSW at hand that could check these locally?

**Comment by plbossart** [comment]
> I tested on a ICL device with some HDA ext codec and HDMI and no issues found.
> 
> The CI results also seems suprisingly good. The BDW/BSW failures are interesting. Audio is played back, but there is a lot of noise in playback and/or volume is very, very low (check the wavs in failing case). Alsa-bat does find the correct 1kHz test sine tone, but it also finds multiple peaks other peaks in the signal and thus the failure. So basic PCM setup is correct and seemingly e.g. playback speed is correct. Maybe an issue with jack detection and/or mixer settings?
> 
> Anyone with BDW/BSW at hand that could check these locally?

Ack, I can reproduce the error on my BSW Cyan:
````
[   37.130066] sof-audio-acpi 808622A8:00: Firmware info: version 1:1:0-655d0
[   37.130071] sof-audio-acpi 808622A8:00: Firmware: ABI 3:11:0 Kernel ABI 3:15:0
[   37.134883] cht-bsw-max98090 cht-bsw-max98090: info: override BE DAI link SSP2-Codec
[   37.135741] sof-audio-acpi 808622A8:00: Topology: ABI 3:11:0 Kernel ABI 3:15:0
[   37.135751] sof-audio-acpi 808622A8:00: warning: widget type 1 name codec_out0 not handled
[   37.136740] sof-audio-acpi 808622A8:00: warning: widget type 7 name ssp2 Rx not handled
[   37.136744] sof-audio-acpi 808622A8:00: warning: widget type 1 name codec_out1 not handled
[   37.137319] sof-audio-acpi 808622A8:00: warning: widget type 7 name ssp2 Tx not handled
[   37.137326] sof-audio-acpi 808622A8:00: warning: widget type 0 name codec_in0 not handled
[   37.138036] sof-audio-acpi 808622A8:00: warning: widget type 0 name codec_in1 not handled
[   37.139368] sof-audio-acpi 808622A8:00: ASoC: Parent card not yet available, widget card binding deferred
[   37.164164] max98090 i2c-193C9890:00: MAX98090 REVID=0x43
[   37.165832] cht-bsw-max98090 cht-bsw-max98090: HiFi <-> ssp2-port mapping ok
[   37.165899] cht-bsw-max98090 cht-bsw-max98090: snd-soc-dummy-dai <-> Low Latency 0 mapping ok
[   37.165959] cht-bsw-max98090 cht-bsw-max98090: snd-soc-dummy-dai <-> Media Playback 1 mapping ok
[   37.166052] cht-bsw-max98090 cht-bsw-max98090: ASoC: no DMI vendor name!
[   37.167865] input: sof-chtmax98090 Headset Jack as /devices/platform/808622A8:00/cht-bsw-max98090/sound/card2/input5
[   41.597233] mach_set_rtc_mmss: RTC write failed with error -22
[   49.597322] mach_set_rtc_mmss: RTC write failed with error -22
[   56.381814]  SSP2-Codec: ASoC: no backend playback stream
[   57.597136] mach_set_rtc_mmss: RTC write failed with error -22
[   58.410015]  SSP2-Codec: ASoC: no users playback at close - state 0
[   65.597172] mach_set_rtc_mmss: RTC write failed with error -22
[   67.060968]  SSP2-Codec: ASoC: no backend playback stream
[   73.596857] mach_set_rtc_mmss: RTC write failed with error -22
````
This doesn't happen with topic/sof-dev, so we should be able to bisect.

**Comment by plbossart** [comment]
Problem on Baytrail/Cherrytrail linked to commit 9b5db059366ae2 ("ASoC: soc-pcm: dpcm: Only allow playback/capture if supported")
Adding an explicit .min_channels for SSPs solves the problem.

Now I don't get at all why we only saw this with alsa-bat tests, this should have been reported across the board. @marc-hb @wenqingfu we should definitively check why even basic playback was reported as successful.

**Comment by sebcarlucci** [comment]
@kv2019i wrote:
> Hmm, you'll probably get this with vanilla 5.7-rc1 as well? I recall getting a very similar error when I last build upstream kernel in ChromeOS SDK -- seems to be a recurring theme with kernel updates.

Same thing happens with vanilla 5.7. We will look into this issue then.

**Comment by plbossart** [comment]
@kv2019i  @ranj063 the functionality seems restored for BYT/CHT/BDW, the only remaining issues are the usual ICL and GLK issues, so we can probably merge tomorrow?

**Pull request merged**
