### PR TITLE
ASoC: SOF: IPC fallback and extended IPC file profile

### PR DESCRIPTION
**Pull request by ujfalusi**
Hi,

this PR contains
https://github.com/thesofproject/linux/pull/4331
and
https://github.com/thesofproject/linux/pull/4382

On top of these it implements support for different file layouts per IPC type (for IPC4 to be specific):
```c
/**
 * enum sof_fw_layout_type - pre-defined file-layout for loadable fw files
 * @SOF_FW_LAYOUT_IPC3_SOF:
 *	firmware path:		<vendor>/sof</fw_path_postfix>
 *	firmware name:		sof-<platform>.ri
 *	topology path:		<vendor>/sof-tplg/
 * @SOF_FW_LAYOUT_IPC4_SOF:
 *	firmware path:		<vendor>/sof-ipc4/<platform></fw_path_postfix>
 *	firmware name:		sof-<platform>.ri
 *	firmware lib path:	<vendor>/sof-ipc4-lib/<platform></fw_path_postfix>
 *      topology path:		<vendor>/sof-ipc4-tplg/
 * @SOF_FW_LAYOUT_IPC4_INTEL_ACE:
 *	firmware path:		intel/sof-ipc4/<platform></fw_path_postfix>
 *	firmware name:		sof-<platform>.ri
 *	firmware lib path:	intel/sof-ipc4-lib/<platform></fw_path_postfix>
 *	topology path:		intel/sof-ace-tplg/
 * @SOF_FW_LAYOUT_IPC4_INTEL_AVS:
 *	firmware path:		intel/avs/<platform></fw_path_postfix>
 *	firmware name:		dsp_basefw.bin
 *	firmware lib path:	intel/avs/<platform></fw_path_postfix>
 *	topology path:		intel/avs-tplg/
 */
```
If IPC4 is selected then the kernel will test the profiles and picks the one which has all the files needed for the board.

on TGL these are the paths:
```
sof-audio-pci-intel-tgl 0000:00:1f.3: Supported default profiles
sof-audio-pci-intel-tgl 0000:00:1f.3: - ipc type 0 (Fallback):
sof-audio-pci-intel-tgl 0000:00:1f.3:  Firmware layout: SOF IPC3
sof-audio-pci-intel-tgl 0000:00:1f.3:   Firmware file: intel/sof/community/sof-tgl.ri
sof-audio-pci-intel-tgl 0000:00:1f.3:   Topology file: intel/sof-tplg/sof-hda-generic.tplg
sof-audio-pci-intel-tgl 0000:00:1f.3: - ipc type 1 (Requested):
sof-audio-pci-intel-tgl 0000:00:1f.3:  Firmware layout: SOF IPC4
sof-audio-pci-intel-tgl 0000:00:1f.3:   Firmware file: intel/sof-ipc4/tgl/community/sof-tgl.ri
sof-audio-pci-intel-tgl 0000:00:1f.3:   Topology file: intel/sof-ipc4-tplg/sof-hda-generic.tplg
sof-audio-pci-intel-tgl 0000:00:1f.3:  Firmware layout: SOF IPC4 for Intel ACE platforms
sof-audio-pci-intel-tgl 0000:00:1f.3:   Firmware file: intel/sof-ipc4/tgl/community/sof-tgl.ri
sof-audio-pci-intel-tgl 0000:00:1f.3:   Topology file: intel/sof-ace-tplg/sof-hda-generic.tplg
sof-audio-pci-intel-tgl 0000:00:1f.3:  Firmware layout: Intel AVS IPC4
sof-audio-pci-intel-tgl 0000:00:1f.3:   Firmware file: intel/avs/tgl/community/dsp_basefw.bin
sof-audio-pci-intel-tgl 0000:00:1f.3:   Topology file: intel/avs-tplg/sof-hda-generic.tplg
```

### CODE REVIEW

**Comment by plbossart** [comment]
@ujfalusi do you mind closing obsolete PRs, I can't keep up with 4 PRs on the same topics. Thanks!

**Comment by ujfalusi** [comment]
> @ujfalusi do you mind closing obsolete PRs, I can't keep up with 4 PRs on the same topics. Thanks!

This draft PR contains 3 topics:
#4331: IPC type fallback support - ability to switch back to IPC3 in case IPC4 files are missing
#4382: Fix the incorrect firmware and topology path/names for CAV2.5 family (the avs path is no longer valid for these)
The new patches on top of the two PRs: support for different layouts per IPC type which is mainly targeting IPC4 and it will allow the kernel to seamlessly discover the layout of the IPC4 supported machine. This is going to help a lot with CAV2.5 and ACE family.

Both of the open PRs received(ing) quite a bit of pushback, the new stuff in the draft will cause even more eyebrows to be lifted.

But, if you think that these should be combined then I can close the other two, but I would like to have the #4382 merged separately to be able to send ti upstream asap.

**Comment by plbossart** [comment]
I can't review 4 PRs that look similar, it's just confusing. It was already confusing and review fatigue hit 2 months ago already.

**Comment by ujfalusi** [comment]
> I can't review 4 PRs that look similar, it's just confusing. It was already confusing and review fatigue hit 2 months ago already.

OK, let me close this and I will open this when the other two is done.

**Pull request closed without merging**
