### PR TITLE
[HACK] soundwire: stream: add traces to figure out bank switch issues

### PR DESCRIPTION
**Pull request by plbossart**

### CODE REVIEW

**Comment by plbossart** [comment]
https://sof-ci.01.org/linuxpr/PR5039/build3360/devicetest/index.html?model=LNLM_SDW_AIOC&testcase=check-playback-3times

````
[  280.197459] kernel: sdw_acquire_bus_lock: acquiring locks for stream subdevice #0-Playback
[  280.197461] kernel: sdw_acquire_bus_lock: acquired locks for stream subdevice #0-Playback
[  280.197462] kernel: _sdw_prepare_stream: start for stream subdevice #0-Playback
[  280.198067] kernel: _sdw_prepare_stream: before bank switch for stream subdevice #0-Playback
[  280.297479] kernel: soundwire_cadence:cdns_update_slave_status_work: soundwire_intel soundwire_intel.link.0: Slave status change: 0x4000000
[  283.248642] kernel: soundwire sdw-master-0-0: Controller Timed out on bank switch
[  283.248750] kernel: soundwire sdw-master-0-0: multi link bank switch failed: -110
````

Humm, this looks very suspicious.
@bardliao FYI

It could very well be that there's some sort of deadlock.

The bank switch starts, so there's a command that's gated until the Sync_go happens. But an interrupt happens, during which we want to send a read command that cannot go through because the write didn't complete. and then we we don't get the interrupt for the deferred write so everything times out.

**Comment by plbossart** [comment]
https://sof-ci.01.org/linuxpr/PR5039/build3380/devicetest/index.html

problem not reproduced with the trace, wondering if this is an Heisenbug symptomatic of a race condition...

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by bardliao** [comment]
It failed again at https://sof-ci.01.org/linuxpr/PR5039/build3390/devicetest/index.html

**Comment by bardliao** [comment]
We handle either normal message transfer or defer message transfer when we receive a CDNS_MCP_INT_RX_WL interrupt. [if (int_status & CDNS_MCP_INT_RX_WL)](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/soundwire/cadence_master.c#L923). Is it possible that a normal message transfer is triggered right after bank switch and cause problem?

**Comment by plbossart** [comment]
> We handle either normal message transfer or defer message transfer when we receive a CDNS_MCP_INT_RX_WL interrupt. [if (int_status & CDNS_MCP_INT_RX_WL)](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/soundwire/cadence_master.c#L923). Is it possible that a normal message transfer is triggered right after bank switch and cause problem?

In theory there's a 'message_lock' that should prevent two messages from being sent on top of each other, but I am not sure if this works with deferred processing.

**Comment by plbossart** [comment]
The last failure doesn't seem to be due to any interference between interrupts or other messages

````
[  701.527897] kernel: snd_sof:sof_widget_setup_unlocked: sof-audio-pci-intel-lnl 0000:00:1f.3: widget host-copier.4.capture setup complete
[  701.527904] kernel: snd_sof:sof_ipc4_route_setup: sof-audio-pci-intel-lnl 0000:00:1f.3: bind alh-copier.SDW1-Capture.0:0 -> host-copier.4.capture:0
[  701.527910] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-lnl 0000:00:1f.3: ipc tx      : 0x45000004|0x10004: MOD_BIND
[  701.528350] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-lnl 0000:00:1f.3: ipc tx reply: 0x65000000|0x10004: MOD_BIND
[  701.528492] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-lnl 0000:00:1f.3: ipc tx done : 0x45000004|0x10004: MOD_BIND
[  701.529173] kernel: sdw_acquire_bus_lock: acquiring locks for stream subdevice #0-Capture
[  701.529177] kernel: sdw_acquire_bus_lock: acquired locks for stream subdevice #0-Capture
[  701.529179] kernel: _sdw_prepare_stream: start for stream subdevice #0-Capture
[  701.530123] kernel: _sdw_prepare_stream: before bank switch for stream subdevice #0-Capture
[  704.593782] kernel: soundwire sdw-master-0-1: Controller Timed out on bank switch
[  704.593869] kernel: soundwire sdw-master-0-1: multi link bank switch failed: -110
[  704.593900] kernel: _sdw_prepare_stream: do_bank_switch failed for stream subdevice #0-Capture: -110
[  704.593934] kernel: sdw_release_bus_lock: releasing locks for stream subdevice #0-Capture
[  704.593937] kernel: sdw_release_bus_lock: released locks for stream subdevice #0-Capture
[  704.593941] kernel:  SDW1-Capture: ASoC: error at snd_soc_link_prepare on SDW1-Capture: -110
[  704.593972] kernel:  SDW1-Capture: ASoC: error at __soc_pcm_prepare on SDW1-Capture: -110
[  704.593996] kernel:  Microphone: ASoC: error at dpcm_be_dai_prepare on Microphone: -110
[  704.594022] kernel:  Microphone: ASoC: error at dpcm_fe_dai_prepare on Microphone: -110
````

It's a "pure fail" in a completely serial way.

**Pull request closed without merging**
