### PR TITLE
Upstream/dcpm cleanup v4

### PR DESCRIPTION
**Pull request by plbossart**

### CODE REVIEW

**Comment by plbossart** [comment]
Surprising results
````
[    5.880136] kernel: sof_sdw sof_sdw: both playback/capture are available, but not using playback_only flag (SDW0-Playback)
[    5.880231] kernel: sof_sdw sof_sdw: dpcm_playback/capture are no longer needed, please use playback/capture_only instead
[    5.880271] kernel: sof_sdw sof_sdw: both playback/capture are available, but not using playback_only flag (SDW2-Playback)
[    5.880294] kernel: sof_sdw sof_sdw: dpcm_playback/capture are no longer needed, please use playback/capture_only instead
````

@bardliao do you know if we set the dpcm_playback/capture flags for SoundWire BE dailinks

**Comment by bardliao** [comment]
> Surprising results
> 
> ```
> [    5.880136] kernel: sof_sdw sof_sdw: both playback/capture are available, but not using playback_only flag (SDW0-Playback)
> [    5.880231] kernel: sof_sdw sof_sdw: dpcm_playback/capture are no longer needed, please use playback/capture_only instead
> [    5.880271] kernel: sof_sdw sof_sdw: both playback/capture are available, but not using playback_only flag (SDW2-Playback)
> [    5.880294] kernel: sof_sdw sof_sdw: dpcm_playback/capture are no longer needed, please use playback/capture_only instead
> ```
> 
> @bardliao do you know if we set the dpcm_playback/capture flags for SoundWire BE dailinks

Yes, [dai_links->dpcm_playback = playback;](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/intel/boards/sof_sdw.c#L1262) and [dai_links->dpcm_capture = capture;](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/intel/boards/sof_sdw.c#L1263)

**Comment by plbossart** [comment]
Grrr, build stuck.

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
Jenkins aborted the build but won't let me see why. Yay.

**Comment by plbossart** [comment]
SOFCI TEST

**Pull request closed without merging**
