### PR TITLE
Replace "[NOT FOR UPSTREAM] x86/cpu: Add INTEL_LUNARLAKE_M to X86_BUG_…

### PR DESCRIPTION
**Pull request by kv2019i**
…MONITOR"

This replaces  commit 81ce24baf515fa78b8748caf4d8698097f68ca0d with merged upstream version.

### CODE REVIEW

**Review by bardliao — DISMISSED** [review]

**Review by lgirdwood — DISMISSED** [review]

**Comment by lgirdwood** [comment]
Rerun CI to test with updated BIOS.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by kv2019i** [comment]
New version:
- the patch is now merged to upstream, so no need to revert
- replace the earlier patch with the merged upstream version (no change to code)

**Review by ujfalusi — APPROVED** [review]

**Review by bardliao — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
LNL is clean.

**Pull request merged**
