### PR TITLE
upstream merge 20191209 - v5.5-rc1

### PR DESCRIPTION
**Pull request by plbossart**
This is a rather large merge with a change to v5.5-rc1

Testers, start your engines

@kv2019i i removed the previous patches for DRM/i915. Please double-check if we need more patches or if the merge is ok as is. 

Thanks!

### CODE REVIEW

**Comment by plbossart** [comment]
@fredoh9 @xiulipan what are all those timeouts in CI reports?

**Comment by xiulipan** [comment]
@plbossart Regressions happened when we want to show more status such as `TIMEOUT` in the 01.org html. It seems we have some wrong handling for the TIMEOUT status. Will try to fix and re-run the ci.

**Comment by kv2019i** [comment]
@plbossart Manual tests completed on APL+CML+CFL+TGL, nothing suprising found.

@plbossart  wrote:
> @kv2019i i removed the previous patches for DRM/i915. Please double-check if we need more > patches or if the merge is ok as is.

The three patches to gen10+ display are now in 5.5-rc1, so dropping those is good. I have one additional TGL patch in i915, but that's not in sof-dev either so we can ignore that (not critical for any of our current use-cases -> (drm/i915/dp: fix DP audio for PORT_A on gen12+).

**Comment by plbossart** [comment]
thanks @kv2019i for your tests. @xiulipan if I don't have CI feedback by tomorrow, I will merge anyway to have more validation results with the QA team.

**Comment by cujomalainey** [comment]
I'm seeing errors in various locations

```
/mnt/host/source/src/third_party/kernel/v5.4/security/selinux/hooks.c:6812:15: error: use of undeclared identifier 'PERF_EVENT__OPEN'         
                requested = PERF_EVENT__OPEN;                                                                                                 
                            ^                                                                                                                 
/mnt/host/source/src/third_party/kernel/v5.4/security/selinux/hooks.c:6814:15: error: use of undeclared identifier 'PERF_EVENT__CPU'          
                requested = PERF_EVENT__CPU;                                                                                                  
                            ^                                                                                                                 
/mnt/host/source/src/third_party/kernel/v5.4/security/selinux/hooks.c:6816:15: error: use of undeclared identifier 'PERF_EVENT__KERNEL'; did you mean 'PERF_CONTEXT_KERNEL'?                                                                                                                
                requested = PERF_EVENT__KERNEL;                                                                                               
                            ^~~~~~~~~~~~~~~~~~                                                                                                
                            PERF_CONTEXT_KERNEL                                                                                               
/mnt/host/source/src/third_party/kernel/v5.4/include/uapi/linux/perf_event.h:1032:2: note: 'PERF_CONTEXT_KERNEL' declared here                
        PERF_CONTEXT_KERNEL             = (__u64)-128,                                                                                        
        ^                                                                                                                                     
/mnt/host/source/src/third_party/kernel/v5.4/security/selinux/hooks.c:6818:15: error: use of undeclared identifier 'PERF_EVENT__TRACEPOINT'; did you mean 'PERF_TYPE_TRACEPOINT'?
                requested = PERF_EVENT__TRACEPOINT;                    
                            ^~~~~~~~~~~~~~~~~~~~~~                                                                                            
                            PERF_TYPE_TRACEPOINT                                                                                              
/mnt/host/source/src/third_party/kernel/v5.4/include/uapi/linux/perf_event.h:32:2: note: 'PERF_TYPE_TRACEPOINT' declared here                 
        PERF_TYPE_TRACEPOINT                    = 2,                                                                                          
        ^                                                                                                                                     
/mnt/host/source/src/third_party/kernel/v5.4/security/selinux/hooks.c:6822:48: error: use of undeclared identifier 'SECCLASS_PERF_EVENT'      
        return avc_has_perm(&selinux_state, sid, sid, SECCLASS_PERF_EVENT,                                                                    
                                                      ^                                                                                       
/mnt/host/source/src/third_party/kernel/v5.4/security/selinux/hooks.c:6816:15: warning: implicit conversion from 'unsigned long' to 'u32' (aka 'unsigned int') changes value from 18446744073709551488 to 4294967168 [-Wconstant-conversion]                                                
                requested = PERF_EVENT__KERNEL;                        
                          ~ ^~~~~~~~~~~~~~~~~~                         
/mnt/host/source/src/third_party/kernel/v5.4/security/selinux/hooks.c:6854:8: error: use of undeclared identifier 'SECCLASS_PERF_EVENT'       
                            SECCLASS_PERF_EVENT, PERF_EVENT__READ, NULL);                                                                     
                            ^                                          
/mnt/host/source/src/third_party/kernel/v5.4/security/selinux/hooks.c:6854:29: error: use of undeclared identifier 'PERF_EVENT__READ'         
                            SECCLASS_PERF_EVENT, PERF_EVENT__READ, NULL);                                                                                                                                                                                                                   
                                                 ^                     
/mnt/host/source/src/third_party/kernel/v5.4/security/selinux/hooks.c:6863:8: error: use of undeclared identifier 'SECCLASS_PERF_EVENT'       
                            SECCLASS_PERF_EVENT, PERF_EVENT__WRITE, NULL);                                                                    
                            ^                                                                                                                 
/mnt/host/source/src/third_party/kernel/v5.4/security/selinux/hooks.c:6863:29: error: use of undeclared identifier 'PERF_EVENT__WRITE'        
                            SECCLASS_PERF_EVENT, PERF_EVENT__WRITE, NULL);                                                                    
                                                 ^                                                                                            
1 warning and 9 errors generated.                                                                                                             
make[3]: *** [/mnt/host/source/src/third_party/kernel/v5.4/scripts/Makefile.build:265: security/selinux/hooks.o] Error 1
```

```
/mnt/host/source/src/third_party/kernel/v5.4/arch/x86/entry/syscall_32.c:30:37: error: use of undeclared identifier '__ia32_sys_ni_syscall'   
        [0 ... __NR_syscall_compat_max] = &__sys_ni_syscall,                                                                                  
                                           ^                                                                                                                                                                                                                                                
/mnt/host/source/src/third_party/kernel/v5.4/arch/x86/entry/syscall_32.c:13:26: note: expanded from macro '__sys_ni_syscall'                  
#define __sys_ni_syscall __ia32_sys_ni_syscall                                                                                                
                         ^                                                                                                                                                                                                                                                                  
1 error generated.  
```

**Comment by plbossart** [comment]
> I'm seeing errors in various locations

@cujomalainey could it be a configuration issue? the default SOF configs don't seem to have a problem if I believe the CI results?

**Comment by cujomalainey** [comment]
I am running the chromeos configs, so that is very possible.

**Comment by xiulipan** [comment]
@plbossart re-test once. https://sof-ci.01.org/linuxpr/PR1610/build2683/devicetest/ It seems CFL do not boot up. re-test again now.

**Pull request merged**
