### PR TITLE
ASoC: Intel: sof_sdw: Remove get codec dai by name

### PR DESCRIPTION
**Pull request by bardliao**
The dai is passed from the parameter. We don't need to find the dai by name.

### CODE REVIEW

**Comment by bardliao** [comment]
rebase needed once https://github.com/thesofproject/linux/pull/4991 is merged.

**Comment by plbossart** [comment]
> rebase needed once #4991 is merged.

merged now, please rebase @bardliao

**Comment by bardliao** [comment]
> > rebase needed once #4991 is merged.
> 
> merged now, please rebase @bardliao

done

**Review by ujfalusi — APPROVED** [review]
nice cleanup!

**Review by charleskeepax — APPROVED** [review]

**Review by plbossart — APPROVED** [review]

**Pull request merged**
