### PR TITLE
Fix resume failure with pulseaudio

### PR DESCRIPTION
**Pull request by ranj063**
PCM_FREE ipc should be send to the DSP after the STOP trigger
to prevent hw_params errors upon resuming. This is usually
done during pcm close but since we do not close the pcm
during suspend, this needs to be done explicitly. This patch
fixes issues with resuming playback with pulseaudio.

Fixes https://github.com/thesofproject/linux/issues/764

### CODE REVIEW

**Comment by RanderWang** [comment]
@ranj063  The free operation would reset pipeline in FW, how about BE setting (link dma) in kernel?  As I know, BE setting is not restored after SOF resumed. Thanks!

**Comment by ranj063** [comment]
> @ranj063 The free operation would reset pipeline in FW, how about BE setting (link dma) in kernel? As I know, BE setting is not restored after SOF resumed. Thanks!

@RanderWang with my other PR #795 , the BE hw_params is set up in prepare when resuming from S3. Is that what you're referring to?

**Comment by ranj063** [comment]
> but it's not clear why we need to re-send PCM_PARAMS on resume in the first-place.

@plbossart this is the fundamental problem we have in SOF. I still dont know why though but judging from Takashi's response, it doesnt seem overly unusual. 

This commit should ideally be part of the other PR #795 that I have but I separated it out because this needs to be done regardless of whether we decide to keep INFO_RESUME or not.

**Comment by RanderWang** [comment]
> > @ranj063 The free operation would reset pipeline in FW, how about BE setting (link dma) in kernel? As I know, BE setting is not restored after SOF resumed. Thanks!
> 
> @RanderWang with my other PR #795 , the BE hw_params is set up in prepare when resuming from S3. Is that what you're referring to?

yes, I get it.

**Comment by ranj063** [comment]
@plbossart closing this one. will merge with my other PR

**Pull request closed without merging**
