### PR TITLE
ALSA: hda/hdmi: set of KAE fixes

### PR DESCRIPTION
**Pull request by kv2019i**
Set of fixes prompted by:
https://gitlab.freedesktop.org/drm/intel/-/issues/7353

### CODE REVIEW

**Comment by kv2019i** [comment]
V2 update:
- fix a problem in V1 related to S3 suspend on DG2 -- the stream/channel programming is lost if system is suspended, and upon resume, the codec driver state is not in sync with hardware -> audio playback is muted if silent-stream is enabled and system goes to S3 (driver thinks hw is correctly programmed already. while it isn't)

**Review by plbossart — DISMISSED** [review]

**Comment by rodrigovivi** [comment]
It works neatly on my DG2!
Feel free to use
Tested-by: Rodrigo Vivi <rodrigo.vivi@intel.com>

**Comment by kv2019i** [comment]
Still some issue in V2:
 - system with monitor connected, silent stream enabled
 - system suspend (S3)
 - system resume 
 - PROBLEM: codec driver not woken up currently, unable to reprogram keepalive
 - playback attempt to monitor -> initial samples lost as silent-stream was not active

**Comment by kv2019i** [comment]
V3 update:
- added reviewed-by and tested-by for the 2 first patches (unmodified)
- last patch in series reworked to handle variation in hardware behaviour .. make the KAE reprogramming conditional on resume
- tested on multiple ADL-P and DG2 systems

**Comment by kv2019i** [comment]
V4 update:
- typo fixed in code comment, no functional changes

**Comment by kv2019i** [comment]
@plbossart I modified 3rd patch, so I left your signed-off out (and @rodrigovivi 's tested-by) from this one patch. If you have time, please re-review.

If no objections, I'll send this upstream tomorrow. @jairaj-arava also did additional testing with this, so this seems to be good now. As I'm adding a new HDA codec quirk flag, this is probably better sent to alsa-devel directly and discussed there.

**Review by plbossart — APPROVED** [review]

**Comment by kv2019i** [comment]
Thanks all, sent to upstream, closing here.

**Pull request closed without merging**
