### PR TITLE
ASoC: SOF: hda-ipc: fix IPC handled wrong issue

### PR DESCRIPTION
**Pull request by keyonjie**
When IPC interrupt arrived, we need to check HDA_DSP_REG_HIPCCTL to make
sure we can tell the message initiator(new or reply from DSP),
otherwise, we may treat new message as reply one by mistake, and see
error message reported as "error: rx list empty but received ...".

Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>

### CODE REVIEW

**Comment by plbossart** [comment]
@keyonjie I am having a hard time reviewing this, it seems to undo some of the fixes in 4a2a987d4fd1d9f33510c00075b57c3054ae2db8 ('ASoC: SOF: apl: clear BUSY bit after done with received ipc') - merged in August and squashed since.
I would like to make sure this patch does not reopen the issues we had with missed messages.

**Comment by keyonjie** [comment]
> @keyonjie I am having a hard time reviewing this, it seems to undo some of the fixes in [4a2a987](https://github.com/thesofproject/linux/commit/4a2a987d4fd1d9f33510c00075b57c3054ae2db8) ('ASoC: SOF: apl: clear BUSY bit after done with received ipc') - merged in August and squashed since.
> I would like to make sure this patch does not reopen the issues we had with missed messages.

@plbossart I think that's another kind of issue, here my patch fix a potential issue of previous fix passingly(maybe I should split it), @xiulipan @RanderWang can you confirm?

**Comment by keyonjie** [comment]
just talked with @RanderWang , we need to do the same fix for cnl, @RanderWang can you help provide the CNL fix?

**Comment by keyonjie** [comment]
APL part updated.

**Comment by RanderWang** [comment]
@plbossart 
this patch fix another issue and doesn't revert my patch.

@keyonjie 
how about BDW and BYT?

**Comment by keyonjie** [comment]
@RanderWang yes, we need that for BDW and BYT also.

**Pull request merged**
