### PR TITLE
Merge/sound upstream 20230404

### PR DESCRIPTION
**Pull request by ujfalusi**
New merge to sync up with upstream. Nothing looks out of place based on local testing.

### CODE REVIEW

**Comment by ujfalusi** [comment]
```
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper
```
needed since 36862e14e316 ("kbuild: deb-pkg: use dh_listpackages to know enabled packages")

Added a revert for this to check again.

**Comment by marc-hb** [comment]
> needed since https://github.com/thesofproject/linux/commit/36862e14e31611f9786622db366327209a7aede7 ("kbuild: deb-pkg: use dh_listpackages to know enabled packages")

It shouldn't be difficult to add a missing package.

However you didn't save the link to the logs, this does not help.

**Comment by greg-intel** [comment]
SOFCI TEST

**Comment by greg-intel** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
SOFCI TEST

@marc-hb EDIT: no testing, there was a storage outage

**Comment by marc-hb** [comment]
SOFCI TEST

Fri  7 Apr 2023 04:25:05 UTC EDIT: still not running :-(

Yet recent https://sof-ci.01.org/linuxpr/PR4287/build4064/devicetest/index.html  was fine?

**Comment by ujfalusi** [comment]
closing, new merge is created: #4304

**Pull request closed without merging**
