### PR TITLE
ktest: new ssh-watch.sh and examples/reboot-ubuntu20-once.conf 

### PR DESCRIPTION
**Pull request by marc-hb**
The ssh-watch.sh script keeps trying to ssh and prints a fake "login:" prompt when
it does so ktest knows when the system successfully (re)booted. It's
meant to keep running forever in a forgotten terminal.

Besides a few lines to adjust at the top, the sample, short
ktest configuration file should drive any Ubuntu 20.04 target (and likely
other distributions) without any change and save you the most common
ktest pitfalls.

### CODE REVIEW

**Comment by marc-hb** [comment]
The checkpatch warning is `WARNING: added, moved or deleted file(s), does MAINTAINERS need updating?`.
Does it?

The only travis-ci failure is the checkpatch failure.

The Jenkins failure can't be related because nothing uses these two new files now.

**Comment by kv2019i** [comment]
@marc-hb Hmm, not sure whether we should put this to Linux repo. Maybe to sof-test/tools or even to the kconfig repo (latter is checked out by all kernel developers). I'm open for debate, but as a ground rule, I'd keep amount of not-for-upstream patches to a minimum in sof-dev.

**Comment by plbossart** [comment]
> @marc-hb Hmm, not sure whether we should put this to Linux repo. Maybe to sof-test/tools or even to the kconfig repo (latter is checked out by all kernel developers). I'm open for debate, but as a ground rule, I'd keep amount of not-for-upstream patches to a minimum in sof-dev.

same here, we should maybe try and upstream ssh-watch.sh as a extension for ktest.pl directly, and the configs don't below in the kernel tree.

**Comment by marc-hb** [comment]
Thanks, I will resubmit to sof-test. Please don't wait for that to start using it :-)

**Comment by plbossart** [comment]
@marc-hb should we close this?

**Pull request closed without merging**
