### PR TITLE
Merge/upstream merge 20190607

### PR DESCRIPTION
**Pull request by plbossart**
Usual weekly merge from upstream.
This one changes all the dailink representations to the 'modern style' so we had quite a few conflicts to sort out.
Testers, start your engines.

### CODE REVIEW

**Comment by juimonen** [comment]
@plbossart hmm getting following in byt/rt5682 at boot:
[    6.416362] sof-audio-acpi 80860F28:01: tplg: load pcm Low Latency 0
[    6.416385] sof-audio-acpi 80860F28:01: error: no platforms
[    6.416536] sof-audio-acpi 80860F28:01: ASoC: FE link loading failed
[    6.416686] sof-audio-acpi 80860F28:01: tplg: load pcm Media Playback 1
[    6.416702] sof-audio-acpi 80860F28:01: error: no platforms
[    6.416828] sof-audio-acpi 80860F28:01: ASoC: FE link loading failed

**Comment by kv2019i** [comment]
@plbossart Similar issues as Jaska on UP2, seems ok in nocodec mode but with hifiberry config, I'm getting:

[    6.825320] sof-audio-pci 0000:00:0e.0: ipc tx succeeded: 0x40070000: GLB_PM_MSG: CORE_ENABLE
[    6.825333] sof-audio-pci 0000:00:0e.0: tplg: load pcm Port5 0
[    6.825346] sof-audio-pci 0000:00:0e.0: error: no platforms
[    6.825695] sof-audio-pci 0000:00:0e.0: ASoC: FE link loading fail

On CFL with hda generic topology, errors are similar:

[   14.136501] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x40070000: GLB_PM_MSG: CORE_ENABLE
[   14.136509] sof-audio-pci 0000:00:1f.3: tplg: load pcm DMIC32 6
[   14.136517] sof-audio-pci 0000:00:1f.3: error: no platforms
[   14.136575] sof-audio-pci 0000:00:1f.3: ASoC: FE link loading failed
[   14.136631] sof-audio-pci 0000:00:1f.3: tplg: load pcm DMIC16 7
[   14.136636] sof-audio-pci 0000:00:1f.3: error: no platforms
[   14.136682] sof-audio-pci 0000:00:1f.3: ASoC: FE link loading failed
[   14.136735] sof-audio-pci 0000:00:1f.3: tplg: load pcm HDA Analog 0
[   14.136747] sof-audio-pci 0000:00:1f.3: error: no platforms

The patches to add the dailinks with modern style seem ok upon a quick glance, but something is going wrong. 
UPDATE: tried to remove the check for 'link->platforms' in sof_link_load() and audio started working on UP2, but on CFL, there were still plenty of errors.

**Comment by plbossart** [comment]
@juimonen @kv2019i thanks for testing. I am not sure why CI earlier reported these changes were fine, indeed there was a mistake in the topology handling. I fixed this, please retest.

**Comment by plbossart** [comment]
@xiulipan CI delays? It's been an hour and the PR isn't built?

**Comment by cujomalainey** [comment]
From a quick sanity build standpoint its fine, don't have time to deploy on a chromebook unfortunately

**Comment by xiulipan** [comment]
SOFCI TEST

**Comment by xiulipan** [comment]
@plbossart 
It seems this PR toke Jenkins 8 hours to go before we manually kill it. Maybe something is wrong.

Rerun the test now.

**Comment by juimonen** [comment]
@plbossart now with minnow/rt5682 this is working as previous. So tested playback with default rt5682 topology to both playback pipes and it is ok. No errors on boot.

**Comment by kv2019i** [comment]
@plbossart With the additional fix, playback is now ok on APL UP2, but I'm still getting issues on CFL with HDA audio and HDMI:

[   24.505688] sof-audio-pci 0000:00:1f.3: ASoC: can't set Analog CPU DAI hw params: -22
[   24.505692]  Analog Playback and Capture: ASoC: hw_params BE failed -22
[   24.505693]  HDA Analog: ASoC: hw_params BE failed -22

Same topology with sof-dev kernel does work, so something wrong still.

**Comment by plbossart** [comment]
> @plbossart With the additional fix, playback is now ok on APL UP2, but I'm still getting issues on CFL with HDA audio and HDMI:
> 
> [ 24.505688] sof-audio-pci 0000:00:1f.3: ASoC: can't set Analog CPU DAI hw params: -22
> [ 24.505692] Analog Playback and Capture: ASoC: hw_params BE failed -22
> [ 24.505693] HDA Analog: ASoC: hw_params BE failed -22
> 
> Same topology with sof-dev kernel does work, so something wrong still.

I am tempted to merge this anyway, it's been too long and we are not making progress.

**Comment by plbossart** [comment]
@kv2019i can you please test, I found an issue with the core topology stuff which corrupted memory. It works on a test WHL/HDAudio device so pretty much the same you have.

**Comment by RanderWang** [comment]
@plbossart  I also tested it on WHL & CFL HDAudio with latest change and didn't find any issue.
My test items:
(1) analog playback
(2) both analog & DMIC capture
(3) two pipeline simultaneous test

**Comment by kv2019i** [comment]
@plbossart wrote:
> @kv2019i can you please test, I found an issue with the core topology stuff which corrupted memory. > It works on a test WHL/HDAudio device so pretty much the same you have.

Ouch, that was a nasty bug, great that you spotted it! 

All looks fine now, audio playback works as expected on platforms that failed earlier.

**Pull request merged**
