### PR TITLE
ALSA/ASoC: Intel: fix copyright information

### PR DESCRIPTION
**Pull request by plbossart**
For some reason, some files used the 'all rights reserved' statements and others didn't.

Follow internal guidance and remove all instances of 'all rights reserved' in Intel-contributed sound-related files.

@ujfalusi @bardliao @ranj063 @crojewsk-intel FYI

@lgirdwood @kv2019i the same is likely required for all firmware contributions from Intel?

### CODE REVIEW

**Review by bardliao — APPROVED** [review]

**Comment by crojewsk-intel** [comment]
Guess we have Rafael to thank for these : D

For all Intel bits:
Acked-by: Cezary Rojewski <cezary.rojewski@intel.com>

For the rest:
Reviewed-by: Cezary Rojewski <cezary.rojewski@intel.com>

**Review by ujfalusi — APPROVED** [review]

**Comment by plbossart** [comment]
V2: no change except tags from @crojewsk-intel. Thanks for the reviews @bardliao @ujfalusi

**Comment by plbossart** [comment]
Humm, the TGL/ADL nocodec stuff is still not quite right. Wondering if the nocodec changes from @kv2019i were taken into account here?

**Comment by plbossart** [comment]
merging, there's no way any of the changes in this PR causes CI issues.

**Pull request merged**
