### PR TITLE
Merge/sound upstream 20200619

### PR DESCRIPTION
**Pull request by bardliao**
Upstream sync.

Matching updated sof-dev-rebase (without reorderings):
https://github.com/bardliao/linux/tree/merge/sof-dev-rebase-20200619

### CODE REVIEW

**Comment by plbossart** [comment]
Thanks @bardliao. Can we have additional volunteers to test on platforms that are not in the CI list, e.g. Soundwire laptops and others?

**Comment by RanderWang** [comment]
I tested it on TGL. playback & capture,  runtime PM & S3, multi-pipeline cases, rmmod & insmod. everything works in my tests.

**Comment by kv2019i** [comment]
Thanks @bardliao Rebase looks - local tests on APL, CFL and TGL are all good. I do have some trouble on ICL system, but this could be unrelated (UPDATE: not related to this PR). I'll do some more tests on this.
@RanderWang and others, if you have tested ok, please hit approve. I'll merge once we have 2+ approvals.

**Review by kv2019i — APPROVED** [review]

**Comment by bardliao** [comment]
It passes sof-test.sh test on CML-H laptop.

**Comment by plbossart** [comment]
> It passes sof-test.sh test on CML-H laptop.

what sof-test.sh script are you referring to @bardliao ?

**Review by plbossart — APPROVED** [review]
works for me as well

**Comment by bardliao** [comment]
> > It passes sof-test.sh test on CML-H laptop.
> 
> what sof-test.sh script are you referring to @bardliao ?

Oops. I thought you have it. I use [sof-test.txt](https://github.com/thesofproject/linux/files/4819671/sof-test.txt) 
to run the test cases in https://github.com/thesofproject/sof-test/tree/master/test-case.
The command is ``./sof-test.sh <tplg name>``
Note that you should run ./env-check.sh before running any test script to ensure there is no problem in your environment.

**Comment by plbossart** [comment]
@bardliao there's no such sof-test.sh file in the sof-test repo. Can you double-check? maybe you were referring to another test file?

**Comment by bardliao** [comment]
> @bardliao there's no such sof-test.sh file in the sof-test repo. Can you double-check? maybe you were referring to another test file?

No, it is not in the sof-test repo. I got it from our QA team. They merge all test cases in the sof-test repo in sof-test.sh Maybe we should upload it to the sof-test repo?

**Comment by plbossart** [comment]
> > @bardliao there's no such sof-test.sh file in the sof-test repo. Can you double-check? maybe you were referring to another test file?
> 
> No, it is not in the sof-test repo. I got it from our QA team. They merge all test cases in the sof-test repo in sof-test.sh Maybe we should upload it to the sof-test repo?

yes indeed, no reason why there are tests that are not version-controlled...

**Pull request merged**
