### PR TITLE
Merge/sound upstream 20240115

### PR DESCRIPTION
**Pull request by ujfalusi**
Short sync-up to get back one fix from upstream

### CODE REVIEW

**Review by plbossart — APPROVED** [review]

**Comment by bardliao** [comment]
Not sure is https://sof-ci.01.org/linuxpr/PR4778/build1008/devicetest/index.html?model=TGLU_RVP_NOCODEC-ipc4&testcase=check-suspend-resume-with-playback a known issue

**Comment by ujfalusi** [comment]
> Not sure is https://sof-ci.01.org/linuxpr/PR4778/build1008/devicetest/index.html?model=TGLU_RVP_NOCODEC-ipc4&testcase=check-suspend-resume-with-playback a known issue

@bardliao, it is this: https://github.com/thesofproject/sof/issues/8721

But we have a kernel issue as well if you take a look at the full dmesg:
the firmware panic happens on stop when setting the pipeline to reset state, the IPC times out (the DSP crashed) and we skip the rest of the trigger:stop.
on next playback we boot the DSP up with purge but the old state from the previous run was still there and all IPCs will fail.

I have a workaround patch under work for this in kernel - will not fix the firmware panic, but we will have working audio next time.

**Comment by ujfalusi** [comment]
@bardliao, https://github.com/thesofproject/linux/pull/4780 for the 'recovery' on the kernel side

**Comment by ujfalusi** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
@bardliao any idea what the SoundWire issue is in https://sof-ci.01.org/linuxpr/PR4778/build1073/devicetest/index.html?model=TGLU_RVP_SDW-ipc4&testcase=check-signal-stop-start-playback-10

**Comment by ujfalusi** [comment]
> @bardliao any idea what the SoundWire issue is in https://sof-ci.01.org/linuxpr/PR4778/build1073/devicetest/index.html?model=TGLU_RVP_SDW-ipc4&testcase=check-signal-stop-start-playback-10

An SOF PR also have similar fail:
https://sof-ci.ostc.intel.com/#/result/planresultdetail/37103?model=TGLU_RVP_SDW-ipc4&testcase=check-signal-stop-start-playback-10

**Comment by plbossart** [comment]
yeah, known issue https://github.com/thesofproject/linux/issues/4832. That's starting to be concerning, not sure why we have this -7 offset

**Comment by bardliao** [comment]
> yeah, known issue [thesofproject/linux#4832](https://github.com/thesofproject/linux/issues/4832). That's starting to be concerning, not sure why we have this -7 offset

Yeah, @RanderWang is working on it. It looks like we clear node_id in sof_ipc4_unprepare_copier_module() and has some race condition.

**Comment by ujfalusi** [comment]
Replaced by thesofproject/sof#4793, aka first 6.8-rc1 attempt.

**Pull request closed without merging**
