### PR TITLE
ASoC: SOF: Intel: ssp: BCLK delay parameter

### PR DESCRIPTION
**Pull request by jajanusz**
Some codecs require BCLK to be on for some time, before sending
any data. SOF can enable BCLK and then wait for guaranteed time,
before starting DMA on SSP start.

This is kernel-side patch for: https://github.com/thesofproject/sof/pull/1600

Signed-off-by: Janusz Jankowski <janusz.jankowski@linux.intel.com>

### CODE REVIEW

**Comment by jajanusz** [comment]
@bardliao I meant that *this is* kernel side patch for fw PR in the link ;)

**Comment by bardliao** [comment]
> @bardliao I meant that _this is_ kernel side patch for fw PR in the link ;)

Oh yes. I see :)

**Comment by lgirdwood** [comment]
ABI minor 9

**Comment by jajanusz** [comment]
@ranj063 FW patch was merged. Feel free to merge this one also. Regarding checkpatch warn - it can be ignored as it is better to keep it consistent with other uint32_t types instead of using u32 just for one field.

**Comment by jajanusz** [comment]
@plbossart @ranj063 FYI FW has merged all PRs for ABI.minor <= 8, this one is first of minor 9.

**Comment by ranj063** [comment]
@jajanusz could you please rebase and resubmit?

**Comment by jajanusz** [comment]
@ranj063 Rebased. Why do you need it? I think it's enough to just click "Rebase and merge" on GitHub's merge button (it shows when you click that little triangle).

**Comment by ranj063** [comment]
> @ranj063 Rebased. Why do you need it? I think it's enough to just click "Rebase and merge" on GitHub's merge button (it shows when you click that little triangle).

@jajanusz not when the branch is out-of-date. there's something missing in the settings probably for the linux repo which is making the process different. I'll discuss it with Pierre when he's back.

**Pull request merged**
