### PR TITLE
[TEST] SoundWire - use FIELD_PREP/GET

### PR DESCRIPTION
**Pull request by plbossart**
checking if patches from Vinod work.

### CODE REVIEW

**Comment by bardliao** [comment]
This doesn't work on both my CML-U and CML-H laptops. I will look into it.

**Comment by RanderWang** [comment]
> This doesn't work on both my CML-U and CML-H laptops. I will look into it.

yes,  it also failed on TGL

**Comment by bardliao** [comment]
@plbossart I got the reason why the change doesn't work. See the patch below. The ``addr`` is 16 bits, but ``CDNS_MCP_CMD_REG_ADDR_L`` is 8 bits only. We didn't meet the issue is because that SDW_REG_SHIFT() only shifts but not masks ``CDNS_MCP_CMD_REG_ADDR_L``. 
```patch
--- a/drivers/soundwire/cadence_master.c
+++ b/drivers/soundwire/cadence_master.c
@@ -135,6 +135,7 @@ MODULE_PARM_DESC(cdns_mcp_int_mask, "Cadence MCP IntMask");
 #define CDNS_MCP_CMD_DEV_ADDR                  GENMASK(27, 24)
 #define CDNS_MCP_CMD_REG_ADDR_H                        GENMASK(23, 16)
 #define CDNS_MCP_CMD_REG_ADDR_L                        GENMASK(15, 8)
+#define CDNS_MCP_CMD_REG_ADDR                  GENMASK(23, 8)
 #define CDNS_MCP_CMD_REG_DATA                  GENMASK(7, 0)

 #define CDNS_MCP_CMD_READ                      2
@@ -529,7 +530,7 @@ _cdns_xfer_msg(struct sdw_cdns *cdns, struct sdw_msg *msg, int cmd,
        for (i = 0; i < count; i++) {
                data = FIELD_PREP(CDNS_MCP_CMD_DEV_ADDR, msg->dev_num);
                data |= FIELD_PREP(CDNS_MCP_CMD_COMMAND, cmd);
-               data |= FIELD_PREP(CDNS_MCP_CMD_REG_ADDR_L, addr);
+               data |= FIELD_PREP(CDNS_MCP_CMD_REG_ADDR, addr);
                addr++;

                if (msg->flags == SDW_MSG_FLAG_WRITE)
```

**Comment by plbossart** [comment]
> @plbossart I got the reason why the change doesn't work. See the patch below. The `addr` is 16 bits, but `CDNS_MCP_CMD_REG_ADDR_L` is 8 bits only. We didn't meet the issue is because that SDW_REG_SHIFT() only shifts but not masks `CDNS_MCP_CMD_REG_ADDR_L`.
> 
> ```diff
> --- a/drivers/soundwire/cadence_master.c
> +++ b/drivers/soundwire/cadence_master.c
> @@ -135,6 +135,7 @@ MODULE_PARM_DESC(cdns_mcp_int_mask, "Cadence MCP IntMask");
>  #define CDNS_MCP_CMD_DEV_ADDR                  GENMASK(27, 24)
>  #define CDNS_MCP_CMD_REG_ADDR_H                        GENMASK(23, 16)
>  #define CDNS_MCP_CMD_REG_ADDR_L                        GENMASK(15, 8)
> +#define CDNS_MCP_CMD_REG_ADDR                  GENMASK(23, 8)
>  #define CDNS_MCP_CMD_REG_DATA                  GENMASK(7, 0)
> 
>  #define CDNS_MCP_CMD_READ                      2
> @@ -529,7 +530,7 @@ _cdns_xfer_msg(struct sdw_cdns *cdns, struct sdw_msg *msg, int cmd,
>         for (i = 0; i < count; i++) {
>                 data = FIELD_PREP(CDNS_MCP_CMD_DEV_ADDR, msg->dev_num);
>                 data |= FIELD_PREP(CDNS_MCP_CMD_COMMAND, cmd);
> -               data |= FIELD_PREP(CDNS_MCP_CMD_REG_ADDR_L, addr);
> +               data |= FIELD_PREP(CDNS_MCP_CMD_REG_ADDR, addr);
>                 addr++;
> 
>                 if (msg->flags == SDW_MSG_FLAG_WRITE)
> ```



> @plbossart I got the reason why the change doesn't work. See the patch below. The `addr` is 16 bits, but `CDNS_MCP_CMD_REG_ADDR_L` is 8 bits only. We didn't meet the issue is because that SDW_REG_SHIFT() only shifts but not masks `CDNS_MCP_CMD_REG_ADDR_L`.

Oh, so all addresses above 255 were clipped because of the zero mask?

That's a nice find, maybe share it on alsa-devel?

**Comment by plbossart** [comment]
> That's a nice find, maybe share it on alsa-devel?

Actually no, we need to remove all instances of ADDR_L now, it's also used for paging.

**Comment by bardliao** [comment]
Verified on CML-H laptop.

**Review by RanderWang — APPROVED** [review]
tested it on TGL-U.

**Comment by plbossart** [comment]
Closing now that the tests are fine.

@bardliao can you work with Vinod to get this upstream?
We should provide a Tested-by tag for both you and @RanderWang, I'll add my Reviewed-by when I see the update.
Thanks

**Comment by bardliao** [comment]
> Closing now that the tests are fine.
> 
> @bardliao can you work with Vinod to get this upstream?
> We should provide a Tested-by tag for both you and @RanderWang, I'll add my Reviewed-by when I see the update.
> Thanks

Sure

**Pull request closed without merging**
