### PR TITLE
[TEST] sdw upstream merge 20230216

### PR DESCRIPTION
**Pull request by plbossart**
draft to see if we can narrow down the upstream merge issues with FAIL suspend-resume reported in https://sof-ci.01.org/linuxpr/PR4197/build3239/devicetest/index.html

### CODE REVIEW

**Comment by plbossart** [comment]
pretty crazy, I have no issues with suspend-resume with https://sof-ci.01.org/linuxpr/PR4199/build3248/devicetest/index.html

But I only took the patches from soundwire/next, and there are additional ones that came from ASoC. Those actually change the prepare stuff which is quite related to suspend-resume. Let me add them on top.

**Comment by ranj063** [comment]
> pretty crazy, I have no issues with suspend-resume with https://sof-ci.01.org/linuxpr/PR4199/build3248/devicetest/index.html
> 
> But I only took the patches from soundwire/next, and there are additional ones that came from ASoC. Those actually change the prepare stuff which is quite related to suspend-resume. Let me add them on top.



> pretty crazy, I have no issues with suspend-resume with https://sof-ci.01.org/linuxpr/PR4199/build3248/devicetest/index.html
> 
> But I only took the patches from soundwire/next, and there are additional ones that came from ASoC. Those actually change the prepare stuff which is quite related to suspend-resume. Let me add them on top.

seems to be failing now @plbossart

**Comment by plbossart** [comment]
A single patch added and the tests fail https://sof-ci.01.org/linuxpr/PR4199/build3251/devicetest/index.html ?

Wow. Revert and retry, we'll see if this is repeatable.

**Comment by plbossart** [comment]
sounds like reverting did help, no errors on https://sof-ci.01.org/linuxpr/PR4199/build3254/devicetest/index.html

Let's re-add it once more to be sure.

**Comment by plbossart** [comment]
wow, it's spectacular, re-adding this patch makes the FAIL in suspend-resume re-appear.

https://sof-ci.01.org/linuxpr/PR4199/build3260/devicetest/index.html

**Comment by aiChaoSONG** [comment]
xrun happened if you check mtrace.

**Comment by aiChaoSONG** [comment]
SOFCI TEST

**Comment by miRoox** [comment]
SOFCI TEST

**Pull request closed without merging**
