### PR TITLE
Merge/sound upstream 20231204

### PR DESCRIPTION
**Pull request by plbossart**
it should have been a straightforward exercise but we had multiple conflicts with the hdac and ch_maps updates. @bardliao @ranj063 if you can check the changes to hda-dai.c and hda-dai-ops.c it'd be greatly appreciated.

### CODE REVIEW

**Comment by plbossart** [comment]
the only worrying FAIL is this: https://sof-ci.01.org/linuxpr/PR4730/build646/devicetest/index.html?model=MTLP_RVP_NOCODEC&testcase=check-alsabat-nocodec-32bits-821

````
2023-12-04 23:20:12 UTC [REMOTE_COMMAND] alsabat -Phw:sofnocodec,0 --standalone -n 240000 -r 48000 -c 2 -f S32_LE -F 821 -k 2.1
2023-12-04 23:20:13 UTC [REMOTE_COMMAND] alsabat -Chw:sofnocodec,0 -c 2 -r 48000 -f S32_LE -F 821 -k 2.1
 FAIL: Peak freq too high 837.16 Hz
````

@keqiaozhang  @fredoh9 is this a known issue?

**Comment by ujfalusi** [comment]
@plbossart, looks good to my eyes and local tests.

**Comment by bardliao** [comment]
@plbossart The hda-dai.c and hda-dai-ops.c change looks good to me

**Comment by plbossart** [comment]
I'll go ahead and merge, if there's really an alsa-bat issue chances are we'll see it more widely during testing.

**Pull request merged**
