### PR TITLE
Upstream merge 20200226

### PR DESCRIPTION
**Pull request by ranj063**

### CODE REVIEW

**Comment by ranj063** [comment]
@plbossart updated with soundwire merge now. I have not pushed the sof-dev-rebase branch yet though. There were multiple conflicts with a couple of soundwire files and I hope I did the right thing. Could you please take a look?

**Comment by plbossart** [comment]
> @plbossart updated with soundwire merge now. I have not pushed the sof-dev-rebase branch yet though. There were multiple conflicts with a couple of soundwire files and I hope I did the right thing. Could you please take a look?

can you push your sof-dev-rebase to your github (not the sof one)?

**Comment by ranj063** [comment]
@plbossart CI has become a bit too complex to decipher for me now. There are a few failures and a few tests that are "skipped" and some that are "not tested". I'm not sure what the subtle difference between these 2 CI jargons is. I have also pushed the sof-dev-rebase after this merge to my branch here: https://github.com/ranj063/linux/tree/sof-dev-rebase/20200226

**Comment by plbossart** [comment]
> @plbossart CI has become a bit too complex to decipher for me now. There are a few failures and a few tests that are "skipped" and some that are "not tested". I'm not sure what the subtle difference between these 2 CI jargons is. I have also pushed the sof-dev-rebase after this merge to my branch here: https://github.com/ranj063/linux/tree/sof-dev-rebase/20200226

I'll be less polite. @wenqingfu @xiulipan CI is broken, there's no way anyone could make a decision to merge or not with such cryptic results.

**Comment by ranj063** [comment]
> > @plbossart CI has become a bit too complex to decipher for me now. There are a few failures and a few tests that are "skipped" and some that are "not tested". I'm not sure what the subtle difference between these 2 CI jargons is. I have also pushed the sof-dev-rebase after this merge to my branch here: https://github.com/ranj063/linux/tree/sof-dev-rebase/20200226
> 
> I'll be less polite. @wenqingfu @xiulipan CI is broken, there's no way anyone could make a decision to merge or not with such cryptic results.

@plbossart @wenqingfu I have a feeling CI has been a bit heavy with a lot of tests added to it. We need a smarter way for CI to indicate whether or not to merge a patch. Ideally, there should be a baseline (this probably can even include failures that are seen on sof-dev) and the results with a new PR should be compared against the baseline to show if there is a regression or not. 

Also, the table itself is exploding in size now with new tests and new platforms. We need to make the reporting a bit smarter as well. The current method will not scale when we start adding TGL/SDW etc

**Comment by plbossart** [comment]
@bardliao @RanderWang can you try and test, we've done quite a bit of conflict resolution for the multi-cpu dai stuff, so you'd really want to check for regressions here. Thanks!

**Comment by xiulipan** [comment]
@ranj063 The `skippep` means the case is not capable to run on the DUT (feature not enabled, pipeline missed).  The `not tested` means the test is not run with unknown reason, no log is captured.

@ranj063 @plbossart Glad that you have some suggestions for CI. 
To me CI is only a tool that help to show test result, finally it is still human need to decide what is good or not. So you input is very important to make the CI better. 

So to make the result presentation more concise and precise. Here are some info that I would like to have your input.
- Could you help to give some example of the desired result you would expect?
- What is the minimum test cases that must be passed for a PR?
- What is the minimum DUT model you would like to have for a PR?

We are looking forward your feedback to optimize the result presentation.

@wenqingfu I think we may start to optimize the test cases in the base test. Some complex test case may not be appropriate for PR tests.

**Comment by bardliao** [comment]
> @bardliao @RanderWang can you try and test, we've done quite a bit of conflict resolution for the multi-cpu dai stuff, so you'd really want to check for regressions here. Thanks!

I did a quick test on cml laptop. Playback works fine, but somehow headset capture volume is very low. Note that headset capture volume is good If I test it without this PR with the same FW and topology

**Comment by plbossart** [comment]
> > @bardliao @RanderWang can you try and test, we've done quite a bit of conflict resolution for the multi-cpu dai stuff, so you'd really want to check for regressions here. Thanks!
> 
> I did a quick test on cml laptop. Playback works fine, but somehow headset capture volume is very low. Note that headset capture volume is good If I test it without this PR with the same FW and topology

Thanks @bardliao for the tests. I am leaning on an error with the capture DAI handling, but it's probably needs to be debugged off-line rather than hold the merge. I will try to debug using the sof-dev-rebase branch where it's easier to revert upstream patches.

**Comment by kv2019i** [comment]
Late ack @ranj063 @plbossart . Tested on multiple platforms and no issues found. HDA, HDMI, suspend flows all seem to work, so looks indeed good to go.

**Pull request merged**
