### PR TITLE
Merge/sound upstream 20220223

### PR DESCRIPTION
**Pull request by ujfalusi**
after a long pause, a bit painful upstream merge...

### CODE REVIEW

**Comment by ujfalusi** [comment]
@dbaluta, compress.c is causing quite a bit of headache with this merge, now down to this one:
sound/soc/sof/compress.c:310:25: error: symbol 'sof_compressed_ops' was not declared. Should it be static?

It is not used anywhere in upstream from where it is coming. I tried to find a hint on where you are putting it, but failed so far.

**Comment by plbossart** [comment]
CI is completely in the weeds?

https://sof-ci.01.org/linuxpr/PR3454/build7222/devicetest/ shows all devices as not available and the only thing I can see is "暂无数据" which Google Translate shows as 'no data'

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
> CI is completely in the weeds?

Not sure, I checked the PRs immediately before and after and they seem fine. This is a very large merge, maybe CI is just doing its job this time.

PR immediately before this one: https://sof-ci.01.org/linuxpr/PR3443/build7220/devicetest/
immediately after: https://sof-ci.01.org/sofpr/PR5393/build12115/devicetest/

I checked a few others.

**Comment by marc-hb** [comment]
https://sof-ci.01.org/linuxpr/PR3454/build7223/devicetest/ failed the same again.

At the same time, https://github.com/thesofproject/sof-test/pull/864 is being tested just fine.

The breakage is specific to this PR.

**Comment by ujfalusi** [comment]
Should we close this PR and open a new one tomorrow as merge-20220224 ?

**Comment by plbossart** [comment]
> Should we close this PR and open a new one tomorrow as merge-20220224 ?

Possibly. We should let the team in Shanghai look at the issue and you can assess tomorrow your morning what makes sense @ujfalusi 

It looks like @dbaluta posted a patch upstream for the sparse problem so we may want to pick it up as well.

**Comment by plbossart** [comment]
CI still broken https://sof-ci.01.org/linuxpr/PR3454/build7231/devicetest/

@XiaoyunWu6666 @keqiaozhang @aiChaoSONG @marc-hb @fredoh9 @greg-intel can someone please try to see what is happening by checking what the devices actually do?

**Comment by ujfalusi** [comment]
> > Should we close this PR and open a new one tomorrow as merge-20220224 ?
> 
> Possibly. We should let the team in Shanghai look at the issue and you can assess tomorrow your morning what makes sense @ujfalusi

Make sense.
 
> It looks like @dbaluta posted a patch upstream for the sparse problem so we may want to pick it up as well.

I have sent a new version, see the commit message for the reasoning:
https://lore.kernel.org/alsa-devel/20220224172324.17976-1-peter.ujfalusi@linux.intel.com/T/#u

**Comment by fredoh9** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
unexpected SoundWire suspend/resume issues reported in https://sof-ci.01.org/linuxpr/PR3454/build7233/devicetest/?model=TGLU_RVP_SDW&testcase=check-suspend-resume-with-playback-5

Let's redo the tests to see if this is a consistent problem

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by ujfalusi** [comment]
SOFCI TEST

**Comment by ujfalusi** [comment]
I have re-done the merge today to pick up few fixes from upstream. I'll open a new PR for that.

**Pull request closed without merging**
