### PR TITLE
ASoC: SOF: amd: Fix for incorrect DMA ch status register offset

### PR DESCRIPTION
**Pull request by Venkata-Prasad-Potturu**
DMA ch status register offset change in acp7.0 platform

Incorrect DMA channel status register offset check lead to firmware boot failure.

[   14.432497] snd_sof_amd_acp70 0000:c4:00.5: ------------[ DSP dump start ]------------
[   14.432533] snd_sof_amd_acp70 0000:c4:00.5: Firmware boot failure due to timeout
[   14.432549] snd_sof_amd_acp70 0000:c4:00.5: fw_state: SOF_FW_BOOT_IN_PROGRESS (3)
[   14.432610] snd_sof_amd_acp70 0000:c4:00.5: invalid header size 0x71c41000. FW oops is bogus
[   14.432626] snd_sof_amd_acp70 0000:c4:00.5: unexpected fault 0x71c40000 trace 0x71c40000
[   14.432642] snd_sof_amd_acp70 0000:c4:00.5: ------------[ DSP dump end ]------------
[   14.432657] snd_sof_amd_acp70 0000:c4:00.5: error: failed to boot DSP firmware -5
[   14.432672] snd_sof_amd_acp70 0000:c4:00.5: fw_state change: 3 -> 4
[   14.433260] dmic-codec dmic-codec: ASoC: Unregistered DAI 'dmic-hifi'
[   14.433319] snd_sof_amd_acp70 0000:c4:00.5: fw_state change: 4 -> 0
[   14.433358] snd_sof_amd_acp70 0000:c4:00.5: error: sof_probe_work failed err: -5

Update correct register offset for DMA ch status register.

Fixes: bff3c2a4062d ("ASoC: SOF: amd: add support for acp7.0 based platform")

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

**Comment by vijendarmukunda** [comment]
test this please

**Comment by Venkata-Prasad-Potturu** [comment]
As this is a fix, in parallel sending this patch to MarkBrown's repo to avoid delay in merging to mainline

**Review by ranj063 — APPROVED** [review]

**Comment by bardliao** [comment]
Close it as it is sent to mailing list and Mark Brown has applied it.

**Pull request closed without merging**
