### PR TITLE
[TEST] SoundWire sysfs upstream changes

### PR DESCRIPTION
**Pull request by plbossart**
need to check if the hierarchy is preserved.

### CODE REVIEW

**Comment by plbossart** [comment]
The first patch in this series seems to prevent LunarLake devices from booting to SSH, even with the sof-pci-lnl driver blacklisted. IOW something non-audio is going boink. We would need to test with a direct device access, testing remotely is impossible.

**Comment by djbw** [comment]
@plbossart any update on the debug?

I posted a debug patch to get more info [here](http://lore.kernel.org/r/65baa2c754e8d_37ad2941f@dwillia2-xfh.jf.intel.com.notmuch)

**Comment by plbossart** [comment]
> @plbossart any update on the debug?
> 
> I posted a debug patch to get more info [here](http://lore.kernel.org/r/65baa2c754e8d_37ad2941f@dwillia2-xfh.jf.intel.com.notmuch)

Sorry, we've been busy fixing bugs while most of our team was on CNY vacation. @marc-hb is looking into this today.

**Comment by plbossart** [comment]
@djbw the results are the same, the boot process is stopped while dealing with the initramfs. I'll have to leave you in the capable hands of JF-based @marc-hb, it's likely that LNL has some sort of sysfs tree snafu that is exposed by your patch.

**Comment by djbw** [comment]
> @djbw the results are the same, the boot process is stopped while dealing with the initramfs. I'll have to leave you in the capable hands of JF-based @marc-hb, it's likely that LNL has some sort of sysfs tree snafu that is exposed by your patch.

Sounds good, I was not expecting the patch to help, but hopefully give more info of which is_visible() callback might have been problematic, but if you don't even get a console / log out of the machine then not much to work with.

**Comment by marc-hb** [comment]
Dan's commit "sysfs: Introduce a mechanism to hide static attribute_groups" is definitely the trigger. In addition to comparing the base versus first commit of this PR, I also cherry picked it over v6.8-rc4 with the very same results: v6.8-rc4 alone works fine; hard hang and no logs at all with the cherry-pick on top.

What this patch triggers is a super hard hang while or immediately after loading the initramfs. So there is absolutely ZERO kernel logs on the eDP panel.

I tried the following kernel params: `debug break=top`. They work fine without the trigger, the system stops at the start of the initramfs. With the commit, the system crashes too early for  these to have any effect.

Without Dan's commit,  Ctrl-alt-del and SysRq work fine after `break=top`. With it, these key strokes have no effect while the kernel is locked up. Using the reset button on the front panel is required. 

I changed the initramfs compression in the odd chance. No difference.

https://lore.kernel.org/all/65baa2c754e8d_37ad2941f@dwillia2-xfh.jf.intel.com.notmuch/raw didn't apply, it seems to have spaces instead of tabs.
Pierre fixed that patch for me and shared it in this PR. I added it but it made not difference. I never tried the other, later commits in  this PR.


For complete disclosure these ACPI error show up every time the system boots:

```
Feb 17 00:00:46 jf-lnlm-rvp-nocodec-1 kernel: ACPI BIOS Error (bug): Failure creating named object [\_SB.BGNV], AE_ALREADY_EXISTS (20230331/dswload2-326)
Feb 17 00:00:46 jf-lnlm-rvp-nocodec-1 kernel: ACPI Error: AE_ALREADY_EXISTS, During name lookup/catalog (20230331/psobject-220)
Feb 17 00:00:46 jf-lnlm-rvp-nocodec-1 kernel: ACPI BIOS Error (bug): Failure creating named object [\_SB.BGMA], AE_ALREADY_EXISTS (20230331/dsfield-637)
Feb 17 00:00:46 jf-lnlm-rvp-nocodec-1 kernel: ACPI BIOS Error (bug): Failure creating named object [\_SB.BGMS], AE_ALREADY_EXISTS (20230331/dsfield-637)
Feb 17 00:00:46 jf-lnlm-rvp-nocodec-1 kernel: ACPI BIOS Error (bug): Failure creating named object [\_SB.BGIA], AE_ALREADY_EXISTS (20230331/dsfield-637)
Feb 17 00:00:46 jf-lnlm-rvp-nocodec-1 kernel: ACPI BIOS Error (bug): Failure creating named object [\_SB.PC00.PTMA], AE_ALREADY_EXISTS (20230331/dswload2-326)
Feb 17 00:00:46 jf-lnlm-rvp-nocodec-1 kernel: ACPI Error: AE_ALREADY_EXISTS, During name lookup/catalog (20230331/psobject-220)
Feb 17 00:00:46 jf-lnlm-rvp-nocodec-1 kernel: ACPI BIOS Error (bug): Failure creating named object [\_SB.PC00.PTMS], AE_ALREADY_EXISTS (20230331/dswload2-326)
Feb 17 00:00:46 jf-lnlm-rvp-nocodec-1 kernel: ACPI Error: AE_ALREADY_EXISTS, During name lookup/catalog (20230331/psobject-220)
Feb 17 00:00:46 jf-lnlm-rvp-nocodec-1 kernel: ACPI BIOS Error (bug): Failure creating named object [\_SB.PC00.PTIA], AE_ALREADY_EXISTS (20230331/dswload2-326)
Feb 17 00:00:46 jf-lnlm-rvp-nocodec-1 kernel: ACPI Error: AE_ALREADY_EXISTS, During name lookup/catalog (20230331/psobject-220)
Feb 17 00:00:46 jf-lnlm-rvp-nocodec-1 kernel: ACPI Error: Cannot assign type [Device] to [Integer] (must be type Int/Str/Buf) (20230331/exstoren-90)
Feb 17 00:00:46 jf-lnlm-rvp-nocodec-1 kernel: ACPI: \: Can't tag data node
Feb 17 00:00:46 jf-lnlm-rvp-nocodec-1 kernel: ACPI: \: Can't tag data node
Feb 17 00:00:46 jf-lnlm-rvp-nocodec-1 kernel: ACPI: \: Can't tag data node
Feb 17 00:00:46 jf-lnlm-rvp-nocodec-1 kernel: ACPI: \: Can't tag data node
Feb 17 00:00:46 jf-lnlm-rvp-nocodec-1 kernel: ACPI: \: Can't tag data node
Feb 17 00:00:46 jf-lnlm-rvp-nocodec-1 kernel: i8042: Can't read CTR while initializing i8042
Feb 17 00:00:50 jf-lnlm-rvp-nocodec-1 kernel: ucsi_acpi USBC000:00: failed to reset PPM!
Feb 17 00:00:50 jf-lnlm-rvp-nocodec-1 kernel: ucsi_acpi USBC000:00: error -ETIMEDOUT: PPM init failed
```

The next steps could/should be:

- Split Dan's commit into even smaller parts and try to isolate which part makes a difference
- Find a serial port and try `earlyprintk`

**Comment by marc-hb** [comment]
For people not familiar with SOF, these test results show no undesirable effect on generations other than LNL:
https://sof-ci.01.org/linuxpr/PR4799/build1464/devicetest/index.html
https://sof-ci.01.org/linuxpr/PR4799/build1465/devicetest/index.html
https://sof-ci.01.org/linuxpr/PR4799/build1466/devicetest/index.html

**Comment by marc-hb** [comment]
I found how to use a serial connection to this board. Crashes in `perf_event_sysfs_init`  every time:

```
.
.
.
[    5.747097] pci 0000:00:15.1: Adding to iommu group 13
[    5.752857] pci 0000:00:15.2: Adding to iommu group 13
[    5.758619] pci 0000:00:15.3: Adding to iommu group 13
[    5.764395] pci 0000:00:16.0: Adding to iommu group 14
[    5.770246] pci 0000:00:1c.0: Adding to iommu group 15
[    5.776040] pci 0000:00:1f.0: Adding to iommu group 16
[    5.781803] pci 0000:00:1f.3: Adding to iommu group 16
[    5.787568] pci 0000:00:1f.4: Adding to iommu group 16
[    5.793325] pci 0000:00:1f.5: Adding to iommu group 16
[    5.799186] pci 0000:7f:00.0: Adding to iommu group 17
[    5.805494] DMAR: Intel(R) Virtualization Technology for Direg for IO (SWIOTLB)
[    5.819731] software IO TLB: mapped [mem [    5.828831] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x28680fa287f, max_idle_ns: 440795281151 ns
[    5.839895] clocksource: Switched to clocksource tsc
[    5.845484] platform rtc_cmos: registered platform RTC device[    5.857089] BUG: kernel NULL pointer dereference, address: 00rnel mode
[    5.857658] #PF: error_code(0x0000) - not-present ] PREEMPT SMP NOPTI
[    5.857658] CPU: 1 PID: 1 Comm: swapper/IP: 0010:exra_is_visible+0x14/0x20
[    5.857658] Code: 00 00 0 5.857658] RSP: 0000:ffffaa1d400f7dd0 EFLAGS: 00010206
[    5.8 R08: fffffffffff742c3 R09: ffff9daec26c0000
[    5.857658] R10ffff9db22ec00000(0000) knlGS:0000000000000000
[    5.857658] CS2: 0000000000000000
[    5.857658] DR3: 0000000000000000 DR6: 0x181/0x490
[    5.857658]  ? exc_page_fault+0x68/0x190
[    5.5.857658]  internal_create_groups+0x42/0xa0
[    5.857658]  pmu_dev_alloc+0xc0/0xe0
[    5.857658]  perf_event_sysfs_init+0x580000000000 ]---
[    5.857658] RIP: 0010:exra_is_visible+0x14/0 90 90 90 90 90 90 90 90 90 f3 0f 1e fa 0f 1f 44 00 00 31 c0 83   5.857658] RBP: 0000000000000001 R08: fffffffffff742c3 R09: fff000000001 R12: ffff9da
ec355f800
[    5.857658] R13: ffffffffab80000000080050033
[    5.857658] CR2: 0000000000000008 CR3: 0000000400
[    5.857658] PKRU: 55555554
[    5.857658] note: swap[    6.235716] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000009
[    6.236701] Kernel Offset: 0x28c00000

```

**Comment by djbw** [comment]
I think this is the fixup, I did not expect empty attribute arrays, but that seems to be standard practice for perf pmu.


```
diff --git a/fs/sysfs/group.c b/fs/sysfs/group.c
index ccb275cdabcb..8c63ba3cfc47 100644
--- a/fs/sysfs/group.c
+++ b/fs/sysfs/group.c
@@ -33,10 +33,10 @@ static void remove_files(struct kernfs_node *parent,
 
 static umode_t __first_visible(const struct attribute_group *grp, struct kobject *kobj)
 {
-	if (grp->attrs && grp->is_visible)
+	if (grp->attrs && grp->attrs[0] && grp->is_visible)
 		return grp->is_visible(kobj, grp->attrs[0], 0);
 
-	if (grp->bin_attrs && grp->is_bin_visible)
+	if (grp->bin_attrs && grp->bin_attrs[0] && grp->is_bin_visible)
 		return grp->is_bin_visible(kobj, grp->bin_attrs[0], 0);
 
 	return 0;
-- 
2.43.0
```

**Comment by marc-hb** [comment]
> I think this is the fixup, I did not expect empty attribute arrays, but that seems to be standard practice for perf pmu.

This fixup works. System boots and nothing suspicious in the logs.

**Comment by plbossart** [comment]
closing since there are no issues remaining

**Pull request closed without merging**
