### PR TITLE
Fix/boards use modules

### PR DESCRIPTION
**Pull request by plbossart**
More cleanups in Kconfig/Makefiles

Implement suggestion from https://github.com/thesofproject/linux/issues/1963 for HDMI and extend it to Maxim helpers.

### CODE REVIEW

**Review by kv2019i — CHANGES_REQUESTED** [review]
@lyakh  @plbossart  Is this really needed? The savings at least for dsp-common are tiny and on most systems only one machine driver is loaded, so this is only saving disk space in the end.

On the other hand, too fine grained modules have their disadvantages. Module params, dynamic debugs, etc are spread out over dozens of modules with similar sounding names... compared to more monolith approaches, this can be harder to work with.

**Comment by lyakh** [comment]
> @lyakh @plbossart Is this really needed? The savings at least for dsp-common are tiny and on most systems only one machine driver is loaded, so this is only saving disk space in the end.
> 
> On the other hand, too fine grained modules have their disadvantages. Module params, dynamic debugs, etc are spread out over dozens of modules with similar sounding names... compared to more monolith approaches, this can be harder to work with.

@kv2019i I count 10 instances of linking hda_dsp_common.o that are removed by this patch. I think it's a worthwhile goal to eliminate that redundancy. As for how, I agree, that too many modules make things more difficult to work with. So, if possible I'd rather link that object to one of existing HDA kernel modules. However, if that's impossible, I do think having 10 users justifies sharing that code even if that means creating yet one more module.

**Comment by plbossart** [comment]
> > @lyakh @plbossart Is this really needed? The savings at least for dsp-common are tiny and on most systems only one machine driver is loaded, so this is only saving disk space in the end.
> > On the other hand, too fine grained modules have their disadvantages. Module params, dynamic debugs, etc are spread out over dozens of modules with similar sounding names... compared to more monolith approaches, this can be harder to work with.
> 
> @kv2019i I count 10 instances of linking hda_dsp_common.o that are removed by this patch. I think it's a worthwhile goal to eliminate that redundancy. As for how, I agree, that too many modules make things more difficult to work with. So, if possible I'd rather link that object to one of existing HDA kernel modules. However, if that's impossible, I do think having 10 users justifies sharing that code even if that means creating yet one more module.

I think it's useful and forces an explicit description of dependencies. We are sloppy with HDMI and maxim, even to the point where in the latter case the prefixes are all mixed for the symbols being used.
Yes discipline is hard but do we really want to continue down this path of uncontrolled code use?

**Comment by kv2019i** [comment]
@plbossart How is HDMI sloppy in this case? It's two functions, correct namespaces ("hda_dsp_hdmi_") and the dependencies are explictly written down in both the Makefile and the c file (via header inclusion). 

I did consider the module option, but back then I thought creating a new module for just two small funcitons, is an overkill. I also considered having the functions inlined in the header, but that seemed the sloppy option to me. OTOH, the maxim-common seems to have slightly more content, and if we push the maxim stuff to a separate module, then it's odd not to do the same for hda-dsp-common. 

@lyakh 10 times, but it's two small functions and any given system will load only one, so it's wasting tiny amount of storage space here. And there aren't really any convenient options to push these functions to some existing module. We have no other common code specific to Intel machine drivers.

**Review by kv2019i — COMMENTED** [review]
I'll lift my request-changes -- still not super convinced this is easier to manage, but I can see how this will turn into problems if we start to have more common code shared.

**Comment by plbossart** [comment]
> @plbossart How is HDMI sloppy in this case? It's two functions, correct namespaces ("hda_dsp_hdmi_") and the dependencies are explictly written down in both the Makefile and the c file (via header inclusion).

apologies. I meant in the maxim case there is no consistency between prefixes and no clear API.

For HDMI the only issue is the multiple inclusion.

 
> I did consider the module option, but back then I thought creating a new module for just two small funcitons, is an overkill. I also considered having the functions inlined in the header, but that seemed the sloppy option to me. OTOH, the maxim-common seems to have slightly more content, and if we push the maxim stuff to a separate module, then it's odd not to do the same for hda-dsp-common.
> 
> @lyakh 10 times, but it's two small functions and any given system will load only one, so it's wasting tiny amount of storage space here. And there aren't really any convenient options to push these functions to some existing module. We have no other common code specific to Intel machine drivers.

I am not comfortable merging this PR if @kv2019i does not agree. I thought we had a consensus here, and if not then I can live without this.

**Comment by ranj063** [comment]
> I'll lift my request-changes -- still not super convinced this is easier to manage, but I can see how this will turn into problems if we start to have more common code shared.

@kv2019i maybe it looks like a bit of an overkill now but if and when we start dding new machine drivers, it will be more convenient if these were separate modules.

**Review by kv2019i — APPROVED** [review]
I was checking other drivers in the sound tree and the use of "common" modules (as modules) seems to be the norm, so let's go with the flow.

**Review by lyakh — APPROVED** [review]

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by kv2019i** [comment]
We need to patch kconfig before we merge this:

--cut--
rmmod: ERROR: Module snd_soc_core is in use by: snd_soc_intel_sof_maxim_common
--cut--

**Comment by plbossart** [comment]
> We need to patch kconfig before we merge this:
> 
> --cut--
> rmmod: ERROR: Module snd_soc_core is in use by: snd_soc_intel_sof_maxim_common
> --cut--

wish granted: https://github.com/thesofproject/sof-test/pull/604

**Comment by kv2019i** [comment]
SOFCI TEST

**Pull request merged**
