### PR TITLE
[TEST] Test for Takashi's PCM API cleanups and the corresponding SOF changes

### PR DESCRIPTION
**Pull request by ranj063**

### CODE REVIEW

**Comment by ranj063** [comment]
SOFCI TEST

**Comment by xiulipan** [comment]
@ranj063 Please do not retest this PR on CI before you make any fix. It will make most device hang. Please try to test on local device first.

**Comment by ranj063** [comment]
@xiulipan I have tested this on my up2 without any issues. What's causing the hang? Are there any logs? I checked with @fredoh9 and he told me to restart the test

**Comment by xiulipan** [comment]
@ranj063 Most device is hang and can not be access with SSH. So I would ask some local test to get some output from screen.

**Comment by ranj063** [comment]
> @ranj063 Most device is hang and can not be access with SSH. So I would ask some local test to get some output from screen.

@xiulipan OK let me retest

**Comment by ranj063** [comment]
closing for now until I figure out the device hang issue

**Comment by plbossart** [comment]
> @ranj063 Please do not retest this PR on CI before you make any fix. It will make most device hang. Please try to test on local device first.

WHY? don't you have networked power supplies and the ability to restart a device that's stuck?
If not, CI will not be very useful for developers.... It's expected that we will make devices hang.

**Pull request closed without merging**
