### PR TITLE
Merge/backport v5.0 intel audio v20190419

### PR DESCRIPTION
**Pull request by plbossart**
This backport contains fixes from Libin for hdac_hdmi and BE hw params. I need 2 volunteers to test and approve.

### CODE REVIEW

**Comment by plbossart** [comment]
need 2 approvers -> this PR will be delayed until approved...

**Comment by xiulipan** [comment]
@ranj063 
Please have a look about this simple PR.

**Comment by ranj063** [comment]
@xiulipan @plbossart sorry for the delay. I will give this a go by afternoon today

**Comment by libinyang** [comment]
LGTM

**Pull request merged**
