### PR TITLE
Upstream: revert some core/dapm patches

### PR DESCRIPTION
**Pull request by ranj063**
4c10c44 : this patch is not needed as we call snd_soc_tplg_component_remove() in free_topology().
5711d8e9: this one is not required because even if the creation of kcontrols fails, the memory allocated will be freed during snd_soc_damp_widget_free()
0576373: This patch is not needed as well because with the topology freed before the card is removed, the null pointer exception will not be hit anymore.

Please do not merge yet. @bardliao and I are doing some further testing with this PR

### CODE REVIEW

**Comment by ranj063** [comment]
@plbossart I've tested sof_remove and sof_insert with these changes and it works OK. @bardliao is doing further testing today.

**Comment by bardliao** [comment]
@ranj063 It can pass ./sof_bootloop.sh test on my Up2. But after looking at the issue, I think we need to remove snd_soc_tplg_component_remove() in snd_sof_free_topology(). 
Please see the flow below.
```
soc_cleanup_card_resources()
    -> snd_card_free(card->snd_card) /* card->snd_card will be used by snd_soc_tplg_component_remove() */
    -> soc_remove_dai_links()
         -> soc_remove_link_components()
             -> soc_remove_component()
                   ->component->driver->remove()  ie. sof_pcm_remove()
                       -> snd_sof_free_topology()
                          -> snd_soc_tplg_component_remove()
```
So we can say that we will always hit the oops if snd_soc_tplg_component_remove() is not called before soc_cleanup_card_resources().

**Comment by plbossart** [comment]
sorry @bardliao I couldn't figure out what you were trying to explain and what oops you are referring to. Care to elaborate/clarify?

**Comment by ranj063** [comment]
@bardliao but if we dont call snd_soc_tplg_component_remove() in free_topology() when will it ever get called?

**Comment by plbossart** [comment]
@ranj063 can you clarify the commit message and use the name of the patches you want to revert in addition to the SHA1. Also you added precisions for 2 patches but revert 3.

**Comment by ranj063** [comment]
@plbossart updated the commit messages

**Comment by wenqingfu** [comment]
> sorry @bardliao I couldn't figure out what you were trying to explain and what oops you are referring to. Care to elaborate/clarify?

in the commit message of 0576373, @lyakh mentioned issue #144 which is an oops case ... a small act before, a big favor for later. 👍  

IIRC, the other commits were for oops panics as well. I'll see if there are ways to find out the corresponding issues.

**Comment by plbossart** [comment]
> > sorry @bardliao I couldn't figure out what you were trying to explain and what oops you are referring to. Care to elaborate/clarify?
> 
> in the commit message of [0576373](https://github.com/thesofproject/linux/commit/057637349447338e7eeb289921380cd7011b84c9), @lyakh mentioned issue #144 which is an oops case ... a small act before, a big favor for later. 
> 
> IIRC, the other commits were for oops panics as well. I'll see if there are ways to find out the corresponding issues.

None of these issues are based on current code and can't be reproduced I am afraid. I've asked multiple times what those patches were supposed to fix, and if there isn't a strong motivation or explanation let's remove it. If there is a regression then a git bisect will show what happened and we'll put it back.

**Comment by plbossart** [comment]
@ranj063 @bardliao I am not able to follow if you guys agree or not, so will merge when both of you are ok with the change. Thanks!

**Comment by ranj063** [comment]
> > sorry @bardliao I couldn't figure out what you were trying to explain and what oops you are referring to. Care to elaborate/clarify?
> 
> in the commit message of [0576373](https://github.com/thesofproject/linux/commit/057637349447338e7eeb289921380cd7011b84c9), @lyakh mentioned issue #144 which is an oops case ... a small act before, a big favor for later. 
> 
> IIRC, the other commits were for oops panics as well. I'll see if there are ways to find out the corresponding issues.

@wenqingfu @plbossart the 3 commits reverted here address the kernel oops seen when you call platform_unregister before freeing topology. Those 3 commits were trying to fix the issues by covering up  the errors in the core/dapm code when the problem was at the driver level. That is what this PR fixes.

**Comment by ranj063** [comment]
> @ranj063 @bardliao I am not able to follow if you guys agree or not, so will merge when both of you are ok with the change. Thanks!

@plbossart understood. I'll check with @bardliao tonight.

**Comment by bardliao** [comment]
@ranj063 snd_soc_tplg_component_remove() will be called in  __snd_soc_unregister_component() and that's why we need to call snd_soc_unregister_component() first in sof_remove(). Regarding the oops, please see the commit message on 4c10c44. card->snd_card is no longer valid after snd_card_free(card->snd_card), but we will use it in remove_widget() ```struct snd_card *card = comp->card->snd_card``` and some similar functions calling by snd_soc_tplg_component_remove(). So basically, we can't call snd_soc_tplg_component_remove() after snd_card_free(). And sof_pcm_remove() will be invoked by soc_remove_dai_links() which is called after snd_card_free() in soc_cleanup_card_resources(). That's why I suggest to remove snd_soc_tplg_component_remove() from snd_sof_free_topology()

**Comment by ranj063** [comment]
@plbossart , @bardliao and I agreed that this fix is good for now.
He has another issue in mind which could potentially cause an oops in case the component driver is not unregistered before the platform device is. He will file an issue for it if it is legit.

**Comment by ranj063** [comment]
@plbossart please dont merge this PR. I am testing another possible way to fix it which might be the right way to do it.

**Comment by ranj063** [comment]
@plbossart looks like I was just a tad bit late. I'll submit changes later if required.

**Pull request merged**
