### PR TITLE
Merge/upstream merge 20190821

### PR DESCRIPTION
**Pull request by plbossart**
weekly merge. Should be rather boring (which is a good thing) with TGL/EKL and SoundWire stuff merged upstream

Go forth and test.

### CODE REVIEW

**Comment by plbossart** [comment]
we seem to have an across the board issue with "Workqueue: events sof_pcm_period_elapsed_work"
Gah.

**Comment by plbossart** [comment]
@xiulipan I tested this PR on a WHL HDAudio + GLK Bobba, I don't see any errors in dmesg. Could it be that you have a different Kconfig? See attached what I use.
[sof-dev-defconfig.txt](https://github.com/thesofproject/linux/files/3527249/sof-dev-defconfig.txt)

**Comment by xiulipan** [comment]
@plbossart 
It seems to be a good result to me in CI. As the input/output error is a known issue from https://github.com/thesofproject/sof/issues/1578

Nocodec issue comes from https://github.com/thesofproject/sof/pull/1734

I do see the `Workqueue: events sof_pcm_period_elapsed_work`. I will go through our test logs to see when do we start to get the warning message about this.

PS: the diff about the kconfig is:
[config-def-pr1148.txt](https://github.com/thesofproject/linux/files/3536806/config-def-pr1148.txt)
```diff
diff sof-dev-defconfig.txt config-def-pr1148.txt
3c3
< # Linux/x86 5.3.0-rc1 Kernel Configuration
---
> # Linux/x86 5.3.0-rc5 Kernel Configuration
7c7
< # Compiler: gcc (Ubuntu 8.3.0-6ubuntu1) 8.3.0
---
> # Compiler: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
10c10
< CONFIG_GCC_VERSION=80300
---
> CONFIG_GCC_VERSION=70400
95c95
< # CONFIG_PREEMPT_LL is not set
---
> # CONFIG_PREEMPT is not set
590d589
< # CONFIG_ISCSI_IBFT_FIND is not set
1036a1036
> # CONFIG_NF_CONNTRACK_BRIDGE is not set
1534d1533
< # CONFIG_SCSI_LOWLEVEL_PCMCIA is not set
3323,3324c3322
< CONFIG_SND_DYNAMIC_MINORS=y
< CONFIG_SND_MAX_CARDS=32
---
> # CONFIG_SND_DYNAMIC_MINORS is not set
3332d3329
< CONFIG_SND_VMASTER=y
3417,3437c3414
< CONFIG_SND_HDA=m
< CONFIG_SND_HDA_INTEL=m
< CONFIG_SND_HDA_HWDEP=y
< CONFIG_SND_HDA_RECONFIG=y
< CONFIG_SND_HDA_INPUT_BEEP=y
< CONFIG_SND_HDA_INPUT_BEEP_MODE=1
< CONFIG_SND_HDA_PATCH_LOADER=y
< CONFIG_SND_HDA_CODEC_REALTEK=m
< CONFIG_SND_HDA_CODEC_ANALOG=m
< CONFIG_SND_HDA_CODEC_SIGMATEL=m
< CONFIG_SND_HDA_CODEC_VIA=m
< CONFIG_SND_HDA_CODEC_HDMI=m
< CONFIG_SND_HDA_CODEC_CIRRUS=m
< CONFIG_SND_HDA_CODEC_CONEXANT=m
< CONFIG_SND_HDA_CODEC_CA0110=m
< CONFIG_SND_HDA_CODEC_CA0132=m
< # CONFIG_SND_HDA_CODEC_CA0132_DSP is not set
< CONFIG_SND_HDA_CODEC_CMEDIA=m
< CONFIG_SND_HDA_CODEC_SI3054=m
< CONFIG_SND_HDA_GENERIC=m
< CONFIG_SND_HDA_POWER_SAVE_DEFAULT=0
---
> # CONFIG_SND_HDA_INTEL is not set
3445a3423
> CONFIG_SND_INTEL_NHLT=m
3512a3491
> CONFIG_SND_SOC_INTEL_DA7219_MAX98357A_GENERIC=m
3518d3496
< CONFIG_SND_SOC_INTEL_SKL_HDA_DSP_GENERIC_MACH=m
3519a3498,3499
> # CONFIG_SND_SOC_INTEL_CML_LP_DA7219_MAX98357A_MACH is not set
> CONFIG_SND_SOC_INTEL_TGL_RT1308_MACH=m
3558,3559c3538,3545
< # CONFIG_SND_SOC_SOF_COMETLAKE_LP_SUPPORT is not set
< # CONFIG_SND_SOC_SOF_COMETLAKE_H_SUPPORT is not set
---
> CONFIG_SND_SOC_SOF_COMETLAKE_LP=m
> CONFIG_SND_SOC_SOF_COMETLAKE_LP_SUPPORT=y
> CONFIG_SND_SOC_SOF_COMETLAKE_H=m
> CONFIG_SND_SOC_SOF_COMETLAKE_H_SUPPORT=y
> CONFIG_SND_SOC_SOF_TIGERLAKE_SUPPORT=y
> CONFIG_SND_SOC_SOF_TIGERLAKE=m
> CONFIG_SND_SOC_SOF_ELKHARTLAKE_SUPPORT=y
> CONFIG_SND_SOC_SOF_ELKHARTLAKE=m
3562c3548
< CONFIG_SND_SOC_SOF_HDA_AUDIO_CODEC=y
---
> # CONFIG_SND_SOC_SOF_HDA_AUDIO_CODEC is not set
3628d3613
< CONFIG_SND_SOC_HDAC_HDA=m
3656a3642
> CONFIG_SND_SOC_RT1308=m
3692a3679
> # CONFIG_SND_SOC_UDA1334 is not set

```

**Comment by plbossart** [comment]
@xiulipan I am not clear on why we have such configuration differences, are you not using the 'official' Kconfig stuff on thesofproject? Or is this me that didn't update?

**Pull request merged**
