### PR TITLE
ALSA: hda: patch_realtek: add quirk for Asus N7601ZM

### PR DESCRIPTION
**Pull request by plbossart**
Add pins and verbs needed to enable speakers and jack.

Link: https://github.com/thesofproject/linux/issues/4176
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

### CODE REVIEW

**Comment by ErikEngerd** [comment]
I tested this patch today and I can confirm that it is working. I now have audio through the speakers and the analog headphones. Also the built-in digital microphone is working. Also USB headphones and USB mic are working.

I was not able to test an analog microphone simply because I do not have one but that is the only thing. 

I tested on Rocky linux 9, with kernel version 5.14.0-162.12.1.el9_1.0.2.x86_64.

As far as I am concerned this is 'problem solved'. Thanks a lot for you quick response to this issue.

**Comment by plbossart** [comment]
@ErikEngerd thanks for testing. When we submit this patch upstream, it'd be good to give you credit for both reporting and testing this. We typically add tags such as 

Reviewed-by: Erik Engerd <email.address@provider.something>

Also I could use some comments on what the values set for the pins actually do:

````
			{ 0x19, 0x03A11050 }, /* FIXME: add comment */
			{ 0x1a, 0x03A11C30 }, /* FIXME: add comment */
			{ 0x21, 0x03211420 }, /* FIXME: add comment */
```` 

is there any documentation and pointer on this?

**Comment by ErikEngerd** [comment]
I don't know what these pins mean. I just followed the instructions and for me these are just hex codes.

**Comment by plbossart** [comment]
@bardliao @kv2019i you good with this?

**Review by kv2019i — APPROVED** [review]

**Review by bardliao — APPROVED** [review]

**Pull request merged**
