### PR TITLE
Merge/sound upstream 20241001

### PR DESCRIPTION
**Pull request by bardliao**
First upstream merge for 6.13

@kv2019i Can you double check drivers/gpu/drm/xe/xe_pci.c for the force_probe?

### CODE REVIEW

**Comment by bardliao** [comment]
https://sof-ci.01.org/linuxpr/PR5196/build4869/devicetest/index.html?model=LNLM_RVP_HDA&testcase=verify-kernel-boot-log
```
[    5.472025] kernel: xe 0000:00:02.0: [drm] *ERROR* GT0: Unsupported GuC v70.20.0! v70.29.2 or newer is required
[    5.472046] kernel: xe 0000:00:02.0: [drm] *ERROR* GT0: GuC init failed with -EINVAL
[    5.472052] kernel: xe 0000:00:02.0: [drm] *ERROR* GT0: Failed to initialize uC (-EINVAL)
[    5.472064] kernel: xe 0000:00:02.0: probe with driver xe failed with error -22
```
@kv2019i Could you take a look? Where can we get the latest GuC firmware? https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915?

**Comment by bardliao** [comment]
SOFCI TEST

**Comment by bardliao** [comment]
> https://sof-ci.01.org/linuxpr/PR5196/build4869/devicetest/index.html?model=LNLM_RVP_HDA&testcase=verify-kernel-boot-log
> 
> ```
> [    5.472025] kernel: xe 0000:00:02.0: [drm] *ERROR* GT0: Unsupported GuC v70.20.0! v70.29.2 or newer is required
> [    5.472046] kernel: xe 0000:00:02.0: [drm] *ERROR* GT0: GuC init failed with -EINVAL
> [    5.472052] kernel: xe 0000:00:02.0: [drm] *ERROR* GT0: Failed to initialize uC (-EINVAL)
> [    5.472064] kernel: xe 0000:00:02.0: probe with driver xe failed with error -22
> ```
> 
> @kv2019i Could you take a look? Where can we get the latest GuC firmware? https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915?

I updated /lib/firmware/xe/lnl_guc_70.bin and it works. Let's trigger CI test again

**Comment by ujfalusi** [comment]
@bardliao, the results are quite bad, can we try a new merge which would be on 6.12-rc2?
Things like
`kernel: psmouse serio1: pixart_ps2: init: Unable to query PixArt touchpad hardware.`
will be gone for example.

but even stable-2.2 is red, which is not right..

**Comment by bardliao** [comment]
> @bardliao, the results are quite bad, can we try a new merge which would be on 6.12-rc2? Things like `kernel: psmouse serio1: pixart_ps2: init: Unable to query PixArt touchpad hardware.` will be gone for example.
> 
> but even stable-2.2 is red, which is not right..

The CI didn't restart. But, yeah, let's try 6.12-rc2.

**Pull request closed without merging**
