### PR TITLE
Merge/20190626

### PR DESCRIPTION
**Pull request by ranj063**
Filling in for Pierre with the usual upstream merge.
Could I please request some sanity tests with this PR?

### CODE REVIEW

**Comment by RanderWang** [comment]
I just tested it on WHL RVP to check hda feature.
(1) playback & capture work
(2) two pipeline work
(3) s3 work
(4) jack detection work

I didn't have enough time to do stress test.

**Comment by ranj063** [comment]
Thanks @RanderWang 

I have tested UP2 as well and no regressions there.

**Comment by kv2019i** [comment]
I did not have time for a longer test, but on both CFL and UP2 all basic tests were ok, so seems good to go.

**Comment by ranj063** [comment]
@fredoh9 can I please request some sanity tests on GLK Ubuntu?

**Comment by ranj063** [comment]
@plbossart can I click on update branch to merge the latest changes from sof-dev into this branch before merging? or do I have to rebase?

**Comment by ranj063** [comment]
replaced by #1065

**Pull request closed without merging**
