### PR TITLE
Fix DSP suspend after a crash

### LINKED ISSUE #4023: DSP transition to wrong substate (D0I3) and playback was broken soon after resume from DSP panic
In 5.10 and 5.15 kernel code base when a forced DSP panic is created and as shown below with subsequent suspend cycles, system is transiting to wrong DSP substate (D0I3) eventhough there is no WOV stream.

[  361.163611] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc3_tx_msg_unlocked: ipc message send for 0x40080000 failed: -19
[  361.163628] sof-audio-pci-intel-tgl 0000:00:1f.3: error: PM_GATE ipc error -19
[  361.163651] input input8: PM: calling input_dev_suspend+0x0/0x43 @ 7256, parent: 0018:04F3:2F6F.0001
**[  361.163659] sof-audio-pci-intel-tgl 0000:00:1f.3: failed to set requested target DSP state 0 substate 1**
[  361.163667] input input8: PM: input_dev_suspend+0x0/0x43 returned 0 after 1 usecs
[  361.163670] sof-audio-pci-intel-tgl 0000:00:1f.3: error: setting dsp state 0 substate 1
[  361.163675] sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to power down DSP during suspend -19
[  361.163676] usb 3-10: PM: calling usb_dev_suspend+0x0/0x14 @ 186, parent: usb3
[  361.163677] usb 2-3: PM: calling usb_dev_suspend+0x0/0x14 @ 9, parent: usb2
[  361.163680] PM: pci_pm_suspend(): snd_sof_suspend+0x0/0x11 [snd_sof] returns -19

Also, soon after resume from DSP panic, the playback is broken in 5.15 kernel in contrast to 5.10 kernel.

### PR DESCRIPTION
**Pull request by ranj063**
Fixes https://github.com/thesofproject/linux/issues/4023

### CODE REVIEW

**Comment by jairaj-arava** [comment]
@cujomalainey @andyross @sathya-nujella

**Review by cujomalainey — APPROVED** [review]
Looks like a great fix, just trying to understand how it applies in our 5.4 and 5.10 kernels as those don't have the concept of the panic state yet.

**Comment by jairaj-arava** [comment]
> Looks like a great fix, just trying to understand how it applies in our 5.4 and 5.10 kernels as those don't have the concept of the panic state yet.
@cujomalainey 
[ASoC: SOF: pm: Always tear down pipelines before DSP suspend]
This is applicable only to  5.15 kernel since soon after resume we see playback is not happening since the pieplines are not tared down before the system suspends. On 5.10 we don't see this issue.
Whereas [ASoC: SOF: pm: Set target state earlier] is applicable to both 5.10 and 5.15.

**Comment by cujomalainey** [comment]
> Whereas [ASoC: SOF: pm: Set target state earlier] is applicable to both 5.10 and 5.15.

Hmm, in 5.10 I still don't see how that is true. In 5.10 `fw_state` is either `SOF_FW_BOOT_NOT_STARTED` or `SOF_FW_BOOT_COMPLETE` by the time FW load is complete. Suspend has an early bail for `NOT_STARTED` and the bug requires it to be not in the `BOOT_COMPLETE` state.

**Comment by ranj063** [comment]
> > Whereas [ASoC: SOF: pm: Set target state earlier] is applicable to both 5.10 and 5.15.
> 
> Hmm, in 5.10 I still don't see how that is true. In 5.10 `fw_state` is either `SOF_FW_BOOT_NOT_STARTED` or `SOF_FW_BOOT_COMPLETE` by the time FW load is complete. Suspend has an early bail for `NOT_STARTED` and the bug requires it to be not in the `BOOT_COMPLETE` state.

I do  not think the fix applies for the kernels that do not change the FW state after a crash. But wouldnt hurt to initialize the target state at the beginning even in those cases.

**Comment by cujomalainey** [comment]
> > > Whereas [ASoC: SOF: pm: Set target state earlier] is applicable to both 5.10 and 5.15.
> > 
> > 
> > Hmm, in 5.10 I still don't see how that is true. In 5.10 `fw_state` is either `SOF_FW_BOOT_NOT_STARTED` or `SOF_FW_BOOT_COMPLETE` by the time FW load is complete. Suspend has an early bail for `NOT_STARTED` and the bug requires it to be not in the `BOOT_COMPLETE` state.
> 
> I do not think the fix applies for the kernels that do not change the FW state after a crash. But wouldnt hurt to initialize the target state at the beginning even in those cases.

That I agree with, but it unfortunately means we likely don't have our smoking gun

**Review by plbossart — APPROVED** [review]
looks good but there's no information on the actual issue this PR is supposed to fix. The commit message and comment hint at a Chrome problem?
Also shouldn't there be a Fixes: tag for both commits?

**Comment by ranj063** [comment]
> looks good but there's no information on the actual issue this PR is supposed to fix. The commit message and comment hint at a Chrome problem? Also shouldn't there be a Fixes: tag for both commits?

@plbossart bug report coming soon. @jairaj-arava please link the bug to this PR once you have posted it. Thanks!

**Comment by ranj063** [comment]
> looks good but there's no information on the actual issue this PR is supposed to fix. The commit message and comment hint at a Chrome problem? Also shouldn't there be a Fixes: tag for both commits?

@plbossart I im not sure about a fixes tag. Unfortunately this part of the code hasnt changed for a long time but what changed was the addition of the fw state machine and the addition of the state change during a DSP panic which basically makes the check if (fw_state != BOOT_COMPLETE) not true

**Comment by plbossart** [comment]
Fine @ranj063, I'll let you decide if this needs to be merged now or later.

**Comment by ranj063** [comment]
> Fine @ranj063, I'll let you decide if this needs to be merged now or later.

@plbossart should I update the patches with "Link:,..."?

**Comment by plbossart** [comment]
> > Fine @ranj063, I'll let you decide if this needs to be merged now or later.
> 
> @plbossart should I update the patches with "Link:,..."?

it's probably ok without the link - or it can be added when upstreaming.

**Review by bardliao — APPROVED** [review]

**Review by ujfalusi — APPROVED** [review]

**Pull request merged**
