### PR TITLE
[TEST] ASoC: soc-pcm: upstream patches 210222

### PR DESCRIPTION
**Pull request by kv2019i**
Test PR for following series sent to upstream today:
ASoC: soc-pcm: unpack dpcm_set_fe_runtime()
ASoC: soc-pcm: add dpcm_runtime_setup()
ASoC: soc-pcm: add dpcm_runtime_setup_fe()
ASoC: soc-pcm: unpack dpcm_init_runtime_hw()
ASoC: soc-pcm: remove strange format storing

### CODE REVIEW

**Comment by kv2019i** [comment]
FYI @plbossart ... running a test run this time

**Comment by plbossart** [comment]
Thanks @kv2019i looks all good to me. Do you mind sending your Tested-by for that series?

**Comment by kv2019i** [comment]
> Thanks @kv2019i looks all good to me. Do you mind sending your Tested-by for that series?

I want to have time to review the code as well before sending a tested-by. I'm not sure our CI really stresses out the soc-pcm.c enough, so while nothing exploded, I'm not sure this is still all good to go.

**Comment by plbossart** [comment]
@kv2019i this PR doesn't seem relevant any longer, shall we close?

**Pull request closed without merging**
