### PR TITLE
ASoC: SOF: ipc4-topology: Correct data structures for the SRC and GAIN module

### PR DESCRIPTION
**Pull request by ujfalusi**
Hi,

Collect the data under of_ipc4_src_data/of_ipc4_gain_data struct which is used as payload for the init instance message and passed to the firmware.

### CODE REVIEW

**Comment by ujfalusi** [comment]
Changes since v1:
- correct the GAIN patch since part of the init instance message is also used as a gain update with large_config_set
 -  separate that a sof_ipc4_gain_params

**Review by plbossart — APPROVED** [review]
approving blindly, I really don't understand any of this but I don't have any objections either.

**Review by bardliao — APPROVED** [review]

**Comment by ujfalusi** [comment]
> approving blindly, I really don't understand any of this but I don't have any objections either.

The general issue is this:
```c
struct sof_ipc4_base_module_cfg {
	uint32_t cpc; /* the max count of Cycles Per Chunk processing */
	uint32_t ibs; /* input Buffer Size (in bytes)  */
	uint32_t obs; /* output Buffer Size (in bytes) */
	uint32_t is_pages; /* number of physical pages used */
	struct sof_ipc4_audio_format audio_fmt;
} __packed __aligned(4);

struct module_private {
	struct sof_ipc4_base_module_cfg base_config;
	/* varous parameters sent along with the MOD_INIT_INSTANCE message */
	...
	struct sof_ipc4_available_audio_format available_fmt;
	struct sof_ipc4_msg msg;
};
```
and we were copying this to the mailbox as payload:
```c
struct module_private *priv = swidget->private;
void data = priv;
size_t size = sizeof(struct sof_ipc4_base_module_cfg) + <size of the extra stuff>;

memcpy(mailbox, data, size);
```
the extra data after the base_cfg is not marked as packed, aligned and there is no indication what is sent and what is local variable.

**Comment by plbossart** [comment]
@ranj063 ok with those changes?

**Review by ranj063 — APPROVED** [review]
@ujfalusi this change is good but we;ve got sof_ipc4_process with the same problem. Can you please look into that too?

**Comment by ujfalusi** [comment]
> @ujfalusi this change is good but we;ve got sof_ipc4_process with the same problem. Can you please look into that too?

Process module handling is correct. It is using  a separately allocated area for the message to be sent. It is not memory optimized (the basecfg have two copies with this approach) but not different compared to how the copier is handled.

No update is needed for this PR.

**Pull request merged**
