### PR TITLE
 Test for [PATCH v3 00/23] ASoC: Replace dpcm_playback/capture to playback/capture_assertion

### PR DESCRIPTION
**Pull request by plbossart**

### CODE REVIEW

**Comment by plbossart** [comment]
https://sof-ci.01.org/linuxpr/PR4937/build2357/devicetest/index.html
bad results for CML and no results for GLK, let's redo the tests and hope for a different answer.

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
Looks like https://sof-ci.01.org/linuxpr/PR4937/build2361/devicetest/index.html still has a problem on Helios, @marc-hb @fredoh9 do you know if we can get the logs?

**Comment by marc-hb** [comment]
I'm working on fixing https://github.com/thesofproject/sof-test/issues/1112 and I made some progress but it's not done yet, so for now you need ssh when the firmware does not load :-(

So I did use ssh and here it the regression below.

I found that error 8 times and every time it was with this PR and kernel merge.

Commit: Merge [9be6af3a99f4](https://github.com/thesofproject/linux/commit/9be6af3a99f40fb05a32d03d6f60961d4706f3d3) into [4dc32018572e](https://github.com/thesofproject/linux/commit/4dc32018572e43814ef03a421f4aca0ad067b1ad)
 ⇒ [b32bc69645c4](https://github.com/thesofproject/linux/commit/b32bc69645c4becfa02c825def718d90d6a74f3e)

```
sudo journalctl --since '2024-04-18'  -g 'cml_rt5682_def.*create|Linux'
```

```
Apr 19 14:01:13 jf-cml-hel-rt5682-07 kernel: snd_sof:ipc3_log_header: sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx: 0x30130000: GLB_TPLG_MSG: PIPE_COMPLETE
Apr 19 14:01:13 jf-cml-hel-rt5682-07 kernel: snd_sof:sof_ipc3_complete_pipeline: sof-audio-pci-intel-cnl 0000:00:1f.3: tplg: complete pipeline PIPELINE.3.DMIC0.IN id 15
Apr 19 14:01:13 jf-cml-hel-rt5682-07 kernel: snd_sof:ipc3_log_header: sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx: 0x30130000: GLB_TPLG_MSG: PIPE_COMPLETE
Apr 19 14:01:13 jf-cml-hel-rt5682-07 kernel: snd_sof:sof_ipc3_complete_pipeline: sof-audio-pci-intel-cnl 0000:00:1f.3: tplg: complete pipeline PIPELINE.2.SSP0.IN id 11
Apr 19 14:01:13 jf-cml-hel-rt5682-07 kernel: snd_sof:ipc3_log_header: sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx: 0x30130000: GLB_TPLG_MSG: PIPE_COMPLETE
Apr 19 14:01:13 jf-cml-hel-rt5682-07 kernel: snd_sof:sof_ipc3_complete_pipeline: sof-audio-pci-intel-cnl 0000:00:1f.3: tplg: complete pipeline PIPELINE.1.SSP0.OUT id 5
Apr 19 14:01:13 jf-cml-hel-rt5682-07 kernel: snd_sof:ipc3_log_header: sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx: 0x30130000: GLB_TPLG_MSG: PIPE_COMPLETE
Apr 19 14:01:13 jf-cml-hel-rt5682-07 kernel: rt1011 i2c-10EC1011:00: ADC offset=0x0
Apr 19 14:01:13 jf-cml-hel-rt5682-07 kernel: rt1011 i2c-10EC1011:00: Gain0 offset=0x247
Apr 19 14:01:13 jf-cml-hel-rt5682-07 kernel: rt1011 i2c-10EC1011:00: Gain1 offset=0xd7
Apr 19 14:01:15 jf-cml-hel-rt5682-07 kernel: asix 1-2.1.1:1.0 enx000ec6706ff5: Link is Up - 100Mbps/Full - flow control off
Apr 19 14:01:15 jf-cml-hel-rt5682-07 kernel: rt1011 i2c-10EC1011:00: r0 resistance about 7.09 ohm, reg=0x240C96
Apr 19 14:01:15 jf-cml-hel-rt5682-07 kernel: rfkill: input handler disabled
Apr 19 14:01:15 jf-cml-hel-rt5682-07 kernel: rt1011 i2c-10EC1011:01: ADC offset=0x0
Apr 19 14:01:15 jf-cml-hel-rt5682-07 kernel: rt1011 i2c-10EC1011:01: Gain0 offset=0x6f
Apr 19 14:01:15 jf-cml-hel-rt5682-07 kernel: rt1011 i2c-10EC1011:01: Gain1 offset=0x1ffeea
Apr 19 14:01:17 jf-cml-hel-rt5682-07 kernel: rt1011 i2c-10EC1011:01: r0 resistance about 7.16 ohm, reg=0x23B53E
Apr 19 14:01:18 jf-cml-hel-rt5682-07 kernel:  SSP0-Codec: enable ASRC
Apr 19 14:01:18 jf-cml-hel-rt5682-07 kernel: rt1011 i2c-10EC1011:02: ADC offset=0x0
Apr 19 14:01:18 jf-cml-hel-rt5682-07 kernel: rt1011 i2c-10EC1011:02: Gain0 offset=0xc3
Apr 19 14:01:18 jf-cml-hel-rt5682-07 kernel: rt1011 i2c-10EC1011:02: Gain1 offset=0x1c
Apr 19 14:01:20 jf-cml-hel-rt5682-07 kernel: rt1011 i2c-10EC1011:02: r0 resistance about 6.15 ohm, reg=0x29915E
Apr 19 14:01:20 jf-cml-hel-rt5682-07 kernel: rt1011 i2c-10EC1011:03: ADC offset=0x0
Apr 19 14:01:20 jf-cml-hel-rt5682-07 kernel: rt1011 i2c-10EC1011:03: Gain0 offset=0x26c
Apr 19 14:01:20 jf-cml-hel-rt5682-07 kernel: rt1011 i2c-10EC1011:03: Gain1 offset=0x225
Apr 19 14:01:22 jf-cml-hel-rt5682-07 kernel: rt1011 i2c-10EC1011:03: r0 resistance about 5.78 ohm, reg=0x2C3527
Apr 19 14:01:22 jf-cml-hel-rt5682-07 kernel:  SSP1-Codec: SSP1-Codec capture assertion check error
Apr 19 14:01:22 jf-cml-hel-rt5682-07 kernel: sof_rt5682 cml_rt5682_def: ASoC: can't create pcm SSP1-Codec :-22
Apr 19 14:01:22 jf-cml-hel-rt5682-07 kernel: sof_rt5682 cml_rt5682_def: probe with driver sof_rt5682 failed with error -22

``

**Comment by plbossart** [comment]
ok this is clearly a problem with this PR, thanks @marc-hb, will report upstream.

````
Apr 19 14:01:22 jf-cml-hel-rt5682-07 kernel:  SSP1-Codec: SSP1-Codec capture assertion check error
Apr 19 14:01:22 jf-cml-hel-rt5682-07 kernel: sof_rt5682 cml_rt5682_def: ASoC: can't create pcm SSP1-Codec :-22
````

**Comment by plbossart** [comment]
I think I know the issue: these patches added a stricter check that both cpu and codec dais support a direction. That is not true when we have an echo reference generated in the firmware: the codec dai does not support capture at all.

**Comment by plbossart** [comment]
3 hours and the build is not complete?

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
These look relevant:
https://sof-ci.01.org/linuxpr/PR4937/build2507/devicetest/index.html

```
[  807.304740] kernel:  SSP1-Codec: CPU dai SSP1 Pin supports capture but codec DAI rt1011-aif does not
[  807.304825] kernel:  SSP1-Codec: CPU dai SSP1 Pin supports capture but codec DAI rt1011-aif does not
[  807.304881] kernel:  SSP1-Codec: CPU dai SSP1 Pin supports capture but codec DAI rt1011-aif does not
[  807.304935] kernel:  SSP1-Codec: CPU dai SSP1 Pin supports capture but codec DAI rt1011-aif does not
```

**Comment by plbossart** [comment]
Yeah, the errors above validate my theory that the new criteria are too strict. The Helios machine driver have a capture dailink that's connected to SSP1, even though the amplifiers don't support capture.

**Pull request closed without merging**
