### PR TITLE
Merge/sound upstream 20230313 (v6.3-rc1 - try 2)

### PR DESCRIPTION
**Pull request by ujfalusi**
Another try...

picked https://lore.kernel.org/lkml/20230312200731.599706-3-masahiroy@kernel.org/ on top to test in CI also.

### CODE REVIEW

**Comment by ujfalusi** [comment]
Replaces #4223

**Comment by ujfalusi** [comment]
@plbossart, looks like nvme SSD fail on ADLP and the SDW resume issues...

The good news is that I can reproduce now locally after:
```
sudo pacman -S gcc-11
cd ~/bin
ln -s $(which gcc-11) gcc
ln -s $(which g++-11) g++
```
and rebuild the kernel with the same config.
the two logs (`aplay -i -Dhw:0,0 -fdat /dev/zero`): 
[resume_gcc11.txt](https://github.com/thesofproject/linux/files/10958081/resume_gcc11.txt)
[resume_gcc12.txt](https://github.com/thesofproject/linux/files/10958016/resume_gcc12.txt)

There is certainly different sequence of events, the trigger start is at line 195 in both logs but in case of gcc-11 we have a trigger stop coming in instead of the stream to recover and play.

The machine is Dell `SKU Number: 0A3E`

**Comment by plbossart** [comment]
@ujfalusi this Dell SKU 0A3E is used with IPC3 firmware with the production key, yes?  I think I have one of these.

That would clearly point us to some sort of stack or memory corruption, exposed by differences in how the code is generated/optimized.

**Comment by ujfalusi** [comment]
@plbossart, yes, production key, IPC3.
6.3-rc2 is affected, 6.2 is working with gcc-11, but we did needed to bump the compiler version already for 6.2, so the root of the issue might be older and in 6.2.
Let's see what bisect will throw out and speculate after that.

**Comment by plbossart** [comment]
I can also reproduce the issue @ujfalusi on this PR, with gcc-11 installed. Different model (TGLU_SKU0A32_SDCA) but same problem. This is good because it means it's not a random platform-specific issue.

**Comment by plbossart** [comment]
````
[  304.800728] snd_sof:ipc3_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  304.836579] PM: suspend exit

<<< TRIGGER STOP AFTER 2s - sounds like xrun immediately after resume?

[  306.524775] snd_sof:sof_pcm_trigger: sof-audio-pci-intel-tgl 0000:00:1f.3: pcm: trigger stream 0 dir 0 cmd 0
[  306.524788] snd_sof:ipc3_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
````

**Comment by plbossart** [comment]
6.1 and 6.2 work fine with GCC-11, 6.3-rc1 is broken. More bisect needed - possibly leading to nonsensical results...

**Comment by plbossart** [comment]
who said it'd be an easy one? git bisect is broken for this release, lots of commits will not boot or handle USB dongles that I need.

````
git checkout v6.2
git bisect good
git checkout v6.3-rc1
git bisect bad
...
git bisect skip v6.2..307e14c039063f0c9bd7a18a7add8f940580dcc9
git bisect skip v6.2..07db5e247ab5858439b14dd7cc1fe538b9efcf32
git bisect skip v6.2..982818426a0ffaf93b0621826ed39a84be3d7d62
git bisect skip v6.2..3ee88df1b063962e39d7798ccc3b18fd10cea813
````

man.

**Comment by plbossart** [comment]
no luck @ujfalusi, I had to skip most of the -rc1 commits since the device would not boot. see log 
[bisect.log](https://github.com/thesofproject/linux/files/10963394/bisect.log)

I also tried with audio-only patches in PR https://github.com/thesofproject/linux/pull/4244, nothing problematic seen in local tests.

The only reproducible point is to add the log in https://github.com/thesofproject/linux/pull/4243, this works for me but don't ask me why. @bardliao maybe you can check if you see anything wrong with the dai->suspended flag?

Not an easy one to crack.

**Comment by ujfalusi** [comment]
@plbossart, I got it down to a single commit, but it does not help either :(
```
$ git bisect log   
git bisect start
# status: waiting for both good and bad commits
# bad: [eeac8ede17557680855031c6f305ece2378af326] Linux 6.3-rc2
git bisect bad eeac8ede17557680855031c6f305ece2378af326
# status: waiting for good commit(s), bad commit known
# good: [c9c3395d5e3dcc6daee66c6908354d47bf98cb0c] Linux 6.2
git bisect good c9c3395d5e3dcc6daee66c6908354d47bf98cb0c
# bad: [307e14c039063f0c9bd7a18a7add8f940580dcc9] Merge tag '6.3-rc-smb3-client-fixes' of git://git.samba.org/sfrench/cifs-2.6
git bisect bad 307e14c039063f0c9bd7a18a7add8f940580dcc9
# good: [36289a03bcd3aabdf66de75cb6d1b4ee15726438] Merge tag 'v6.3-p1' of git://git.kernel.org/pub/scm/linux/kernel/git/herbert/crypto-2.6
git bisect good 36289a03bcd3aabdf66de75cb6d1b4ee15726438
# good: [1a30a6b25f263686dbf2028d56041ac012b10dcb] wifi: brcmfmac: p2p: Introduce generic flexible array frame member
git bisect good 1a30a6b25f263686dbf2028d56041ac012b10dcb
# bad: [13e574b4941ee1931f8c70f33c3011f74e5fbd30] Merge tag 'spi-v6.3' of git://git.kernel.org/pub/scm/linux/kernel/git/broonie/spi
git bisect bad 13e574b4941ee1931f8c70f33c3011f74e5fbd30
# good: [7933b90b42896f5b6596e6a829bb31c5121fc2a9] Merge branch 'for-linus' into for-next
git bisect good 7933b90b42896f5b6596e6a829bb31c5121fc2a9
# good: [01bb11ad828b320749764fa93ad078db20d08a9e] sched/topology: fix KASAN warning in hop_cmp()
git bisect good 01bb11ad828b320749764fa93ad078db20d08a9e
# good: [4d4266e3fd321fadb628ce02de641b129522c39c] page_pool: add a comment explaining the fragment counter usage
git bisect good 4d4266e3fd321fadb628ce02de641b129522c39c
# good: [937ca916bf4de427242fb78105a0089af0dd43b3] MAINTAINERS: Remove file reference for Broadcom Broadband SoC HS SPI driver entry
git bisect good 937ca916bf4de427242fb78105a0089af0dd43b3
# good: [7f62cb8861190e7cc1018ff37597fc49b2eaafa8] regulator: max597x: Align for simple_mfd_i2c driver
git bisect good 7f62cb8861190e7cc1018ff37597fc49b2eaafa8
# bad: [064d7dcf51a82b480e953a15cca47e5df0426502] Merge tag 'sound-6.3-rc1' of git://git.kernel.org/pub/scm/linux/kernel/git/tiwai/sound
git bisect bad 064d7dcf51a82b480e953a15cca47e5df0426502
# good: [d1b4b4117f890978c23c8e84a58a6c4c713fb400] MAINTAINERS: Switch maintenance for mcr20a driver over
git bisect good d1b4b4117f890978c23c8e84a58a6c4c713fb400
# good: [b60417a9f2b890a8094477b2204d4f73c535725e] selftest: fib_tests: Always cleanup before exit
git bisect good b60417a9f2b890a8094477b2204d4f73c535725e
# good: [d1fabc68f8e0541d41657096dc713cb01775652d] Merge git://git.kernel.org/pub/scm/linux/kernel/git/netdev/net
git bisect good d1fabc68f8e0541d41657096dc713cb01775652d
# good: [f3dd0c53370e70c0f9b7e931bbec12916f3bb8cc] bpf: add missing header file include
git bisect good f3dd0c53370e70c0f9b7e931bbec12916f3bb8cc
# first bad commit: [064d7dcf51a82b480e953a15cca47e5df0426502] Merge tag 'sound-6.3-rc1' of git://git.kernel.org/pub/scm/linux/kernel/git/tiwai/sound
```

**Comment by ujfalusi** [comment]
No matter how hard I try, I always end up with that merge commit to blame, these are the changes behind: [the-blame.txt](https://github.com/thesofproject/linux/files/10966459/the-blame.txt)

Curiously it includes single SDW core change, which looks too familiar:
43f1a7f905fc ("soundwire: stream: Add specific prep/deprep commands to port_prep callback")
Reverting it and (again) makes suspend/resume working.

This still does not make any sense as this is a NOP in our machines.

**Comment by plbossart** [comment]
@ujfalusi The only common thing I can find is that something happens in the prepare step.

My PR https://github.com/thesofproject/linux/pull/4243 adds a log and changes the timing and I would guess that https://github.com/thesofproject/linux/commit/43f1a7f905fcc796620c6488a7098068a05484ca ("soundwire: stream: Add specific prep/deprep commands to port_prep callback") does the same. It's a nop in all cases but enough to make the test pass.

My guess is that the tests fail because we end-up NOT resending the IPC to the DSP on prepare (invoked by the ALSA/ASoC core on resume), and that causes an xrun and and error.

The only odd thing that I found is that the order is not exactly the same for hw_params, prepare and trigger, but I didn't see a smoking gun here.

````
hw_params:
     snd_soc_link_hw_params
     snd_soc_dai_hw_params (codec then cpu)
     snd_soc_pcm_component_hw_params

prepare
    snd_soc_link_prepare
    snd_soc_pcm_component_prepare
    snd_soc_pcm_dai_prepare

trigger
     snd_soc_link_trigger
     snd_soc_pcm_component_trigger
    snd_soc_pcm_dai_trigger
````

**Comment by ujfalusi** [comment]
Closing, new merge created: #4256

**Pull request closed without merging**
