### PR TITLE
Merge/sound upstream 20200820

### PR DESCRIPTION
**Pull request by plbossart**
First merge based on v5.9-rc1 (Takashi's branch is still a bit behind).

I had a couple of merge issues on SoundWire (intel.c/intel.h) and a change I did upstream on @RanderWang work that was not yet shared (sound/soc/sof/intel/hda-codec.c).

There's one regression in W=1 for a DA7219 codec so Travis CI should report a compilation issue (good test). Edit: it does fail as planned!

Let's see how this goes.

### CODE REVIEW

**Comment by plbossart** [comment]
Complete fail for sof-test on GLK-BOBBA
````
2020-08-20 19:24:53 UTC [REMOTE_ERROR] Pipeline(s) from topology don't match pipeline(s) from system
````

@fredoh9 @ranj063 can you help here? This could be a configuration issue, no?

**Comment by ranj063** [comment]
> Complete fail for sof-test on GLK-BOBBA
> 
> ```
> 2020-08-20 19:24:53 UTC [REMOTE_ERROR] Pipeline(s) from topology don't match pipeline(s) from system
> ```
> 
> @fredoh9 @ranj063 can you help here? This could be a configuration issue, no?

@plbossart we've got a codec probe failure
kernel: [    5.258979] sof-audio-pci 0000:00:0e.0: codec #2 probe error, ret: -5
kernel: [    5.259177] sof-audio-pci 0000:00:0e.0: no hda codecs found!

And the machine driver never probes. I wonder why

**Comment by plbossart** [comment]
> > Complete fail for sof-test on GLK-BOBBA
> > ```
> > 2020-08-20 19:24:53 UTC [REMOTE_ERROR] Pipeline(s) from topology don't match pipeline(s) from system
> > ```
> > 
> > 
> > @fredoh9 @ranj063 can you help here? This could be a configuration issue, no?
> 
> @plbossart we've got a codec probe failure
> kernel: [ 5.258979] sof-audio-pci 0000:00:0e.0: codec #2 probe error, ret: -5
> kernel: [ 5.259177] sof-audio-pci 0000:00:0e.0: no hda codecs found!

we've seen those errors before, they are not fatal IIRC. @kv2019i this is one question for you I guess.

> And the machine driver never probes. I wonder why

Yep, the tag provided by Takashi to Linus works, but at some point Linus' tree doesn't work any more. bisecting is the only way to know I guess

**Comment by ranj063** [comment]
> > And the machine driver never probes. I wonder why
> 
> Yep, the tag provided by Takashi to Linus works, but at some point Linus' tree doesn't work any more. bisecting is the only way to know I guess

I'll try bisecting tonight and see whats going on

**Comment by plbossart** [comment]
> > > And the machine driver never probes. I wonder why
> > 
> > 
> > Yep, the tag provided by Takashi to Linus works, but at some point Linus' tree doesn't work any more. bisecting is the only way to know I guess
> 
> I'll try bisecting tonight and see whats going on

working on it, it seems to be in the DRM stuff.

**Comment by plbossart** [comment]
Bisect results

````
4f0b4352bd26eff85f972ccf12bcdf9236a42175 is the first bad commit
commit 4f0b4352bd26eff85f972ccf12bcdf9236a42175
Author: Stanislav Lisovskiy <stanislav.lisovskiy@intel.com>
Date:   Tue May 19 16:11:12 2020 +0300

    drm/i915: Extract cdclk requirements checking to separate function
    
    In Gen11+ whenever we might exceed DBuf bandwidth we might need to
    recalculate CDCLK which DBuf bandwidth is scaled with.
    Total Dbuf bw used might change based on particular plane needs.
    
    Thus to calculate if cdclk needs to be changed it is not enough
    anymore to check plane configuration and plane min cdclk, per DBuf
    bw can be calculated only after wm/ddb calculation is done and
    all required planes are added into the state. In order to keep
    all min_cdclk related checks in one place let's extract it into
    separate function, checking and modifying any_ms.
    
    Reviewed-by: Manasi Navare <manasi.d.navare@intel.com>
    Signed-off-by: Stanislav Lisovskiy <stanislav.lisovskiy@intel.com>
    Signed-off-by: Manasi Navare <manasi.d.navare@intel.com>
    Link: https://patchwork.freedesktop.org/patch/msgid/20200519131117.17190-3-stanislav.lisovskiy@intel.com

 drivers/gpu/drm/i915/display/intel_display.c | 30 ++++++++++++++++++++--------
 1 file changed, 22 insertions(+), 8 deletions(-)
````

@kv2019i do you have a GLK Bobba device and can you look into this?

**Comment by RanderWang** [comment]
validated it with sof-test on TGL-RVP. pass!

**Comment by kv2019i** [comment]
@plbossart wrote:
>     drm/i915: Extract cdclk requirements checking to separate function
[...]
> @kv2019i do you have a GLK Bobba device and can you look into this?

I can arrange it. I'll try on another GLK device first, I suspect this will trigger on all GLK platforms. I suggest reverting this for now in sof-dev. I'll raise this with Stanislav as well. GKL are an exception case with very low base cdclk clock freq and this patch changes the logic related to cdclk changes. Just based on the outcome, I suspect the clock is not getting raised as it should in probe and thus the failure.

**Comment by plbossart** [comment]
@kv2019i I did a bunch of blind reverts, this seems to work locally, so pushed to GitHub to see the results on the CI devices.
Here's the list of what I reverted

````
19aefbc778b8 drm/i915: Fix wrong CDCLK adjustment changes
cac91e671ad5 drm/i915: Fix includes and local vars order
cd1915460861 drm/i915: Adjust CDCLK accordingly to our DBuf bw needs
8435576b3f69 drm/i915: Introduce for_each_dbuf_slice_in_mask macro
cf129762ba15 drm/i915: Plane configuration affects CDCLK in Gen11+
9877c37e05c8 drm/i915: Check plane configuration properly
4f0b4352bd26 drm/i915: Extract cdclk requirements checking to separate function
````

**Comment by plbossart** [comment]
also added a fix for the DA7219 issue so we should be good to go. Fingers crossed.

**Comment by plbossart** [comment]
@fredoh9 @xiulipan @ranj063 can you help with the error on ICL RVP:

````
kernel: [  450.204615] sof-audio-pci 0000:00:1f.3: error: extended rom status: 0x6000010 0x0 0x0 0x0 0x0 0x0 0x2001182 0x0
````

Could it me that we need to filter this in sof-test (the message has changed)?

Also why is BSW Cyan not online?

I don't want to merge until those two platforms are cleared.

**Comment by ranj063** [comment]
> @fredoh9 @xiulipan @ranj063 can you help with the error on ICL RVP:
> 
> ```
> kernel: [  450.204615] sof-audio-pci 0000:00:1f.3: error: extended rom status: 0x6000010 0x0 0x0 0x0 0x0 0x0 0x2001182 0x0
> ```
> 
> Could it me that we need to filter this in sof-test (the message has changed)?
> 
> Also why is BSW Cyan not online?
> 
> I don't want to merge until those two platforms are cleared.

@plbossart ICL is a known issue. Sometimes it takes more than 1 attempt to boot the firmware and an error shown in the first attempt results in a failed test. Wehave an issue filed to track this already https://github.com/thesofproject/sof-test/issues/340

**Comment by fredoh9** [comment]
> Also why is BSW Cyan not online?

BSW platform has two devices. All are online. I think, daily build and other pr took all of them at that moment. I will trigger one more time.

**Comment by fredoh9** [comment]
SOFCI TEST

**Comment by fredoh9** [comment]
@plbossart BSW_CYN_MAX98090 is verified. Although this time APL_UP2_NOCODEC didn't run, good to go.

**Comment by kv2019i** [comment]
@plbossart wrote:
> @kv2019i I did a bunch of blind reverts, this seems to work locally, so pushed to GitHub to see the results on the CI devices.
> Here's the list of what I reverted

Seems good to me. I tried to debug this on a Helios, but it so far I've not been able to boot 5.9-rc on it at all due to NVME failures. Might take longer to figure this out, so I'm ok to push ahead with the merge given the Bobba GLK device in CI gives greenlight for this.

**Review by kv2019i — APPROVED** [review]

**Pull request merged**
