### PR TITLE
[NOT FOR UPSTREAM] CODEOWNERS: add @ujfalusi and AMD/MTK owners

### PR DESCRIPTION
**Pull request by plbossart**
We need to make sure all reviewers are kept in the loop

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

### CODE REVIEW

**Review by ranj063 — APPROVED** [review]

**Comment by kuanhsuncheng** [comment]
Hi @plbossart, 
Could you help me add anther owner (@yaochunhung) for Mediatek? 
thanks.

**Comment by yaochunhung** [comment]
@plbossart  could you please also add owner for this file below? Thanks.
include/sound/sof/dai-mediatek.h        @yaochunhung @kuanhsuncheng

**Review by dbaluta — DISMISSED** [review]

**Comment by kv2019i** [comment]
@yaochunhung Let's wait US holidays to update the misssing entries. Or alternative, I'll merge this and you send a new PR to update the missing ones.

**Comment by yaochunhung** [comment]
@kv2019i  We can wait after US holiday if not urgent. thanks..

**Review by ranj063 — APPROVED** [review]

**Review by kuanhsuncheng — APPROVED** [review]

**Pull request merged**
