### PR TITLE
[SQUASHME]ASoC: sof: topology: fix memleak when errror happen

### PR DESCRIPTION
**Pull request by xiulipan**
Add kfree function when other error happens.

Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>

### CODE REVIEW

**Comment by ranj063** [comment]
@plbossart @xiulipan  this looks good.

One thing to add is freeing scontrol in control_unload too.

**Comment by xiulipan** [comment]
@ranj063 @plbossart 
will update this after ranjani's patch mereged. code scan may find more error after that.

**Comment by plbossart** [comment]
@ranj063 do you have any issues if we take this first if there are no blatant conflicts? I prefer to squash issues first rather than keep old bugs alive.

**Comment by ranj063** [comment]
@plbossart yes, please go ahead. This looks good. It will not affect my work.

**Pull request merged**
