### PR TITLE
[TEST] Morimto For ALSA SoC test 2019-10-16

### PR DESCRIPTION
**Pull request by morimoto**
cared SOF new driver. I still have sof/header.h compile issue, but do nothing so far. Maybe no problem on SOF CI (?)

### CODE REVIEW

**Comment by plbossart** [comment]
@xiulipan I think it's just better to avoid rebasing on top of topic/sof-dev, and just use @morimoto -san's PRs as is, only using the existing configs. Can we do this with the CI infrastructure?

**Comment by xiulipan** [comment]
@plbossart I am not sure what is this PR about. Do we need to merge this into sof-dev or we just need to test about this? The sof-ci now is only track PR that will merge into sof-dev. If need to test with some other branch, we can set up some temp job for this.

**Comment by lyakh** [comment]
> @plbossart I am not sure what is this PR about. Do we need to merge this into sof-dev or we just need to test about this? The sof-ci now is only track PR that will merge into sof-dev. If need to test with some other branch, we can set up some temp job for this.

@xiulipan I think it's just about testing, don't think this should or even can (reasonably) be merged into sof-dev

**Comment by xiulipan** [comment]
@lyakh Got that. Then we should not use PR test for this.
@morimoto Can you try to push to a branch? We can do some test with branch.

**Comment by plbossart** [comment]
> @lyakh Got that. Then we should not use PR test for this.
> @morimoto Can you try to push to a branch? We can do some test with branch.

@xiulipan what do you mean with a 'push to a branch'? that'd mean bypassing the GitHub UI really. 
Or did you mean having @morimoto maintain a baseline branch (e.g. Mark Brown's latest for-next) and create a Pull Request against that branch, as we do for SoundWire?

**Comment by xiulipan** [comment]
@plbossart @morimoto 
What I mean is that if branch `morimoto:for-alsa-soc-test-2019-10-16` do not need to be merged into sof-dev. Then we can have some standalone test for the branch itself or create a PR to the right target.

Below is the detail:
1. Create a right PR for the patches
If the branch  target is for-next. just make a simple fork branch in thesofproject:alsa-soc

Then recreate a PR  into  thesofproject:alsa-soc from morimoto:for-alsa-soc-test-2019-10-16

2. Use some branch test
@morimoto Can you try to push the morimoto:for-alsa-soc-test-2019-10-16 to thesofproject:sandbox/for-alsa-soc-test-2019-10-16

The CI can only work with the thesofproject for now, so need the branch pushed to thesofproject repo. I will create a temp test job for the branch.

**Comment by morimoto** [comment]
@xiulipan thank you for your help.
I tried to push my branch into thesofproject:sandbox/for-alsa-soc-test-2019-10-16, but I couldn't.
I guess I need to send my ssh key ? (Or am I misunderstanding ?)
And also I wonder it is OK for thesofproject security point of view ??

**Comment by morimoto** [comment]
+1 question.
If I could push my branch, then, I don't need to based on sof-dev branch anymore ?

**Comment by xiulipan** [comment]
@morimoto I think this is because some setting, so I also ask @plbossart for what kind of solution he would like.

We can do some white-list to let people to push branch to sandbox/  and CI can track on this branches.

**Comment by plbossart** [comment]
@morimoto did you accept the invite to join the project? I don't see you as a member so that is probably why you can't push.
There are rules and you can't erase our working branches.

**Comment by morimoto** [comment]
@plbossart sorry I didn't. It seems I lost invite mail. Can you please re-send it to me ?

**Comment by plbossart** [comment]
> @plbossart sorry I didn't. It seems I lost invite mail. Can you please re-send it to me ?

done. invite sent to @morimoto

**Comment by morimoto** [comment]
@plbossart thank you for your help. It seems strong gmail filter has made me confused.
I guess I could join to the SOF. I will push branch.
If I could do that, I will close this PR

**Comment by morimoto** [comment]
Hi All. Thanks a lot. Now I could push my branch to sof as "sandbox/morimoto-for-alsa-soc-test-2019-10-24".
If it works OK for you guys, I will close this PR.

**Pull request closed without merging**
