### PR TITLE
ASoC: SOF: ipc4-topology: Harden loops for looking up ALH copiers

### PR DESCRIPTION
**Pull request by ujfalusi**
Other, non DAI copier widgets could have the same  stream name (sname) as the ALH copier and in that case the copier->data is NULL, no alh_data is attached, which could lead to NULL pointer dereference. We could check for this NULL pointer in sof_ipc4_prepare_copier_module() and avoid the crash, but a similar loop in sof_ipc4_widget_setup_comp_dai() will miscalculate the ALH device count, causing broken audio.

The correct fix is to harden the matching logic by making sure that the
1. widget is a DAI widget - so dai = w->private is valid
2. the dai (and thus the copier) is ALH copier

Fixes: 0e357b529053 ("ASoC: SOF: ipc4-topology: add SoundWire/ALH aggregation support")
Reported-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>
Link: https://github.com/thesofproject/sof/pull/9652

### CODE REVIEW

**Comment by bardliao** [comment]
That happens when the topology provides less ALH dais in the aggregation mode. For example, there are 2 amps in different links, but `NUM_SDW_AMP_LINKS=1` in topology. Shouldn't we return error in this case?

**Comment by ujfalusi** [comment]
> That happens when the topology provides less ALH dais in the aggregation mode. For example, there are 2 amps in different links, but `NUM_SDW_AMP_LINKS=1` in topology. Shouldn't we return error in this case?

No, this happens when a module copier have the same stream name as the alh copier: https://github.com/thesofproject/sof/pull/9652#issuecomment-2488376131

That is a NULL dereference, but we also miscount the number of alh things.

**Review by lgirdwood — APPROVED** [review]

**Review by ranj063 — APPROVED** [review]

**Comment by bardliao** [comment]
@ujfalusi Can you fix the checkpatch warning?
```WARNING: Reported-by: should be immediately followed by Closes: with a URL to the report```
I.e. Change `Link: https://github.com/thesofproject/sof/pull/9652` to `Closes: https://github.com/thesofproject/sof/pull/9652`

**Comment by ujfalusi** [comment]
> @ujfalusi Can you fix the checkpatch warning? `WARNING: Reported-by: should be immediately followed by Closes: with a URL to the report` I.e. Change `Link: https://github.com/thesofproject/sof/pull/9652` to `Closes: https://github.com/thesofproject/sof/pull/9652`

I thought about that but it does not sound correct, the link is PR and not an issue and that PR is now updated to _not_ set the stream name for the module.copier.
At the same time I want to give credit to Seppo for the find, I will leave it as `Link:`

**Review by bardliao — APPROVED** [review]

**Pull request merged**
