### PR TITLE
IMX DAI fixes

### PR DESCRIPTION
**Pull request by dbaluta**
2 fixes related to propagating mclk/fsync rates from topology to DSP.

### CODE REVIEW

**Comment by dbaluta** [comment]
> What made it work before?

@paulstelian97 

That is a good question. I could only see this problem when testing compress interface.

At a first glance mlck_rate and fsync_rate are used in order to set the correct BCLK and FSYNC clocks on DSP side. Anyhow, since we fix the clocks from DTS we already set them to the correct rates, so it doesn't matter if we send BCLK/FSYNC as 0 to firmware because it no longer uses it.

With PCM interface (aplay receives rate parameter for example as a command line parameter with -c). 
With compress interface (cplay doesn't provide this rate parameter) and I think the lower kernel leves take this parameter
from sof_pcm_dai_link_fixup which the second patch addresses it).

**Comment by paulstelian97** [comment]
Oh, so before it was hacked around and somehow worked anyway. Alright, it's better now than never that a proper fix is given.

**Comment by dbaluta** [comment]
> Oh, so before it was hacked around and somehow worked anyway. Alright, it's better now than never that a proper fix is given.

Hacked is not quite the proper word. Because we cannot easily control the clocks from DSP side (remember we need to go through a special SCFW firmware) we control the clocks from ARM core side.

I think a proper wording is: "due to IMX design decisions".

**Comment by plbossart** [comment]
> > Oh, so before it was hacked around and somehow worked anyway. Alright, it's better now than never that a proper fix is given.
> 
> Hacked is not quite the proper word. Because we cannot easily control the clocks from DSP side (remember we need to go through a special SCFW firmware) we control the clocks from ARM core side.
> 
> I think a proper wording is: "due to IMX design decisions".

hardware's never broken, only requires specific programming sequences :-)

**Pull request merged**
