### PR TITLE
soundwire: intel: exit clock-stop mode before system suspend

### PR DESCRIPTION
**Pull request by plbossart**
Intel validation reported an issue where the HW_RST self-clearing bit
is not cleared in hardware, which as a ripple effect creates issues
with the clock stop mode.

This happens is a specific sequence where the Intel manager is
pm_runtime suspended with the clock-stop mode enabled. During the
system suspend, we currently do nothing, which can lead to potential
issues on system resume and the following pm_runtime suspend,
depending on the hardware state.

This patch suggests a full resume if the clock-stop mode is used. This
may require extra time but will make the suspend/resume flows
completely symmetric. This also removes a race condition where we
could not access SHIM registers if the parent was suspended as
well. Resuming the link also resumes the parent by construction.

BugLink: https://github.com/thesofproject/linux/issues/2606
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

### CODE REVIEW

**Comment by bardliao** [comment]
SOFCI TEST

**Comment by RanderWang** [comment]
@plbossart  copy your comments in https://github.com/thesofproject/linux/issues/2606#issuecomment-865499548 

"I have a possible explanation: this problem happens when the link is already pm_runtime suspended, so we are in clock-stop
mode. But when we do a system suspend, we don't resume the link out of clock stop. And when we do a system resume, we 
may be in a zombie state. It could very well be that we have to do a pm_runtime resume first, and do a full system suspend."

if we do a pm_runtime resume first, then we will find sdw controller is not in clock stop0 mode in intel_resume_runtime function for this case since sdw controller is powered off and clock stop0 state is not sustained.  And it will go normal path like intel_resume for s3.  I don't see any difference between intel_resume  vs intel_resume_runtime + intel_resume

**Comment by bardliao** [comment]
@plbossart It is interesting that `rt711_dev_system_suspend` was not invoked when I ran "sudo rtcwake -m mem -s 5" command. Did I miss something?

**Comment by plbossart** [comment]
> @plbossart It is interesting that `rt711_dev_system_suspend` was not invoked when I ran "sudo rtcwake -m mem -s 5" command. Did I miss something?

that was the case on the earlier version but that's no longer the case in the update, please double-check.

**Comment by plbossart** [comment]
> @plbossart copy your comments in [#2606 (comment)](https://github.com/thesofproject/linux/issues/2606#issuecomment-865499548)
> 
> "I have a possible explanation: this problem happens when the link is already pm_runtime suspended, so we are in clock-stop
> mode. But when we do a system suspend, we don't resume the link out of clock stop. And when we do a system resume, we
> may be in a zombie state. It could very well be that we have to do a pm_runtime resume first, and do a full system suspend."
> 
> if we do a pm_runtime resume first, then we will find sdw controller is not in clock stop0 mode in intel_resume_runtime function for this case since sdw controller is powered off and clock stop0 state is not sustained. And it will go normal path like intel_resume for s3. I don't see any difference between intel_resume vs intel_resume_runtime + intel_resume

@RanderWang the change is on the suspend path. The proposal is to bring the devices back to full power, i.e. exit the clock stop mode before doing the system suspend.
We don't know what the state of the hardware is when we do a system resume, and we obviously have real issues with the HW_RST bit that isn't cleared, so when in doubt the proposal is to avoid any dependency on a state that is related to clock stop.

**Comment by plbossart** [comment]
@bardliao @RanderWang I am not fully happy with this PR, there's got to be a way to force the devices to resume at the bus level, maybe with a .prepare step.

**Comment by plbossart** [comment]
@bardliao @RanderWang I think the update "should" provide a better solution, if only I found why the sdw_slave_suspend() callback doesn't seem to be called... Gah.

**Comment by bardliao** [comment]
> > @plbossart It is interesting that `rt711_dev_system_suspend` was not invoked when I ran "sudo rtcwake -m mem -s 5" command. Did I miss something?
> 
> that was the case on the earlier version but that's no longer the case in the update, please double-check.

@plbossart I double checked it with your latest update. I can only see `rt711 sdw:1:025d:0711:00: plb resume start`, but no `"plb system suspend start` or `plb sdw_slave_suspend start`
[dmesg_pr3006_0624.txt](https://github.com/thesofproject/linux/files/6706614/dmesg_pr3006_0624.txt)
I have to do some investigation.

**Comment by bardliao** [comment]
> @bardliao @RanderWang I think the update "should" provide a better solution, if only I found why the sdw_slave_suspend() callback doesn't seem to be called... Gah.

@plbossart The reason why `sdw_slave_suspend()` isn't called is because [dev->power.direct_complete](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/base/power/main.c#L1634) is true.
dev->power.direct_complete is assigned at [device_prepare](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/base/power/main.c#L1849). It is `true` due to `ret > 0` where [ret = callback(dev);](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/base/power/main.c#L1831).
We have `dev->pm_domain` for the sdw Slave devices so the callback is dev->pm_domain->ops.prepare which is [acpi_subsys_prepare](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/acpi/device_pm.c#L1016).
And [acpi_dev_needs_resume](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/acpi/device_pm.c#L990) will return `false` for `pm_runtime_suspended(dev)` is true. 
So `sdw_slave_suspend()` and `rt711_dev_system_suspend()` will be called if you do system suspend in playback.
ie.
1. Start a playback
2. Use another terminal to run the `sudo rtcwake -m mem -s 5` command.

**Comment by plbossart** [comment]
> > @bardliao @RanderWang I think the update "should" provide a better solution, if only I found why the sdw_slave_suspend() callback doesn't seem to be called... Gah.
> 
> @plbossart The reason why `sdw_slave_suspend()` isn't called is because [dev->power.direct_complete](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/base/power/main.c#L1634) is true.
> dev->power.direct_complete is assigned at [device_prepare](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/base/power/main.c#L1849). It is `true` due to `ret > 0` where [ret = callback(dev);](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/base/power/main.c#L1831).
> We have `dev->pm_domain` for the sdw Slave devices so the callback is dev->pm_domain->ops.prepare which is [acpi_subsys_prepare](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/acpi/device_pm.c#L1016).
> And [acpi_dev_needs_resume](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/acpi/device_pm.c#L990) will return `false` for `pm_runtime_suspended(dev)` is true.
> So `sdw_slave_suspend()` and `rt711_dev_system_suspend()` will be called if you do system suspend in playback.
> ie.
> 
> 1. Start a playback
> 2. Use another terminal to run the `sudo rtcwake -m mem -s 5` command.

Nice analysis @bardliao, you saved me a lot of time here.

I think we can just set the NO_DIRECT_COMPLETE flag and prevent all this
````c
dev->power.direct_complete = state.event == PM_EVENT_SUSPEND &&
		(ret > 0 || dev->power.no_pm_callbacks) &&
		!dev_pm_test_driver_flags(dev, DPM_FLAG_NO_DIRECT_COMPLETE); 
````

if we set this flag the result is logically false. Testing this now.

**Comment by plbossart** [comment]
> > > @bardliao @RanderWang I think the update "should" provide a better solution, if only I found why the sdw_slave_suspend() callback doesn't seem to be called... Gah.
> > 
> > 
> > @plbossart The reason why `sdw_slave_suspend()` isn't called is because [dev->power.direct_complete](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/base/power/main.c#L1634) is true.
> > dev->power.direct_complete is assigned at [device_prepare](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/base/power/main.c#L1849). It is `true` due to `ret > 0` where [ret = callback(dev);](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/base/power/main.c#L1831).
> > We have `dev->pm_domain` for the sdw Slave devices so the callback is dev->pm_domain->ops.prepare which is [acpi_subsys_prepare](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/acpi/device_pm.c#L1016).
> > And [acpi_dev_needs_resume](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/acpi/device_pm.c#L990) will return `false` for `pm_runtime_suspended(dev)` is true.
> > So `sdw_slave_suspend()` and `rt711_dev_system_suspend()` will be called if you do system suspend in playback.
> > ie.
> > 
> > 1. Start a playback
> > 2. Use another terminal to run the `sudo rtcwake -m mem -s 5` command.
> 
> Nice analysis @bardliao, you saved me a lot of time here.
> 
> I think we can just set the NO_DIRECT_COMPLETE flag and prevent all this
> 
> ```c
> dev->power.direct_complete = state.event == PM_EVENT_SUSPEND &&
> 		(ret > 0 || dev->power.no_pm_callbacks) &&
> 		!dev_pm_test_driver_flags(dev, DPM_FLAG_NO_DIRECT_COMPLETE); 
> ```
> 
> if we set this flag the result is logically false. Testing this now.

No luck @bardliao , with this change the direct_complete is false but still we don't call sdw_slave_suspend...

**Comment by bardliao** [comment]
> No luck @bardliao , with this change the direct_complete is false but still we don't call sdw_slave_suspend...

@plbossart I must be wrong with my last comment. `sdw_slave_suspend` should not be called by sdw devices. See [__device_suspend](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/base/power/main.c#L1591) line [1653](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/base/power/main.c#L1653) to line [1681](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/base/power/main.c#L1681). 
`dev->pm_domain` is the highest priority and `dev->bus->pm` is the lowest priority. Slave devices has `dev->pm_domain` which is ACPI domain. So `dev->bus->pm` will never be called. 
I don't know if change pm priority make sense or not. If yes, we can add pm ops in `sdw_slave_type`. If no, we may need to call `pm_runtime_resume` from each codec's prepare pm ops. BTW, I think it seems be more reasonable to call `pm_runtime_resume` from `prepare` instead of `suspend`.

**Comment by plbossart** [comment]
Good explanation @bardliao, I had no idea how power domains worked ;-)

It seems the issue is that "rtcwake -m mem" translates to S0 state, which means no resume:

https://github.com/thesofproject/linux/blob/bf96c0965401b833d4d762ca80b99bf7c2435f6d/drivers/acpi/device_pm.c#L999

Maybe that means that instead of forcing the codec to resume to work-around the clock stop issue, we need to deal with the intel_suspend differently and keep the clock stop mode and wakes in S0. @RanderWang I wonder if what we did assumed a transition to S3.

**Comment by bardliao** [comment]
SOFCI TEST

**Comment by bardliao** [comment]
@plbossart I like this version since all changes are in intel specific code. But we have to test `if (pm_runtime_enabled(dev))` before calling `pm_runtime_resume(dev)`. That should be able to fix the pr-device-test issue.
For example
```
static int intel_resume_child_device(struct device *dev, void *data)
{
        int ret = 0;

        if (pm_runtime_enabled(dev))
                ret = pm_runtime_resume(dev);

        return ret;
}
```

**Comment by plbossart** [comment]
> @plbossart I like this version since all changes are in intel specific code. But we have to test `if (pm_runtime_enabled(dev))` before calling `pm_runtime_resume(dev)`. That should be able to fix the pr-device-test issue.
> For example
> 
> ```
> static int intel_resume_child_device(struct device *dev, void *data)
> {
>         int ret = 0;
> 
>         if (pm_runtime_enabled(dev))
>                 ret = pm_runtime_resume(dev);
> 
>         return ret;
> }
> ```

@bardliao are you referring to this error?
````
[ 1037.444421] kernel: PM: device_prepare(): intel_pm_prepare+0x0/0x60 [soundwire_intel] returns -13
[ 1037.444439] kernel: soundwire_intel soundwire_intel.link.0: PM: not prepared for power transition: code -13
````

I don't see it in my local tests, and I don't understand why it happens either. If something disables pm_runtime(), then it's not clear to me how we would resume the device... Oh well, this needs more work obviously.

**Comment by plbossart** [comment]
update with one test to discard 'ghost' codec devices and trace in case of pm_runtime_resume errors

**Comment by plbossart** [comment]
Amazing how many bad configs this PR exposes. Now we have a case where we suspend/resume even when we are not using the SoundWire IP https://sof-ci.01.org/linuxpr/PR3006/build5945/devicetest/?model=TGLH_RVP_HDA&testcase=check-suspend-resume-5

````
[  821.104721] kernel: soundwire sdw:0:025d:0701:00: intel_resume_child_device: skipping device, no probed driver
[  821.104729] kernel: rt700 sdw:0:025d:0700:00: intel_resume_child_device: skipping device, never detected on bus
[  821.104739] kernel: soundwire sdw:1:025d:0701:00: intel_resume_child_device: skipping device, no probed driver
[  821.104742] kernel: rt700 sdw:1:025d:0700:00: intel_resume_child_device: skipping device, never detected on bus
[  821.105343] kernel: soundwire_intel soundwire_intel.link.1: intel_link_power_down: Unbalanced power-up/down calls
[  821.105346] kernel: soundwire_intel soundwire_intel.link.1: intel_link_power_down: powering down all links
[  821.106775] kernel: soundwire_intel soundwire_intel.link.1: intel_link_power_down: could not power down link
[  821.106778] kernel: soundwire_intel soundwire_intel.link.1: Link power down failed: -11
````

added a test to only do PM/wake sequences if we started the link.

**Comment by bardliao** [comment]
> Amazing how many bad configs this PR exposes. Now we have a case where we suspend/resume even when we are not using the SoundWire IP https://sof-ci.01.org/linuxpr/PR3006/build5945/devicetest/?model=TGLH_RVP_HDA&testcase=check-suspend-resume-5
> 
> ```
> [  821.104721] kernel: soundwire sdw:0:025d:0701:00: intel_resume_child_device: skipping device, no probed driver
> [  821.104729] kernel: rt700 sdw:0:025d:0700:00: intel_resume_child_device: skipping device, never detected on bus
> [  821.104739] kernel: soundwire sdw:1:025d:0701:00: intel_resume_child_device: skipping device, no probed driver
> [  821.104742] kernel: rt700 sdw:1:025d:0700:00: intel_resume_child_device: skipping device, never detected on bus
> [  821.105343] kernel: soundwire_intel soundwire_intel.link.1: intel_link_power_down: Unbalanced power-up/down calls
> [  821.105346] kernel: soundwire_intel soundwire_intel.link.1: intel_link_power_down: powering down all links
> [  821.106775] kernel: soundwire_intel soundwire_intel.link.1: intel_link_power_down: could not power down link
> [  821.106778] kernel: soundwire_intel soundwire_intel.link.1: Link power down failed: -11
> ```
> 
> added a test to only do PM/wake sequences if we started the link.

@plbossart This didn't fix the issue. The problem is that the link is enabled but all of its child are 'ghost'. And pm runtime will not be enabled for the 'ghost' devices. As a result, soundwire link device will not be resumed in the prepare process. My proposal is that we can check if we can find any 'real' child device before calling `intel_resume_child_device()`.
See https://github.com/bardliao/linux/commit/fdbde71ba17150726f1fc37a3248e004298fad1d

**Comment by bardliao** [comment]
> 
> @bardliao are you referring to this error?
> 
> ```
> [ 1037.444421] kernel: PM: device_prepare(): intel_pm_prepare+0x0/0x60 [soundwire_intel] returns -13
> [ 1037.444439] kernel: soundwire_intel soundwire_intel.link.0: PM: not prepared for power transition: code -13
> ```


Yes
> 
> I don't see it in my local tests, and I don't understand why it happens either. If something disables pm_runtime(), then it's not clear to me how we would resume the device... Oh well, this needs more work obviously.

It didn't appear on my test, either. But I can reproduce it when I added a 'ghost' to my acpi table on purpose and finally figured out what happen. We call `pm_runtime_enable(&slave->dev);` in codec driver's `io_init` function. That say pm runtime will not be enabled if the device is a 'ghost'.

**Comment by plbossart** [comment]
@bardliao I 'fixed' the issue for TGL_RVP_HDA by working around the problem: if we have an HDaudio platform we shouldn't start the links. That gets rid of multiple power-up/down issues that make no sense in the first place.

now checking with @ranj063 why we have a DSP panic with PCM_FREE that should not happen.

**Comment by plbossart** [comment]
Removed [TEST] prefix and made the PR 'ready for review'. Let's see if we still have a DSP panic with the COMP_FREE.

**Comment by plbossart** [comment]
@ranj063 I added a WARN_ON() that only triggers a trace for the TGL SoundWire RVP. No idea why we unconditionally send a buffer_ and comp_free IPC even when dynamic pipelines are not enabled. There's something specific about DMICs somehow (D0ix-compatible, suspend-ignore?)

**Comment by ranj063** [comment]
> @ranj063 I added a WARN_ON() that only triggers a trace for the TGL SoundWire RVP. No idea why we unconditionally send a buffer_ and comp_free IPC even when dynamic pipelines are not enabled. There's something specific about DMICs somehow (D0ix-compatible, suspend-ignore?)

@plbossart suspending during playback/capture always frees the widget for all platforms. This is needed because when we resume from S0ix, the suspended streams will be restarted and hw_params will be done again. So the free you're seeing is correct.

**Review by RanderWang — APPROVED** [review]
LGTM. It is much clear than before.

**Comment by bardliao** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
> SOFCI TEST

we still have a recurring issue with TGL_RVP_SDW, @ranj063 and I have no idea what's happening. More debug is required :-)

**Comment by ranj063** [comment]
> we still have a recurring issue with TGL_RVP_SDW, @ranj063 and I have no idea what's happening. More debug is required :-)

@plbossart after a bit of debug what I see is that the intel_pm_prepare() ends up stopping the DMIC PCM. Bard confirmed that it is due to an xrun. But its not clear why resuming the bus results in an xrun in the DMIC pipeline.

That aside, I think resuming devices during prepare is not a good idea. I think the intention is to resume the bus back to full power before suspending it. I think we should maybe look at the PCI bus for inspiration on how to do this right.

**Comment by plbossart** [comment]
> @plbossart after a bit of debug what I see is that the intel_pm_prepare() ends up stopping the DMIC PCM. Bard confirmed that it is due to an xrun. But its not clear why resuming the bus results in an xrun in the DMIC pipeline.

Xruns can happen at any time, that doesn't explain why we send 'illegal' IPCs to the firmware in that case?
I also don't see how the resume would stop the DMIC PCM. If the DMIC was operational nothing would be resumed, and if the DMIC was not operational the resume wouldn't stop it.

I must be missing something on the root-cause....

> That aside, I think resuming devices during prepare is not a good idea. I think the intention is to resume the bus back to full power before suspending it. I think we should maybe look at the PCI bus for inspiration on how to do this right.

I consulted with Rafael on this and didn't find any other way. If we only restart the parent we'll still have weird configurations. See how many versions of this PR I pushed...

**Comment by bardliao** [comment]
> > @plbossart after a bit of debug what I see is that the intel_pm_prepare() ends up stopping the DMIC PCM. Bard confirmed that it is due to an xrun. But its not clear why resuming the bus results in an xrun in the DMIC pipeline.
> 
> Xruns can happen at any time, that doesn't explain why we send 'illegal' IPCs to the firmware in that case?
> I also don't see how the resume would stop the DMIC PCM. If the DMIC was operational nothing would be resumed, and if the DMIC was not operational the resume wouldn't stop it.

@plbossart I think it is exactly the xrun stops the DMIC PCM. I added `dump_stack();` when we get a trigger stop cmd.
```patch
diff --git a/sound/soc/soc-pcm.c b/sound/soc/soc-pcm.c
index ff6da58b3a33..80ee0378b0e3 100644
--- a/sound/soc/soc-pcm.c
+++ b/sound/soc/soc-pcm.c
@@ -2098,7 +2098,8 @@ static int dpcm_dai_trigger_fe_be(struct snd_pcm_substream *substream,
        if (fe_first) {
                dev_dbg(fe->dev, "ASoC: pre trigger FE %s cmd %d\n",
                        fe->dai_link->name, cmd);
-
+               if (cmd == 0)
+                       dump_stack();
                ret = soc_pcm_trigger(substream, cmd);
                if (ret < 0)
                        return ret;
```
and got
```
[   27.480735]  DMIC: ASoC: pre trigger FE DMIC cmd 0
[   27.480739] CPU: 2 PID: 22 Comm: kworker/2:0 Not tainted 5.13.0-rc7+ #17
[   27.480743] Hardware name: Intel Corporation Tiger Lake Client Platform/TigerLake U DDR4 SODIMM RVP, BIOS TGLSFWI1.R00.3264.A00.2006251828 06/25/2020
[   27.480746] Workqueue: events snd_sof_pcm_period_elapsed_work [snd_sof]
[   27.480761] Call Trace:
[   27.480766]  dump_stack+0x64/0x7c
[   27.480773]  dpcm_dai_trigger_fe_be+0xbf/0xd0 [snd_soc_core]
[   27.480799]  dpcm_fe_dai_do_trigger+0x8f/0x1d0 [snd_soc_core]
[   27.480817]  ? usleep_range+0x40/0x90
[   27.480825]  snd_pcm_do_stop+0x33/0x60 [snd_pcm]
[   27.480836]  snd_pcm_action_single+0x2e/0x80 [snd_pcm]
[   27.480845]  __snd_pcm_xrun+0x36/0xa0 [snd_pcm]
[   27.480857]  snd_pcm_update_state+0xf9/0x100 [snd_pcm]
[   27.480866]  snd_pcm_update_hw_ptr0+0x1bb/0x400 [snd_pcm]
[   27.480874]  ? __lock_acquire.isra.33+0x149/0x680
[   27.480883]  snd_pcm_period_elapsed_under_stream_lock+0x52/0x80 [snd_pcm]
[   27.480892]  snd_pcm_period_elapsed+0x1a/0x30 [snd_pcm]
[   27.480900]  process_one_work+0x2b9/0x580
[   27.480909]  worker_thread+0x34/0x3f0
[   27.480913]  ? process_one_work+0x580/0x580
[   27.480915]  kthread+0x132/0x150
[   27.480920]  ? kthread_park+0x80/0x80
[   27.480925]  ret_from_fork+0x1f/0x30
```
[dmesg_tglu_rvp.txt](https://github.com/thesofproject/linux/files/6809296/dmesg_tglu_rvp.txt)
The xrun happens consistently on TGLU_RVP_SDW platforms, but it seems no other platforms meet the same issue.
I tested CML_RVP_SDW and Volteer with the same command, and both platforms work fine. 
I have no idea how the xrun happens.
Also, I suspect that we may meet the DSP panic issue if we inject a xrun manually and do system suspend.
Do you know a way to inject a xrun manually?
I vaguely remember we have a way to do this, but I can't remember it anymore.

> 
> I must be missing something on the root-cause....

**Comment by plbossart** [comment]
@bardliao @ranj063 I have a theory here... We are capturing with the DMIC and resume the RT711. At some point there will be an interrupt to deal with the jack detection on the SoundWire link, and IF that interrupt takes too much time to be processed it may impact the DMIC DMA. I think it's the only logical connection between the two parts, we only have one interrupt to deal with both SoundWire and DMIC.

It could also be that the .prepare has a side effect on interrupt handling.

**Comment by ranj063** [comment]
> @bardliao @ranj063 I have a theory here... We are capturing with the DMIC and resume the RT711. At some point there will be an interrupt to deal with the jack detection on the SoundWire link, and IF that interrupt takes too much time to be processed it may impact the DMIC DMA. I think it's the only logical connection between the two parts, we only have one interrupt to deal with both SoundWire and DMIC.
> 
> It could also be that the .prepare has a side effect on interrupt handling.

@plbossart it must be something to do with the prepare stage. I mean I tried resuming the RT711 by opening a playback PCM during DMIC recording and didnt see any xruns.

**Comment by plbossart** [comment]
@ranj063 @bardliao the prepare is one possibility, but we also need to much with jack detection while DMICs are capturing. I think this is a likely problem as well, we've never tested this since the test devices are all remote....

**Comment by plbossart** [comment]
For the record, I get the issue on Google Volteer with the same topology as TGLU_RVP_SDW

[dmesg.txt](https://github.com/thesofproject/linux/files/6811066/dmesg.txt)

sof-tgl-sdw-max98373-rt5682-dmic4ch-ampref

**Comment by plbossart** [comment]
@bardliao @ranj063 @RanderWang Update with pm_request_resume() instead of pm_runtime_resume() - this seems to solve the weird COMP_FREE issues and the DMIC underrun.

I am not fully sure why this works, but I also got good results by manually doing a pm_runtime_resume in the codec .suspend callbacks. It's really the .prepare operation with the pm_runtime_resume() done serially that doesn't seem to work well.

**Comment by plbossart** [comment]
> @bardliao @ranj063 I have a theory here... We are capturing with the DMIC and resume the RT711. At some point there will be an interrupt to deal with the jack detection on the SoundWire link, and IF that interrupt takes too much time to be processed it may impact the DMIC DMA. I think it's the only logical connection between the two parts, we only have one interrupt to deal with both SoundWire and DMIC.

I disabled the IMP_DEF interrupts and no improvement, so it wasn't the jack detection that caused issues

> It could also be that the .prepare has a side effect on interrupt handling.

It's the use of pm_runtime_resume() that does not work for some odd reason.

**Comment by plbossart** [comment]
https://sof-ci.01.org/linuxpr/PR3006/build6016/devicetest/ all PASS. I haven't seen this in a while :-)

**Review by ranj063 — DISMISSED** [review]

**Review by bardliao — DISMISSED** [review]

**Review by RanderWang — APPROVED** [review]

**Comment by plbossart** [comment]
started a longer validation with Intel test 5283. If no issue reported we can merge.

**Comment by plbossart** [comment]
Complete failure on Intel test 5283, on TGLU_SKU0A32_SDCA we see random power_down/power_up sequences leading to a bus clash. Gah.

````
[  170.199758] kernel: soundwire_intel soundwire_intel.link.2: intel_link_power_down: powering down all links
[  170.199771] kernel: soundwire_intel soundwire_intel.link.1: intel_link_power_up: powering up all links
[  170.199771] kernel: soundwire_intel soundwire_intel.link.1: intel_link_power_up: first link up, programming SYNCPRD
[  170.200118] kernel: rt1316-sdca sdw:1:025d:1316:01: sdw_modify_slave_status: initializing enumeration and init completion for Slave 1
[  170.200971] kernel: soundwire_intel soundwire_intel.link.1: Slave status change: 0x2
[  170.200975] kernel: soundwire sdw-master-1: Slave attached, programming device number
[  170.201141] kernel: soundwire sdw-master-1: SDW Slave Addr: 31025d131601
[  170.201142] kernel: soundwire sdw-master-1: SDW Slave class_id 0x01, mfg_id 0x025d, part_id 0x1316, unique_id 0x1, version 0x3
[  170.201143] kernel: soundwire sdw-master-1: Slave already registered, reusing dev_num:1
[  170.201370] kernel: soundwire_intel soundwire_intel.link.1: Msg ignored for Slave 0
[  170.201371] kernel: soundwire sdw-master-1: No more devices to enumerate
[  170.201395] kernel: soundwire_intel soundwire_intel.link.1: Slave status change: 0x21
[  170.201397] kernel: rt1316-sdca sdw:1:025d:1316:01: sdw_modify_slave_status: signaling enumeration completion for Slave 1
[  170.201573] kernel: rt1316-sdca sdw:1:025d:1316:01: Configured bus base 1, scale 3, mclk 19200000, curr_freq 4800000
[  170.214595] kernel: rt1316-sdca sdw:1:025d:1316:01: rt1316_io_init hw_init complete
[  170.214596] kernel: rt1316-sdca sdw:1:025d:1316:01: sdw_handle_slave_status: signaling initialization completion for Slave 1
[  170.214624] kernel: soundwire_intel soundwire_intel.link.1: Slave status change: 0x40
[  170.224398] kernel: soundwire_intel soundwire_intel.link.1: intel_link_power_down: powering down all links
[  170.224405] kernel: soundwire_intel soundwire_intel.link.0: intel_link_power_up: powering up all links
[  170.224406] kernel: soundwire_intel soundwire_intel.link.0: intel_link_power_up: first link up, programming SYNCPRD
[  170.224460] kernel: soundwire_intel soundwire_intel.link.1: Bus clash for control word
````

**Comment by ranj063** [comment]
> Complete failure on Intel test 5283, on TGLU_SKU0A32_SDCA we see random power_down/power_up sequences leading to a bus clash. Gah.

@plbossart I think doing the resume for the codecs in their prepare/suspend routine sychronously might be a better option. Worth trying I think

**Comment by plbossart** [comment]
> > Complete failure on Intel test 5283, on TGLU_SKU0A32_SDCA we see random power_down/power_up sequences leading to a bus clash. Gah.
> 
> @plbossart I think doing the resume for the codecs in their prepare/suspend routine sychronously might be a better option. Worth trying I think

It'd be horrible, we only need to do this when the clock-stop mode is used, and that's a property of the parent. Not to mention that we would push an Intel-specific requirement to ALL codecs, that would be problematic if a codec is also used on a non-Intel product.

**Comment by ranj063** [comment]
> It'd be horrible, we only need to do this when the clock-stop mode is used, and that's a property of the parent. Not to mention that we would push an Intel-specific requirement to ALL codecs, that would be problematic if a codec is also used on a non-Intel product.

@plbossart how about adding a flag to the child device that can  be set from the parent to indicate if it should resume or not?

**Comment by plbossart** [comment]
that was my initial PR @ranj063, but it still requires codec modifications. I still want to get to the bottom of the 2 issues we found, already fixed one issue on CML and one to go on TGL

**Comment by plbossart** [comment]
@bardliao we still have a race condition somewhere that's exposed with the changes in this PR.

See 
[dmesg.txt](https://github.com/thesofproject/linux/files/6830388/dmesg.txt), there is a sequence where we power-off link1, but still get an interrupt for link1 that throws a bus clash/parity error interrupt.

````
[ 5104.524004] kernel: soundwire_intel soundwire_intel.link.1: intel_suspend: start plb
[ 5104.524543] kernel: soundwire_intel soundwire_intel.link.1: intel_link_power_down: powering down all links
[ 5104.524549] kernel: soundwire_intel soundwire_intel.link.1: intel_suspend: done plb

At this point link1.link_up == false

[ 5104.524552] kernel: soundwire_intel soundwire_intel.link.0: intel_resume_runtime: start plb
[ 5104.524553] kernel: soundwire_intel soundwire_intel.link.0: intel_link_power_up: powering up all links
[ 5104.524554] kernel: soundwire_intel soundwire_intel.link.0: intel_link_power_up: first link up, programming SYNCPRD

But we have interrupts that are only handled when link1.link_up == true

[ 5104.524629] kernel: soundwire_intel soundwire_intel.link.1: Parity error
[ 5104.524639] kernel: soundwire_intel soundwire_intel.link.1: Bus clash for control word
````

the code in the power_down sequence is weird

````c
	mutex_unlock(sdw->link_res->shim_lock);

	if (ret < 0) {
		dev_err(sdw->cdns.dev, "%s: could not power down link\n", __func__);

		return ret;
	}

	sdw->cdns.link_up = false;	
        return 0;
````

Do you remember if this is intentional? we added this code in commit 	4a17c441c7cb06ac1e5fd3409a64d8ce78151983,
wondering if we need to move the link_up assignment under the mutex_lock protection - though I still don't see how this would change the interrupt handling.

Very odd sequence indeed.

**Comment by plbossart** [comment]
@bardliao @RanderWang with the update on the last commit to protect the link_up flag, I don't see any errors any more:

https://sof-ci.sh.intel.com/#/result/planresultdetail/5332

I'll run more tests over the week-end with thousands of cycles but that last commit does seem to have an effect.

**Comment by bardliao** [comment]
> Do you remember if this is intentional? we added this code in commit [4a17c44](https://github.com/thesofproject/linux/commit/4a17c441c7cb06ac1e5fd3409a64d8ce78151983),
> wondering if we need to move the link_up assignment under the mutex_lock protection - though I still don't see how this would change the interrupt handling.
> 

I am not sure if it is intentional. But I think the idea was that we use mutex to protect the HW process and set `sdw->cdns.link_up = false;` when the the link is physically down. But I agree with you that we should set `sdw->cdns.link_up = false;` first and don't set it back to true if CPA bit is not cleared since we don't want to handle the interrupt right after `intel_link_power_down` is called.

**Comment by plbossart** [comment]
@bardliao @RanderWang @ranj063 I ran a bunch of tests and don't see any regression with the last patches. Let's try and merge this with your reviews and test further.

**Review by ranj063 — APPROVED** [review]
LGTM @plbossart.

**Review by bardliao — APPROVED** [review]

**Pull request merged**
