### PR TITLE
Merge/sound upstream 20220616

### PR DESCRIPTION
**Pull request by plbossart**
Upstream merge to reset now that most MeteorLake patches are in maintainer branches.

### CODE REVIEW

**Review by bardliao — DISMISSED** [review]
PASS run-all-tests.sh on my local TGL device (SKU 0A3E)

**Review by ujfalusi — DISMISSED** [review]

**Comment by plbossart** [comment]
alsa-bat fails across the board https://sof-ci.01.org/linuxpr/PR3702/build236/devicetest/
Gah.

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
It's a repeatable fail, so likely a regression somewhere in the kernel. Darn. This was not a good week, was it?

**Comment by kv2019i** [comment]
@plbossart This smells of mixer trouble. In the amixer contents output, this pops out:

https://sof-ci.01.org/linuxpr/PR3702/build236/devicetest/
```
numid=5,iface=MIXER,name='PGA4.0 4 Master Capture Volume'
  ; type=BOOLEAN,access=rw---R--,values=2
  : values=on,on
  | dBscale-min=-50.00dB,step=1.00dB,mute=1
```

Why is the type BOOLEAN? Does not seem right.

**Comment by plbossart** [comment]
Added an upstream patch just posted on alsa-devel

[PATCH] ASoC: ops: Fix multiple value control type

**Comment by plbossart** [comment]
All alsa-bat results are now passing. Phew.

**Comment by plbossart** [comment]
Updated branch with an additional revert, now matches sof-dev-rebase-20220616-1

**Comment by kv2019i** [comment]
> Added an upstream patch just posted on alsa-devel
> 
> [PATCH] ASoC: ops: Fix multiple value control type

Yup, this fixes the problem, mixer controls now look good with that included.

**Review by kv2019i — APPROVED** [review]

**Comment by plbossart** [comment]
Better results now, merging

**Pull request merged**
