### PR TITLE
Merge/sound upstream 20200512

### PR DESCRIPTION
**Pull request by kv2019i**
Upstream sync.

Matching updated sof-dev-rebase (without reorderings):
https://github.com/kv2019i/linux/tree/merge/sof-dev-rebase-20200512

### CODE REVIEW

**Comment by kv2019i** [comment]
Sorry, a bit of shuffle. I had a "one empty line" difference in the wm8994 driver changes between sof-dev and sof-dev-rebase and that's now fixes (aligns with what was merged upstream).

**Comment by RanderWang** [comment]
I tested basic playback & capture on sdw platforms and didn't find any issues.  @ClarexZhou could you help to do a complete validation on this huge income ?  Thanks!

**Comment by kv2019i** [comment]
@RanderWang wrote:
> I tested basic playback & capture on sdw platforms and didn't find any issues. @ClarexZhou could you help to do a complete validation on this huge income ? Thanks!

Thanks! Given the patches are already merged upstream and our CI looks green, I think I will go ahead and merge this end-of-day (10am PST, in 8 hours from now) unless someone raises issues before that.

**Comment by ClarexZhou** [comment]
Verified on all platforms, all work ok, no regression issue

**Comment by kv2019i** [comment]
> Thanks! Given the patches are already merged upstream and our CI looks green, I think I will go ahead and merge this end-of-day (10am PST, in 8 hours from now) unless someone raises issues before that.

Oops, I'm 12min late from the schedule! Merging...

**Pull request merged**
