### PR TITLE
Merge/sound upstream 20211118

### PR DESCRIPTION
**Pull request by kv2019i**
Another attempt for 5.16-rc1 sync and replaces https://github.com/thesofproject/linux/pull/3278/

One extra revert on top to make the ADL systems in CI boot up.

### CODE REVIEW

**Comment by kv2019i** [comment]
@dbaluta @ajitkupandey  @yaochunhung please check. I had some conflicts that required manual attention w.r.t. the patches that were merged this week upstream. This should be ok, but please double-check.

**Comment by kv2019i** [comment]
This looks good to go now. There are errors on CML and UP2 related to rtcwake, tracked in:
https://github.com/thesofproject/sof-test/issues/806

These need follow-up, but given the failures are already merged upstream, I don't think we should hold back sof-dev on an older baseline because of this.

**Comment by marc-hb** [comment]
> These need follow-up, but given the failures are already merged upstream, I don't think we should hold back sof-dev on an older baseline because of this.

Should we temporarily disable suspend/resume tests? Would avoid a lot of failures, even before 5.16 :-)

**Comment by dbaluta** [comment]
@kv2019i looks good! Thanks for taking care of this. Some more minor conflicts should be noticed for the patches merged yesterday.
Let me know if there are any questions about those.

**Review by plbossart — APPROVED** [review]

**Pull request merged**
