### PR TITLE
ASoC: SOF: Intel: Fix CFL and CML FW binary names.

### PR DESCRIPTION
**Pull request by lgirdwood**
The manifest information is different between CNL, CML and CFL platforms
hence we need to load different files.

Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>

### CODE REVIEW

**Comment by plbossart** [comment]
@lgirdwood is this because of the PV bit shenanigans?

If yes, your patch only fixes the nocodec mode. The real fix would be to split sound/soc/intel/common/soc-acpi-intel-cnl-match.c in pieces.

I can see references to CML in there, but I don't have a clue who uses CFL with I2S codecs?

**Comment by mengdonglin** [comment]
@plbossart It's for the PV bit shenanigans. No customers use CFL with I2S codecs now.

**Comment by mengdonglin** [comment]
@jajanusz @lgirdwood Are we going to use new FW name sof-cfl.ri for CFL and sof-cml.ri for CML platforms? Or will we keep the old name sof-cnl.ri for CNL/CFL,  and only use the new name sof-cml.ri for CML?

**Comment by jajanusz** [comment]
Just CML has PV bit, so maybe we can have 1 binary for cnl&cfl and 1 for cml (unless you need different image index in manifest).

**Comment by plbossart** [comment]
replaced by PR #1393

**Pull request closed without merging**
