### PR TITLE
ASoC: codec: Fix IO timeout when doing jack detection

### PR DESCRIPTION
**Pull request by RanderWang**
Since btn_check_handler and jack_detect_handler work in
work thread, we need to wake up codecs when doing jack
detection.

Signed-off-by: Rander Wang <rander.wang@intel.com>

### CODE REVIEW

**Comment by RanderWang** [comment]
@YvonneYang2  Please test this PR with soundwire-latest.  Thanks!

**Comment by RanderWang** [comment]
@shumingfan  hi shuming, please review. thanks!

**Comment by bardliao** [comment]
@RanderWang Can we do this around [slave->ops->interrupt_callback(slave, &slave_intr);](https://github.com/thesofproject/linux/blob/integration/soundwire-latest/drivers/soundwire/bus.c#L991)? I think all slave has to be waked up when it received an interrupt. And the active time should be enough if we call pm_runtime_mark_last_busy().

**Comment by shumingfan** [comment]
> @shumingfan hi shuming, please review. thanks!
Sorry, I don't know what's condition you try to fix. 
How to reproduce this issue?

**Comment by plbossart** [comment]
> @RanderWang Can we do this around [slave->ops->interrupt_callback(slave, &slave_intr);](https://github.com/thesofproject/linux/blob/integration/soundwire-latest/drivers/soundwire/bus.c#L991)? I think all slave has to be waked up when it received an interrupt. And the active time should be enough if we call pm_runtime_mark_last_busy().

I don't think the solution is correct. I am ready to bet that the timeout happens because we end-up resuming the bus while there is an alert.

I think we should instead play with pm_runtime refcounts in 
static int sdw_handle_slave_alerts(struct sdw_slave *slave)

so that we never read/write slave registers before resuming properly.

**Comment by RanderWang** [comment]
> > @shumingfan hi shuming, please review. thanks!
> Sorry, I don't know what's condition you try to fix.
> How to reproduce this issue?

@shumingfan found in two cases now:
(1) clock stop enabled,  plug headphone,  then both master & slave are waken up. then unplug and plug a headphone for a few times, you will get IO error in rt711_jack_detect_handler,  because at this time slave is suspended
(2) disable master and sof runtime PM. in this case, intel audio pci device and master are alway active. just plug headphone, every time you will IO error for slave is suspended.

I have question for you: codec driver should deal with pm change or caller should process pm change ? I don't find any PM get in codec driver. Thanks!

**Comment by shumingfan** [comment]
> @shumingfan found in two cases now:
> (1) clock stop enabled, plug headphone, then both master & slave are waken up. then unplug and plug a headphone for a few times, you will get IO error in rt711_jack_detect_handler, because at this time slave is suspended
> (2) disable master and sof runtime PM. in this case, intel audio pci device and master are alway active. just plug headphone, every time you will IO error for slave is suspended.
> 
> I have question for you: codec driver should deal with pm change or caller should process pm change ? I don't find any PM get in codec driver. Thanks!

I know what's problem you fixed now. The codec driver will access registers when the JD/Btn interrupt happened. Due to the cache_only was enabled in suspend function, the interrupt callback function will get the return value (-EBUSY) from regmap_read/write.
I agree the suggestion that the master has to wake up the slave while there is an alert.

**Comment by RanderWang** [comment]
> > @RanderWang Can we do this around [slave->ops->interrupt_callback(slave, &slave_intr);](https://github.com/thesofproject/linux/blob/integration/soundwire-latest/drivers/soundwire/bus.c#L991)? I think all slave has to be waked up when it received an interrupt. And the active time should be enough if we call pm_runtime_mark_last_busy().
> 
> I don't think the solution is correct. I am ready to bet that the timeout happens because we end-up resuming the bus while there is an alert.
> 
> I think we should instead play with pm_runtime refcounts in
> static int sdw_handle_slave_alerts(struct sdw_slave *slave)
> 
> so that we never read/write slave registers before resuming properly.

yes, this a good solution. I talked to shuming about your idea and I will fix this bug in sdw_handle_slave_alerts in PR https://github.com/thesofproject/linux/pull/1589

**Pull request closed without merging**
