### PR TITLE
GithubActions: add arm32 compilation

### PR DESCRIPTION
**Pull request by plbossart**
We have reports of broken compilations in ARM mode, let's try to
expand compilation to the 32-bit mode.

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

### CODE REVIEW

**Comment by paulstelian97** [comment]
Who is the main user of arm32? AFAIK NXP only uses arm64...

**Comment by dbaluta** [comment]
@paulstelian97 I don't think there is any user as of this moment. Anyway, compilation should go without issues.

**Comment by plbossart** [comment]
this comes from a report from Arnd Bergman in https://github.com/thesofproject/linux/commit/7fc223e746faf72a7c0d04a7037d6a24ca7f8f0f#commitcomment-54097663

**Comment by plbossart** [comment]
There's just too many versions of ARM, so this PR didn't even catch the problem with our existing configuration.
Closing for now, if needed it can be added back.

**Pull request closed without merging**
