### PR TITLE
ASoC: SOF: Intel: revisit module/namespace split for SoundWire/BPT support

### PR DESCRIPTION
**Pull request by plbossart**
Unfortunately without a complete rework of module support, we will have a circular dependency:

depmod: ERROR: Cycle detected: soundwire_intel -> snd_sof_intel_hda_sdw_bpt -> snd_sof_intel_hda_common -> soundwire_intel

This might have been avoided if the SoundWire Intel parts were moved to ASoC/SOF...

### CODE REVIEW

**Comment by plbossart** [comment]
All module load/remove failed, let's retest now that https://github.com/thesofproject/sof-test/pull/1130 is merged

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
maybe one day we'll get test results in less than 5 days. Oh well, 'main-cavs' is shown as pending.

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
dependencies issues reported in https://sof-ci.01.org/linuxpr/PR4703/build610/devicetest/index.html, fixed now by https://github.com/thesofproject/sof-test/pull/1133

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
I don't think CI took my changes
https://sof-ci.01.org/linuxpr/PR4703/build618/devicetest/index.html?model=TGLU_RVP_NOCODEC-ipc4&testcase=check-kmod-load-unload

````
SKIP	snd_sof_pci_intel_apl  	not loaded
RMMOD	snd_sof_pci_intel_cnl
rmmod: ERROR: Module snd_sof_pci_intel_cnl is in use by: snd_sof_pci_intel_tgl
````

https://github.com/thesofproject/sof-test/blob/main/tools/kmod/sof_remove.sh#L87


remove_module snd_sof_pci_intel_tgl
remove_module snd_sof_pci_intel_icl
remove_module snd_sof_pci_intel_cnl

What a mess.

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by keqiaozhang** [comment]
> I don't think CI took my changes

@plbossart  I think this is because CI needs time to synchronize the changes to the storage gitweb after merging PR.
I have checked the Jenkins logs, the last CI tests include your sof-test changes.

**Comment by plbossart** [comment]
All module tests are now passing now with updated sof-test and lots of waiting.

@ujfalusi @bardliao @ranj063 do you mind reviewing, this needs to be merged soon and sent upstream since it's very invasive. We want enough time to fix any misses reported by randconfig and other bots on intel next. Thanks!

**Review by bardliao — APPROVED** [review]

**Comment by plbossart** [comment]
@ujfalusi @ranj063 your review would be greatly appreciated, I'd like to merge this tomorrow latest. Thanks!

**Review by ranj063 — APPROVED** [review]

**Pull request merged**
