### PR TITLE
Remove everything which is not upstream: compressed hsw skl kbl spi virtio

### PR DESCRIPTION
**Pull request by plbossart**
I've been carrying a debt of stuff that's not maintained, not tested and generates conflicts with upstream merges.
I am done, let's remove all this. Half-baked features that are not maintained need to go. We will have to add compressed and virtio stuff at some point, but we'll have to do it right.

### CODE REVIEW

**Comment by ranj063** [comment]
@plbossart I wonder what breaks the UP2 device test here?

**Comment by keyonjie** [comment]
BTW, is it possible to reverse commits directly(and squash/delete them after rebase to new asoc 5.2 Mark's for-next base)?

**Comment by mengdonglin** [comment]
@plbossart this PR cause CFL-S RVP hang in CI test, reported by @DarrenxWang

**Comment by DarrenxWang** [comment]
@plbossart 
This PR would cause an debugfs copying issue, when I tried to copy /sys/kernel/debug/sof/dsp to other directory, it couldn't be interrupted by any key, even though 'ctrl + c', and the system also hung. the same operation does't hung system based on daily build version. please help to check it.

Reproduce Steps
sudo su -c 'cp -rf /sys/kernel/debug/sof/dsp /tmp/'

sof (master): 39a37350
linux (topic/sof-dev): PR#918
topology: sof-hda-generic.tplg
Kconfig: https://sof-ci.01.org/linuxpr/PR918/build1232/build/config-hda-pr918-1.txt

**Comment by plbossart** [comment]
> BTW, is it possible to reverse commits directly(and squash/delete them after rebase to new asoc 5.2 Mark's for-next base)?

no, there's no way to do a revert, we have to apply the patches taken from topic/sof-dev-rebase

**Comment by plbossart** [comment]
@ranj063 @DarrenxWang you are not providing any inputs as to what might cause the problems so what am I supposed to do here? The patches have nothing to do with debugfs and don't touch the Up2 code?

**Comment by plbossart** [comment]
And CI tells me everything passed but the overall report is fail...Gah.

**Comment by plbossart** [comment]
> This is helpful to relax us, can we archive them that we can find them back quickly once needed?

the code is on the branch archive/compressed-hsw-skl-kbl-spi-20190508. I'll add restrictions to keep it alive.

**Comment by ranj063** [comment]
> @ranj063 @DarrenxWang you are not providing any inputs as to what might cause the problems so what am I supposed to do here? The patches have nothing to do with debugfs and don't touch the Up2 code?

@plbossart I am clueless as to whats causing the debugfs problems with this PR or the other one which has nothing to do with debugfs. I can take a look today morning.

**Comment by ranj063** [comment]
> @plbossart
> This PR would cause an debugfs copying issue, when I tried to copy /sys/kernel/debug/sof/dsp to other directory, it couldn't be interrupted by any key, even though 'ctrl + c', and the system also hung. the same operation does't hung system based on daily build version. please help to check it.
> 
> Reproduce Steps
> sudo su -c 'cp -rf /sys/kernel/debug/sof/dsp /tmp/'
> 
> sof (master): 39a37350
> linux (topic/sof-dev): PR#918
> topology: sof-hda-generic.tplg
> Kconfig: https://sof-ci.01.org/linuxpr/PR918/build1232/build/config-hda-pr918-1.txt

@plbossart @DarrenxWang I see no issues copying the debugfs on the Up2 with this PR. I dont have a HDA platform to test this though.

**Comment by plbossart** [comment]
> @plbossart I wonder what breaks the UP2 device test here?

@ranj063 what issues do you see?

**Comment by ranj063** [comment]
> @ranj063 what issues do you see?

Nothing now. When I approved the changes yesterday the CI Test results reported the UP2 device test as FAILED. Not sure how it changed to a PASS today

**Comment by plbossart** [comment]
Thanks @ranj063. I will take a calculated risk and merge. if there are issues they were probably hidden behind code we never used, so we should fix them separately.

**Comment by plbossart** [comment]
btw 5 approvers for one PR must be some sort of record ;-)

**Pull request merged**
