### PR TITLE
[TEST] Fix/incomplete topology

### PR DESCRIPTION
**Pull request by plbossart**
Friday afternoon attempt to fix incomplete topologies, or cases where virtual widgets are missing.

No merge for now, just to check if this has any negative effects.

### CODE REVIEW

**Comment by kv2019i** [comment]
Hmm, odd, kernel builds ok but no device tests. Let's try again. The patch seems good and probably something we'll need sooner or later.

**Comment by kv2019i** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
@kv2019i I think the CI farm is not functional today...

**Comment by plbossart** [comment]
sent upstream directly

**Pull request closed without merging**
