### PR TITLE
[HACK] ASoC: SOF: ipc4-loader: log ASTATE_COUNT

### PR DESCRIPTION
**Pull request by plbossart**
see how much space is allocated for A-State tables.

### CODE REVIEW

**Comment by plbossart** [comment]
Results:
[    5.053327] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ASTATE_COUNT 3
[    3.358887] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ASTATE_COUNT 3

**Comment by plbossart** [comment]
well d'oh, this is all defined in SOF base_fw.h

````
/* Power Manager Astate Table */
struct ipc4_astate_table {
	/* Number of entries in astates_ array. The value does not exceed maximum
	 * number specified by MAX_ASTATE_COUNT member of Base FWs
	 * FIRMWARE_CONFIG parameter.
	 */
	uint32_t astates_count_;
	/* Array of states. */
	struct ipc4_astate astates_[3];
} __attribute__((packed, aligned(4)));

````

**Comment by fredoh9** [comment]
came to my radar due to failures on verify-kernel-boot-log.sh.

**Comment by plbossart** [comment]
The interface seems to exist but at this point it's unclear if the firmware support any modified A-state tables, nor if it can even handle default ones. This looks like a placeholder @ranj063 @ujfalusi @lgirdwood

**Comment by ujfalusi** [comment]
Yes, now that I'm aware of the A-State, I knew that we can query the number of A-States supported by the firmware, but no point of touching it just for the sake of it. If we have a plan for the A-State, we will need the count, but not before.

**Comment by ujfalusi** [comment]
> Results:
> [ 5.053327] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ASTATE_COUNT 3
> [ 3.358887] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ASTATE_COUNT 3

$ git grep IPC4_MAX_CLK_STATES
src/audio/base_fw.c:    set_tuple_uint32(tuple, IPC4_MAX_ASTATE_COUNT_FW_CFG, IPC4_MAX_CLK_STATES);
src/include/ipc4/base_fw.h:#define IPC4_MAX_CLK_STATES 3

This is aligned with the reference firmware.

**Pull request closed without merging**
