### PR TITLE
Remove developer debug code

### PR DESCRIPTION
**Pull request by cujomalainey**
Left over printk from development that got merged in, removing for cleanliness

### CODE REVIEW

**Comment by cujomalainey** [comment]
I have been sending them to this branch to be cherry picked over for releases. I can switch to the regular cros branch if you prefer

**Comment by plbossart** [comment]
We will have to clean-up this topic/cos-sof-v4.14-rebase branch, this is  meant to be a backport of the topic/sof-dev-rebase but is only an input for Cros integration, so for now I don't really want to use github to touch this branch...

**Comment by cujomalainey** [comment]
@plbossart that is fine, but this code appears to have been introduced to a commit that exists exclusively in the CROS branches (4893360fd8ea58ab2d885a2ca6fc4f97255f5c14). Also the patch will need to be updated as I found 2 other lines that should be removed. Also I would like to get this patch into topic/sof-dev so we can run the branch without having to rebase patches to enable audio first.

This patch is also a "HACK" but doesn't explain what part of it is hacky, I would think we should avoid this in sof-dev but it would be really nice to enable the glk dialog maxim driver, @plbossart do you know what should be fixed about the patch before it goes up?

**Comment by plbossart** [comment]
@cujomalainey sorry curtis you lost me here. this code is not in topic/sof-dev, not sure what you are asking. Also don't see the point about the dialog maxim driver.

**Comment by ranj063** [comment]
@plbossart I think this problem should go away after the clean up you're working on

**Comment by cujomalainey** [comment]
Let's close this if that is the case

**Pull request closed without merging**
