### PR TITLE
Merge/sound upstream 20210301

### PR DESCRIPTION
**Pull request by plbossart**
First attempt with v5.12-rc1.

I don't have a matching topic/sof-dev-rebase due to issues with the script used to add github reviews

### CODE REVIEW

**Comment by plbossart** [comment]
Same results as last Friday, all tests are broken -> bisect required. Gah.

**Comment by plbossart** [comment]
it's possibly an sof-test/CI issue:

````
modprobe snd-sof-pci
export TPLG=/lib/firmware/intel/sof-tplg/sof-tgl-rt715-rt711-rt1308-mono.tplg 
~/sof-test/test-case/check-pause-resume.sh -c 10 -m playback
...
2021-03-01 19:02:15 UTC [INFO] Test Result: PASS!

root@plb-Latitude-9520:~# ps -edf | grep aplay
root        1360       1 95 13:01 ?        00:00:41 aplay -D hw:0,0 -r 48000 -c 2 -f S16_LE -vv -i /dev/zero -q
root        1419       1 96 13:02 ?        00:00:37 aplay -D hw:0,2 -r 48000 -c 2 -f S16_LE -vv -i /dev/zero -q
root        1478       1 95 13:02 ?        00:00:34 aplay -D hw:0,5 -r 48000 -c 2 -f S16_LE -vv -i /dev/zero -q
root        1539       1 94 13:02 ?        00:00:31 aplay -D hw:0,6 -r 48000 -c 2 -f S16_LE -vv -i /dev/zero -q
root        1598       1 95 13:02 ?        00:00:27 aplay -D hw:0,7 -r 48000 -c 2 -f S16_LE -vv -i /dev/zero -q
root        1669    1120  0 13:02 pts/0    00:00:00 grep --color=auto aplay
````

Killing those processes restores functionality. The question is why aren't they killed already and what changed?

@marc-hb @fredoh9 @xiulipan @aiChaoSONG FYI, this looks real bad.

**Comment by fredoh9** [comment]
I was looking at "audio open error: Device or resource busy" errors. Let me check why aplay or arecord didnot be killed after the test.

**Comment by plbossart** [comment]
> I was looking at "audio open error: Device or resource busy" errors. Let me check why aplay or arecord didnot be killed after the test.

I started a bisect since this worked with 5.11, this could also be a kernel regression, who knows?

**Comment by fredoh9** [comment]
aplay or arecord interactive mode(-i) didn't be killed after the pause-resume test. 100% reproducible with this pr.

Current sof-test(check-pause-resume) do not kill the process after exit of expect script. topic/sof-dev works fine, so it might be a kernel regression.

**Comment by plbossart** [comment]
Definitively a TTY issue indeed

````
33d4ae98859873ddd49e22e4ca724387548b3d89 is the first bad commit
commit 33d4ae98859873ddd49e22e4ca724387548b3d89
Author: Corey Minyard <cminyard@mvista.com>
Date:   Mon Nov 23 18:49:02 2020 -0600

    drivers:tty:pty: Fix a race causing data loss on close
    
    Remove the tty_vhangup() from the pty code and just release the
    redirect.  The tty_vhangup() results in data loss and data out of order
    issues.
    
    If you write to a pty master an immediately close the pty master, the
    receiver might get a chunk of data dropped, but then receive some later
    data.  That's obviously something rather unexpected for a user.  It
    certainly confused my test program.
    
    It turns out that tty_vhangup() on the slave pty gets called from
    pty_close(), and that causes the data on the slave side to be flushed,
    but due to races more data can be copied into the slave side's buffer
    after that.  Consider the following sequence:
    
    thread1          thread2         thread3
    -------          -------         -------
     |                |-write data into buffer,
     |                | n_tty buffer is filled
     |                | along with other buffers
     |                |-pty_close(master)
     |                |--tty_vhangup(slave)
     |                |---tty_ldisc_hangup()
     |                |----n_tty_flush_buffer()
     |                |-----reset_buffer_flags()
     |-n_tty_read()   |
     |--up_read(&tty->termios_rwsem);
     |                |------down_read(&tty->termios_rwsem)
     |                |------clear n_tty buffer contents
     |                |------up_read(&tty->termios_rwsem)
     |--tty_buffer_flush_work()       |
     |--schedules work calling        |
     |  flush_to_ldisc()              |
     |                                |-flush_to_ldisc()
     |                                |--receive_buf()
     |                                |---tty_port_default_receive_buf()
     |                                |----tty_ldisc_receive_buf()
     |                                |-----n_tty_receive_buf2()
     |                                |------n_tty_receive_buf_common()
     |                                |-------down_read(&tty->termios_rwsem)
     |                                |-------__receive_buf()
     |                                |       copies data into n_tty buffer
     |                                |-------up_read(&tty->termios_rwsem)
     |--down_read(&tty->termios_rwsem)
     |--copy buffer data to user
    
    >From this sequence, you can see that thread2 writes to the buffer then
    only clears the part of the buffer in n_tty.  The n_tty receive buffer
    code then copies more data into the n_tty buffer.
    
    But part of the vhangup, releasing the redirect, is still required to
    avoid issues with consoles running on pty slaves.  So do that.
    As far as I can tell, that is all that should be required.
    
    Signed-off-by: Corey Minyard <cminyard@mvista.com>
    Link: https://lore.kernel.org/r/20201124004902.1398477-3-minyard@acm.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

 drivers/tty/pty.c    | 15 +++++++++++++--
 drivers/tty/tty_io.c |  5 +++--
 2 files changed, 16 insertions(+), 4 deletions(-)
````

**Comment by marc-hb** [comment]
https://lwn.net/Articles/343828/
> There are dark areas of the kernel where only the bravest hackers dare to tread. Places where the code is twisted, the requirements are complex, and everything depends on ancient code which has seen little change over the years because even the most qualified developers fear the consequences. Arguably, no part of the kernel is darker and scarier than the serial terminal (TTY) code. 

(2009)

**Comment by fredoh9** [comment]
> > There are dark areas of the kernel...
>> everything depends on ancient code which has seen little change over the years...

hehehe~

**Comment by fredoh9** [comment]
@plbossart I verified without the TTY you identified. It worked fine on my ICL. We can wait for the device test result.

**Comment by plbossart** [comment]
> @plbossart I verified without the TTY you identified. It worked fine on my ICL. We can wait for the device test result.

Same here, the revert solves the issue on my local TGL test device. I let the author + maintainer know.

**Comment by plbossart** [comment]
Added a couple of commits for fix warnings and compilation issues

**Comment by plbossart** [comment]
@fredoh9 can we run an Intel daily test with this PR? The results look fine now, but more evidence wouldn't hurt to avoid disturbing developers.

**Review by kv2019i — APPROVED** [review]
My local tests pass, so if daily test is ok, good for me.

**Comment by fredoh9** [comment]
Manual daily test ID is 2414.
suspend/resume test failed in EHL_RVP_I2S due to i915 error. Other than this, all results are good.

`
[   24.661004] kernel: i915 0000:00:02.0: [drm] *ERROR* Suspending crtc's failed with -22
`

**Comment by plbossart** [comment]
@kv2019i I am not sure how to deal with the EHL_RVP issue above. Those boards are in short supply and this should be a dedicated debug effort. I'll let you make a call if you want to merge since this is a DRM problem beyond my understanding.

**Pull request merged**
