### PR TITLE
[TEST] Morimoto ALSA SoC cleanup 2019-10-10-v1

### PR DESCRIPTION
**Pull request by morimoto**
This is first pull request for me, but not yet 100% understand the system.
Please let me know if this is not good.

### CODE REVIEW

**Comment by dbaluta** [comment]
Something went wrong. You should see only your commits in the PR. Make sure you use topic/sof-dev branch and you update it before adding your patches.

**Comment by lyakh** [comment]
@morimoto Hi Morimoto-san, Thanks for your work! I agree with @dbaluta - obviously, this PR isn't what you really want us to merge. In fact I'm not even sure why you want to use GitHub for your work. If you want to contribute *to* the SOF project itself, i.e. your patches' primary goal is development of SOF drivers, sure this would be a good place to get your work integrated. However, if your primary development goals are outside the SOF driver, even if your changes touch the SOF code, I think ALSA mailing lists are still the correct place to have your work reviewed and merged. We cannot and do not want to replace the ALSA ML in its code review function. It's also good to CC any your SOF-related work to sound-open-firmware@alsa-project.org, in which case you also obviously don't have to base your code on the SOF development tree.

**Comment by morimoto** [comment]
Hi Guennadi
Cc Pierre-Louis

> @morimoto Hi Morimoto-san, Thanks for your work! I agree with @dbaluta - obviously, this PR isn't what you really want us to
> merge. In fact I'm not even sure why you want to use GitHub for your work. If you want to contribute to the SOF project
> itself, i.e. your patches' primary goal is development of SOF drivers, sure this would be a good place to get your work
> integrated. However, if your primary development goals are outside the SOF driver, even if your changes touch the SOF code, I
> think ALSA mailing lists are still the correct place to have your work reviewed and merged. We cannot and do not want to
> replace the ALSA ML in its code review function. It's also good to CC any your SOF-related work to 
> sound-open-firmware@alsa-project.org, in which case you also obviously don't have to base your code on the SOF development
> tree.

Thank you for your feedback, and so sorry to bother you.
Actually, my purpose is just kernel test on Intel platform.

I have posted some patches to ALSA SoC ML, and then, I indicated
that I couldn't test some of them, because Intel is only(?) user.
At that time, Pierre-Louis kindly teach me that Intel+GitHub has
auto test system, and he invited me to this project.

I'm sorry but I'm not 100% understand the system and rule.
My purpose is just kernel test on Intel platform, not for SOF.


Thank you for your help !!
Best regards
---
Kuninori Morimoto

**Comment by dbaluta** [comment]
@morimoto testing here is fine as @plbossart advised. Anyhow, make sure you use this Linux kernel repo
https://github.com/thesofproject/linux.git and topic/sof-dev branch.

Then add your patches on top of this and then create a new pull request.

**Comment by plbossart** [comment]
@lyakh @dbaluta I invited @morimoto and offered to use the GitHub SOF CI for his nice DPCM cleanup. We do depend on his work to implement the multi-cpu support for SoundWire, so he's a VIP in my book.

@morimoto our CI currently only tests patches against topic/sof-dev, which tracks Mark's tree on a weekly basis. We can however ask @xiulipan to test your branches directly if you prefer.

**Comment by lyakh** [comment]
@morimoto @plbossart ah, sure, sorry, I didn't know it was for testing only. Maybe we need a tag for such PRs so we don't treat them as a request for review, or at least some keywords in the PR subject like [TEST-ONLY]?

**Comment by plbossart** [comment]
> @morimoto @plbossart ah, sure, sorry, I didn't know it was for testing only. Maybe we need a tag for such PRs so we don't treat them as a request for review, or at least some keywords in the PR subject like [TEST-ONLY]?

the title already is [TEST] ;-)

**Comment by xiulipan** [comment]
@plbossart @morimoto Could you give  list of the branches to that need to be tracked in https://github.com/thesofproject/linux
And other branches needed to track in other repo. I will try to first track the build status and enable on-device test later.

**Comment by morimoto** [comment]
Thank you for your help all. I will try to rebase to topic/sof-dev, and re-PR again with [TEST] Subject.
The purpose is for device test only, not for SOF. I will close pull request if I could check the test result.
(I will close *this* pull request, soon).

**Pull request closed without merging**
