### PR TITLE
Merge/sound upstream 20210524

### PR DESCRIPTION
**Pull request by kv2019i**
Please check @ranj063  and @juimonen , I had conflicts requiring manual fixups related to your patches.

sof-dev-rebase not yet updated but pushed as sof-dev-rebase-20210524-newbase

### CODE REVIEW

**Comment by kv2019i** [comment]
There's a one-line different in one of the merged commits. I added one commit to this PR to account for the difference and dropped the related patch from sof-dev-rebase-20210524-newbase and the trees now match again.

Here's the delta commit:
https://github.com/thesofproject/linux/pull/2938/commits/c006d7ba41e350433c40ae53d9d8a415f99d89b9

**Comment by plbossart** [comment]
@fredoh9 can we run this PR as a overnight 'daily test', just to see if there is no regression (the daily test doesn't seem to be in very good state atm so our mileage may vary). Thanks!

**Comment by fredoh9** [comment]
Sure, I'm going to trigger one right after scheduled daily test.

**Comment by fredoh9** [comment]
I just triggered the test, Internal TestPlan Result 4191. Sorry for the delay.

**Comment by plbossart** [comment]
I don't see any regression with this upstream code so let's go and merge.

**Pull request merged**
