### PR TITLE
[TEST] upstream Broadwell changes

### PR DESCRIPTION
**Pull request by plbossart**

### CODE REVIEW

**Comment by plbossart** [comment]
@greg-intel @marc-hb I could use some help on what happens with git/GitHub here. All the conflicts seem to be solved when I try by hand, is there a problem in our CI scripts?

````
pbossart@pbossart-mobl3:/data/pbossart/ktest/sof-dev$ git merge --no-ff test/haswell
Auto-merging sound/pci/hda/hda_intel.c
CONFLICT (content): Merge conflict in sound/pci/hda/hda_intel.c
Auto-merging sound/soc/codecs/ak4613.c
Auto-merging sound/soc/codecs/cs35l45.h
Auto-merging sound/soc/codecs/tlv320adc3xxx.c
Auto-merging sound/soc/codecs/wm_adsp.c
Auto-merging sound/soc/fsl/fsl_sai.c
Auto-merging sound/soc/intel/atom/sst-atom-controls.c
Auto-merging sound/soc/intel/boards/bytcr_rt5640.c
Auto-merging sound/soc/intel/boards/bytcr_rt5651.c
Auto-merging sound/soc/intel/boards/cht_bsw_rt5645.c
Auto-merging sound/soc/intel/boards/sof_sdw.c
Auto-merging sound/soc/intel/boards/sof_sdw.c
Auto-merging sound/soc/intel/common/soc-acpi-intel-mtl-match.c
CONFLICT (add/add): Merge conflict in sound/soc/intel/common/soc-acpi-intel-mtl-match.c
Auto-merging sound/soc/soc-ops.c
Auto-merging sound/soc/soc-ops.c
Auto-merging sound/soc/sof/intel/hda-dsp.c
Auto-merging sound/soc/sof/intel/hda-loader.c
Auto-merging sound/soc/sof/intel/hda.h
Auto-merging sound/soc/sof/sof-audio.c
Merge made by the 'ort' strategy.
 include/sound/soc-card.h                              |   1 +
 include/sound/soc.h                                   |   3 +-
 sound/pci/hda/patch_realtek.c                         |   1 +
 sound/soc/codecs/msm8916-wcd-digital.c                |  46 ++++++++++----------
 sound/soc/codecs/rt274.c                              |   9 ++--
 sound/soc/codecs/rt286.c                              |  17 +++-----
 sound/soc/codecs/rt286.h                              |   2 -
 sound/soc/codecs/rt298.c                              |  17 +++-----
 sound/soc/codecs/rt298.h                              |   2 -
 sound/soc/codecs/wcd9335.c                            |  81 +++++++++++++++-------------------
 sound/soc/intel/avs/topology.c                        |   4 +-
 sound/soc/intel/boards/Kconfig                        |   4 +-
 sound/soc/intel/boards/Makefile                       |   4 +-
 sound/soc/intel/boards/bdw_rt286.c                    | 257 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 sound/soc/intel/boards/broadwell.c                    | 338 ---------------------------------------------------------------------------------------------------------------------------------------------
 sound/soc/intel/boards/bxt_rt298.c                    |   2 +-
 sound/soc/intel/boards/haswell.c                      | 202 ------------------------------------------------------------------------------------
 sound/soc/intel/boards/hsw_rt5640.c                   | 176 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 sound/soc/intel/boards/skl_rt286.c                    |   2 +-
 sound/soc/intel/common/soc-acpi-intel-hsw-bdw-match.c |   6 +--
 sound/soc/qcom/qdsp6/q6apm-dai.c                      |   6 +++
 sound/soc/soc-card.c                                  |   6 +++
 sound/soc/soc-core.c                                  |   1 +
 sound/usb/mixer_us16x08.c                             |   6 +--
 24 files changed, 537 insertions(+), 656 deletions(-)
 create mode 100644 sound/soc/intel/boards/bdw_rt286.c
 delete mode 100644 sound/soc/intel/boards/broadwell.c
 delete mode 100644 sound/soc/intel/boards/haswell.c
 create mode 100644 sound/soc/intel/boards/hsw_rt5640.c
pbossart@pbossart-mobl3:/data/pbossart/ktest/sof-dev$ git diff
pbossart@pbossart-mobl3:/data/pbossart/ktest/sof-dev$ git log
commit 46f393111092439ae0ab5a73672267023879afd9 (HEAD -> topic/sof-dev)
Merge: 9eaf67f8c40cc b1eac0839e22d
Author: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Date:   Mon Jun 13 08:42:24 2022 -0500

    Merge branch 'test/haswell' into topic/sof-dev

````

**Comment by marc-hb** [comment]
The conflict error message in this screenshot is purely from Github, zero custom script of ours involved.

Looking into it now.
Screenshot 2022-06-13 at 09 44 32

**Comment by plbossart** [comment]
@marc-hb I was referring to this " sof-ci/jenkins/pr-build — PR has merge conflicts! Need to rebase to continue test! "

**Comment by marc-hb** [comment]
> @marc-hb I was referring to this " sof-ci/jenkins/pr-build — PR has merge conflicts! Need to rebase to continue test! "

Considering "pure" Github concurs, I'm looking at Github first.

**Comment by marc-hb** [comment]
This could be related:

```
git merge-base -a 9eaf67f8c40c b1eac0839e22

b0378c1168bdd4d4bfa5d84f2d065fecbdae8285
142d456204cf4dabe18be59e043d806440f609d4
4643e10a17e549467420aaeeb35c9b3480716618
5f3d696eea916693b2d4ed7e62794653fcdd6ec0
687e2ae186029be194c28fef8544e4e54623adf9
```

(Saving full, 40-digit SHA1s here for direct fetch even after pull/3693/head and origin/topic/sof-dev have moved on: 9eaf67f8c40cc9398904dc86c870e6f059fd7f89  b1eac0839e22da0685c95ce944f2a37bc7ffd08c )

**Comment by plbossart** [comment]
what are you trying to say @marc-hb ?

**Comment by marc-hb** [comment]
I had a look at Jenkins too and I believe Jenkins is merely performing the api.github.com equivalent of `git fetch origin pull/3693/merge` which obviously fails right now. In other words, I believe Jenkins relies on Github merges, Jenkins does not perform merges itself. Why would it when it can just leverage Github? @greg-intel , @fredoh9 , @keqiaozhang can you confirm?
https://api.github.com/repos/thesofproject/linux/statuses/b1eac0839e22da0685c95ce944f2a37bc7ffd08c

I also tried various `git merge --strategy=` and the only one that fails was `--strategy=octopus` but I don't see why it would be used by Github for pull requests.

> what are you trying to say @marc-hb ?

This is a complex merge with many merge bases and a couple deleted files. Github is constantly attempting to merge every pull request against the moving target branch. As this is likely expensive, it's possible that Github has optimized their merge operation and diverged from plain git. This divergence could cause problems in more complex cases.

Some background: [Our merge bases sometimes suck](https://public-inbox.org/git/539A25BF.4060501@alum.mit.edu/#r)
https://public-inbox.org/git/539A25BF.4060501@alum.mit.edu/

**Comment by marc-hb** [comment]
Maybe there's a workaround: merge locally and try to submit that as a pull request.

**Comment by fredoh9** [comment]
> I had a look at Jenkins too and I believe Jenkins is merely performing the api.github.com equivalent of git fetch origin pull/3693/merge which obviously fails right now. In other words...

That's right, Current Jenkins rely on github api response for checking merge conflict.

```
06:37:14  GitHub pull request #3693 of commit b1eac0839e22da0685c95ce944f2a37bc7ffd08c, has merge conflicts.
...
06:37:19  Checking merge conflict
06:37:19  sofhttp with http://sof-ci.sh.intel.com/api/github/repos/thesofproject/linux/statuses/b1eac0839e22da0685c95ce944f2a37bc7ffd08c, POST, 
06:37:19          {
06:37:19              "state":"failure",
06:37:19              "target_url":"",
06:37:19              "description":"PR has merge conflicts! Need to rebase to continue test!",
06:37:19              "context": "sof-ci/jenkins/pr-build"
06:37:19          }
```

**Comment by plbossart** [comment]
replaced by https://github.com/thesofproject/linux/pull/3696

One day I'll try to find the time to understand git branches, RUST, jenkins, etc.

**Pull request closed without merging**
