### PR TITLE
Merge/backport v5.0 intel audio v20190319

### PR DESCRIPTION
**Pull request by plbossart**
Rather large backport this week before we post the 4th batch of upstream patches on alsa-devel.

### CODE REVIEW

**Comment by plbossart** [comment]
forced update to fix issues with hda stripe and i915 support

**Comment by plbossart** [comment]
@RanderWang @ranj063 @libinyang @lyakh @juimonen can you help run a smoke test before tomorrow on this branch? I'd like to make sure there's no major regression introduced.

**Comment by ranj063** [comment]
@plbossart sure on it now

**Comment by ranj063** [comment]
@plbossart minnowboard and up2 are good with this PR. Just FYI, I used an older version of the FW to test HDMI playback on the UP2

**Comment by plbossart** [comment]
Thanks @ranj063, will merge now so that I can see the full daily validation report tomorrow.

**Pull request merged**
